#!/bin/sh

# 
# @OSF_COPYRIGHT@
# COPYRIGHT NOTICE
# Copyright (c) 1990, 1991, 1992, 1993, 1996 Open Software Foundation, Inc.
# ALL RIGHTS RESERVED (DCE).  See the file named COPYRIGHT.DCE in the
# src directory for the full copyright text.
# 
# HISTORY
# $Log: chkproc,v $
# Revision 1.1.85.2  1996/02/17  23:29:13  marty
# 	Update OSF copyright year
# 	[1996/02/17  22:45:59  marty]
#
# Revision 1.1.85.1  1995/12/11  22:50:34  root
# 	Submit OSF/DCE 1.2.1
# 	[1995/12/11  22:23:32  root]
# 
# Revision 1.1.82.1  1993/10/15  21:16:03  ohara
# 	SVR4 porting changes - 8596
# 	[1993/10/15  16:35:43  ohara]
# 
# Revision 1.1.5.2  1993/02/05  15:27:49  cjd
# 	Embedded copyright notice
# 	[1993/02/05  14:48:54  cjd]
# 
# Revision 1.1.3.2  1993/02/05  13:16:05  cjd
# 	Embedded copyright notice
# 
# Revision 1.1.2.2  1992/06/04  19:09:13  kenny
# 	Changed to reflect no status return from 'ps'
# 	[1992/06/04  19:07:10  kenny]
# 
# $EndLog$


#
#   TEST_NAME: chkproc
#
#   COMPONENT_NAME: dce.systest
#
#   FUNCTIONS:	usage
#
#   ORIGINS: 27
#
#
#   (C) COPYRIGHT International Business Machines Corp. 1991
#   All Rights Reserved
#
#
#  DESCRIPTION
#
#  Use getproc to determine if any processes are running that match
#  string_to_match.  Return 0 if there was at least one process that matched,
#  otherwise return 1.
#
#  CHANGE ACTIVITY:
#  DATE		AUTHOR		REASON
#  06/26/90	Wayne Mock	Initial Draft
#  06/14/91	Wayne Mock	Added the -p option.  See usage() for more
#				information.
#  09/30/91	Wayne Mock	Ported to work on the osf1 platforms.
#  
#******************************************************************************

#******************************************************************************
# usage()
#
# Prints the usage string for this command
#******************************************************************************

usage()
{
	echo "
usage: $PGM [-s host_to_run_on] [-p] string_to_match{|...}

 -s host_to_run_on  Specifies the machine on which the $PGM command will be
                    executed.  Default is the local host.
 -p                 Specifying this option forces $PGM to treat 
                    string_to_match as a PID and search on that column only.
 string_to_match    This string will be used to determine which PIDs will be
                    searched for.
"
	exit 1

} # end usage()


#******************************************************************************
# main 
#******************************************************************************

PGM=`basename $0`
unset PROC_ONLY

set -- `getopt ps: $*` 		# parse the command line arguments
test $? -ne 0 && usage

while :
do
	case "$1" in
	-s)	HOST_TO_RUN_ON="$2"
		shift 1
		;;
	-p)	PROC_ONLY="true"
		;;
	--)	shift
		break 2
	esac
	shift
done

STRING="$1"
test "$STRING" || usage

if [ "$PROC_ONLY" ]; then
	if [ "$HOST_TO_RUN_ON" ]; then
		rshsp $HOST_TO_RUN_ON $PGM -p $STRING
	else
		case "$SYSTYPE" in
		sun*|ultrix*)
			ps -a$STRING >/dev/null 2>&1
			;;
		aix*|osf1*|*)
			ps -p $STRING | grep $STRING >/dev/null 2>&1
			;;
		esac
	fi
else
	list=`getproc $ARGS -l $$ "$STRING"`
	test "$list"
fi

exit $?

#******************************************************************************
# end of main
#******************************************************************************
