#!/bin/ksh
#
# @OSF_COPYRIGHT@
# COPYRIGHT NOTICE
# Copyright (c) 1990, 1991, 1992, 1993, 1996 Open Software Foundation, Inc.
# ALL RIGHTS RESERVED (DCE).  See the file named COPYRIGHT.DCE in the
# src directory for the full copyright text.
#
# HISTORY
# $Log: expmachinfo,v $
# Revision 1.1.14.2  1996/03/11  02:49:23  marty
# 	Update OSF copyright years
# 	[1996/03/10  20:10:01  marty]
#
# Revision 1.1.14.1  1995/12/11  22:50:47  root
# 	Submit OSF/DCE 1.2.1
# 
# 	HP revision /main/HPDCE02/1  1994/07/05  18:43 UTC  bissen
# 	Merge hpdce02 (DCE 1.1 beta) and HPDCE01 into HPDCE02
# 
# 	HP revision /main/HPDCE01/1  1994/04/12  14:11 UTC  truitt
# 
# 	HP revision /main/truitt_junk/1  1994/04/12  14:06 UTC  truitt
# 	clean up file
# 	[1995/12/11  22:23:35  root]
# 
# Revision 1.1.11.2  1993/10/15  21:16:04  ohara
# 	SVR4 porting changes - 8596
# 	[1993/10/15  16:35:47  ohara]
# 
# Revision 1.1.11.1  1993/09/02  15:19:38  pellis
# 	Updated with AIX 3.2.4 information.
# 	[1993/09/02  15:19:20  pellis]
# 
# Revision 1.1.9.3  1993/08/11  17:44:07  pellis
# 	Merged with final version of test from DCE 1.0.2.
# 	[1993/08/11  17:40:26  pellis]
# 
# Revision 1.1.9.2  1993/07/28  19:39:31  cmckeen
# 	HP's TET'ized version of the system tests
# 	[1993/07/27  13:55:08  cmckeen]
# 
# Revision 1.1.5.3  1993/05/27  19:00:42  eheller
# 	*** empty log message ***
# 
# Revision 1.1.5.2  1993/05/27  14:16:06  eheller
# 	*** empty log message ***
# 	[1993/05/26  18:41:00  eheller]
# 
# Revision 1.1.6.2  1993/04/23  15:57:36  sekhar
# 	Merged Hp_dce1_0_1 changes
# 	[1993/04/16  14:59:26  sekhar]
# 
# Revision 1.1.1.7  1993/03/11  22:15:45  osfrcs
# 	    Loading drop DCE1_0_2B18
# 	Revision 1.1.4.2  1992/11/06  19:40:08  mgm
# 	DCE 1.0.1 Release
# 	[1992/11/06  19:39:12  mgm]
# 
# Revision 1.1.3.2  1993/02/05  19:33:47  zeliff
# 	Embedding copyrights
# 	[1993/02/05  19:29:48  zeliff]
# 
# Revision 1.1.1.6  1992/09/21  18:42:06  osfrcs
# 	Loading drop Dce1_0_1fnl
# 
# $EndLog$
#
#
#   NAME: expmachinfo
#
#   COMPONENT_NAME: dce.systest
#
#   FUNCTIONS: none
#
#   ORIGINS: 27
#
#
#   (C) COPYRIGHT International Business Machines Corp. 1991
#   All Rights Reserved
#
#
#   DESCRIPTION:
#   The file should be sourced in profile.dcest
#
#   The following chart represents the supported operating systems to date:
#
#   OS			SYSTYPE   OSTYPE   OSVERSION   OSRELEASE   NFSVER
#   ----------------------------------------------------------------------
#   AIX v1.2		aix12     AIX      1           2           *
#   AIX v2.1		aix21     AIX      2           1           *
#   AIX v3.1		aix32	  AIX	   3           1           nfs12
#   AIX v3.2		aix32	  AIX	   3           2           nfs12
#   AIX v3.2.4		aix32	  AIX	   3           2           nfs12
#   Domain OS		domain	  DomainOS *           *           *
#   OSF/1 on mips	osf1mips  osf1	   b5	       1.1.1	   nfs11
#   OSF/1 on i386	osf1i386  osf1	   b8	       1.2	   nfs11
#   SunOS		sunos     SunOS    *           *           *
#   Ultrix v4.1		ultrix41  ULTRIX   n/a         4.1         nfs12
#   Ultrix v4.2		ultrix42  ULTRIX   n/a         4.2         nfs12
#   HP-UX 9.0           hpux      HP-UX    E           A.09.0      nfs11
#   HP-UX 9.01		hpux      HP-UX    A           A.09.01     nfs11
#   HP-UX 9.03		hpux      HP-UX    E           A.09.03     nfs11
#   HP-UX 10.0		hpux      HP-UX    E           B.10.0L     nfs11
#   HP-UX 8.07          hpux      HP-UX    E           A.08.07     nfs11
#   HP-UX 8.02          hpux      HP-UX    E           A.08.02     nfs11
#   HP-UX 8.00          hpux      HP-UX    E           B.08.00     nfs11
#
#   HISTORY: 
#	01/05/91	Wayne Mock	Initial design
#	09/30/91	Wayne Mock	Added OSF/1 on the Mips platform support.
#	06/18/92	Mary MacGregor  Added HPUX Support

OSTYPE=`uname -s`
OSVERSION=`uname -v`
OSRELEASE=`uname -r`
SYSTYPE=''

case "$OSTYPE" in
AIX*)
	case "$OSVERSION" in
	1)	
		SYSTYPE=aix12
		;;
	2)
		SYSTYPE=aix21
		;;
	3)
		SYSTYPE=aix32
		;;
	*)
		echo "Unknown OS version ($OSVERSION)"
		;;
	esac
	;;

DomainOS)
	SYSTYPE=domain
	;;

OSF1)
	case `uname -m` in
	mips)
		SYSTYPE=osf1mips
		;;
	i386)
		SYSTYPE=osf1i386
		;;
	*)	
		echo "Unknown machine type (`uname -m`)"
		;;
	esac
	;;

SunOS)
	SYSTYPE=sunos
	;;

ULTRIX)
	case "$OSRELEASE" in
	4.1)
		SYSTYPE=ultrix41
		;;
	4.2)
		SYSTYPE=ultrix42
		;;
	*)
		echo "Unknown OS version ($OSRELEASE)"
		;;
	esac
	;;

SINIX*)
        OSTYPE=SVR4
        TARGET_OS=SINIX
        case "$OSVERSION" in
        A*)
                SYSTYPE=SNISVR4
                ;;
        B*)
                SYSTYPE=SNISVR4
                ;;
        C*)
                SYSTYPE=SNISVR4
                ;;
        D*)
                SYSTYPE=SNISVR4
                ;;
        *)
               echo "Unknown OS version ($OSVERSION)"
                ;;
        esac
        export TARGET_OS
        ;;

SVR4V3)
        SYSTYPE=svr4v3
        OSTYPE=SVR4V3
        TARGET_OS=SVR4V3
        export TARGET_OS
        ;;

HP-UX)
        SYSTYPE=hpux
        ;;

*)
	echo "Unknown OS type ($OSTYPE)"
	;;
esac

export OSTYPE OSVERSION OSRELEASE SYSTYPE

#
# Determine the version of NFS running on this machine
#
if [ -f /usr/etc/exportfs ]; then
	NFSVER=nfs12
else
	NFSVER=nfs11
fi

export NFSVER
