/*
 * @OSF_COPYRIGHT@
 * COPYRIGHT NOTICE
 * Copyright (c) 1990, 1991, 1992, 1993, 1996 Open Software Foundation, Inc.
 * ALL RIGHTS RESERVED (DCE).  See the file named COPYRIGHT.DCE in the
 * src directory for the full copyright text.
 */
/*
 * HISTORY
 * $Log: ropen_idl.idl,v $
 * Revision 1.1.14.2  1996/03/11  02:49:30  marty
 * 	Update OSF copyright years
 * 	[1996/03/10  20:10:08  marty]
 *
 * Revision 1.1.14.1  1995/12/13  21:56:25  root
 * 	Submit OSF/DCE 1.2.1
 * 	[1995/12/13  21:45:44  root]
 * 
 * Revision 1.1.10.2  1993/07/28  19:40:03  cmckeen
 * 	HP's TET'ized version of the system tests
 * 	[1993/07/27  13:55:35  cmckeen]
 * 
 * Revision 1.1.6.3  1993/05/27  19:02:20  eheller
 * 	*** empty log message ***
 * 
 * Revision 1.1.6.2  1993/05/27  14:21:09  eheller
 * 	*** empty log message ***
 * 	[1993/05/26  18:45:22  eheller]
 * 
 * Revision 1.1.7.2  1993/04/23  15:58:50  sekhar
 * 	Merged Hp_dce1_0_1 changes
 * 	[1993/04/16  15:02:04  sekhar]
 * 
 * Revision 1.1.1.7  1993/03/11  22:16:39  osfrcs
 * 	    Loading drop DCE1_0_2B18
 * 
 * Revision 1.1.4.2  1993/02/05  15:29:14  cjd
 * 	Embedded copyright notice
 * 	[1993/02/05  14:49:58  cjd]
 * 
 * Revision 1.1.3.3  1992/11/09  13:12:30  mgm
 * 	Ported to HPUX
 * 	[1992/11/06  20:35:50  mgm]
 * 
 * Revision 1.1.2.2  1992/07/15  18:03:36  gmd
 * 	Changed msg_t to msg_struct to avoid conflict
 * 	with AIX /usr/include/sys/localedef31.h.
 * 	[1992/07/15  18:01:55  gmd]
 * 
 * Revision 1.1  1992/01/19  14:33:48  devrcs
 * 	Initial revision
 * 
 * $EndLog$
 */
/*
 *
 *   FILE_NAME: ropen_idl.idl
 *
 *   COMPONENT_NAME: dce.systest
 *
 *   FUNCTIONS: none.
 *
 *   ORIGINS: 27
 *
 *   (C) COPYRIGHT International Business Machines Corp. 1991
 *   All Rights Reserved
 *
 *   FOR_TEST: All
 *
 *
 * DESCRIPTION
 *	Contains the description of the RPC interface for the ropen command.
 *
 * CHANGE HISTORY
 * 11/02/90	Wayne Mock		Initial design and coding.
 * 12/19/90	Wayne Mock		Updated IDL to reflect nidl changes
 */                                                                   

/*
 * ncsrpc uuid number
 */
[uuid(1ccb4ee4-7a4b-11c9-adcd-fefefefefefe), endpoint("ncadg_ip_udp:[3008]"), version(0)]


interface ropen_idl
{
	const long int ROPEN_BG = 0;
	const long int ROPEN_WIN = 1;
	const long int MAXCMDLEN = 2048;	/* max string length */
	const long int MAXNAMELEN = 2048;	/* max name length */
	const long int MAXPRINLEN = 64;		/* max user and password len */
	const char* PORT_NUMBER = "3008";	/* socket port number */

	typedef struct msg 
	{
		char command[0..MAXCMDLEN];	/* command to execute, given 
						 *by caller 
						 */
		char display[0..MAXCMDLEN];	/* X windows display string 
						 * [name:number] 
						 */
		char name[0..MAXNAMELEN];	/* name of the window */
		char uname[0..MAXPRINLEN];	/* name of user to authenticate
						 * as
						 */
		char upasswd[0..MAXPRINLEN];	/* password of uname
						 */
		long int uid;			/* UID of initiating process 
						 */
		long int gid;			/* GID of initiating process 
						 */
		long int wait_flg;			/* TRUE:  wait for a ENTER 
						 *        before exit 
						 * FALSE: just exit 
						 */
		long int ptype;			/* ROPEN_BG:  start process in backgroup only
						 * ROPEN_WIN:  use the windowing system
						 */
		long int icon;			/* TRUE: open window as an icon
						 * FALSE: open as full window
						 */
	} msg_struct;


	void remoteopen( 
		[in] handle_t handle,
		[in] msg_struct* m,
		[out] long int* rc
		);

}





