#!/bin/ksh
# 
# @OSF_COPYRIGHT@
# COPYRIGHT NOTICE
# Copyright (c) 1990, 1991, 1992, 1993, 1996 Open Software Foundation, Inc.
# ALL RIGHTS RESERVED (DCE).  See the file named COPYRIGHT.DCE in the
# src directory for the full copyright text.
#
# HISTORY
# $Log: rshsp,v $
# Revision 1.1.16.2  1996/03/11  02:49:31  marty
# 	Update OSF copyright years
# 	[1996/03/10  20:10:09  marty]
#
# Revision 1.1.16.1  1995/12/11  22:51:21  root
# 	Submit OSF/DCE 1.2.1
# 
# 	HP revision /main/HPDCE02/1  1994/07/05  18:59 UTC  bissen
# 	Merge hpdce02 (DCE 1.1 beta) and HPDCE01 into HPDCE02
# 
# 	HP revision /main/HPDCE01/1  1994/02/01  18:55  bissen
# 	merge kk and hpdce01
# 	[1995/12/11  22:23:46  root]
# 
# Revision 1.1.7.2  1993/07/09  16:30:29  root
# 	Initial King Kong branch
# 	[1993/07/09  16:29:59  root]
# 
# Revision 1.1.5.3  1993/04/23  15:09:20  giza
# 	added OS portability changes
# 	[1993/04/23  15:08:37  giza]
# 
# Revision 1.1.5.2  1993/04/23  13:23:38  sekhar
# 	Merged Hp_dce1_0_1 changes
# 	[1993/04/16  15:02:21  sekhar]
# 
# 	Embedding copyrights
# 	[1993/02/05  19:30:30  zeliff]
# 
# Revision 1.1.1.7  1993/03/11  22:16:43  osfrcs
# 	    Loading drop DCE1_0_2B18
# 
# Revision 1.1.1.6  1992/09/21  18:43:31  osfrcs
# 	    Loading drop Dce1_0_1fnl
# 
# $EndLog$
#
#
#   NAME: rshsp
#
#   COMPONENT_NAME: dce.systest
#
#   ORIGINS: 27
#
#
#   (C) COPYRIGHT International Business Machines Corp. 1991
#   All Rights Reserved
#
#  DESCRIPTION
#  rshsp duplicates the actions of the rsh command except /etc/profile
#  is sourced before the command is run AND it forces the command to
#  be executed under the Korn Shell.  This command cannot be used to
#  rlogin to a machine.  It will only allow the execution of commands
#  remotely.  All shell special characters which you desire to pass to the remote
#  machine must be triple quoted, eg to do "echo $RANDOM" on the remote
#  machine you must say "rshsp <remote-machine-name> echo \\\$RANDOM" 
#
#  CHANGE ACTIVITY:
#  DATE				AUTHOR				REASON
#  06/13/90			Wayne Mock			Initial Draft
#  11/06/92			Mary MacGregor			Ported to HPUX
#******************************************************************************

#******************************************************************************
# usage()
#
# Prints the usage string for this command
#******************************************************************************

usage()
{
	echo "usage: $PGM host [ -l login ] [ -n ] command"
	exit 1

} # end usage()


#******************************************************************************
# main 
#******************************************************************************
PGM=`basename $0`
RSHSP_FILE=${RSHSP_FILE:-/.kshrc}
TMPFILE=/tmp/$PGM.$$

test $# -lt 2 && usage

HOST=$1; shift

set -- `getopt l:n $*`			# determine the validity of the arguments
test $? -ne 0 && usage

# 
# parse the options
#
unset OPTIONS
while :
do
	case "$1" in
	-l)
		OPTIONS="$OPTIONS-l $2 "
		shift
		;;
	-n)
		OPTIONS="$OPTIONS-n "
		;;
	--)
		shift
		break 2
		;;
	esac
	shift
done

#
# Do not allow rsh to rlogin onto a machine.  there must be a command
#

test $# -eq 0 && usage

# 
# make the rsh call.  It will source the profile then execute the
# given command, all under Korn Shell on the remote machine.
# Characters which are special to the shells on either machine must be
# triple quoted with \\\ in order for them to arrive intact at the
# remote ksh.  Watch it, though, as certain command execution
# interfaces do NOT strip the backslashes.  Experimentation is advised
# in complex situations.
#

${RSH_COMM} $HOST $OPTIONS "ksh -c \". $RSHSP_FILE >/dev/null; \
$* ; echo RSHSP_RETURN_CODE=\\\$?\"" 2>&1 | tee $TMPFILE | \
grep -v RSHSP_RETURN_CODE=

line=`grep RSHSP_RETURN_CODE= $TMPFILE`

if [ "$line" ]; then
	rc=`echo "$line" | cut -f2 -d=`
else
	rc=1		# the remote shell must have failed
	echo "rshsp:  remote shell failed" >&2
fi

rm -f $TMPFILE

# 
# return the return code of the command to the calling process.
#
exit $rc

#******************************************************************************
# end of main
#******************************************************************************
