#!/bin/ksh
# 
# @OSF_COPYRIGHT@
# COPYRIGHT NOTICE
# Copyright (c) 1990, 1991, 1992, 1993, 1996 Open Software Foundation, Inc.
# ALL RIGHTS RESERVED (DCE).  See the file named COPYRIGHT.DCE in the
# src directory for the full copyright text.
#
# HISTORY
# $Log: xx_error,v $
# Revision 1.1.11.2  1996/03/11  02:49:38  marty
# 	Update OSF copyright years
# 	[1996/03/10  20:10:16  marty]
#
# Revision 1.1.11.1  1995/12/11  22:51:49  root
# 	Submit OSF/DCE 1.2.1
# 	[1995/12/11  22:23:54  root]
# 
# Revision 1.1.9.2  1993/07/28  19:40:34  cmckeen
# 	HP's TET'ized version of the system tests
# 	[1993/07/27  13:56:04  cmckeen]
# 
# Revision 1.1.5.3  1993/05/27  19:03:05  eheller
# 	*** empty log message ***
# 
# Revision 1.1.5.2  1993/05/27  14:22:56  eheller
# 	*** empty log message ***
# 	[1993/05/26  18:46:56  eheller]
# 
# Revision 1.1.5.2  1993/04/23  16:20:06  sekhar
# 	Merged Hp_dce1_0_1 changes
# 	[1993/04/16  15:03:09  sekhar]
# 
# Revision 1.1.1.7  1993/03/11  22:16:58  osfrcs
# 	    Loading drop DCE1_0_2B18
# 
# Revision 1.1.3.2  1993/02/05  19:35:02  zeliff
# 	Embedding copyrights
# 	[1993/02/05  19:30:49  zeliff]
# 
# $EndLog$
#
#
#   FILE_NAME: xx_error
#
#   COMPONENT_NAME: dce.systest
#
#   FUNCTIONS: None
#
#   ORIGINS: 27
#
#
#   (C) COPYRIGHT International Business Machines Corp. 1991
#   All Rights Reserved
#
#
#   FOR_TEST: Any
#
#   USAGE:
#
#      xx_error string
#
#      where:
#         string      is the message to be included in
#                     the journal file.
#
#   DESCRIPTION:
#      This is one of the logging tools used
#      by the DCE system tests.
#
#   HISTORY: 
#      11/15/90   Ken Walker     Initial code
#

echo "-error---: $1" | tee -a $JOURNAL
