# 
# @OSF_COPYRIGHT@
# COPYRIGHT NOTICE
# Copyright (c) 1990, 1991, 1992, 1993, 1994, 1996 Open Software Foundation, Inc.
# ALL RIGHTS RESERVED (DCE).  See the file named COPYRIGHT.DCE for
# the full copyright text.
# 
# HISTORY
# $Log: Makefile,v $
# Revision 1.1.4.2  1996/03/11  02:48:41  marty
# 	Update OSF copyright years
# 	[1996/03/10  20:09:28  marty]
#
# Revision 1.1.4.1  1995/12/11  22:48:22  root
# 	Submit OSF/DCE 1.2.1
# 	[1995/12/11  22:22:52  root]
# 
# Revision 1.1.2.3  1994/06/22  16:40:54  hester
# 	added run.svc
# 	[1994/06/22  16:27:48  hester]
# 
# Revision 1.1.2.2  1994/06/17  18:46:22  devsrc
# 	cr10872 - fix copyright
# 	[1994/06/17  18:38:08  devsrc]
# 
# Revision 1.1.2.1  1994/05/18  21:12:28  hester
# 	initial version for svc cfg systests
# 	[1994/05/13  20:16:34  hester]
# 
# $EndLog$

run.svc_IDIR    = /test/tet/system/svc/bin/
tetexec.cfg_IDIR = /test/tet/system/svc/
tet_scen_IDIR   = /test/tet/system/svc/
tet_code_IDIR   = /test/tet/system/svc/
README_IDIR     = /test/tet/system/svc/
ILIST           = run.svc tetexec.cfg tet_scen tet_code README
SUBDIRS         = ts


.include <${RULES_MK}>
