/*
 * @OSF_COPYRIGHT@
 * COPYRIGHT NOTICE
 * Copyright (c) 1996 Open Software Foundation, Inc.
 * ALL RIGHTS RESERVED (DCE).  See the file named COPYRIGHT.DCE for
 * the full copyright text.
 * 
 */
/*
 * HISTORY
 * $Log: number.idl,v $
 * Revision 1.1.2.2  1996/03/09  20:49:47  marty
 * 	Add OSF copyright
 * 	[1996/03/09  20:28:06  marty]
 *
 * Revision 1.1.2.1  1995/12/11  19:35:39  root
 * 	Submit OSF/DCE 1.2.1
 * 	[1995/12/11  19:18:43  root]
 * 
 * $EndLog$
 */
[
    uuid(b5afb342-ad90-11ce-b8df-08002b39789f)
] interface Number
{
    /* Get the value from the Number object */
    double get();

    void die();

}
