/*
 * @OSF_COPYRIGHT@
 * COPYRIGHT NOTICE
 * Copyright (c) 1990, 1991, 1992, 1993, 1996 Open Software Foundation, Inc.
 * ALL RIGHTS RESERVED (DCE).  See the file named COPYRIGHT.DCE in the
 * src directory for the full copyright text.
 */
/*
 * HISTORY
 * $Log: stringts.idl,v $
 * Revision 1.1.4.2  1996/03/11  02:18:58  marty
 * 	Update OSF copyright years
 * 	[1996/03/10  19:55:48  marty]
 *
 * Revision 1.1.4.1  1995/12/11  19:30:30  root
 * 	Submit OSF/DCE 1.2.1
 * 	[1995/12/11  19:16:06  root]
 * 
 * Revision 1.1.2.2  1993/01/07  23:38:57  bbelch
 * 	Embedding copyright notice
 * 	[1993/01/06  13:45:28  bbelch]
 * 
 * Revision 1.1  1992/01/19  03:28:33  devrcs
 * 	Initial revision
 * 
 * $EndLog$
 */
/*
*/
[uuid(2ede3e38-ffc4-11c8-8ae4-08002b104860), version(0)]
interface stringts
{
    typedef byte PRIVATE_CHAR_8;
    typedef struct {
	byte row,column;
	} PRIVATE_CHAR_16;

    void op_fixed (
        [in] handle_t h,
        [in,string] char f_i[81],
        [in,out,string] char f_io[81],
        [out,string] char f_o[81]
    );

    void op_conf (
        [in] handle_t h,
        [in] small i_size,
        [in,string,size_is(i_size)] byte c_i[],
        [in] short io_size,
        [in,out,string, size_is(io_size)] byte c_io[],
        [in] long o_size,
        [out,string,size_is(o_size)] byte c_o[]
    );

    void op_self (
        [in] handle_t h,
        [in,string] ISO_LATIN_1 s_i[],
        [in,out,string] ISO_LATIN_1 s_io[]
    );

    typedef struct private_8 {
        [string] PRIVATE_CHAR_8 f_p_8[27];
        [string] PRIVATE_CHAR_8 s_p[];
    } private_8;

    typedef struct two_byte {
        [string] ISO_MULTI_LINGUAL m_l[27];
        [string] PRIVATE_CHAR_16 p_16[];
    } two_byte;

    void op_multi (
        [in] handle_t h,
        [in,string] ISO_UCS m_i[],
        [out,string] ISO_UCS m_o[14],
        [in,out] private_8 *p8,
        [in,out] two_byte *tb
    );

}
