# 
# @OSF_COPYRIGHT@
# COPYRIGHT NOTICE
# Copyright (c) 1996 Open Software Foundation, Inc.
# ALL RIGHTS RESERVED (DCE).  See the file named COPYRIGHT.DCE for
# the full copyright text.
# 
# 
# HISTORY
# $Log: Makefile,v $
# Revision 1.1.2.2  1996/11/14  16:15:27  arvind
# 	OSF DCE 1.2.2 Drop 5
# 	[1996/11/14  14:30:16  arvind]
#
# $EndLog$
# 

SUBDIRS	= ggacl ggapi ggcmd ggstrs
DATA_SUBDIRS = ggacl ggapi ggcmd ggstrs

.include <${RULES_MK}>

