/*
 * @OSF_COPYRIGHT@
 * Copyright (c) 1994, 1996 Open Software Foundation, Inc.
 * ALL RIGHTS RESERVED (DCE).  See the file named COPYRIGHT.DCE in the
 * src directory for the full copyright text.
 * 
 */
/*
 * HISTORY
 * $Log: dts_test.idl,v $
 * Revision 1.1.4.2  1996/03/11  02:48:00  marty
 * 	Update OSF copyright years
 * 	[1996/03/10  20:08:58  marty]
 *
 * Revision 1.1.4.1  1995/12/11  22:45:13  root
 * 	Submit OSF/DCE 1.2.1
 * 	[1995/12/11  22:21:28  root]
 * 
 * Revision 1.1.2.2  1994/10/18  18:51:35  agd
 * 	expand copyright
 * 	[1994/10/18  17:40:06  agd]
 * 
 * Revision 1.1.2.1  1994/09/29  21:02:53  bhaim
 * 	submit dlgcfg002 test
 * 	[1994/09/29  21:01:29  bhaim]
 * 
 * $EndLog$
 */
[
    uuid(0014e5cf-85c4-1e11-9b81-0000c083e054)

]


interface dts_test {

    import "dce/aclbase.idl";
    boolean32 dts_test_access (
        [in]        handle_t                    h,
        [in]        sec_acl_component_name_t    component_name,
        [in]        sec_acl_permset_t           *permset,
        [out]       error_status_t              *st
    );

}

