/*
 * @OSF_COPYRIGHT@
 * COPYRIGHT NOTICE
 * Copyright (c) 1990, 1991, 1992, 1993, 1996 Open Software Foundation, Inc.
 * ALL RIGHTS RESERVED (DCE).  See the file named COPYRIGHT.DCE in the
 * src directory for the full copyright text.
 */
/*
 * HISTORY
 * $Log: arrayp.idl,v $
 * Revision 1.1.4.2  1996/03/11  02:09:09  marty
 * 	Update OSF copyright years
 * 	[1996/03/10  19:51:25  marty]
 *
 * Revision 1.1.4.1  1995/12/11  19:56:10  root
 * 	Submit OSF/DCE 1.2.1
 * 	[1995/12/11  19:28:12  root]
 * 
 * Revision 1.1.2.2  1993/01/07  19:04:08  bbelch
 * 	Embedding copyright notice
 * 	[1993/01/06  13:25:58  bbelch]
 * 
 * Revision 1.1  1992/01/19  03:29:27  devrcs
 * 	Initial revision
 * 
 * $EndLog$
 */
/*
*/
[
uuid(b2688cfe-f7ff-11c9-ae64-08002b1110fa),
version(0),
pointer_default(ptr)
]
interface arrayp
{
    const long MAXNAME = 10;

    typedef struct {char c;} char_t;
    typedef struct {long l;} long_t;

    typedef struct
    {
        long one;
        char_t *two;
        short three;
    } cp_t;

    typedef union switch (long i) tag
    {
        case 0: char name[MAXNAME];
        case 1: char *namep[MAXNAME];
        default:;
    } u_t;

    typedef struct
    {
        short namelen;
        u_t body;
        long checksum;
    } s_t;

    short op0 ([in] handle_t h, 
               [in] long l,
               [in] long check1,
               [in] long check2,
               [in, out, size_is(l)] cp_t carray[], 
               [in, out, size_is(l)] long_t *larray[]);

    short op1([in] handle_t h, [in] long size, 
              [in, size_is(size)] s_t sarray[]);
}
