#
# @OSF_COPYRIGHT@
# COPYRIGHT NOTICE
# Copyright (c) 1990, 1991, 1992, 1993, 1996 Open Software Foundation, Inc.
# ALL RIGHTS RESERVED (DCE).  See the file named COPYRIGHT.DCE in the
# src directory for the full copyright text.
#
#
# HISTORY
# $Log: Makefile,v $
# Revision 1.1.8.2  1996/03/11  02:09:06  marty
# 	Update OSF copyright years
# 	[1996/03/10  19:51:24  marty]
#
# Revision 1.1.8.1  1995/12/11  19:56:05  root
# 	Submit OSF/DCE 1.2.1
# 	[1995/12/11  19:28:11  root]
# 
# Revision 1.1.6.1  1993/12/28  22:09:15  pellis
# 	Updated for ODE 2.3 make
# 	[1993/12/28  21:52:56  pellis]
# 
# Revision 1.1.4.2  1993/01/07  19:04:03  bbelch
# 	Embedding copyright notice
# 	[1993/01/06  13:25:55  bbelch]
# 
# Revision 1.1  1992/01/19  03:29:26  devrcs
# 	Initial revision
# 
# $EndLog$
#

IDLBASE = arrayp
OTHER_CLIENT_FILES = client_aux.o

.include "../maketest.mk"
