#
# @OSF_COPYRIGHT@
# COPYRIGHT NOTICE
# Copyright (c) 1990, 1991, 1992, 1993, 1996 Open Software Foundation, Inc.
# ALL RIGHTS RESERVED (DCE).  See the file named COPYRIGHT.DCE in the
# src directory for the full copyright text.
#
# HISTORY
# $Log: Makefile,v $
# Revision 1.1.4.2  1996/03/11  02:37:16  marty
# 	Update OSF copyright years
# 	[1996/03/10  20:04:50  marty]
#
# Revision 1.1.4.1  1995/12/11  21:54:07  root
# 	Submit OSF/DCE 1.2.1
# 	[1995/12/11  20:54:46  root]
# 
# Revision 1.1.2.2  1993/03/24  20:29:47  gmd
# 	Original submission for 1.0.2.
# 	[1993/03/24  20:07:27  gmd]
# 
# $EndLog$
#
OTHERS	= admin_checklist

ILIST	= ${OTHERS}

.include <${RULES_MK}>

