/*
 * @OSF_COPYRIGHT@
 * COPYRIGHT NOTICE
 * Copyright (c) 1990, 1991, 1992, 1993, 1996 Open Software Foundation, Inc.
 * ALL RIGHTS RESERVED (DCE).  See the file named COPYRIGHT.DCE in the
 * src directory for the full copyright text.
 */
/*
 * HISTORY
 * $Log: refptrs.idl,v $
 * Revision 1.1.4.2  1996/03/11  02:17:41  marty
 * 	Update OSF copyright years
 * 	[1996/03/10  19:55:05  marty]
 *
 * Revision 1.1.4.1  1995/12/11  19:28:44  root
 * 	Submit OSF/DCE 1.2.1
 * 	[1995/12/11  19:15:17  root]
 * 
 * Revision 1.1.2.2  1993/01/07  23:33:34  bbelch
 * 	Embedding copyright notice
 * 	[1993/01/06  13:41:32  bbelch]
 * 
 * Revision 1.1  1992/01/19  03:27:01  devrcs
 * 	Initial revision
 * 
 * $EndLog$
 */
/*
*/
[
uuid (52817c7c-ffc4-11c8-8ae4-08002b104860),
pointer_default(ptr),
version(0.0)
]
interface refptrs
{

    typedef char leafchar_t;

    typedef struct refleaf_t {
        char rl_char;
        [ref] leafchar_t *rl_ptr;
    } refleaf_t;

    typedef struct refnode_t {
        char rn_char;
        [ref] refleaf_t *rn_ptr;
    } refnode_t;

    typedef struct mutnode_t {
        char mn_char;
        refleaf_t *mn_ptr;
    } mutnode_t;

    void op1 (
        [in] handle_t h,
        [in,out] refnode_t *p_refnode,
        [in,out] mutnode_t *p_notchanged,
        [in,out] mutnode_t *p_changed
    );
}
