# @OSF_COPYRIGHT@
# COPYRIGHT NOTICE
# Copyright (c) 1990, 1991, 1992, 1993, 1994, 1996 Open Software Foundation, Inc.
# ALL RIGHTS RESERVED (DCE).  See the file named COPYRIGHT.DCE for
# the full copyright text.
# 
# 
# HISTORY
# $Log: Makefile,v $
# Revision 1.1.4.2  1996/03/11  02:50:07  marty
# 	Update OSF copyright years
# 	[1996/03/10  20:10:46  marty]
#
# Revision 1.1.4.1  1995/12/11  22:56:33  root
# 	Submit OSF/DCE 1.2.1
# 	[1995/12/11  22:34:26  root]
# 
# Revision 1.1.2.2  1994/06/10  20:50:58  devsrc
# 	cr10872 - fixed copyright
# 	[1994/06/10  17:20:02  devsrc]
# 
# Revision 1.1.2.1  1994/02/10  22:54:36  rousseau
# 	Initial version
# 	[1994/02/10  22:51:42  rousseau]
# 
# 	Created TCL API.
# 	[1993/12/17  21:03:16  rousseau]
# 
# $EndLog$

SUBDIRS		= api
DATA_SUBDIRS	= ${SUBDIRS}

.include <${RULES_MK}>
