/*
 * @OSF_COPYRIGHT@
 * COPYRIGHT NOTICE
 * Copyright (c) 1990, 1991, 1992, 1993, 1996 Open Software Foundation, Inc.
 * ALL RIGHTS RESERVED (DCE).  See the file named COPYRIGHT.DCE in the
 * src directory for the full copyright text.
 */
/*
 * HISTORY
 * $Log: rpc_sec_2.idl,v $
 * Revision 1.1.75.2  1996/03/11  02:47:01  marty
 * 	Update OSF copyright years
 * 	[1996/03/10  20:08:34  marty]
 *
 * Revision 1.1.75.1  1995/12/11  22:44:17  root
 * 	Submit OSF/DCE 1.2.1
 * 	[1995/12/11  22:20:53  root]
 * 
 * Revision 1.1.73.1  1993/09/09  19:13:10  cmckeen
 * 	 HP's TET'ized version
 * 	[1993/09/09  19:12:05  cmckeen]
 * 
 * Revision 1.1.6.2  1993/08/16  14:45:53  eheller
 * 	File tetified.
 * 	[1993/07/23  17:48:53  eheller]
 * 
 * Revision 1.1.2.4  1993/02/25  20:16:56  mhickey
 * 	Fixing bcs problem
 * 	[1993/02/25  20:03:18  mhickey]
 * 
 * Revision 1.1.2.3  1993/02/05  15:23:28  cjd
 * 	Embedded copyright notice
 * 	[1993/02/05  14:44:59  cjd]
 * 
 * Revision 1.1.4.2  1993/02/04  22:14:32  cjd
 * 	Embedded copyright notice
 * 
 * Revision 1.1.2.2  1992/12/03  19:53:38  mhickey
 * 	Initial check submit for rpc.sec.2 system test.
 * 
 * 	Defect 5887.
 * 	[1992/12/03  15:44:15  mhickey]
 * 
 * 	Version 1.1 of the interface.  Added definitions for a struct
 * 	containing a conformant array of longs, and a function call
 * 	tstrpc_cnf_str().
 * 	[1992/10/10  03:08:22  mhickey]
 * 
 * 	Initial checkin for base for rpc.security.2
 * 	[1992/10/06  17:28:32  mhickey]
 * 
 * $EndLog$
 */

/*---*
 *---* rpc.sec.2.idl - IDL file for the rpc.sec.2 System test
 *---*
 *---* ASSOCIATION
 *---*    This file is part of the rpc.sec.2 DCE System Test
 *---*
 *---*    The rpc.sec.2 system test corresponds to test rpc.sec.2 in the 
 *---*    DCE1.0.2 Core Component System Test plan.  For more information on 
 *---*    the operation and goals of the rpc.sec.2 system test, see the test 
 *---*    plan, or the README file in this directory.
 *---* 
 *---* FUNCTION
 *---*    Declares the interface UUID, interface signature and data structures
 *---*    used by calls to the interface for system test rpc.sec.2.
 *---* 
 *---* CALLED BY
 *---*    Referenced during build of the client and server programs.
 *---* 
 *---* CALLS INTO 
 *---*    Nothing.
 *---*
 *---* PREREQUISITES
 *---*    None.
 *---*
 *---*/

/*---* Interface UUID (from uuidgen) *---*/

[
uuid(00868D82-3B6F-1ABF-A630-08002B14B387),
pointer_default(ptr),
version(1.1)
]

interface rpcsec2
{
   /*---* define the struct containing the conformant array *---*/
   typedef struct 
           {
             long id;          /*---* thread or proc idfor checksum use *---*/
             short   size;            /*---* size for array member      *---*/
             [size_is(size)] long array[];  /*---* the array member *---*/
	   } long_conf_struct_t, *long_conf_struct_p_t;

   void rpcsec2_nop(
     [in,out] small          *val,
     [in,out] long           *stat,
     [in,out] error_status_t *fstat,
     [in,out] error_status_t *cstat);

   void rpcsec2_cnf_str(
     [in]     short type_flag,                 /*---* type of array      *---*/
     [in,out] long_conf_struct_t *conf_str_p,  /*---* struct pointer     *---*/
     [in,out] long           *stat,            /*---* function return    *---*/
     [in,out] error_status_t *fstat,           /*---* fault status       *---*/
     [in,out] error_status_t *cstat);          /*---* comm status        *---*/
}



