/*
 *  @OSF_COPYRIGHT@
 *  COPYRIGHT NOTICE
 *  Copyright (c) 1990, 1991, 1992, 1993, 1996 Open Software Foundation, Inc.
 *  ALL RIGHTS RESERVED (DCE).  See the file named COPYRIGHT.DCE in the
 *  src directory for the full copyright text.
 */

/*
 * HISTORY
 * $Log: dcesx0.idl,v $
 * Revision 1.1.6.2  1996/03/11  01:45:08  marty
 * 	Update OSF copyright years
 * 	[1996/03/10  19:15:52  marty]
 *
 * Revision 1.1.6.1  1995/12/08  22:09:58  root
 * 	Submit OSF/DCE 1.2.1
 * 	[1995/12/08  21:44:22  root]
 * 
 * Revision 1.1.4.2  1993/01/12  18:29:37  bbelch
 * 	Embedding copyright notice
 * 	[1993/01/07  01:13:26  bbelch]
 * 
 * Revision 1.1.2.2  1992/06/08  19:58:14  weisman
 * 		Original submission.
 * 	[1992/06/08  19:30:03  weisman]
 * 
 * $EndLog$
 */
/*
**  Copyright (c) 1991 by
**      Digital Equipment Corporation, Maynard, Mass.
**
**  %a%copyright(,**  )
**
**  NAME
**
**      dcesx0.idl
**
**  FACILITY:
**
**      DCE System Exerciser
**
**  ABSTRACT:
**
**  Definitions of types/constants external to the DCE System Exerciser.
**
**  %a%private_begin
**
**  MODIFICATION HISTORY:
**
**  27-aug-91 sudama    original creation
**
**  %a%private_end  
*/


[
uuid(9b1a44e8-712b-11ca-87dc-08002b1ac4a1),
version(1.0)
]

interface dcesx_if0
{

void dcesx_server
(
        [in]  handle_t                  rpc_binding_handle,
        [in]  unsigned long             if_index,
        [out] error_status_t            *status
);

}
