/*
 * @OSF_COPYRIGHT@
 * COPYRIGHT NOTICE
 * Copyright (c) 1990, 1991, 1992, 1993, 1994, 1996 Open Software Foundation, Inc.
 * ALL RIGHTS RESERVED (DCE).  See the file named COPYRIGHT.DCE for
 * the full copyright text.
 * 
 */
/*
 * HISTORY
 * $Log: string_conv3.idl,v $
 * Revision 1.1.4.2  1996/03/11  02:48:13  marty
 * 	Update OSF copyright years
 * 	[1996/03/10  20:09:05  marty]
 *
 * Revision 1.1.4.1  1995/12/11  22:46:11  root
 * 	Submit OSF/DCE 1.2.1
 * 	[1995/12/11  22:21:55  root]
 * 
 * Revision 1.1.2.2  1994/10/06  20:47:26  agd
 * 	expand copyright
 * 	[1994/10/06  14:33:10  agd]
 * 
 * Revision 1.1.2.1  1994/09/19  18:15:55  bhaim
 * 	multidelegate test
 * 	[1994/09/19  17:50:12  bhaim]
 * 
 * $EndLog$
 */
/*
 ***************************************************************************
 * This .idl file declares an interface for string conversion and a single
 * remote procedure.  The interface defines a fixed-length string type that
 * is passed by reference to the remote procedure, modified, and passed
 * back.
 ***************************************************************************
 */
/*
 * (c) Copyright 1992, 1993 Hewlett-Packard Co.
 */

/* 
 * Define the interface for this application.  This interface specification
 * defines pointers to be reference-style by default for efficiency.  For a
 * description of reference and full pointers, refer to the DCE Application
 * Development Guide, section 17.14.7.1, Pointer Attributes.  The pointers
 * used in this application conform to the restrictions of reference
 * pointers so they are used because they are faster and easier to use.
 * 
 * NOTE: The RPC runtime uses the UUID below to identify this interface.  If
 * you leverage this code, BE SURE TO CHANGE THE UUID!  (Use "uuidgen").
 */

[uuid(0c57ca10-2942-11cd-90bf-0800096159f5),
pointer_default(ref),
version(1.0)]
interface string_conv3
{
   import "string_conv.idl";

   /* Define the server number for this idl.  We will compare the user
    * supplied number with this number to determine if we are in the
    * correct function.
    */
   const unsigned long  conv_3_interface_number = 3;

   /*
    * Define the procedure to convert a string to uppercase.  The
    * string_convert_uppercase procedure takes a handle, since the explicit
    * binding method is used to locate a server.  The other argument is a
    * string data type used both for input and output.  This emulates a C
    * "call by reference": upon return from the procedure call the pointer
    * now points to different data, but the pointer address is still the
    * same.  (The client stub unmarshals the data it receives from the
    * server into the same space).
    * 
    * The string_convert_uppercase function is declared to be idempotent
    * for efficiency reasons.  The idempotent attribute tells the IDL
    * compiler that if the function is called multiple times with the same
    * arguments it will have the same effect.  This means a call to an
    * idempotent function can be resent without adverse side effects; this
    * allows the RPC protocol to be more efficient, at least when using a
    * datagram transport.
    */
   [idempotent] void string_convert_uppercase3
   (
   [in]	handle_t          h,		/* Use explicit binding */
   [in,out] string_ref_t  conv_string,	/* The string to convert */
   [in] string_ref_t      num_serv,	/* Number of servers to use for delegation */
   [out] error_status_t   *auth_status  /* [jdl 14 Feb 1994] */
   );
}
