/*
 * @OSF_COPYRIGHT@
 * COPYRIGHT NOTICE
 * Copyright (c) 1990, 1991, 1992, 1993, 1996 Open Software Foundation, Inc.
 * ALL RIGHTS RESERVED (DCE).  See the file named COPYRIGHT.DCE in the
 * src directory for the full copyright text.
 */
/*
 * (c) Copyright 1991, 1992 Siemens-Nixdorf Information Systems, Burlington, MA, USA
 * All Rights Reserved
 */
/*
 * HISTORY
 * $Log: epv.idl,v $
 * Revision 1.1.5.2  1996/03/11  02:12:45  marty
 * 	Update OSF copyright years
 * 	[1996/03/10  19:52:49  marty]
 *
 * Revision 1.1.5.1  1995/12/11  20:03:34  root
 * 	Submit OSF/DCE 1.2.1
 * 	[1995/12/11  19:30:39  root]
 * 
 * Revision 1.1.3.3  1993/01/07  19:55:48  bbelch
 * 	Embedding copyright notice
 * 	[1993/01/06  13:33:07  bbelch]
 * 
 * Revision 1.1.3.2  1992/09/29  21:21:12  devsrc
 * 	SNI/SVR4 merge.  OT 5373
 * 	[1992/09/11  15:46:30  weisman]
 * 
 * Revision 1.1  1992/01/19  03:29:02  devrcs
 * 	Initial revision
 * 
 * $EndLog$
 */
[
    uuid(d9255460-fda6-11c9-98cf-08001e0218e9),
    version(0.0)
]
interface epv {

    const char *epv_name = "'-cepv and no -no_mepv' test";

    const long epv_length = 16;
    const char *epv_name_op0 = "epv_op0";
    const char *epv_name_op1 = "epv_op1";

    typedef [string] char namearray[epv_length];

    void epv_op0(
        [in]            handle_t    h,
	[in,out] namearray	name
    );

    void epv_op1(
        [in]            handle_t    h,
	[in,out] namearray	name
    );

}
