/*
 * @OSF_COPYRIGHT@
 * COPYRIGHT NOTICE
 * Copyright (c) 1990, 1991, 1992, 1993 Open Software Foundation, Inc.
 * ALL RIGHTS RESERVED (DCE).  See the file named COPYRIGHT.DCE in the
 * src directory for the full copyright text.
 */
/*
 * HISTORY
 * $Log: spoke.idl,v $
 * Revision 1.1.618.1  1996/10/17  18:28:41  damon
 * 	Submitting on behalf of Transarc
 * 	[1996/10/17  16:54:24  damon]
 *
 * Revision 1.1.613.1  1994/02/04  20:46:21  devsrc
 * 	Merged from 1.0.3a to 1.1
 * 	[1994/02/04  15:24:59  devsrc]
 * 
 * Revision 1.1.611.1  1993/12/07  17:45:25  jaffe
 * 	1.0.3a update from Transarc
 * 	[1993/12/03  19:23:50  jaffe]
 * 
 * Revision 1.1.4.3  1993/01/11  18:32:09  htf
 * 	Embedded copyright notice
 * 	[1993/01/11  17:12:46  htf]
 * 
 * Revision 1.1.4.2  1992/11/20  19:05:33  jaffe
 * 	Interface file for itl/spoke program
 * 	[1992/11/20  19:04:33  jaffe]
 * 
 * $EndLog$
 */
[
uuid(00897236-3F2E-1ACB-85E4-C037CF490000),
version(1.0)
]
interface spoke
{
	typedef struct {
		unsigned32 tv_sec, tv_usec;
	} spoke_time_t;

	/* a do-nothing RPC, used to "fully bind" a handle. */
	error_status_t spoke_remote_null([in] handle_t h);

	/* handshake RPC, for setting up two-way hub-spoke communication */
	error_status_t
	spoke_remote_setup( [in] handle_t h,
		[in, ptr, string] char * client_binding);

	/* synchronization RPC:  blocking, made by client to server */
	error_status_t
	spoke_remote_syncpoint( [in] handle_t h,
		[in, string] char * syncpoint_name,
		[in] unsigned32 timeout_value,
		[out] unsigned32 * timed_out );

	/* execute the supplied string as if it were an ITL procedure */

	error_status_t
	spoke_execute_string( [in] handle_t h,
		[ in, ptr, string] char * executeString,
		[ out] unsigned32 * status );

	/* causes the spoke to exit */

[maybe, idempotent]
	void
	spoke_remote_exit(
		[ in ] handle_t h
	);	
}
