/* ______________________________________________________________________
 * Copyright (c) 1996 The Open Group, Inc., Cambridge, MA USA
 * All rights reserved.
 * ______________________________________________________________________
 *
 *	M O S _ C O N V E R T . I D L
 *
 * Conversion functions, for serializing data (to be written to backing
 * stores and the ack structure).
 * ______________________________________________________________________
 *
 * $Log: mos_convert.idl,v $
 * Revision 1.2  1996/11/13  17:22:15  bowe
 * Remove mos_ack_convert.
 *
 * Revision 1.1  1996/09/12  15:42:58  bowe
 * Initial revision
 *
 * $EndLog$
 * ______________________________________________________________________
 */

[
    uuid(8c0245fc-3d75-11d0-8293-080009cd681c),
    pointer_default(ptr),
    version(1.0)
]

interface mos_convert
{
    import "mos_base.idl";

    /* ________________________________________________________ */

    /* attributes of a queue */
    void mos_qattr_convert(
	[in]		handle_t	h,
	[in,out]	mos_qattr_t	*data,
	[in,out]	error_status_t	*st
    );

    /* persistent queue items */
    void mos_q_item_convert(
	[in]		handle_t	h,
	[in,out]	mos_qitem_t	*data,
	[in,out]	error_status_t	*st
    );

    /* ________________________________________________________ */
}


