/* ______________________________________________________________________
 * Copyright (c) 1996 The Open Group, Inc., Cambridge, MA USA
 * All rights reserved.
 * ______________________________________________________________________
 *
 *	M O S _ M G M T . I D L
 *
 * Message-Oriented Services management interface.
 * ______________________________________________________________________
 *
 * $Log: mos_mgmt.idl,v $
 * Revision 1.5  1996/09/26  15:25:17  bowe
 * Added mos_mgmt_info.
 *
 * Revision 1.4  1996/09/25  15:17:45  bowe
 * In mos_mgmt_create_queue, make qattr [in,out]. Remove id arg.
 *
 * Revision 1.3  1996/09/18  17:43:38  bowe
 * Remove mos_mgmt_dump_queue operation.
 *
# Revision 1.2  1996/09/17  20:19:45  bowe
# Removed 'name' param from mos_mgmt_create_queue.
#
# Revision 1.1  1996/09/12  15:42:58  bowe
# Initial revision
#
 * $EndLog$
 * ______________________________________________________________________
 */

[
    uuid(27bb4a22-b985-11cf-a81a-0800092474cc),
    pointer_default(ptr),
    version(1.0)
]

interface mos_mgmt
{
    import "mos_base.idl";

    /* ________________________________________________________ */

    /* Create a new queue */
    void mos_mgmt_create_queue(
	[in]	handle_t	h,
	[in,out]
		mos_qattr_t	*qattr,
	[out]	error_status_t	*st
    );

    /* Get list of all queues (IDs) */
    void mos_mgmt_get_id_list(
	[in]	handle_t	h,
	[out]	mos_uuid_list_t	*ids,
	[out]	error_status_t	*st
    );
    /* Get list of all queues (names) */
    void mos_mgmt_get_name_list(
	[in]	handle_t	h,
	[out]	mos_string_list_t *names,
	[out]	error_status_t	*st
    );

    /* Rename a queue */
    void mos_mgmt_rename(
	[in]	handle_t	h,
	[in,string]
		char		*from_name,
	[in,string]
		char		*to_name,
	[out]	error_status_t	*st
    );

    /* Get info about the qmgr */
    void mos_mgmt_info(
	[in]	handle_t	h,
	[out]	mos_kv_pair_list_t
				*list,
	[out]	error_status_t	*st
    );
    /* Migrate all items of one queue to another */
    void mos_mgmt_move(
	[in]	handle_t	h,
	[in,string]
		char		*from_queue,
	[in,string]
		char		*to_queue,
	[out]	error_status_t	*st
    );

    /* ________________________________________________________ */
}

