/*
 * @OSF_COPYRIGHT@
 * COPYRIGHT NOTICE
 * Copyright (c) 1996 Open Software Foundation, Inc.
 * ALL RIGHTS RESERVED (DCE).  See the file named COPYRIGHT.DCE for
 * the full copyright text.
 * 
 */
/*
 * HISTORY
 * $Log: icalculate.idl,v $
 * Revision 1.1.2.2  1996/03/09  20:49:57  marty
 * 	Add OSF copyright
 * 	[1996/03/09  20:28:13  marty]
 *
 * Revision 1.1.2.1  1995/12/11  19:35:53  root
 * 	Submit OSF/DCE 1.2.1
 * 	[1995/12/11  19:18:49  root]
 * 
 * $EndLog$
 */
[uuid(de41d120-e2db-11ce-beea-08002be415b2)]

/*
** An interface for a reverse Polish notatoin calculator.
** An Stack is maintained in the clients address space but the 
** arithmetic operation occur in the server's address space.
** The server needs access to the client's Stack object.
*/

interface ICalculate
{
	import "istack.idl";		/* get the IStack definition */

	/* 
	** static function to create a new calculator
	*/
	static ICalculate *newCalc(
		[in] IStack *s		/* stack interface pointer  */
	);

	/*
	** The arithmetic operations
	*/
	void plus();
	void minus();
	void multiply();
	void divide();
}
