/*
 * @OSF_COPYRIGHT@
 * COPYRIGHT NOTICE
 * Copyright (c) 1996 Open Software Foundation, Inc.
 * ALL RIGHTS RESERVED (DCE).  See the file named COPYRIGHT.DCE for
 * the full copyright text.
 * 
 */
/*
 * HISTORY
 * $Log: istack.idl,v $
 * Revision 1.1.2.2  1996/03/09  20:49:59  marty
 * 	Add OSF copyright
 * 	[1996/03/09  20:28:14  marty]
 *
 * Revision 1.1.2.1  1995/12/11  19:35:56  root
 * 	Submit OSF/DCE 1.2.1
 * 	[1995/12/11  19:18:50  root]
 * 
 * $EndLog$
 */
[uuid(0ea74f20-e2dc-11ce-9a8e-08002be415b2)]

/*
** a Stack interface definition - acts as a wrapper to a Stack object so
** that an interface pointer to the Stack object can be used as an RPC
** argument.
*/

interface IStack
{
	/*
	** Define any operations that are part of the Stack class
	** that are to be exported. They allow a remote procedure to access
	** the local object via these exported operations.
	**
	** The acf file uses the cxx_delegate attribute and 
	** these operations must be members of the delegated class.
	*/

	double pop();
	void push(
		[in] double x
	);
}
