/* ______________________________________________________________________
 * Copyright (c) 1996 The Open Group, Inc., Cambridge, MA USA
 * All rights reserved.
 * ______________________________________________________________________
 *
 * MODULE:       charge_base.idl
 *
 * DESCRIPTION:  Defines the "charge message" interface for all telcom
 *               test programs.
 * ______________________________________________________________________
 *
 * $Log: charge_base.idl,v $
Revision 1.1  1996/11/20  17:00:27  salamone
Initial version

 * $EndLog$
 * ______________________________________________________________________
 */

[
    uuid(fd1c7fd6-3975-11d0-94b7-0800095fae3a),
    pointer_default(ptr),
    version(1.0)
]

interface charge_base
{

   import "dce/utctypes.idl";

   /*
    * charge message examples
    *         "999-9999,111-1111,06/06/96,4 minutes,$15.00",
    *         "999-9999,222-2222,06/07/96,2 minutes,$10.30",
    *         "999-9999,333-3333,06/03/96,30 minutes,$90.00",
    *         "999-9999,444-4444,06/04/96,6 minutes,$11.30",
    *         "999-9999,555-5555,06/05/96,1 minute,$20.00",
    */
   typedef struct telcom_datatype_charge_s_t {
      [ptr,string] char *                   calling_party;
      [ptr,string] char *                   called_party;
                   utc_t                    timestamp;
                   unsigned32               duration;
                   unsigned32               cost;
   } telcom_datatype_charge_t;

}
