/* ______________________________________________________________________
 * Copyright (c) 1996 The Open Group, Inc., Cambridge, MA USA
 * All rights reserved.
 * ______________________________________________________________________
 *
 * MODULE:       mwi_base.idl
 *
 * DESCRIPTION:  Defines the "mwi message" interface for all telcom
 *               test programs.
 * ______________________________________________________________________
 *
 * $Log: mwi_base.idl,v $
Revision 1.1  1996/11/20  17:00:42  salamone
Initial version

 * $EndLog$
 * ______________________________________________________________________
 */

[
    uuid(7a0cd0fa-3975-11d0-9ef4-0800095fae3a),
    pointer_default(ptr),
    version(1.0)
]

interface mwi_base
{

    /*
     * Message waiting Indicator: off or on
     */
    const unsigned32 telcom_c_mwi_off    = 0x00000000;
    const unsigned32 telcom_c_mwi_on     = 0x00000001;

    /*
     * mwi message type examples
     *         "111-1111,ON",
     *         "222-2222,ON",
     *         "333-3333,ON",
     *         "444-4444,ON",
     *         "555-5555,ON",
     */
    typedef struct telcom_datatype_mwi_s_t {
       [ptr,string] char *                   phone_number;
                    unsigned32               mwi_status;
    } telcom_datatype_mwi_t;

}
