/* ______________________________________________________________________
 * Copyright (c) 1996 The Open Group, Inc., Cambridge, MA USA
 * All rights reserved.
 * ______________________________________________________________________
 *
 * MODULE:       telcom_convert.idl
 *
 * DESCRIPTION:  Defines the conversion functions necessary to support
 *               marshalling of "mwi" and "charge" messages for all
 *               telcom test programs.
 * ______________________________________________________________________
 *
 * $Log: telcom_convert.idl,v $
Revision 1.1  1996/11/20  17:00:53  salamone
Initial version

 * $EndLog$
 * ______________________________________________________________________
 */

[
    uuid(f0523f1a-3976-11d0-801c-0800095fae3a),
    pointer_default(ptr),
    version(1.0)
]

interface telcom_convert
{
    import "charge_base.idl";
    import "mwi_base.idl";

    void 
    charge_conversion_func(
          [in]        handle_t                     handle, 
          [in, out]   telcom_datatype_charge_t *   charge_data, 
          [in, out]   error_status_t *             status
    );

    void 
    mwi_conversion_func(
          [in]        handle_t                     handle, 
          [in, out]   telcom_datatype_mwi_t *      mwi_data, 
          [in, out]   error_status_t *             status
    );

}
