/*
 * @OSF_COPYRIGHT@
 * COPYRIGHT NOTICE
 * Copyright (c) 1990, 1991, 1992, 1993, 1996 Open Software Foundation, Inc.
 * ALL RIGHTS RESERVED (DCE).  See the file named COPYRIGHT.DCE in the
 * src directory for the full copyright text.
 */
/*
 * HISTORY
 * $Log: oolthings.idl,v $
 * Revision 1.1.4.2  1996/03/11  02:15:45  marty
 * 	Update OSF copyright years
 * 	[1996/03/10  19:54:07  marty]
 *
 * Revision 1.1.4.1  1995/12/11  19:26:10  root
 * 	Submit OSF/DCE 1.2.1
 * 	[1995/12/11  19:14:10  root]
 * 
 * Revision 1.1.2.3  1993/01/13  21:13:12  bbelch
 * 	Embedding copyright notice
 * 	[1993/01/06  13:36:28  bbelch]
 * 
 * Revision 1.1  1992/01/19  03:25:29  devrcs
 * 	Initial revision
 * 
 * $EndLog$
 */
/*
*/
[uuid(d5edc030-7fec-11c9-aac9-08001e01e1e9), version(0)]
interface oolthings
{
    const long FIXED_SIZE = 20;
    const long CONF_SIZE = 10;

    typedef short fixed_array[FIXED_SIZE];
    typedef long conf_array[];

    typedef struct conf_struct {
        long s;
        [size_is(s)] conf_array c_a;
    } conf_struct;

    typedef struct open_struct {
        long s;
        long f;
        long l;
        [size_is(s),first_is(f),last_is(l)] conf_array c_a;
    } open_struct;

    void op0( [in] conf_struct *p_c_s, [out] fixed_array f_a);

    void op1( [in] long s,
              [in, size_is(s)] conf_array c_a,
              [out] long *p_f,
              [out] long *p_l,
              [out, first_is(*p_f), last_is(*p_l)] fixed_array f_a);

    void op2( [in] open_struct *p_o_s,
              [in] long s,
              [out] long *p_f,
              [out] long *p_l,
              [out, size_is(s), first_is(*p_f), last_is(*p_l)] conf_array c_a);

}
