/*
 * @OSF_COPYRIGHT@
 * COPYRIGHT NOTICE
 * Copyright (c) 1990, 1991, 1992, 1993, 1994, 1996 Open Software Foundation, Inc.
 * ALL RIGHTS RESERVED (DCE).  See the file named COPYRIGHT.DCE for
 * the full copyright text.
 */
/*
 * HISTORY
 * $Log: timop_svc.idl,v $
 * Revision 1.1.4.2  1996/03/09  23:15:36  marty
 * 	Update OSF copyright year
 * 	[1996/03/09  22:32:50  marty]
 *
 * Revision 1.1.4.1  1995/12/08  20:55:06  root
 * 	Submit OSF/DCE 1.2.1
 * 	[1995/12/08  20:50:11  root]
 * 
 * Revision 1.1.2.1  1994/06/14  19:57:34  weir
 * 	DCE 1.1 Beta check-in
 * 	[1994/06/14  16:15:14  weir]
 * 
 * $EndLog$
 */
/*
**	timop_svc.idl
**
**	IDL interface specification for remote time operations.
*/

/* We need explicit handles in timop because our client has multiple (actually,
   multi-threaded) RPCs bound to multiple explicitly-specified servers. */

[
uuid(0037ca63-2629-1de2-99b0-08002b0f59ba),
version(1.0)
]
interface timop_svc
{
	/* DTS timestamps are already in a universal format,
	   so are opaque to (the presentation layer of) the RPC
	   (16 = sizeof(utc_t)). */
	const small		SIZEOF_TIMESTAMP = 16;
	typedef byte		timestamp_t[SIZEOF_TIMESTAMP];

	const small		MESSAGE_SIZE = 80;

	/* Failure value for remote status indications. */
	const long		TIMOP_SVC_ERR = -1;

	/* Get the time span to do a job (random factorial). */
	[idempotent]
	void timop_svc_getspan(
		[in]	handle_t		handle,
		[in]	long			rand,
		[in,out,string] char		server_msg[MESSAGE_SIZE],
		[out]	timestamp_t		timestamp,
		[out]	long			*status_p,
		[in,out] error_status_t		*remote_status_p);

}
