/*
 * @OSF_COPYRIGHT@
 * COPYRIGHT NOTICE
 * Copyright (c) 1996 Open Software Foundation, Inc.
 * ALL RIGHTS RESERVED (DCE).  See the file named COPYRIGHT.DCE for
 * the full copyright text.
 * 
 */
/*
 * HISTORY
 * $Log: matrix.idl,v $
 * Revision 1.1.2.2  1996/03/09  20:48:44  marty
 * 	Add OSF copyright
 * 	[1996/03/09  20:27:18  marty]
 *
 * Revision 1.1.2.1  1995/12/11  19:34:10  root
 * 	Submit OSF/DCE 1.2.1
 * 	[1995/12/11  19:17:58  root]
 * 
 * $EndLog$
 */
[
    uuid(c3c84c7e-e459-11cd-b511-08002b3d8412)
] interface Matrix
{
    /* Create a 2x2 matrix */

    Matrix * new2x2EXPLICIT(
	[in] double v11,
	[in] double v12,
	[in] double v21,
	[in] double v22
    );

    Matrix * new2x2IMPLICIT(
	[in] double v11,
	[in] double v12,
	[in] double v21,
	[in] double v22
    );

    /* Set a new value in the matrix */
    void set(
	[in] long row,
	[in] long col,
	[in] double value
	);

    /* Get a value from the matrix */
    double get(
	[in] long row,
	[in] long col
	);

    /* Return the inversion of the specified matrix */
    Matrix * invert();

    /* Return the product */
    Matrix * multiply(
	[in] Matrix * m1
	);

    /* Return the sum */
    Matrix * add(
	[in] Matrix * m1
	);
}
