# @OSF_COPYRIGHT@
# COPYRIGHT NOTICE
# Copyright (c) 1990, 1991, 1992, 1993, 1994, 1996 Open Software Foundation, Inc.
# ALL RIGHTS RESERVED (DCE).  See the file named COPYRIGHT.DCE for
# the full copyright text.
# 
# 
# HISTORY
# $Log: Makefile,v $
# Revision 1.1.4.3  1996/03/11  02:17:16  marty
# 	Update OSF copyright years
# 	[1996/03/10  19:32:23  marty]
#
# Revision 1.1.4.2  1995/12/13  15:26:39  root
# 	Submit OSF/DCE 1.2.1
# 	[1995/12/11  15:53:42  root]
# 
# Revision 1.1.2.1  1994/09/28  21:40:41  melman
# 	moved admin tests to test/functional
# 	[1994/09/28  21:09:56  melman]
# 
# Revision 1.1.2.3  1994/06/10  20:13:28  devsrc
# 	cr10872 - fixed copyright
# 	[1994/06/10  16:54:44  devsrc]
# 
# Revision 1.1.2.2  1994/05/11  14:46:53  rousseau
# 	Updated to new install path and removed bad use of SCRIPTS (CR 10601).
# 	[1994/05/11  14:46:19  rousseau]
# 
# Revision 1.1.2.1  1994/05/02  19:26:10  salamone
# 	Initial version.
# 	[1994/04/29  20:23:45  salamone]
# 
# $EndLog$

LOG_FILES	= log_list_N.tcl log_list_P.tcl \
                  log_show_N.tcl log_show_P.tcl \
                  log_modify_N.tcl log_modify_P.tcl 
IDIR		= /test/tet/functional/admin/dcecp/ts/log/
ILIST		= ${LOG_FILES}
DATAFILES	= ${LOG_FILES}
IMODE		= 755

.include <${RULES_MK}>
