/*
 * @OSF_COPYRIGHT@
 * COPYRIGHT NOTICE
 * Copyright (c) 1996 Open Software Foundation, Inc.
 * ALL RIGHTS RESERVED (DCE).  See the file named COPYRIGHT.DCE for
 * the full copyright text.
 * 
 */
/*
 * HISTORY
 * $Log: matrix.idl,v $
 * Revision 1.1.2.2  1996/03/09  20:48:21  marty
 * 	Add OSF copyright
 * 	[1996/03/09  20:27:01  marty]
 *
 * Revision 1.1.2.1  1995/12/11  19:33:33  root
 * 	Submit OSF/DCE 1.2.1
 * 	[1995/12/11  19:17:42  root]
 * 
 * $EndLog$
 */
[
    uuid(be34a158-dac8-11cd-b293-08002b39789f)
] interface Matrix
{
    /* Create a 2x2 matrix  */
    Matrix * new2x2(
	[in] double v11,
	[in] double v12,
	[in] double v21,
	[in] double v22
    );

    /* Create a 3x3 matrix  */
    Matrix * new3x3(
	[in] double v11,
	[in] double v12,
	[in] double v13,
	[in] double v21,
	[in] double v22,
	[in] double v23,
	[in] double v31,
	[in] double v32,
	[in] double v33
    );

    /* Set a new value in the matrix */
    void set(
	[in] long row,
	[in] long col,
	[in] double value
	);

    /* Get a value from the matrix */
    double get(
	[in] long row,
	[in] long col
	);

    /* Return the inversion of the specified matrix */
    Matrix * invert();

    /* Return the product */
    Matrix * multiply(
	[in] Matrix * m1
	);

    /* Return the sum */
    Matrix * add(
	[in] Matrix * m1
	);
}
