/*
 * @OSF_COPYRIGHT@
 * COPYRIGHT NOTICE
 * Copyright (c) 1990, 1991, 1992, 1993, 1996 Open Software Foundation, Inc.
 * ALL RIGHTS RESERVED (DCE).  See the file named COPYRIGHT.DCE in the
 * src directory for the full copyright text.
 */
/*
 * HISTORY
 * $Log: orecord.idl,v $
 * Revision 1.1.4.2  1996/03/11  02:15:58  marty
 * 	Update OSF copyright years
 * 	[1996/03/10  19:54:12  marty]
 *
 * Revision 1.1.4.1  1995/12/11  19:26:26  root
 * 	Submit OSF/DCE 1.2.1
 * 	[1995/12/11  19:14:18  root]
 * 
 * Revision 1.1.2.3  1993/01/13  21:49:27  bbelch
 * 	Embedding copyright notice
 * 	[1993/01/06  13:37:00  bbelch]
 * 
 * Revision 1.1  1992/01/19  03:29:47  devrcs
 * 	Initial revision
 * 
 * $EndLog$
 */
/*
*/
[uuid(495ebf42-c000-0000-0d00-00feda000000), version(0), 
 endpoint("ncadg_ip_udp:[22220]", "ncadg_dds:[555]")]
interface orecord
{
    typedef struct
    {
        long namelen;
        [last_is(namelen), max_is(namelen)] byte name[];
    } orecord_t;

    [idempotent] long op1
    (
        [in] handle_t h,
        [in] byte c,
        [in] orecord_t *o,
        [in] long d
    );
}
