/*
 * @OSF_COPYRIGHT@
 * COPYRIGHT NOTICE
 * Copyright (c) 1996 Open Software Foundation, Inc.
 * ALL RIGHTS RESERVED (DCE).  See the file named COPYRIGHT.DCE for
 * the full copyright text.
 * 
 */
/*
 * HISTORY
 * $Log: iplayer.idl,v $
 * Revision 1.1.2.2  1996/03/09  20:48:32  marty
 * 	Add OSF copyright
 * 	[1996/03/09  20:27:09  marty]
 *
 * Revision 1.1.2.1  1995/12/11  19:33:50  root
 * 	Submit OSF/DCE 1.2.1
 * 	[1995/12/11  19:17:50  root]
 * 
 * $EndLog$
 */
[uuid(4ce528a1-d64f-11ce-8d1b-08002be415b2)]

/*
** This idl file represents the interface to the C++ Player class.
** It demonstrates how a native C++ class can be wraped by an interface
** class in order to allow remote access to a local instance of a non-RPC
** object.
*/

interface IPlayer
{
	/* Define a char string type */
	typedef [string,ptr] char * aString;

	/*
	** Define any operations that are part of the Player class
	** that are to be exported. They allow a remote procedure to access
	** the local object via these exported operations.
	**
	** Note that these operations must be members of the delegated class.
	*/

	aString getFirstName();

	aString getLastName();

	aString getStatTitle();

	double getStat();
}
