/*
 * @OSF_COPYRIGHT@
 * COPYRIGHT NOTICE
 * Copyright (c) 1996 Open Software Foundation, Inc.
 * ALL RIGHTS RESERVED (DCE).  See the file named COPYRIGHT.DCE for
 * the full copyright text.
 * 
 */
/*
 * HISTORY
 * $Log: account.idl,v $
 * Revision 1.1.2.2  1996/03/09  20:47:56  marty
 * 	Add OSF copyright
 * 	[1996/03/09  20:26:42  marty]
 *
 * Revision 1.1.2.1  1995/12/11  19:33:05  root
 * 	Submit OSF/DCE 1.2.1
 * 	[1995/12/11  19:17:24  root]
 * 
 * $EndLog$
 */
[
uuid(6c44dd20-2741-11ce-8a41-08002b3d8412)
] interface Account
{
	double getAccountBalance();

	void   credit(
		[in] double amt
	);

	/* Get a count of Object Table entries */
	static long getNumOTentries(
		[in] handle_t bh
	);

	static void remote_local_test(
		[in] handle_t bh,
		[in] Account *a
	);

}
