# @OSF_COPYRIGHT@
# COPYRIGHT NOTICE
# Copyright (c) 1990, 1991, 1992, 1993, 1996 Open Software Foundation, Inc.
# ALL RIGHTS RESERVED (DCE).  See the file named COPYRIGHT.DCE in the
# src directory for the full copyright text.
#
#
# HISTORY
# $Log: Makefile,v $
# Revision 1.2.25.4  1996/11/13  18:09:13  arvind
# 	Merge to DCE_1.2.2
# 	[1996/10/25  19:09 UTC  mullan_s  /main/DCE_1.2.2/mullan_dce12_tp_preauth/2]
#
# 	Build tp_preauth.o, extend INCFLAGS for
# 	get_in_tkt.c & preauth.c
# 	[1996/10/15  13:22 UTC  mullan_s  /main/DCE_1.2.2/mullan_dce12_tp_preauth/1]
#
# 	add des_md5.c
# 	[1996/10/16  23:18 UTC  sommerfeld  /main/DCE_1.2.2/sommerfeld_pk_kdc_3/1]
#
# 	Merge to DCE 1.2.2
# 	[1996/06/21  19:28 UTC  mullan_s  /main/DCE_1.2.2/mullan_dce_krb5_der_work/1]
#
# 	Build libkrb5.a for testing purposes
# 	[1996/05/24  23:16 UTC  sommerfeld  /main/DCE_1.2.2/1]
#
# Revision 1.2.25.3  1996/10/03  15:04:33  arvind
# 	Add in_tkt_ktb.c
# 	[1996/09/20  21:32 UTC  sommerfeld  /main/DCE_1.2.2/sommerfeld_pk_kdc_1/2]
# 
# 	add f_etype.c
# 	Add pk preauth.c
# 	build libkrb5.a for testing purposes
# 	[1996/09/16  22:18 UTC  sommerfeld  /main/DCE_1.2.2/sommerfeld_pk_kdc_1/1]
# 
# 	Merge to DCE 1.2.2
# 	[1996/06/21  19:28 UTC  mullan_s  /main/DCE_1.2.2/mullan_dce_krb5_der_work/1]
# 
# 	Build libkrb5.a for testing purposes
# 	[1996/05/24  23:16 UTC  sommerfeld  /main/DCE_1.2.2/1]
# 
# Revision 1.2.25.2  1996/07/08  18:36:55  arvind
# 	Merge to DCE 1.2.2
# 	[1996/06/21  19:28 UTC  mullan_s  /main/DCE_1.2.2/mullan_dce_krb5_der_work/1]
# 
# 	Build libkrb5.a for testing purposes
# 	[1996/05/24  23:16 UTC  sommerfeld  /main/DCE_1.2.2/1]
# 
# Revision 1.2.25.1  1996/06/04  22:03:48  arvind
# 	Merge u2u  change
# 	[1996/05/06  20:49 UTC  burati  /main/DCE_1.2/2]
# 
# 	Merge u2u work
# 	[1996/04/30  20:28 UTC  burati  /main/DCE_1.2/mb_u2u/1]
# 
# 	u2u work off Mothra, before 1.2 branch is available
# 	[1996/04/30  20:17 UTC  burati  /main/HPDCE02/mb_mothra8/1]
# 
# Revision 1.2.23.3  1996/03/09  23:29:50  marty
# 	Update OSF copyright year
# 	[1996/03/09  22:45:11  marty]
# 
# Revision 1.2.23.2  1995/12/08  18:02:11  root
# 	Submit OSF/DCE 1.2.1
# 
# 	HP revision /main/HPDCE02/4  1995/08/21  17:46 UTC  sommerfeld
# 	*nobody* should use ecb_buffer.
# 	[1995/08/01  19:21 UTC  sommerfeld  /main/HPDCE02/sommerfeld_dfsperf/1]
# 
# 	HP revision /main/HPDCE02/3  1995/05/31  14:48 UTC  mullan_s
# 	Merge CHFts15049
# 
# 	HP revision /main/HPDCE02/mullan_mothra_bin_compat3/2  1995/05/30  18:14 UTC  mullan_s
# 	Merge out
# 
# 	HP revision /main/HPDCE02/2  1995/04/15  00:04 UTC  rps
# 	Binary Compatibility Merge
# 	[1995/04/03  22:13 UTC  mullan_s  /main/HPDCE02/1]
# 
# 	Pick up sec_login_pvt.h for fcc_gennew.o, fcc_maybe.o, gc_via_tgt.o
# 	[1995/03/20  14:46 UTC  mullan_s  /main/mullan_mothra_bin_compat2/2]
# 
# 	add new files for fuzzy realm compare, primary realm stuff.
# 	[1995/02/11  00:07 UTC  sommerfeld  /main/sommerfeld_krb5_alias_1/1]
# 
# 	HP revision /main/HPDCE02/mullan_mothra_bin_compat3/1  1995/04/14  20:56 UTC  mullan_s
# 	Pick up sec_login_pvt.h for ktf_util.o.
# 
# 	HP revision /main/HPDCE02/1  1995/04/03  22:13 UTC  mullan_s
# 	Binary Compatibility Merge
# 
# 	HP revision /main/mullan_mothra_bin_compat2/2  1995/03/20  14:46 UTC  mullan_s
# 	Pick up sec_login_pvt.h for fcc_gennew.o, fcc_maybe.o, gc_via_tgt.o
# 	[1995/12/08  17:00:18  root]
# 
# Revision 1.2.18.1  1994/05/11  19:24:25  ahop
# 	hp_sec_to_osf_2 drop
# 	set INCFLAGS for files including lib/krb/int-proto.h
# 	[1994/05/03  19:29:30  ahop]
# 
# 	hp_sec_to_osf_2 drop
# 	[1994/04/29  21:21:33  ahop]
# 
# Revision 1.1.10.5  1993/09/22  19:02:36  sommerfeld
# 	Merge in dce1.0.3b03 drop.
# 	[1993/09/22  14:48:14  sommerfeld]
# 
# 	Re-order makefile options to pick up DES object files.
# 	[1993/09/16  14:48:15  sommerfeld]
# 
# 	Changed $${DES_OFILES} to ${DES_OFILES} to get international
# 	build to work.
# 	[1993/09/15  18:59:57  mgm]
# 
# 	Merge in changes for DES-hidden build
# 	[1993/04/01  00:55:04  ahop]
# 
# Revision 1.2.16.2  1993/06/10  19:27:04  sommerfeld
# 	Delete objects with dependancies on DBM (sigh) for HP-UX.
# 	this is an expediant hack which should be revisited later.
# 	[1993/06/08  18:24:07  sommerfeld]
# 
# Revision 1.2.8.6  1992/12/29  15:59:30  zeliff
# 	Embedding copyright notice
# 	[1992/12/28  21:16:16  zeliff]
# 
# Revision 1.2.8.5  1992/12/12  22:01:14  john
# 	Added NO_Y_H_RULE to turn off automatic conversion of error_message.y
# 	to error.message.h.
# 	[1992/12/12  22:00:24  john]
# 
# Revision 1.2.8.4  1992/12/07  18:28:17  sommerfeld
# 	Add more .o_INCFLAGS for all of keytab/file
# 	[1992/12/07  17:22:44  sommerfeld]
# 
# Revision 1.2.8.3  1992/10/29  20:15:26  sommerfeld
# 	Add more .o_INCFLAGS for all of ccache/file.
# 	[1992/10/23  22:35:24  sommerfeld]
# 
# Revision 1.2.4.9  1992/06/30  21:53:09  burati
# 	CR4516 HP/UX porting
# 	[1992/06/30  04:37:43  burati]
# 
# Revision 1.2.4.8  1992/06/29  20:57:43  sommerfeld
# 	Add incflags for fcc_read.o, too.
# 	[1992/06/26  22:47:09  sommerfeld]
# 
# Revision 1.2.4.7  1992/06/24  21:25:09  sommerfeld
# 	Add INCFLAGS for ktf_util.c to allow building it in sandbox.
# 	[1992/06/22  20:05:07  sommerfeld]
# 
# Revision 1.2.4.6  1992/06/01  20:51:26  sekhar
# 	Merged the des code restructing changes made by Joe Pato
# 	onto the mainline.
# 	[1992/06/01  20:02:12  sekhar]
# 
# Revision 1.2.5.2  1992/05/15  21:36:15  pato
# 	OT#2330 new directory structure for crypto code; add ${SECURITY_CFLAGS}
# 	to CFLAGS;
# 
# Revision 1.2.4.5  1992/05/12  20:44:51  mhickey
# 	Fixed broke bci, really removed NEED_PROJECT_MAKE_DEFS
# 	[1992/05/12  20:38:20  mhickey]
# 
# Revision 1.2.4.4  1992/05/12  20:31:31  mhickey
# 	*** empty log message ***
# 
# Revision 1.2.4.3  1992/05/11  17:51:26  mhickey
# 	Removed obsolete define of NEED_PROJECT_MAKE_DEFS
# 	and include of osf.dce.mk.  Fixes defect 2031.
# 	[1992/04/22  15:23:20  mhickey]
# 
# Revision 1.2.4.2  1992/05/08  17:18:05  sommerfeld
# 	Add _INCFLAGS for a few rc_*.o modules.
# 	[1992/05/05  02:47:02  sommerfeld]
# 
# Revision 1.2  1992/01/19  22:13:50  devrcs
# 	Dropping DCE1.0 OSF1_misc port archive
# 
# $EndLog$
#
#
#
#  OSF DCE Version 1.0 
#
#
# Copyright (c) Hewlett-Packard Company 1991, 1995
# Unpublished work. All Rights Reserved.
#
#
# DCE Security Services 
# krb5/lib/krb5 Makefile
#
###########################################################
# define the following "globally" for the krb5/lib/krb5 build.
###########################################################
###  DO NOT PUT ANYTHING IN THIS SECTION EXCEPT FOR OBJECT
###  FILE LISTS!!!!!
###########################################################
#
DES_OFILES =  cksum.o cbc_cksum.o \
	cbc_encrypt.o des_tables.o ecb_encrypt.o   \
	make_sched.o pcbc_encrypt.o desglue.o des_md5.o new_rn_key.o      \
	process_ky.o init_rkey.o random_key.o string2key.o      \
	finish_key.o fin_rndkey.o key_parity.o weak_key.o 

DCE_OFILES = princ_fcomp.o get_prirlm.o

libkrb5a_OFILES	= init_ets.o	\
	error_message.o et_name.o init_et.o com_err.o \
        KRB5.o \
	decode.o decode_arp.o decode_arq.o \
	encode.o encode_arp.o encode_arq.o krb5-glue.o krb5-manual-glue.o \
	fcc_close.o fcc_destry.o fcc_eseq.o \
	fcc_gennew.o fcc_getnam.o fcc_gprin.o fcc_init.o \
	fcc_maybe.o fcc_nseq.o fcc_read.o fcc_reslv.o fcc_retrv.o \
	fcc_sseq.o fcc_store.o fcc_skip.o fcc_ops.o fcc_write.o \
	fcc_sflags.o fcc_defops.o fcc_errs.o \
	ccbase.o ccdefault.o ccdefops.o \
	ktf_add.o ktf_close.o ktf_endget.o ktf_get_en.o	\
	ktf_get_na.o ktf_next.o	ktf_resolv.o ktf_remove.o \
	ktf_ssget.o ktf_util.o	ktf_ops.o ktf_wops.o	\
	ktf_wreslv.o ktf_defops.o ktadd.o ktbase.o	\
	ktdefault.o ktfr_entry.o ktremove.o read_servi.o \
	addr_comp.o addr_order.o addr_srch.o \
        bld_pr_ext.o bld_princ.o copy_addrs.o \
	copy_athctr.o copy_auth.o copy_checksum.o \
	copy_creds.o copy_data.o copy_key.o	\
	copy_princ.o copy_tick.o cp_key_cnt.o decode_kdc.o decrypt_tk.o \
	encode_kdc.o encrypt_tk.o free_rtree.o faddr_ordr.o \
	gc_2tgt.o gc_frm_kdc.o gc_via_tgt.o gen_rname.o \
        gen_subkey.o get_creds.o get_in_tkt.o
libkrb5b_OFILES	= \
	in_tkt_pwd.o in_tkt_sky.o in_tkt_ktb.o kdc_rep_dc.o krbconfig.o \
	mk_error.o mk_priv.o mk_rep.o mk_req.o mk_req_ext.o \
	mk_safe.o parse.o preauth.o pk_preauth.o pr_to_salt.o princ_comp.o \
	rd_error.o rd_priv.o \
	rd_rep.o rd_req.o rd_req_sim.o	rd_req_dec.o rd_safe.o	\
	send_tgs.o tgtname.o tp_preauth.o unparse.o walk_rtree.o \
	rc_base.o rc_conv.o rc_dfl.o rc_io.o rcdef.o \
	f_addr.o f_address.o f_ap_rep.o \
	f_ap_req.o f_arep_enc.o f_authdata.o \
	f_authent.o f_cksum.o f_creds.o	\
	f_cred_cnt.o f_enc_kdc.o f_enc_tkt.o f_error.o	\
	f_kdc_rep.o f_kdc_req.o	f_keyblock.o f_last_req.o f_padata.o \
	f_princ.o f_priv.o f_priv_enc.o	f_safe.o f_ticket.o \
	f_tickets.o f_tgt_cred.o f_tkt_auth.o f_einfo.o \
	def_realm.o	\
	ccdefname.o free_krbhs.o free_hstrl.o get_krbhst.o \
	hst_realm.o krbfileio.o ktdefname.o localaddr.o \
	locate_kdc.o lock_file.o net_read.o net_write.o \
	osconfig.o rnd_confoun.o read_pwd.o sendto_kdc.o srv_rcache.o \
	timeofday.o unlck_file.o ustime.o port2ip.o \
	cryptoconf.o perror.o syslog.o crc.o \
        md4.o md4crypto.o md4glue.o \
        md5.o md5crypto.o md5glue.o \
	${${TARGET_MACHINE}_libkrb5_OFILES} ${DES_OFILES} ${DCE_OFILES}


DELETED_OFILES=an_to_ln.o kuserok.o 

libkrb5_OFILES	= ${libkrb5a_OFILES} ${libkrb5b_OFILES} 
libkrb5.a_OFILES	= ${libkrb5_OFILES} ${${TARGET_MACHINE}_libkrb5_OFILES}

#
# the rest of the makefile is "private" for the build of libcma.so
#
.if !defined(LIBDCE_LIBRARY_MAKEFILE)
#
# The following definitions are for shared libraries:
#   OBJECTS must be defined to pull in the common rules for compilation
#   LIBS    must be defined to prevent -ldce from appearing on compile lines
#
OBJECTS =
LIBS    =

.if defined (USE_DES)
DES_DIR = domestic
.else
DES_DIR = international
.endif

VPATH	= ../../comerr:../error_tables:../mvr:../ccache/file:../ccache:../keytab/file:../keytab:../krb:../rcache:../free:../os:../kdb:../crypto/common:../crypto/${DES_DIR}:../crc-32:..:../rsa-md4:../rsa-md5

# Always build/export libkrb5.a for testing purposes
LIBRARIES             = libkrb5.a
EXPLIB_TARGETS                = ${LIBRARIES:S/^/export_/g}
#
# Don't want to install any '.a' here if we are using shared libraries
#
.if ${USE_SHARED_LIBRARIES} == 0 || defined(DES_HIDDEN)
  # Libraries to install
  ILIST = libkrb5.a
.endif

EXPSHLIB_TARGETS	= ${libkrb5_OFILES}

CFLAGS	= -DOSF_DCE ${${TARGET_MACHINE}_CFLAGS} ${SECURITY_CFLAGS}

.if ${TARGET_MACHINE} == "HP800"
kuserok.o_CFLAGS = ${CFLAGS} -U_PWD_INCLUDED
.endif

# Directory in which to place exported files
EXPDIR = /usr/lib/

# Directory in which to install
IDIR = /usr/lib/

KRB5.o_INCFLAGS = -I../mvr

et_name.o_INCFLAGS = -I../../comerr
fcc_close.o_INCFLAGS = -I../ccache/file
fcc_destry.o_INCFLAGS = -I../ccache/file
fcc_eseq.o_INCFLAGS = -I../ccache/file
fcc_gennew.o_INCFLAGS = -I../ccache/file -I../../../h
fcc_getnam.o_INCFLAGS = -I../ccache/file
fcc_gprin.o_INCFLAGS = -I../ccache/file
fcc_init.o_INCFLAGS = -I../ccache/file
fcc_maybe.o_INCFLAGS = -I../ccache/file -I../../../h
fcc_nseq.o_INCFLAGS = -I../ccache/file
fcc_read.o_INCFLAGS = -I../ccache/file
fcc_reslv.o_INCFLAGS = -I../ccache/file
fcc_retrv.o_INCFLAGS = -I../ccache/file
fcc_sseq.o_INCFLAGS = -I../ccache/file
fcc_store.o_INCFLAGS = -I../ccache/file
fcc_skip.o_INCFLAGS = -I../ccache/file
fcc_ops.o_INCFLAGS = -I../ccache/file
fcc_write.o_INCFLAGS = -I../ccache/file
fcc_sflags.o_INCFLAGS = -I../ccache/file
fcc_defops.o_INCFLAGS = -I../ccache/file
fcc_errs.o_INCFLAGS = -I../ccache/file
gc_frm_kdc.o_INCFLAGS = -I../krb
gc_2tgt.o_INCFLAGS = -I../krb -I../../../h
gc_via_tgt.o_INCFLAGS = -I../krb -I../../../h
get_in_tkt.o_INCFLAGS = -I../../../h
preauth.o_INCFLAGS = -I../../../h
tp_preauth.o_INCFLAGS = -I../../../h
walk_rtree.o_INCFLAGS = -I../krb
rc_io.o_INCFLAGS = -I../rcache
rc_dfl.o_INCFLAGS = -I../rcache
ktf_add.o_INCFLAGS = -I../keytab/file
ktf_close.o_INCFLAGS = -I../keytab/file
ktf_endget.o_INCFLAGS = -I../keytab/file
ktf_get_en.o_INCFLAGS = -I../keytab/file
ktf_get_na.o_INCFLAGS = -I../keytab/file
ktf_next.o_INCFLAGS = -I../keytab/file
ktf_resolv.o_INCFLAGS = -I../keytab/file
ktf_remove.o_INCFLAGS = -I../keytab/file
ktf_ssget.o_INCFLAGS = -I../keytab/file
ktf_util.o_INCFLAGS = -I../keytab/file -I../../../h
ktf_ops.o_INCFLAGS = -I../keytab/file
ktf_wops.o_INCFLAGS = -I../keytab/file
ktf_wreslv.o_INCFLAGS = -I../keytab/file
ktf_defops.o_INCFLAGS = -I../keytab/file

# Added NO_Y_H_RULE definition to turn off automatic conversion of
# error_message.y to error_message.h.
NO_Y_H_RULE=ON

.include <${RULES_MK}>

.endif

