/*
 * @OSF_COPYRIGHT@
 * COPYRIGHT NOTICE
 * Copyright (c) 1990, 1991, 1992, 1993, 1996 Open Software Foundation, Inc.
 * ALL RIGHTS RESERVED (DCE).  See the file named COPYRIGHT.DCE in the
 * src directory for the full copyright text.
 */
/*
 * HISTORY
 * $Log: ue2.idl,v $
 * Revision 1.1.4.2  1996/03/11  02:19:39  marty
 * 	Update OSF copyright years
 * 	[1996/03/10  19:56:08  marty]
 *
 * Revision 1.1.4.1  1995/12/11  19:31:24  root
 * 	Submit OSF/DCE 1.2.1
 * 	[1995/12/11  19:16:33  root]
 * 
 * Revision 1.1.2.2  1993/08/11  16:29:46  ganni
 * 	tests for new IDL functionality
 * 	[1993/08/11  16:17:06  ganni]
 * 
 * $EndLog$
 */
/*
*/
[
uuid(D0EBDA46-172E-11CC-8861-08002B107359),
version(0.0),
exceptions(my_exc1,my_exc2,my_exc3)
]
interface ue2
{
    void op1([in]handle_t h);
    void op2([in]handle_t h);
    void op3([in]handle_t h);
}
