/*
 * @OSF_COPYRIGHT@
 * COPYRIGHT NOTICE
 * Copyright (c) 1996 Open Software Foundation, Inc.
 * ALL RIGHTS RESERVED (DCE).  See the file named COPYRIGHT.DCE for
 * the full copyright text.
 * 
 */
/*
 * HISTORY
 * $Log: account.idl,v $
 * Revision 1.1.2.2  1996/03/09  20:47:47  marty
 * 	Add OSF copyright
 * 	[1996/03/09  20:26:35  marty]
 *
 * Revision 1.1.2.1  1995/12/11  19:32:54  root
 * 	Submit OSF/DCE 1.2.1
 * 	[1995/12/11  19:17:17  root]
 * 
 * $EndLog$
 */
[
uuid(a5b5432c-f57f-11cd-a3e6-08002b3d8412)
] interface Account
{
	double getAccountBalance();

	void   credit(
		[in] double amt
	);

	/* Get a count of Object Table entries */
	static long getNumOTentries(
		[in] handle_t bh
	);

}
