/*
 * @OSF_COPYRIGHT@
 * COPYRIGHT NOTICE
 * Copyright (c) 1996 Open Software Foundation, Inc.
 * ALL RIGHTS RESERVED (DCE).  See the file named COPYRIGHT.DCE for
 * the full copyright text.
 * 
 */
/*
 * HISTORY
 * $Log: checking.idl,v $
 * Revision 1.1.2.2  1996/03/09  20:47:48  marty
 * 	Add OSF copyright
 * 	[1996/03/09  20:26:36  marty]
 *
 * Revision 1.1.2.1  1995/12/11  19:32:55  root
 * 	Submit OSF/DCE 1.2.1
 * 	[1995/12/11  19:17:18  root]
 * 
 * $EndLog$
 */
[
    uuid(c1b0c352-f7f1-11cd-8541-08002b3d8412)
]   interface Checking
{
	double getCheckingBalance();

	double   withDraw(
		[in] double amt
	);
}
