/*
 * @OSF_COPYRIGHT@
 * COPYRIGHT NOTICE
 * Copyright (c) 1990, 1991, 1992, 1993, 1996 Open Software Foundation, Inc.
 * ALL RIGHTS RESERVED (DCE).  See the file named COPYRIGHT.DCE in the
 * src directory for the full copyright text.
 */
/*
 * HISTORY
 * $Log: binop_alloc.idl,v $
 * Revision 1.1.4.2  1996/03/11  02:10:08  marty
 * 	Update OSF copyright years
 * 	[1996/03/10  19:51:52  marty]
 *
 * Revision 1.1.4.1  1995/12/11  19:58:16  root
 * 	Submit OSF/DCE 1.2.1
 * 	[1995/12/11  19:28:52  root]
 * 
 * Revision 1.1.2.3  1993/02/26  21:26:34  weisman
 * 	Removed binop_alloc_fail test.
 * 	[1993/02/26  21:09:49  weisman]
 * 
 * Revision 1.1.2.2  1993/01/07  19:08:30  bbelch
 * 	Embedding copyright notice
 * 	[1993/01/06  13:28:00  bbelch]
 * 
 * Revision 1.1  1992/01/19  03:29:11  devrcs
 * 	Initial revision
 * 
 * $EndLog$
 */
/*
*/
[uuid(f9f6be80-2ba7-11c9-89fd-08002b13d56d),
 version(0)]
interface binop_alloc
{

    [idempotent] void binop_alloc_enable
    (
        [in] handle_t h,
        [in] long a,
        [in] long b,
        [out] long *c
    );

    void binop_alloc_ss_enable
    (
        [in] handle_t h,
        [in] long a,
        [in] long b,
        [out] long *c
    );

}
