/*
 * @OSF_COPYRIGHT@
 * COPYRIGHT NOTICE
 * (c) Copyright International Business Machines Corp. 1994, 1996
 * Copyright (c) 1990, 1991, 1992, 1993, 1994, 1996 Open Software Foundation, Inc.
 * ALL RIGHTS RESERVED (DCE).  See the file named COPYRIGHT.DCE in the
 * src directory for the full copyright text.
 *
 */
/*
 * HISTORY
 * $Log: audit_update.idl,v $
 * Revision 1.1.6.1  1996/07/08  18:30:26  arvind
 * 	Audit for 1.2.2
 * 	[1996/06/21  20:26 UTC  arvind  /main/arvind_audit122/1]
 *
 * 	Audit for 1.2.2
 * 	[1996/03/09  23:27:15  marty  1.1.4.2]
 *
 * Revision 1.1.4.2  1996/03/09  23:27:15  marty
 * 	Update OSF copyright year
 * 	[1996/03/09  22:42:45  marty]
 * 
 * Revision 1.1.4.1  1995/12/08  17:41:06  root
 * 	Submit OSF/DCE 1.2.1
 * 	[1995/12/08  17:18:03  root]
 * 
 * Revision 1.1.2.1  1993/12/22  12:39:18  zeliff
 * 	First version of code
 * 	[1993/12/21  15:01:32  zeliff]
 * 
 * $EndLog$
 */

[
uuid(00604410-E17E-1C14-A5F4-02608C0FF790),
version(1.0)
]


interface update
{
import "dce/audit_control.idl";

void update_esl_check (
        [in] handle_t 	handle,
        [in] aud_esl_type_t esl_type,
        [in, out] error_status_t *stp
);

void update_eccf_check (
        [in] handle_t 	handle,
        [in, out] error_status_t *stp
);
}
