/*
 * @OSF_COPYRIGHT@
 * COPYRIGHT NOTICE
 * (c) Copyright International Business Machines Corp. 1994, 1996
 * Copyright (c) 1990, 1991, 1992, 1993, 1994, 1996 Open Software Foundation, Inc.
 * ALL RIGHTS RESERVED (DCE).  See the file named COPYRIGHT.DCE in the
 * src directory for the full copyright text.
 *
 */
/*
 * HISTORY
 * $Log: audit_store.idl,v $
 * Revision 1.1.6.1  1996/07/08  18:30:03  arvind
 * 	Audit for 1.2.2
 * 	[1996/06/21  20:26 UTC  arvind  /main/arvind_audit122/1]
 *
 * 	Audit for 1.2.2
 * 	[1996/03/09  23:27:13  marty  1.1.4.2]
 *
 * Revision 1.1.4.2  1996/03/09  23:27:13  marty
 * 	Update OSF copyright year
 * 	[1996/03/09  22:42:43  marty]
 * 
 * Revision 1.1.4.1  1995/12/08  17:40:54  root
 * 	Submit OSF/DCE 1.2.1
 * 	[1995/12/08  17:18:01  root]
 * 
 * Revision 1.1.2.1  1993/12/22  12:39:17  zeliff
 * 	First version of code
 * 	[1993/12/21  15:01:30  zeliff]
 * 
 * $EndLog$
 */

[uuid(00903242-8343-1c87-be14-02608c0ff790),
version(1.0),
pointer_default(unique)
]

interface audit_stor {

    import "dce/utctypes.idl";
    import "dce/aclbase.idl";
    import "dce/audit_log.idl";

    typedef struct {
        unsigned32  		record_count;
        [size_is(record_count)] unsigned32     index[];
    } index_list_t;

    void audit_stor_dencode (
	[in]	    handle_t	           h,
	[in, out]   index_list_t	   ** indexes
    );

}
