/*
 * @OSF_COPYRIGHT@
 * COPYRIGHT NOTICE
 * (c) Copyright International Business Machines Corp. 1994, 1996
 * Copyright (c) 1990, 1991, 1992, 1993, 1994, 1996 Open Software Foundation, Inc.
 * ALL RIGHTS RESERVED (DCE).  See the file named COPYRIGHT.DCE in the
 * src directory for the full copyright text.
 *
 */
/*
 * HISTORY
 * $Log: audit_pickle.idl,v $
 * Revision 1.1.6.1  1996/07/08  18:29:12  arvind
 * 	Audit for 1.2.2
 * 	[1996/06/21  20:25 UTC  arvind  /main/arvind_audit122/1]
 *
 * 	Audit for 1.2.2
 * 	[1996/03/09  23:27:11  marty  1.1.4.2]
 *
 * Revision 1.1.4.2  1996/03/09  23:27:11  marty
 * 	Update OSF copyright year
 * 	[1996/03/09  22:42:41  marty]
 * 
 * Revision 1.1.4.1  1995/12/08  17:40:44  root
 * 	Submit OSF/DCE 1.2.1
 * 	[1995/12/08  17:17:59  root]
 * 
 * Revision 1.1.2.2  1994/07/27  14:54:15  weisz
 * 	CR 11372: added status parameter to audit_pickle_dencode_ev_info.
 * 	[1994/07/27  14:53:29  weisz]
 * 
 * Revision 1.1.2.1  1993/12/22  12:39:15  zeliff
 * 	First version of code
 * 	[1993/12/21  15:01:28  zeliff]
 * 
 * $EndLog$
 */

[
uuid(003dc39a-74bd-1c82-a5eb-02608c0ff790),
version(1.0),
pointer_default(ptr)
]

interface audit_pickle {

    import "dce/utctypes.idl";
    import "dce/aclbase.idl";
    import "dce/audit_log.idl";

    void audit_pickle_dencode_ev_info (
	[in]	    handle_t	           h,
	[in, out]   dce_aud_hdr_t 	   * header,
	[in, out]   aud_log_ev_info_list_t ** info,
        [in, out]       error_status_t         *st
    );

}
