/*
 * @OSF_COPYRIGHT@
 * COPYRIGHT NOTICE
 * Copyright (c) 1990, 1991, 1992, 1993, 1994, 1996 Open Software Foundation, Inc.
 * ALL RIGHTS RESERVED (DCE).  See the file named COPYRIGHT.DCE for
 * the full copyright text.
 * All Rights Reserved
 */
/* 
 * HISTORY
 * $Log: sec_pkss_types_if.idl,v $
 * Revision 1.1.2.1  1996/10/04  16:37:27  arvind
 * 	OSF DCE 1.2.2 Drop 4
 * 	[1996/10/04  16:37:13  arvind]
 *
 * Revision /main/DCE_1.2.2/1  1996/09/09  21:30 UTC  arvind
 * 	     PKSS drop from DEC (DCE1.2.2)
 * 	     [1996/08/30  15:58 UTC  arvind  /main/arvind_pkss/1]
 * 
 * $EndLog$
 */
/* (c) Copyright 1996,
 * Digital Equipment Corporation, Maynard, Massachusetts, USA
 * All Rights Reserved
 *
 */

/*
 * PKSS IDL - all buffers containing sensitive data will be
 * explicitly zeroed before their storage is released.
 *
 * See OSF RFC 94.0 for details
 */

interface sec_pkss_types_if
{

const unsigned long PKSS_PWD_HASH_SIZE = 8;
const unsigned long PKSS_NONCE_SIZE = 8;

//
// PKSS operation ID's 
//

const unsigned long PKSS_PROTO_USR_KEY_GET = 1;
const unsigned long PKSS_PROTO_USR_KEY_CHG_CLT = 2;
const unsigned long PKSS_PROTO_USR_KEY_CHG_SVR = 3;

const unsigned long PKSS_PROTO_MGMT_ADD_USR_CLT = 11;
const unsigned long PKSS_PROTO_MGMT_ADD_USR_SVR = 12;
const unsigned long PKSS_PROTO_MGMT_DEL_USR = 13;
const unsigned long PKSS_PROTO_MGMT_MOD_USR_CLT = 14;
const unsigned long PKSS_PROTO_MGMT_MOD_USR_SVR = 15;

//
// PKSS change key flag values 
//

const unsigned long PKSS_SVR_GEN_KEY_NO = 0;
const unsigned long PKSS_SVR_GEN_KEY_YES = 1;


/*
 * PKSS context handle
 */
typedef [context_handle] void *sec_pkss_ctx_hdl_t;


/*
 * Structure for PKSS messages
 */

typedef struct
{
  unsigned32 msg_len;
  [ptr, size_is (msg_len)] byte *msg_p;
} sec_pkss_msg_buf_t;

typedef [ptr] sec_pkss_msg_buf_t *sec_pkss_msg_buf_p_t;

} /* End interface sec_pkss_types */

