/*
 * @OSF_COPYRIGHT@
 * COPYRIGHT NOTICE
 * Copyright (c) 1990, 1991, 1992, 1993, 1994, 1996 Open Software Foundation, Inc.
 * ALL RIGHTS RESERVED (DCE).  See the file named COPYRIGHT.DCE for
 * the full copyright text.
 * All Rights Reserved
 */
/*
 * HISTORY
 * $Log: sec_pkss_clt_if.idl,v $
 * Revision 1.1.2.1  1996/10/04  14:23:25  arvind
 * 	OSF DCE 1.2.2 Drop 4
 * 	[1996/10/04  13:47:29  arvind]
 *
 * Revision /main/DCE_1.2.2/1  1996/09/09  21:29 UTC  arvind
 * 	PKSS drop from DEC (DCE1.2.2)
 * 	[1996/08/30  15:58 UTC  arvind  /main/arvind_pkss/1]
 * 
 * $EndLog$
 */
/* (c) Copyright 1996,
 * Digital Equipment Corporation, Maynard, Massachusetts, USA
 * All Rights Reserved
 *
 */

/*
 * PKSS IDL - all buffers containing sensitive data will be
 * explicitly zeroed before their storage is released.
 *
 * See OSF RFC 94.0 for details
 */

[
	uuid (635c84c1-93cd-11cf-9fa0-08002b918ea1),
	version (1.0)
]

interface sec_pkss_clt_if
{

import "sec_pkss_types_if.idl";

/*
 * Improved Encrypted Key Exchange (steps one and two)
 */

error_status_t sec_pkss_clt_diffhell
(
  [in] handle_t binding,
  [out] sec_pkss_ctx_hdl_t *ctx_handle_p, /* context handle */
  [in]  sec_pkss_msg_buf_t *to_pkss_p,   /* Username,
					    domain id,
					    key usages bitmask,
					    key version number,
					    [E(Dc)]H2 */
  [out] sec_pkss_msg_buf_p_t *from_pkss_p, /* [E(Dp)]H2:[Np]D */
  [in,out] error_status_t *estatus_p
);

/*
 * Improved Encrypted Key Exchange conclusion (steps three and four)
 */

error_status_t sec_pkss_clt_pkey_get
(
  [in] handle_t binding,
  [in,out] sec_pkss_ctx_hdl_t *ctx_handle_p,   /* context handle */
  [in]  sec_pkss_msg_buf_t *to_pkss_p,   /* [Nc:Np:I]D */
  [out] sec_pkss_msg_buf_p_t *from_pkss_p, /* [[Kxu]H1:Kou:V:Nc]D */
  [in,out] error_status_t *estatus_p
);

/*
 * Change user's password/key (client generates new Kxu, Kou)
 */

error_status_t sec_pkss_chg_key_clt
(
  [in] handle_t binding,
  [in]  sec_pkss_ctx_hdl_t *ctx_handle_p, /* context handle */
  [in]  sec_pkss_msg_buf_t *to_pkss_p,  /* [[Kxu']H1':H2':Kou':[M]Kxu]D */
  [out] sec_pkss_msg_buf_p_t *from_pkss_p,/* [Nc:V:Status]D */
  [in,out] error_status_t *estatus_p
);

/*
 * Change user's password/key (server generates new Kxu, Kou)
 */

error_status_t sec_pkss_chg_key_svr
(
  [in] handle_t binding,
  [in] sec_pkss_ctx_hdl_t *ctx_handle_p,  /* context handle */
  [in]  sec_pkss_msg_buf_t *to_pkss_p,  /* [H1:H2:newpwd:key-chg?:[M]Kxu]D */
  [out] sec_pkss_msg_buf_p_t *from_pkss_p,/* [Nc:V:Status:Kou']D */
  [in,out] error_status_t *estatus_p
);

} /* End interface sec_pkss_clt */
