/*
 * @OSF_COPYRIGHT@
 * COPYRIGHT NOTICE
 * Copyright (c) 1990, 1991, 1992, 1993, 1994, 1996 Open Software Foundation, Inc.
 * ALL RIGHTS RESERVED (DCE).  See the file named COPYRIGHT.DCE for
 * the full copyright text.
 * All Rights Reserved
 */
/*
 * HISTORY
 * $Log: sec_pkss_mgmt_if.idl,v $
 * Revision 1.1.2.1  1996/10/04  14:25:08  arvind
 * 	OSF DCE 1.2.2 Drop 4
 * 	[1996/10/04  13:50:37  arvind]
 *
 * Revision /main/DCE_1.2.2/1  1996/09/09  21:30 UTC  arvind
 * 	PKSS drop from DEC (DCE1.2.2)
 * 	[1996/08/30  15:58 UTC  arvind  /main/arvind_pkss/1]
 * 
 * $EndLog$
 */
/* (c) Copyright 1996,
 * Digital Equipment Corporation, Maynard, Massachusetts, USA
 * All Rights Reserved
 *
 */

/*
 * PKSS management IDL - all buffers containing sensitive data
 * will be explicitly zeroed before their storage is released.
 */

[
	uuid (9a4caaa0-93cd-11cf-abd5-08002b918ea1),
	version (1.0)
]

interface sec_pkss_mgmt_if
{

import "sec_pkss_types_if.idl";

/*
 * PKSS management IDL
 */

/*
 * PKSS Diffie-Hellman key exchange
 */

error_status_t sec_pkss_mgmt_diffhell
(
  [in] handle_t binding,
  [in,out] sec_pkss_ctx_hdl_t *ctx_handle_p,  /* context handle */
  [in]  sec_pkss_msg_buf_t *to_pkss_p,  /* I:E(Dc):algList */
  [out] sec_pkss_msg_buf_p_t *from_pkss_p,/* E(Dp):H(algList):algId */
  [in,out] error_status_t *estatus_p
);

/*
 * PKSS management add user (client generates keys)
 */
error_status_t sec_pkss_mgmt_add_user_clt
(
  [in] handle_t binding,
  [in,out] sec_pkss_ctx_hdl_t *ctx_handle_p,  /* context handle */
  [in]  sec_pkss_msg_buf_t *to_pkss_p,  /* [Username:[Kxu]H1:H2:Kou]D */
  [out] sec_pkss_msg_buf_p_t *from_pkss_p, /* [V:Status]D */
  [in,out] error_status_t *estatus_p
);

/*
 * PKSS management add user (server generates keys)
 */
error_status_t sec_pkss_mgmt_add_user_svr
(
  [in] handle_t binding,
  [in,out] sec_pkss_ctx_hdl_t *ctx_handle_p,  /* context handle */
  [in]  sec_pkss_msg_buf_t *to_pkss_p,  /* [Username:password]D */
  [out] sec_pkss_msg_buf_p_t *from_pkss_p,/* [V:Kou:Status]D */
  [in,out] error_status_t *estatus_p
);

/*
 * PKSS management delete user
 */
error_status_t sec_pkss_mgmt_del_user
(
  [in] handle_t binding,
  [in]  sec_pkss_msg_buf_t *to_pkss_p,   /* Username four-tuple */
  [out] sec_pkss_msg_buf_p_t *from_pkss_p, /* Status */
  [in,out] error_status_t *estatus_p
);

/*
 * PKSS management modify user (client generates keys)
 */
error_status_t sec_pkss_mgmt_mod_user_clt
(
  [in] handle_t binding,
  [in,out] sec_pkss_ctx_hdl_t *ctx_handle_p,  /* context handle */
  [in]  sec_pkss_msg_buf_t *to_pkss_p,  /* [Username:[Kxu]H1:H2:Kou]D */
  [out] sec_pkss_msg_buf_p_t *from_pkss_p,/* [V:Status]D */
  [in,out] error_status_t *estatus_p
);

/*
 * PKSS management modify user (server generates keys)
 */
error_status_t sec_pkss_mgmt_mod_user_svr
(
  [in] handle_t binding,
  [in,out] sec_pkss_ctx_hdl_t *ctx_handle_p,  /* context handle */
  [in]  sec_pkss_msg_buf_t *to_pkss_p,  /* [Username:password:I]D */
  [out] sec_pkss_msg_buf_p_t *from_pkss_p,/* [V:Kou:Status]D */
  [in,out] error_status_t *estatus_p
);

} /* End interface sec_pkss_mgmt */

