/*
 * @OSF_COPYRIGHT@
 * COPYRIGHT NOTICE
 * Copyright (c) 1990, 1991, 1992, 1993, 1996 Open Software Foundation, Inc.
 * ALL RIGHTS RESERVED (DCE).  See the file named COPYRIGHT.DCE in the
 * src directory for the full copyright text.
 */
/*
 * HISTORY
 * $Log: refdels.idl,v $
 * Revision 1.1.4.2  1996/03/11  02:17:36  marty
 * 	Update OSF copyright years
 * 	[1996/03/10  19:55:02  marty]
 *
 * Revision 1.1.4.1  1995/12/11  19:28:38  root
 * 	Submit OSF/DCE 1.2.1
 * 	[1995/12/11  19:15:14  root]
 * 
 * Revision 1.1.2.2  1993/08/11  16:28:56  ganni
 * 	tests for new IDL functionality
 * 	[1993/08/11  16:16:27  ganni]
 * 
 * $EndLog$
 */
/*
*/
[uuid(A8F7B52E-221D-11CC-A608-08002B107359),
 pointer_default(ptr), version(0)] 
interface refdels
{
    typedef struct tree_tag 
    {
        long key;
        struct tree_tag *left;
        struct tree_tag *right;
    } tree_t;

    [reflect_deletions] void prune([in] handle_t h, 
              [in, out] tree_t *p_root, 
              [out] long *p_num_deletes,
              [out] long *p_checksum);

    [reflect_deletions] void ltor([in] handle_t h, 
              [in, out] tree_t *p_root); 

    [reflect_deletions] void triple([in] handle_t h, 
              [in, out] long *p_val);
}
