#
# @OSF_COPYRIGHT@
# COPYRIGHT NOTICE
# Copyright (c) 1990, 1991, 1992, 1993, 1996 Open Software Foundation, Inc.
# ALL RIGHTS RESERVED (DCE).  See the file named COPYRIGHT.DCE in the
# src directory for the full copyright text.
#
#
# HISTORY
# $Log: Makefile,v $
# Revision 1.2.12.2  1996/03/11  02:29:38  marty
# 	Update OSF copyright years
# 	[1996/03/10  20:00:57  marty]
#
# Revision 1.2.12.1  1995/12/11  20:15:37  root
# 	Submit OSF/DCE 1.2.1
# 	[1995/12/11  19:48:36  root]
# 
# Revision 1.2.9.1  1994/02/22  18:38:58  ohara
# 	remove Makefile.svr4 its not in the tree.
# 	[1994/02/18  16:06:56  ohara]
# 
# Revision 1.2.5.4  1993/02/04  20:32:00  cjd
# 	Embedded copyright notice
# 	[1993/02/04  20:28:58  cjd]
# 
# Revision 1.2.5.3  1993/02/01  21:33:38  hinman
# 	[hinman] - SVR4 changes
# 	[1993/02/01  21:04:36  hinman]
# 
# 	[hinman@sni] - Final merge before bsubmit
# 	[1993/01/31  16:30:30  hinman]
# 
# 	[hinman] - Check in merged SNI version
# 	[1993/01/11  16:15:43  hinman]
# 
# Revision 1.2.5.2  1992/12/18  18:17:26  marcyw
# 	Defect 4998: adding disclaimer comment
# 	[1992/12/18  18:10:30  marcyw]
# 
# Revision 1.2  1992/01/19  22:14:25  devrcs
# 	Dropping DCE1.0 OSF1_misc port archive
# 
# $EndLog$
#
#
#  * The Example code is provided to you as "Pass-through Code".
#  * Pass-through Code and its related Documentation are not warrented,
#  * supported, or indemnified by OSF, and are provided "AS IS".
#  * You can use, sublicense, or disribute the same at your own risk.
# 
#
#
#  OSF DCE Version 1.0 
#

IDIR		= /usr/examples/devkit_sample/
ILIST		= Makefile.timop README timop.idl timop.acf \
		  timop_aux.h timop_client.h timop_server.h \
		  timop_client.c timop_server.c timop_manager.c timop_refmon.c
DATAFILES	= ${ILIST}
.include <${RULES_MK}>
