/*
 * @OSF_COPYRIGHT@
 * COPYRIGHT NOTICE
 * Copyright (c) 1990, 1991, 1992, 1993, 1996 Open Software Foundation, Inc.
 * ALL RIGHTS RESERVED (DCE).  See the file named COPYRIGHT.DCE in the
 * src directory for the full copyright text.
 */
/*
 * HISTORY
 * $Log: xmitas_nested.idl,v $
 * Revision 1.1.4.2  1996/03/11  02:20:09  marty
 * 	Update OSF copyright years
 * 	[1996/03/10  19:56:24  marty]
 *
 * Revision 1.1.4.1  1995/12/11  19:32:18  root
 * 	Submit OSF/DCE 1.2.1
 * 	[1995/12/11  19:16:59  root]
 * 
 * Revision 1.1.2.2  1993/01/07  23:58:50  bbelch
 * 	Embedding copyright notice
 * 	[1993/01/06  13:47:50  bbelch]
 * 
 * Revision 1.1  1992/01/19  03:33:36  devrcs
 * 	Initial revision
 * 
 * $EndLog$
 */
/*
*/
[
uuid(b8a77dee-cb42-11c9-b679-08002b1110fa),
version(0.0)
]
interface xmitas_nested
{
typedef struct {long lo;} long_t;
typedef [transmit_as(long_t)] struct {short sh;} short_t;
typedef [transmit_as(short_t)] struct {small sm;} small_t;

void op0([in] handle_t h, [in,out] small_t *sm);
}
