# @OSF_COPYRIGHT@
# COPYRIGHT NOTICE
# Copyright (c) 1990, 1991, 1992, 1993, 1994, 1996 Open Software Foundation, Inc.
# ALL RIGHTS RESERVED (DCE).  See the file named COPYRIGHT.DCE for
# the full copyright text.
# 
# HISTORY
# $Log: Makefile,v $
# Revision 1.1.5.2  1996/03/11  01:37:17  marty
# 	Update copyright years
# 	[1996/03/10  19:40:03  marty]
#
# Revision 1.1.5.1  1995/12/11  16:54:48  root
# 	Submit
# 	[1995/12/11  16:39:19  root]
# 
# Revision 1.1.2.4  1994/07/06  15:12:11  marrek
# 	July 1994 code drop.
# 	[1994/07/06  12:03:45  marrek]
# 
# Revision 1.1.2.3  1994/06/10  20:24:21  devsrc
# 	cr10872 - fixed copyright
# 	[1994/06/10  17:00:38  devsrc]
# 
# Revision 1.1.2.2  1994/05/11  19:48:33  sally
# 	This fixes cf 10605 - vpath was wrong for install
# 	[1994/05/11  19:47:27  sally]
# 
# Revision 1.1.2.1  1994/05/10  14:38:00  marrek
# 	Fixes for April 1994 submission.
# 	[1994/05/06  11:25:53  marrek]
# 
# 	Created in April 1994 submission.
# 	[1994/05/03  12:17:20  marrek]
# 
# $EndLog$
#
# $RCSfile: Makefile,v $ $Revision: 1.1.5.2 $ $Date: 1996/03/11 01:37:17 $
#

IDIR    = /test/tet/functional/directory/xds/ts/lib/
IMODE           = 755

VPATH		= ../../../gds/ts/lib

ILIST           = 	shfuncs

.include <${RULES_MK}>

