/*
 * @OSF_COPYRIGHT@
 * COPYRIGHT NOTICE
 * Copyright (c) 1990, 1991, 1992, 1993, 1994, 1996 Open Software Foundation, Inc.
 * ALL RIGHTS RESERVED (DCE).  See the file named COPYRIGHT.DCE for
 * the full copyright text.
 */
/*
 * HISTORY
 * $Log: acl_encode.idl,v $
 * Revision 1.1.4.2  1996/03/09  23:27:42  marty
 * 	Update OSF copyright year
 * 	[1996/03/09  22:43:09  marty]
 *
 * Revision 1.1.4.1  1995/12/08  17:30:50  root
 * 	Submit OSF/DCE 1.2.1
 * 	[1995/12/08  16:54:45  root]
 * 
 * Revision 1.1.2.2  1994/06/10  17:13:18  annie
 * 	cr10872 - fixed copyright
 * 	[1994/06/10  17:06:08  annie]
 * 
 * Revision 1.1.2.1  1994/06/02  21:28:20  mdf
 * 	hp_sec_to_osf_3 drop, merge up with latest.
 * 	hp_sec_to_osf_3 drop
 * 	 /main/secd_auth/2  1994/05/03  15:24 UTC  burati
 * 	Remove uuid since it does nothing in a local interface anyway
 * 	 /main/secd_auth/1  1994/04/26  19:18 UTC  burati
 * 	DCE ACL encoding interface
 * 	[1994/05/24  15:15:51  mdf]
 * 
 * $EndLog$
 */

/* 
** Copyright (c) Hewlett-Packard Company 1994
** Unpublished work. All Rights Reserved.
*/
/*
** DCE ACL encoding interface 
*/

[
    uuid(5393ee32-5e11-11cd-b1eb-0800092414cc)
]

interface dce_acl_encode {

    import "dce/aclbase.idl";

    /*
     * Routines are used for both encoding and decoding data types.
     * Don't let the _encode suffix fool you. Check the associated
     * ACF file for [encode, decode] attributes to see exactly what's what.
     */
    void dce_acl_entry_encode(
        [in]     handle_t               h,
        [in,out] sec_acl_entry_t        *entry
    );
}
