/*
 * @OSF_COPYRIGHT@
 * COPYRIGHT NOTICE
 * Copyright (c) 1990, 1991, 1992, 1993, 1994, 1996 Open Software Foundation, Inc.
 * ALL RIGHTS RESERVED (DCE).  See the file named COPYRIGHT.DCE for
 * the full copyright text.
 */
/*
 * HISTORY
 * $Log: authz_encode.idl,v $
 * Revision 1.1.4.2  1996/03/09  23:27:46  marty
 * 	Update OSF copyright year
 * 	[1996/03/09  22:43:13  marty]
 *
 * Revision 1.1.4.1  1995/12/08  17:31:00  root
 * 	Submit OSF/DCE 1.2.1
 * 	[1995/12/08  16:54:49  root]
 * 
 * Revision 1.1.2.2  1994/06/17  18:42:16  devsrc
 * 	cr10872 - fix copyright
 * 	[1994/06/17  18:08:55  devsrc]
 * 
 * Revision 1.1.2.1  1994/05/11  19:09:40  ahop
 * 	hp_sec_to_osf_2 drop
 * 	DCE Service Ticket authorization data encoding
 * 	[1994/04/29  21:03:43  ahop]
 * 
 * $EndLog$
 */

/* 
** Copyright (c) Hewlett-Packard Company 1994
** Unpublished work. All Rights Reserved.
*/
/*
** Authorization data encoding interface 
*/

[
    uuid(3786bda6-3200-11cd-9499-0800097086bf)
]

interface sec_authz_encode {

    import "dce/authz_base.idl";

    void v1_1_authz_data_encode(
        [in]     handle_t               h,
        [in,out] sec_v1_1_authz_data_t  *v1_1_authz_data
    );

}
