/*
 * @OSF_COPYRIGHT@
 * COPYRIGHT NOTICE
 * Copyright (c) 1990, 1991, 1992, 1993, 1994, 1996 Open Software Foundation, Inc.
 * ALL RIGHTS RESERVED (DCE).  See the file named COPYRIGHT.DCE for
 * the full copyright text.
 */
/*
 * HISTORY
 * $Log: id_encode.idl,v $
 * Revision 1.1.4.2  1996/03/09  23:27:54  marty
 * 	Update OSF copyright year
 * 	[1996/03/09  22:43:22  marty]
 *
 * Revision 1.1.4.1  1995/12/08  17:31:27  root
 * 	Submit OSF/DCE 1.2.1
 * 	[1995/12/08  16:54:56  root]
 * 
 * Revision 1.1.2.3  1994/06/17  18:42:18  devsrc
 * 	cr10872 - fix copyright
 * 	[1994/06/17  18:08:57  devsrc]
 * 
 * Revision 1.1.2.2  1994/05/11  19:10:14  ahop
 * 	hp_sec_to_osf_2 drop
 * 	Add dlg_token_set
 * 	[1994/04/29  21:04:44  ahop]
 * 
 * Revision 1.1.2.1  1994/01/28  23:10:46  burati
 * 	Initial version (dlg_bl1)
 * 	[1994/01/18  20:52:24  burati]
 * 
 * $EndLog$
 */

/* 
** Copyright (c) Hewlett-Packard Company 1993, 1994
** Unpublished work. All Rights Reserved.
*/
/*
** Identity encoding interface 
*/

[
    uuid(5e1991fe-e1e3-11cc-80a5-0800093569b9)
]

interface sec_id_encode {

    import "dce/id_epac.idl";
    import "dce/prvnbase.idl";

    /*
     * Most routines are used for both encoding
     * and decoding data types.  Don't let the
     * _encode suffix fool you. Check the associated
     * ACF file for [encode, decode] attributes to
     * see exactly what's what.
     */
    void id_epac_data_encode(
        [in]     handle_t               h,
        [in,out] sec_id_epac_data_t     *epac_data
    );

    void id_epac_encode(
        [in]      handle_t              h,
        [in, out] sec_id_epac_t         *epac
    );

    void id_epac_set_encode(
        [in]     handle_t               h,
        [in,out] sec_id_epac_set_t      *epac_set
    );

    void id_dlg_token_set_encode(
        [in]     handle_t               h,
        [in,out] sec_dlg_token_set_t    *dlg_token_set
    );
}
