/*
 * @OSF_COPYRIGHT@
 * COPYRIGHT NOTICE
 * Copyright (c) 1990, 1991, 1992, 1993, 1996 Open Software Foundation, Inc.
 * ALL RIGHTS RESERVED (DCE).  See the file named COPYRIGHT.DCE in the
 * src directory for the full copyright text.
 */
/*
 * HISTORY
 * $Log: krb5rpc.idl,v $
 * Revision 1.1.4.2  1996/03/09  23:27:56  marty
 * 	Update OSF copyright year
 * 	[1996/03/09  22:43:25  marty]
 *
 * Revision 1.1.4.1  1995/12/08  17:31:41  root
 * 	Submit OSF/DCE 1.2.1
 * 	[1995/12/08  16:54:58  root]
 * 
 * Revision 1.1.2.2  1992/12/29  13:29:19  zeliff
 * 	Embedding copyright notice
 * 	[1992/12/28  20:16:41  zeliff]
 * 
 * Revision 1.1  1992/01/19  14:55:38  devrcs
 * 	Initial revision
 * 
 * $EndLog$
 */
/*
*/

/*  krb5rpc.idl V=2 12/16/91 //littl/prgy/src/idl
**
** Copyright (c) Hewlett-Packard Company 1991
** Unpublished work. All Rights Reserved.
**
*/
/* 
 * This interface provides an RPC facility for communicating with the
 * Kerberos V5 KDC.
 */

[
    uuid(8f73de50-768c-11ca-bffc-08001e039431),
    version(1.0)
]

interface krb5rpc {

    import "dce/nbase.idl";

    [idempotent] void rsec_krb5rpc_sendto_kdc (
        [in]        handle_t        h,
        [in]        unsigned32      len,
        [in, size_is(len)]
                    byte            message[],
        [in]        unsigned32      out_buf_len,
        [out]       unsigned32      *resp_len,
        [out, length_is(*resp_len), size_is(out_buf_len)]
                    byte            out_buf[],
        [out]       error_status_t  *st
    );
}
