/*
 * @OSF_COPYRIGHT@
 * COPYRIGHT NOTICE
 * Copyright (c) 1990, 1991, 1992, 1993, 1996 Open Software Foundation, Inc.
 * ALL RIGHTS RESERVED (DCE).  See the file named COPYRIGHT.DCE in the
 * src directory for the full copyright text.
 */
/*
 * HISTORY
 * $Log: oride_base.idl,v $
 * Revision 1.1.8.2  1996/03/09  23:27:58  marty
 * 	Update OSF copyright year
 * 	[1996/03/09  22:43:27  marty]
 *
 * Revision 1.1.8.1  1995/12/08  17:31:49  root
 * 	Submit OSF/DCE 1.2.1
 * 	[1995/12/08  16:55:00  root]
 * 
 * Revision 1.1.6.2  1994/08/31  19:54:28  rsalz
 * 	Add scd bindings file to oride_base.idl and use it (OT CR 10976).
 * 	[1994/08/31  19:31:36  rsalz]
 * 
 * Revision 1.1.6.1  1994/05/05  20:44:36  hasbrouc
 * 	add group override support (RFC 55)
 * 	[1994/05/05  19:11:47  hasbrouc]
 * 
 * Revision 1.1.4.2  1992/12/29  13:29:29  zeliff
 * 	Embedding copyright notice
 * 	[1992/12/28  20:48:21  zeliff]
 * 
 * Revision 1.1.2.2  1992/05/14  18:58:51  burati
 * 	Add sec_override_pw_all
 * 	[1992/05/14  01:52:36  burati]
 * 
 * Revision 1.1  1992/01/19  14:55:11  devrcs
 * 	Initial revision
 * 
 * $EndLog$
 */

/*  oride_base.idl V=3 08/12/91 //littl/prgy/src/idl
**
** Copyright (c) Hewlett-Packard Company 1991
** Unpublished work. All Rights Reserved.
**
*/
/*
 *  Override base types 
 */

interface oride_base {

    const char *   OVERRIDE_FILE        = "/etc/passwd_override";
    const signed32 OVERRIDE_FILE_LEN    = 20;

    const char *   GROUP_OVERRIDE_FILE        = "/etc/group_override";
    const signed32 GROUP_OVERRIDE_FILE_LEN    = 19;

    const char *   SCD_BINDINGS_FILE    = "/var/security/sec_clientd.binding";
    const signed32 SCD_BINDINGS_FILE_LEN= 33;

    typedef  unsigned32  sec_override_fields_t;
    typedef  unsigned32  sec_group_override_fields_t;

        const unsigned32  sec_override_pw_uid      = 0x1;
        const unsigned32  sec_override_pw_gid      = 0x2;
        const unsigned32  sec_override_pw_passwd   = 0x4;
        const unsigned32  sec_override_pw_gecos    = 0x8;
        const unsigned32  sec_override_pw_dir      = 0x10;
        const unsigned32  sec_override_pw_shell    = 0x20;
        /* All override-able fields overridden */
        const unsigned32  sec_override_pw_all      = 0x3F;

        /*
         * bits 7-32 unused 
         */
        const unsigned32  sec_override_none        = 0;

	/* contant bits for group override buffer */
 
	const unsigned32 sec_group_override_none = 0x0;
	const unsigned32 sec_group_override_gr_gid = 0x1;
	const unsigned32 sec_group_override_gr_passwd = 0x2;
	const unsigned32 sec_group_override_member = 0x4;

}

