/*
 * @OSF_COPYRIGHT@
 * COPYRIGHT NOTICE
 * Copyright (c) 1996 Open Software Foundation, Inc.
 * ALL RIGHTS RESERVED (DCE).  See the file named COPYRIGHT.DCE for
 * the full copyright text.
 */
/*
 * HISTORY
 * $Log: passwd_encode.idl,v $
 * Revision 1.1.2.1  1996/08/09  19:19:22  arvind
 * 	Merge Registry support for KDC private key storage
 * 	[1996/07/16  22:18 UTC  aha  /main/aha_pk6/2]
 *
 * 	Add dce/ before imported idl files
 * 	[1996/07/15  18:05 UTC  aha  /main/aha_pk6/1]
 *
 * 	Specifications for using IDL encoding stubs to encode sec_passwd_rec_t
 * 	[1996/07/15  18:05 UTC  aha  /main/aha_pk6/1]
 *
 * 	DCE 1.2.2 intermediate drop (post bl3/pre bl4)
 * 	[1996/08/08  20:24:02  arvind]
 *
 * $EndLog$
 */

/* 
** Copyright (c) Hewlett-Packard Company 1996
** Unpublished work. All Rights Reserved.
*/
/*
** Password encoding interface 
*/

[
    uuid(d42a97b8-cec0-11cf-8ac9-08000919ebb5)
]

interface sec_passwd_encode {

    import "dce/passwd.idl";
    import "dce/sec_pk_base.idl";

    /*
     * Most routines are used for both encoding
     * and decoding data types.  Don't let the
     * _encode suffix fool you. Check the associated
     * ACF file for [encode, decode] attributes to
     * see exactly what's what.
     */
    void pwd_encode(
        [in]     handle_t               h,
        [in,out] sec_passwd_rec_t       *pwd_rec_p
    );
}
