/*
 * @OSF_COPYRIGHT@
 * COPYRIGHT NOTICE
 * Copyright (c) 1990, 1991, 1992, 1993, 1996 Open Software Foundation, Inc.
 * ALL RIGHTS RESERVED (DCE).  See the file named COPYRIGHT.DCE in the
 * src directory for the full copyright text.
 */
/*
 * HISTORY
 * $Log: pkl.idl,v $
 * Revision 1.1.4.2  1996/03/09  23:28:02  marty
 * 	Update OSF copyright year
 * 	[1996/03/09  22:43:30  marty]
 *
 * Revision 1.1.4.1  1995/12/08  17:32:07  root
 * 	Submit OSF/DCE 1.2.1
 * 	[1995/12/08  16:55:04  root]
 * 
 * Revision 1.1.2.2  1992/12/29  13:29:49  zeliff
 * 	Embedding copyright notice
 * 	[1992/12/28  20:16:55  zeliff]
 * 
 * Revision 1.1  1992/01/19  14:55:37  devrcs
 * 	Initial revision
 * 
 * $EndLog$
 */
/*
*/

/*  pkl.idl V=3 12/05/91 //efferdent/d2/idl2
**
** Copyright (c) Hewlett-Packard Company 1991
** Unpublished work. All Rights Reserved.
**
*/
/*
**  Copyright (c) 1991 by
**      Hewlett-Packard Company, Palo Alto, Ca.
**
**   Copyright (c) Hewlett-Packard Company 1991
**   Unpublished work. All Rights Reserved.
**  
**
**  NAME:
**
**      pkl.idl
**
**  FACILITY:
**
**      Pickling support
**
**  ABSTRACT:
**
**      local interface to pickling support
**
**  
**
*/

[
local,
version(1.0)
]
interface pkl
{

import "dce/pklbase.idl";
import "dce/rpcbase.idl";

/*
 * i d l _ p  k l _ g e t _ t y p e _ u u i d
 *
 * Operation to extract a type uuid from (the header part of) an
 * idl_pkl_t.
 */
void idl_pkl_get_type_uuid
(
    [in]  idl_pkl_t  pickle,
    [out] uuid_t    *type
);

/*
 * i d l _ p k l _ g e t _ h e a d e r
 *
 * Operation to extract all "fields" from (the header part of) an
 * idl_pkl_t.
 */
void idl_pkl_get_header
(
    [in]  idl_pkl_t        pickle,
    [out] unsigned8       *version,
    [out] unsigned32      *length,
    [out] rpc_syntax_id_t *syntax,
    [out] uuid_t          *type
);

/*
 * i d l _ p k l _ s e t _ h e a d e r
 *
 * Operation to set all "fields" in (the header part of) an
 * idl_pkl_t.
 */
void idl_pkl_set_header
(
    [out] idl_pkl_t        pickle,
    [in]  unsigned32       version,
    [in]  unsigned32       length,
    [in]  rpc_syntax_id_t *syntax,
    [in]  uuid_t          *type
);

}
