/*
 * @OSF_COPYRIGHT@
 * COPYRIGHT NOTICE
 * Copyright (c) 1990, 1991, 1992, 1993, 1996 Open Software Foundation, Inc.
 * ALL RIGHTS RESERVED (DCE).  See the file named COPYRIGHT.DCE in the
 * src directory for the full copyright text.
 */
/*
 * HISTORY
 * $Log: rpladmn.idl,v $
 * Revision 1.1.4.2  1996/03/09  23:28:16  marty
 * 	Update OSF copyright year
 * 	[1996/03/09  22:43:44  marty]
 *
 * Revision 1.1.4.1  1995/12/08  17:33:16  root
 * 	Submit OSF/DCE 1.2.1
 * 	[1995/12/08  16:55:17  root]
 * 
 * Revision 1.1.2.3  1992/12/29  13:30:34  zeliff
 * 	Embedding copyright notice
 * 	[1992/12/28  20:48:41  zeliff]
 * 
 * Revision 1.1.2.2  1992/11/04  22:26:23  burati
 * 	rgybase.idl must be imported from dce/
 * 	[1992/11/04  21:19:07  burati]
 * 
 * Revision 1.1  1992/01/19  14:55:18  devrcs
 * 	Initial revision
 * 
 * $EndLog$
 */

/*  rpladmn.idl V=2 09/30/91 //littl/prgy/src/idl
**
** Copyright (c) Hewlett-Packard Company 1991
** Unpublished work. All Rights Reserved.
**
*/
/* User Registry - replica management - client agent
*  Copyright (c) Hewlett-Packard Company 1991
* Unpublished work. All Rights Reserved.
*
*  VersionID = @(#)rpladmn.idl	2 - 09/30/91
*/

[local]
interface sec_rgy_rep_admin

{

    import "dce/rgybase.idl";

    /*
     * s e c _ r g y _ r e p  _ a d m i n _ s t o p 
     *
     * Stop the replica identified by this handle.
     */
    void sec_rgy_rep_admin_stop (
        [in]    sec_rgy_handle_t    context,
        [out]   error_status_t      *status
    );

    /*
     * s e c _ r g y _ r e p _ a d m i n _ m a i n t
     *
     * Put replica in or out of maintenance mode.
     */
    void sec_rgy_rep_admin_maint(
        [in]    sec_rgy_handle_t    context,
        [in]    boolean32           in_maintenance,
        [out]   error_status_t      *status
    );

    /*
     * s e c _ r g y _ r e p _ a d m i n _ m k e y
     *
     * Change the master key and re-encrypt the database
     */
    void sec_rgy_rep_admin_mkey(
        [in]    sec_rgy_handle_t    context,
        [out]   error_status_t      *status
    );


    /*
     * s e c _ r g y _ r e p _ a d m i n _ i n f o
     *
     * Retrieve information about this replica.
     */
/*    void sec_rgy_rep_admin_info(
        [in]    sec_rgy_handle_t    context,
        [out]   rs_replica_info_t   *rep_info,
        [out]   error_status_t      *status
    );
*/
}
