/*
 * @OSF_COPYRIGHT@
 * COPYRIGHT NOTICE
 * Copyright (c) 1990, 1991, 1992, 1993, 1996 Open Software Foundation, Inc.
 * ALL RIGHTS RESERVED (DCE).  See the file named COPYRIGHT.DCE in the
 * src directory for the full copyright text.
 */
/*
 * HISTORY
 * $Log: rs_bind.idl,v $
 * Revision 1.1.4.2  1996/03/09  23:28:26  marty
 * 	Update OSF copyright year
 * 	[1996/03/09  22:43:54  marty]
 *
 * Revision 1.1.4.1  1995/12/08  17:34:17  root
 * 	Submit OSF/DCE 1.2.1
 * 	[1995/12/08  16:55:26  root]
 * 
 * Revision 1.1.2.5  1993/02/26  23:49:09  emartin
 * 	em_bl6f: add cellname and update_site_name args
 * 	[1993/02/24  22:06:39  emartin]
 * 
 * Revision 1.1.2.4  1992/12/29  13:30:50  zeliff
 * 	Embedding copyright notice
 * 	[1992/12/28  20:48:48  zeliff]
 * 
 * Revision 1.1.2.3  1992/11/04  23:00:26  ahop
 * 	Third replication drop: bl6a
 * 	[1992/11/04  22:58:48  ahop]
 * 
 * Revision 1.1.2.2  1992/11/04  22:51:40  john
 * 	Initial Creation.
 * 	[1992/11/04  22:51:12  john]
 * 
 * $EndLog$
 */

/*
 * Copyright (c) Hewlett-Packard Company 1992
 * Unpublished work. All Rights Reserved.
 */
/*
 *      Registry server binding operations.
 */

[
    uuid(D46113D0-A848-11CB-B863-08001E046AA5),
    version(2.0),
    pointer_default(ptr)
]
interface rs_bind {

    import  "dce/rgynbase.idl";
    import  "dce/rplbase.idl";


    /*
     * Get a reference to an update site
     */
    void rs_bind_get_update_site(
        [in]    handle_t                h,
        [out]   sec_rgy_name_t          cellname,
        [out]   boolean32               *update_site,       /* is this site an update site? */
        [out]   rs_replica_name_p_t     *update_site_name,  /* cell-relative name of update site */
        [out]   uuid_t                  *update_site_id,    /* uuid of an update site */
        [out]   rs_replica_twr_vec_p_t  *update_site_twrs,  /* tower set of update site */
        [out]   error_status_t          *st
    );

}
