/*
 * @OSF_COPYRIGHT@
 * COPYRIGHT NOTICE
 * Copyright (c) 1990, 1991, 1992, 1993, 1994, 1996 Open Software Foundation, Inc.
 * ALL RIGHTS RESERVED (DCE).  See the file named COPYRIGHT.DCE for
 * the full copyright text.
 */
/*
 * HISTORY
 * $Log: rs_login_activity.idl,v $
 * Revision 1.1.5.2  1996/03/09  23:28:27  marty
 * 	Update OSF copyright year
 * 	[1996/03/09  22:43:55  marty]
 *
 * Revision 1.1.5.1  1995/12/08  17:34:24  root
 * 	Submit OSF/DCE 1.2.1
 * 	[1995/12/08  16:55:26  root]
 * 
 * Revision 1.1.2.3  1994/08/29  15:51:34  hondo
 * 	OT 11919 --login activity idl change to support different address types
 * 	[1994/08/28  21:49:09  hondo]
 * 
 * Revision 1.1.2.2  1994/08/10  19:21:51  annie
 * 	expand copyright with OSF copyright text
 * 	[1994/08/10  17:16:07  annie]
 * 
 * Revision 1.1.2.1  1994/07/15  15:00:10  mdf
 * 	Hewlett Packard Security Code Drop
 * 	[1994/07/14  17:59:45  mdf]
 * 
 * $EndLog$
 */
[
    uuid(bb24e322-dd2d-11cc-a507-080009353559),
    version(1)
]
interface rs_login_activity {

    import "dce/rsbase.idl";
    import "dce/rgynbase.idl";
    import "dce/rs_login_base.idl";


    /* r s _ l o g i n _ a c t i v i t y _ l o o k u p 
     *
     *
     *    In Parameters:
     *
     * Errors:
     */
    void rs_login_activity_lookup(
        [in]    handle_t                        h,
        [in]    sec_rgy_login_name_t            *login_name, 
    [out,ref]   sec_rgy_login_activity_t        *login_part,
        [out]   error_status_t                  *st_p
    );

    void rs_login_activity_update(
        [in]    handle_t                    h,
        [in]    sec_rgy_login_name_t        *login_name,    
        [in]    sec_rgy_login_activity_t    *login_part,   
        [in]    uuid_t                      *client,      
        [out]   error_status_t              *st_p
    );


}
