/*
 * @OSF_COPYRIGHT@
 * COPYRIGHT NOTICE
 * Copyright (c) 1990, 1991, 1992, 1993, 1996 Open Software Foundation, Inc.
 * ALL RIGHTS RESERVED (DCE).  See the file named COPYRIGHT.DCE in the
 * src directory for the full copyright text.
 */
/*
 * HISTORY
 * $Log: rs_prop_plcy.idl,v $
 * Revision 1.1.4.2  1996/03/09  23:28:38  marty
 * 	Update OSF copyright year
 * 	[1996/03/09  22:44:05  marty]
 *
 * Revision 1.1.4.1  1995/12/08  17:35:20  root
 * 	Submit OSF/DCE 1.2.1
 * 	[1995/12/08  16:55:36  root]
 * 
 * Revision 1.1.2.4  1993/03/29  22:19:47  emartin
 * 	CR 7593. Add rs_prop_plcy_set_dom_cache_info
 * 	[1993/03/25  21:26:30  emartin]
 * 
 * 	CR 7395.  Add rs_prop_plcy_set_dom_cache_info
 * 	[1993/03/25  21:17:41  emartin]
 * 
 * Revision 1.1.2.3  1992/12/29  13:31:14  zeliff
 * 	Embedding copyright notice
 * 	[1992/12/28  20:49:03  zeliff]
 * 
 * Revision 1.1.2.2  1992/08/31  18:21:26  sekhar
 * 	First replication code drop.
 * 	[1992/08/31  17:49:19  sekhar]
 * 
 * $EndLog$
 */

/*
 * Copyright (c) Hewlett-Packard Company 1992
 * Unpublished work. All Rights Reserved.
 *
 *  NAME:
 *
 *      rs_prop_plcy.idl
 *
 *  FACILITY:
 *
 *      Security 
 *
 *  ABSTRACT:
 *
 *      Registry server propagation interface - properties and policies
 */

[
    uuid(e6ac5cb8-de3e-11ca-9376-08001e0394c7),
    version(1.1),
    pointer_default(ptr)
]

interface rs_prop_plcy

{
    import 
        "dce/rgynbase.idl",
        "dce/rsbase.idl",
        "dce/rplbase.idl";

    /*
     * rs_prop_properties_set_info 
     */
    void  rs_prop_properties_set_info (
        [in]       handle_t                  h,
        [in, ref]  sec_rgy_properties_t      * properties,
        [in, ref]  rs_replica_master_info_t  * master_info,
        [in]       boolean32                 propq_only,
        [out]      error_status_t            *status
    );

    /*
     * rs_prop_plcy_set_info 
     */
    void  rs_prop_plcy_set_info (
        [in]       handle_t                  h,
        [in, ref]  sec_rgy_name_t            organization,
        [in, ref]  sec_rgy_plcy_t            * policy_data,
        [in, ref]  rs_replica_master_info_t  * master_info,
        [in]       boolean32                 propq_only,
        [out]      error_status_t            *status
    );


    /*
     * rs_prop_auth_plcy_set_info  
     */
   void  rs_prop_auth_plcy_set_info (
        [in]       handle_t                  h,
        [in, ref]  sec_rgy_login_name_t      * account,
        [in, ref]  sec_rgy_plcy_auth_t       * auth_policy,
        [in, ref]  rs_replica_master_info_t  * master_info,
        [in]       boolean32                 propq_only,
        [out]      error_status_t            * status
    );

    /*
     * rs_prop_plcy_set_dom_cache_info 
     */
   void  rs_prop_plcy_set_dom_cache_info (
        [in]       handle_t                  h,
        [in, ref]  rs_cache_data_t           * cache_info,
        [in, ref]  rs_replica_master_info_t  * master_info,
        [in]       boolean32                 propq_only,
        [out]      error_status_t            * status
    );
}


