/*
 * @OSF_COPYRIGHT@
 * COPYRIGHT NOTICE
 * Copyright (c) 1990, 1991, 1992, 1993, 1994, 1996 Open Software Foundation, Inc.
 * ALL RIGHTS RESERVED (DCE).  See the file named COPYRIGHT.DCE for
 * the full copyright text.
 */
/*
 * HISTORY
 * $Log: rs_prop_login_reset.idl,v $
 * Revision 1.1.7.3  1996/03/09  23:28:36  marty
 * 	Update OSF copyright year
 * 	[1996/03/09  22:44:03  marty]
 *
 * Revision 1.1.7.2  1995/12/08  17:35:10  root
 * 	Submit OSF/DCE 1.2.1
 * 	[1995/12/08  16:55:34  root]
 * 
 * Revision 1.1.2.2  1994/10/27  20:07:07  rrizzo
 * 	expand copyright
 * 	[1994/10/27  19:39:23  rrizzo]
 * 
 * Revision 1.1.2.1  1994/10/26  20:00:41  hondo
 * 	changes for propagation of login activity.
 * 	[1994/10/24  22:26:17  hondo]
 * 
 * $EndLog$
 */

/*
 * Copyright (c) Hewlett-Packard Company 1994
 * Unpublished work.  All Rights Reserved.
 */

[ 
   uuid(bb8a80e2-dd2d-11cc-a842-080009353559),
   version(1),
   pointer_default(ptr)
]

interface rs_prop_login

{
    import "dce/rplbase.idl";
    import "dce/rs_login_base.idl";


    /*
     * rs_prop_login_reset
     */
    void rs_prop_login_reset (
        [in]       handle_t                     h,
        [in]       sec_rgy_login_name_t         * login_name,
        [in]       sec_rgy_login_activity_t     * login_part,
        [in]       uuid_t                       * client,
        [in]       sec_timeval_sec_t            * time_now,
        [in]       rs_replica_master_info_t     * master_info,
        [in]       boolean32                    propq_only,
        [out]      error_status_t               *st
    );

}

