/*
 * @OSF_COPYRIGHT@
 * COPYRIGHT NOTICE
 * Copyright (c) 1990, 1991, 1992, 1993, 1996 Open Software Foundation, Inc.
 * ALL RIGHTS RESERVED (DCE).  See the file named COPYRIGHT.DCE in the
 * src directory for the full copyright text.
 */
/*
 * HISTORY
 * $Log: rs_prop_replist.idl,v $
 * Revision 1.1.4.2  1996/03/09  23:28:40  marty
 * 	Update OSF copyright year
 * 	[1996/03/09  22:44:06  marty]
 *
 * Revision 1.1.4.1  1995/12/08  17:35:26  root
 * 	Submit OSF/DCE 1.2.1
 * 	[1995/12/08  16:55:37  root]
 * 
 * Revision 1.1.2.4  1993/01/26  23:00:48  emartin
 * 	rs_prop_replist_delete_replica => rs_prop_replist_del_replica
 * 	[1993/01/13  16:26:08  emartin]
 * 
 * Revision 1.1.2.3  1992/12/29  13:52:46  zeliff
 * 	Embedding copyright notice
 * 	[1992/12/28  20:49:07  zeliff]
 * 
 * Revision 1.1.2.2  1992/08/31  18:21:31  sekhar
 * 	First replication code drop.
 * 	[1992/08/31  17:49:25  sekhar]
 * 
 * $EndLog$
 */

/*
 * Copyright (c) Hewlett-Packard Company 1992
 * Unpublished work. All Rights Reserved.
 *
 *  NAME:
 *
 *      rs_prop_replist.idl
 *
 *  FACILITY:
 *
 *      Security 
 *
 *  ABSTRACT:
 *
 *      Registry server operations to propagate replica list 
 *      updates from master to slave.
 */
  
[
 uuid(B7FB9CE8-DFD4-11CA-8016-08001E02594C),
 version(1.0),
 pointer_default(ptr)
]

interface rs_prop_replist
{
    import "dce/rgynbase.idl";
    import "dce/rplbase.idl";
    
    /*
     *  rs_prop_replist_add_replica
     *
     */
    void rs_prop_replist_add_replica(
        [in]    handle_t                    h,
        [in]    uuid_p_t                    rep_id,
        [in]    rs_replica_name_p_t         rep_name,
        [in]    rs_replica_twr_vec_p_t      rep_twrs,
        [in]    rs_replica_master_info_p_t  master_info,
        [in]    boolean32                   propq_only,
        [out]   error_status_t              *st
    );

    /*
     *  rs_prop_replist_del_replica
     *
     */
    void rs_prop_replist_del_replica(
        [in]    handle_t                    h,
        [in]    uuid_p_t                    rep_id,
        [in]    rs_replica_master_info_p_t  master_info,
        [in]    boolean32                   propq_only,
        [out]   error_status_t              *st
    );

}
