/*
 * @OSF_COPYRIGHT@
 * COPYRIGHT NOTICE
 * Copyright (c) 1990, 1991, 1992, 1993, 1996 Open Software Foundation, Inc.
 * ALL RIGHTS RESERVED (DCE).  See the file named COPYRIGHT.DCE in the
 * src directory for the full copyright text.
 */
/*
 * HISTORY
 * $Log: rs_prop_acl.idl,v $
 * Revision 1.1.6.2  1996/03/09  23:28:33  marty
 * 	Update OSF copyright year
 * 	[1996/03/09  22:44:01  marty]
 *
 * Revision 1.1.6.1  1995/12/08  17:34:56  root
 * 	Submit OSF/DCE 1.2.1
 * 	[1995/12/08  16:55:31  root]
 * 
 * Revision 1.1.4.2  1993/08/04  13:37:43  cuti
 * 	Insert dce/ in front of imported file name
 * 	[1993/08/03  20:51:39  cuti]
 * 
 * Revision 1.1.2.3  1992/12/29  13:31:10  zeliff
 * 	Embedding copyright notice
 * 	[1992/12/28  20:48:56  zeliff]
 * 
 * Revision 1.1.2.2  1992/08/31  18:21:09  sekhar
 * 	First replication code drop.
 * 	[1992/08/31  17:49:02  sekhar]
 * 
 * $EndLog$
 */

/*
 * Copyright (c) Hewlett-Packard Company 1992
 * Unpublished work. All Rights Reserved.
 *
 *  NAME:
 *
 *      rs_prop_acl.idl
 *
 *  FACILITY:
 *
 *      Security 
 *
 *  ABSTRACT:
 *
 *      Registry server propagation interface - ACLs. 
 */

[
    uuid(591d87d0-de64-11ca-a11c-08001e0394c7),
    version(1),
    pointer_default(ptr)
]

interface rs_prop_acl

{
    import 
        "dce/rplbase.idl",
        "dce/aclbase.idl";

    /*
     * data type used for bulk acl replace propagations during intialization 
     */
    typedef  struct {
        sec_acl_component_name_t  component_name;
        uuid_t                    manager_type; 
        sec_acl_type_t            acl_type;
        sec_acl_list_t            * acl_list;
    } rs_prop_acl_data_t;

                
    /*
     * rs_prop_acl_replace 
     */
    void rs_prop_acl_replace (
        [in]       handle_t                    h,
        [in]       unsigned32                  num_acls,
        [in, size_is(num_acls)]
                   rs_prop_acl_data_t          acls[],
        [in, ref]  rs_replica_master_info_t    * master_info,
        [in]       boolean32                   propq_only,
        [out]      error_status_t              * st
    );
}



