/*
 * @OSF_COPYRIGHT@
 * COPYRIGHT NOTICE
 * Copyright (c) 1990, 1991, 1992, 1993, 1996 Open Software Foundation, Inc.
 * ALL RIGHTS RESERVED (DCE).  See the file named COPYRIGHT.DCE in the
 * src directory for the full copyright text.
 */
/*
 * HISTORY
 * $Log: rs_qry.idl,v $
 * Revision 1.1.4.2  1996/03/09  23:28:42  marty
 * 	Update OSF copyright year
 * 	[1996/03/09  22:44:08  marty]
 *
 * Revision 1.1.4.1  1995/12/08  17:35:38  root
 * 	Submit OSF/DCE 1.2.1
 * 	[1995/12/08  16:55:39  root]
 * 
 * Revision 1.1.2.2  1992/12/29  13:52:53  zeliff
 * 	Embedding copyright notice
 * 	[1992/12/28  20:17:36  zeliff]
 * 
 * Revision 1.1  1992/01/19  14:54:45  devrcs
 * 	Initial revision
 * 
 * $EndLog$
 */
/*
*/

/*  rs_qry.idl V=5 11/01/90 //littl/prgy/src/idl
**
** Copyright (c) Hewlett-Packard Company 1991
** Unpublished work. All Rights Reserved.
**
*/

/*
*rs_qry.idl, /us/lib/rgy/src, pato, 09/08/87
*      Find a registry server - query interface
*
* 
*  Copyright (c) Hewlett-Packard Company 1991
* Unpublished work. All Rights Reserved.
*
*
*  VersionID = @(#)rs_qry.idl	5 - 11/01/90
**/
[
 /* V1 format UUID: 3727ee604000.0d.00.00.87.84.00.00.00 */
 uuid(3727EE60-4000-0000-0D00-008784000000),
 version(1)]
interface rs_query
{
import "nbase.idl";


/*
*
* Find a registry server - query interface
* [ broadcast ] 
*/
    [idempotent] void rs_query_are_you_there
    (
        [in] handle_t         h,
        [out] error_status_t  *status
    );
}
