/*
 * @OSF_COPYRIGHT@
 * COPYRIGHT NOTICE
 * Copyright (c) 1990, 1991, 1992, 1993, 1996 Open Software Foundation, Inc.
 * ALL RIGHTS RESERVED (DCE).  See the file named COPYRIGHT.DCE in the
 * src directory for the full copyright text.
 */
/*
 * HISTORY
 * $Log: rs_update.idl,v $
 * Revision 1.1.4.2  1996/03/09  23:28:51  marty
 * 	Update OSF copyright year
 * 	[1996/03/09  22:44:16  marty]
 *
 * Revision 1.1.4.1  1995/12/08  17:36:13  root
 * 	Submit OSF/DCE 1.2.1
 * 	[1995/12/08  16:55:46  root]
 * 
 * Revision 1.1.2.3  1992/12/29  13:53:24  zeliff
 * 	Embedding copyright notice
 * 	[1992/12/28  20:49:24  zeliff]
 * 
 * Revision 1.1.2.2  1992/08/31  18:22:00  sekhar
 * 	First replication code drop.
 * 	[1992/08/31  17:49:49  sekhar]
 * 
 * $EndLog$
 */

/*
 * Copyright (c) Hewlett-Packard Company 1992
 * Unpublished work. All Rights Reserved.
 *
 *  NAME:
 *
 *      rs_update.idl
 *
 *  FACILITY:
 *
 *      Security 
 *
 *  ABSTRACT:
 *
 *      Registry server update interface.  This interface
 *      is registered in the nameservice by the master
 *      replica so that clients can locate the master.
 */

[
 uuid(3B11D6A8-2A9C-11CB-BE8A-08001E0238CA),
 version(1.0),
 pointer_default(ptr)
]
interface rs_update 
{
    import "dce/rgynbase.idl";
    import "dce/rplbase.idl";

    /*
     *  r s _ r e p_ a d m i n _ i n f o
     *
     *  Get basic information about a replica such
     *  as its state, uuid, latest update sequence
     *  number and timestamp, and whether it is the master.
     *  Also get the replica's information about the master's 
     *  uuid and the sequence number when the master was 
     *  designated.
     *
     *  The rs_repadm.idl info mgr routine will be invoked
     *  for this call
     */
    void rs_rep_admin_info(
        [in]    handle_t            h,
        [out]   rs_replica_info_t   *rep_info,
        [out]   error_status_t      *status
    );
}
