/*
 * @OSF_COPYRIGHT@
 * COPYRIGHT NOTICE
 * Copyright (c) 1990, 1991, 1992, 1993, 1996 Open Software Foundation, Inc.
 * ALL RIGHTS RESERVED (DCE).  See the file named COPYRIGHT.DCE in the
 * src directory for the full copyright text.
 */
/*
 * HISTORY
 * $Log: rsec_cert.idl,v $
 * Revision 1.1.4.2  1996/03/09  23:28:53  marty
 * 	Update OSF copyright year
 * 	[1996/03/09  22:44:17  marty]
 *
 * Revision 1.1.4.1  1995/12/08  17:36:21  root
 * 	Submit OSF/DCE 1.2.1
 * 	[1995/12/08  16:55:48  root]
 * 
 * Revision 1.1.2.2  1992/12/29  13:53:33  zeliff
 * 	Embedding copyright notice
 * 	[1992/12/28  20:21:59  zeliff]
 * 
 * Revision 1.1  1992/01/19  14:55:20  devrcs
 * 	Initial revision
 * 
 * $EndLog$
 */
/*
*/

/*  rsec_cert.idl V=2 08/13/91 //littl/prgy/src/idl
**
** Copyright (c) Hewlett-Packard Company 1991
** Unpublished work. All Rights Reserved.
**
*/
/*  rsec_cert.idl - Remote sec_login certify interface
** 
*/

[
    uuid(c57e83f0-58be-11ca-901c-08001e039448),
    version(1)
]

interface rsec_cert {

    /*
     * rsec_login_validate_cert_auth
     *      Validate Certification Authority, by making sure the client can
     *      make an authenticated call.  Presently, the fact that the caller
     *      was able to make the authenticated call is enough, but there is
     *      a status parameter in the signature so that future implementations
     *      may make additional checks if necessary.
     */
    void rsec_login_validate_cert_auth (
        [in]        handle_t                    h,
        [out]       error_status_t              *status
    );
}
