#
# @OSF_COPYRIGHT@
# COPYRIGHT NOTICE
# Copyright (c) 1990, 1991, 1992, 1993, 1996 Open Software Foundation, Inc.
# ALL RIGHTS RESERVED (DCE).  See the file named COPYRIGHT.DCE in the
# src directory for the full copyright text.
# HISTORY
# $Log: sec.msg,v $
# Revision 1.1.12.2  1996/03/09  23:28:57  marty
# 	Update OSF copyright year
# 	[1996/03/09  22:44:21  marty]
#
# Revision 1.1.12.1  1995/12/08  17:36:40  root
# 	Submit OSF/DCE 1.2.1
# 	[1995/12/08  16:55:51  root]
# 
# Revision 1.1.10.5  1994/07/15  15:00:16  mdf
# 	Hewlett Packard Security Code Drop
# 	[1994/07/14  17:17:29  mdf]
# 
# Revision 1.1.10.4  1994/06/02  21:28:38  mdf
# 	hp_sec_to_osf_3 drop, merge up with latest.
# 	[1994/05/24  15:16:17  mdf]
# 
# 	hp_sec_to_osf_3 drop
# 
# Revision 1.1.10.3  1994/05/11  19:13:05  ahop
# 	hp_sec_to_osf_2 drop
# 	Add more sec_pwd_mgmt errors.
# 	add yet more new priv server status codes.
# 	work on sec_attr codes
# 	[1994/04/29  21:08:24  ahop]
# 
# Revision 1.1.10.2  1994/03/02  17:55:23  hanfei
# 	Initial ERA drop
# 	[1994/02/18  19:19:52  hanfei]
# 
# Revision 1.1.7.3  1993/11/03  18:31:45  burati
# 	Add sec_acl_mgr_no_space
# 	[1993/11/03  18:29:05  burati]
# 
# Revision 1.1.7.2  1993/09/29  15:22:55  burati
# 	Fixed sec_login_s_already_valid
# 	[1993/09/29  15:22:09  burati]
# 
# 	bl6c: add some sec_rgy_rep codes
# 	[1992/12/11  22:31:13  emartin]
# 
# Revision 1.1.5.3  1993/09/15  15:41:58  root
# 	    Loading drop DCE1_0_3b03
# 
# Revision 1.1.4.16  1993/03/03  22:31:17  emartin
# 	sec_rgy_rep_doppelganger  new msg
# 	[1993/03/03  22:28:47  emartin]
# 
# Revision 1.1.4.15  1993/02/26  23:49:35  emartin
# 	em_bl6f: add sec_rgy_rep_master_bad_sw_vers,
# 	sec_rgy_rep_slave_bad_sw_vers
# 	[1993/02/22  22:41:35  emartin]
# 
# Revision 1.1.4.14  1993/02/11  20:45:42  ahop
# 	dbcp: add sec_rgy_log_entry_out_of_range
# 	[1993/02/11  20:44:40  ahop]
# 
# Revision 1.1.4.13  1993/02/10  20:34:12  emartin
# 	bl6e: sec_rgy_bad_nameservice_name
# 	[1993/02/04  23:21:26  emartin]
# 
# Revision 1.1.4.12  1993/02/05  21:49:23  sommerfeld
# 	[OT5718] add sec_s_invalid_auth_params
# 	[1993/02/04  22:24:44  sommerfeld]
# 
# Revision 1.1.4.11  1993/01/18  18:33:23  burati
# 	CR6548 New error code for invalid DFS acls
# 	[1993/01/18  16:46:58  burati]
# 
# Revision 1.1.4.10  1992/12/29  13:53:43  zeliff
# 	Embedding copyright notice
# 	[1992/12/28  20:49:32  zeliff]
# 
# Revision 1.1.4.9  1992/12/18  22:11:07  sekhar
# 	[OT 6540] Replication code drop bl6c
# 	[1992/12/18  21:47:37  sekhar]
# 
# Revision 1.1.4.8  1992/12/08  19:02:09  rps
# 	Add tower binding failure.
# 	[1992/12/03  01:25:35  rps]
# 
# Revision 1.1.4.7  1992/11/04  19:33:24  ahop
# 	Third replication drop: bl6a
# 	  Add sec_rgy_mkey_file_io_failed
# 	  Add sec_rgy_rep_init_ekey_invalid
# 	  Add sec_acl_server_bad_state, sec_rgy_host_context_not_avail.
# 	[1992/11/03  18:20:45  ahop]
# 
# Revision 1.1.4.6  1992/10/19  15:21:38  burati
# 	CRs5133,5134 Add new error status for bad DES key parity
# 	[1992/10/19  14:31:37  burati]
# 
# Revision 1.1.4.5  1992/10/14  15:21:59  burati
# 	CR4615 Add new error msg for invalid key table files
# 	[1992/10/13  21:30:12  burati]
# 
# Revision 1.1.4.4  1992/10/12  19:45:35  burati
# 	CR5221 Error text for sec_key_mgmt_key_unavailable wasn't quite correct
# 	[1992/10/12  17:45:55  burati]
# 
# Revision 1.1.4.3  1992/10/07  20:29:41  sekhar
# 	[OT 5566]  Bl5 Replication code drop from HP.
# 	[1992/10/07  19:13:49  sekhar]
# 
# Revision 1.1.5.2  1992/10/06  15:49:38  burati
# 	  Second replication code drop: bl5
# 	  Add sec_acl_server_bad_state, sec_rgy_host_context_not_avail.
# 
# Revision 1.1.4.2  1992/08/31  18:22:07  sekhar
# 	First security replication code drop
# 	[1992/08/31  15:09:00  sekhar]
# 
# Revision 1.1.2.7  1992/06/18  21:22:13  burati
# 	CR3983 Add sec_key_mgmt_e_keytab_not_found
# 	[1992/06/18  21:18:36  burati]
# 
# Revision 1.1.2.6  1992/05/26  20:44:11  sommerfeld
# 	Add sec_id_e_no_at_hack.
# 	[1992/05/22  20:27:42  sommerfeld]
# 
# Revision 1.1.2.5  1992/05/14  18:59:54  burati
# 	Add sec_login_s_ovrd_ent_not_found
# 	[1992/05/14  01:54:03  burati]
# 
# Revision 1.1.2.4  1992/05/08  17:08:53  sommerfeld
# 	Add status code to be returned when getting unexpected NULL parameter.
# 	[1992/05/07  18:11:14  sommerfeld]
# 
# Revision 1.1.2.3  1992/04/27  18:14:40  burati
# 	Shortened 2 sec_lrgy error codes to less than 31 char limit.
# 	[1992/04/24  18:08:56  burati]
# 
# Revision 1.1.2.2  1992/03/31  22:36:46  burati
# 	CR2419 New status codes for local registry support
# 	[1992/03/30  23:03:01  burati]
# 
# Revision 1.1  1992/01/19  19:50:56  devrcs
# 	Initial revision
# 
# $EndLog$
#
#
# Copyright (c) Hewlett-Packard Company 1991, 1992
# Unpublished work. All Rights Reserved.
#
##
##  FACILITY:
##
##	DCE security
##
##  This symbolic message source file (SMSF) defines the errors produced
##  by the security facility.  The first token on each line is the symbolic
##  name of an error.  The rest of the line is the text that describes
##  that error.	An SMSF is like an XPG message source file (MSF) except
##  that symbolic message identifiers are used instead of numbers.
##
##  NOTE WELL:	New errors must be added ONLY AT THE END of this file
##  (or by replacing reserved error codes) to
##  ensure that binary compatibility is maintained.  (We can't allow each
##  version of the security library having different meanings for each integer
##  status code.)  Symbols for errors that are no longer used, must still
##  be maintained here, until a coordinated built of all product components,
##  i.e. the next version.
##
##
sec_s_mod
sec_s_authz_unsupp		authorization protocol unsupported by authentication protocol.
sec_s_keytype_unsupp		unsupported session key type
sec_s_bad_nonce			incorrect response to challenge
sec_s_none_registered		no identity set yet
sec_s_no_pac			no privilege attributes available
sec_s_not_implemented		operation not implemented
sec_s_no_memory			unable to allocate memory.
sec_s_not_trustworthy		data originated by untrustworthy security/privilege server
sec_s_no_key_seed		no random key seed set yet.
sec_s_null_param_illegal	parameter must be non-NULL
sec_s_invalid_nameservice_entry invalid nameservice entry 
sec_s_pgmerr                    security server program error
sec_s_bad_key_parity            DES key has bad parity
sec_s_invalid_auth_params	Invalid authentication params
sec_s_PAD9		sec_s_PAD9
sec_s_PADa		sec_s_PADa
sec_s_PADb		sec_s_PADb
sec_s_PADc		sec_s_PADc
sec_s_PADd		sec_s_PADd
sec_s_PADe		sec_s_PADe
sec_s_PADf		sec_s_PADf
sec_acl_not_implemented		acl operation not implemented
sec_acl_cant_allocate_memory	acl operation unable to allocate memory
sec_acl_invalid_site_name	invalid site name for acl operation
sec_acl_unknown_manager_type	acl manager type not recognized
sec_acl_object_not_found	acl object not found
sec_acl_no_acl_found		no acl found
sec_acl_invalid_entry_name	invalid acl object name
sec_acl_expected_user_obj	acl operation expected user_obj
sec_acl_expected_group_obj	acl operation expected group_obj
sec_acl_invalid_entry_type	acl entry type not valid
sec_acl_invalid_acl_type	acl type not valid
sec_acl_bad_key			bad information in sec_acl_key
sec_acl_invalid_manager_type	acl manager type invalid
sec_acl_read_only		acl operation is read only
sec_acl_site_read_only		update acl operation not valid on a read only site
sec_acl_invalid_permission	permission not valid for this acl
sec_acl_bad_acl_syntax		bad acl syntax
sec_acl_no_owner		at least one control permission bit required on acl
sec_acl_invalid_entry_class	invalid acl entry class
sec_acl_unable_to_authenticate	unable to authenticate on acl operation
sec_acl_name_resolution_failed	name resolution failed on acl operation
sec_acl_rpc_error		rpc error on acl operation
sec_acl_bind_error		binding error on acl operation
sec_acl_invalid_acl_handle	invalid acl handle
sec_acl_no_update_sites		no update sites for this acl operation
sec_acl_mgr_file_open_error	acl manager file open error
sec_acl_missing_required_entry	missing required acl entry
sec_acl_duplicate_entry		duplicate acl entry
sec_acl_bad_parameter		bad parameter for acl operation
sec_acl_not_authorized          operation on acl not authorized
sec_acl_server_bad_state        acl server state doesn't support operation
sec_acl_invalid_dfs_acl	        not a valid DFS acl
sec_acl_mgr_no_space            not enough space for this ACL at specified ACL manager
sec_acl_bad_permset		permission set is not valid for this acl manager type
sec_acl_PAD5		sec_acl_PAD5
sec_acl_PAD6		sec_acl_PAD6
sec_acl_PAD7		sec_acl_PAD7
sec_acl_PAD8		sec_acl_PAD8
sec_acl_PAD9		sec_acl_PAD9
sec_acl_PADa		sec_acl_PADa
sec_acl_PADb		sec_acl_PADb
sec_acl_PADc		sec_acl_PADc
sec_acl_PADd		sec_acl_PADd
sec_acl_PADe		sec_acl_PADe
sec_acl_PADf		sec_acl_PADf
sec_key_mgmt_e_key_unavailable	Requested key is unavailable
sec_key_mgmt_e_authn_invalid	The authentication service is invalid
sec_key_mgmt_e_auth_unavailable	The authentication service is unavailable
sec_key_mgmt_e_unauthorized	The caller is unauthorized to perform operation
sec_key_mgmt_e_key_unsupported	A requested key type is not supported
sec_key_mgmt_e_key_version_ex	Specified key already exists in key store
sec_key_mgmt_e_not_implemented	Operation Not Implemented
sec_key_mgmt_e_keytab_not_found Specified key table not found
sec_key_mgmt_e_ktfile_err	Specified file is not a valid key table
sec_key_mgmt_s_PAD2		sec_key_mgmt_s_PAD2
sec_key_mgmt_s_PAD3		sec_key_mgmt_s_PAD3
sec_key_mgmt_s_PAD4		sec_key_mgmt_s_PAD4
sec_key_mgmt_s_PAD5		sec_key_mgmt_s_PAD5
sec_key_mgmt_s_PAD6		sec_key_mgmt_s_PAD6
sec_key_mgmt_s_PAD7		sec_key_mgmt_s_PAD7
sec_key_mgmt_s_PAD8		sec_key_mgmt_s_PAD8
sec_key_mgmt_s_PAD9		sec_key_mgmt_s_PAD9
sec_key_mgmt_s_PADa		sec_key_mgmt_s_PADa
sec_key_mgmt_s_PADb		sec_key_mgmt_s_PADb
sec_key_mgmt_s_PADc		sec_key_mgmt_s_PADc
sec_key_mgmt_s_PADd		sec_key_mgmt_s_PADd
sec_key_mgmt_s_PADe		sec_key_mgmt_s_PADe
sec_key_mgmt_s_PADf		sec_key_mgmt_s_PADf
sec_priv_s_server_unavailable	priv server unavailable
sec_priv_s_invalid_principal	invalid principal
sec_priv_s_not_member_any_group	not member of any group
sec_priv_s_no_mem		can't allocate memory
sec_priv_s_invalid_authn_svc	authentication service invalid
sec_priv_s_invalid_authz_svc	authorization service invalid
sec_priv_s_invalid_trust_path	trust path invalid
sec_priv_s_invalid_request	malformed request
sec_priv_s_PAD00		random kerberos error occurred.
sec_priv_s_bad_compat_mode	invalid compatibiliity mode 
sec_priv_s_bad_deleg_type       invalid delegation type
sec_priv_s_deleg_not_enabled    delegation not enabled
sec_priv_s_deleg_token_exp      delegation token has expired
sec_priv_s_corrupt_deleg_chain  delegation chain is corrupt
sec_priv_s_invalid_dlg_token    malformed delegation token
sec_priv_s_intercell_deleg_req  privilege service delegation requests cannot cross cell boundaries
sec_priv_s_PAD7		sec_priv_s_PAD7
sec_priv_s_PAD8		sec_priv_s_PAD8
sec_priv_s_PAD9		sec_priv_s_PAD9
sec_priv_s_PADa		sec_priv_s_PADa
sec_priv_s_PADb		sec_priv_s_PADb
sec_priv_s_PADc		sec_priv_s_PADc
sec_priv_s_PADd		sec_priv_s_PADd
sec_priv_s_PADe		sec_priv_s_PADe
sec_priv_s_PADf		sec_priv_s_PADf
sec_rgy_not_implemented		Operation not yet implemented
sec_rgy_bad_domain		Operation not supported on specified domain
sec_rgy_object_exists		Object already exists
sec_rgy_name_exists		Name already exists
sec_rgy_unix_id_changed		Unix id changed on an alias add
sec_rgy_is_an_alias		Query returned an alias and allow_aliases was not set
sec_rgy_no_more_entries		No more matching entries
sec_rgy_object_not_found	Registry object not found
sec_rgy_server_unavailable	Registry server unavailable
sec_rgy_not_member_group	User is not member of specified group
sec_rgy_not_member_org		User is not member of specified org
sec_rgy_not_member_group_org	User is not member of specified group and org
sec_rgy_incomplete_login_name	Incomplete login name specification
sec_rgy_passwd_invalid		Invalid password
sec_rgy_not_authorized		User is not authorized to update record
sec_rgy_read_only		Registry is read only - updates are not allowed
sec_rgy_bad_alias_owner		PGO alias entry has an invalid owner
sec_rgy_bad_data		Invalid data record
sec_rgy_cant_allocate_memory	Unable to allocate memory
sec_rgy_dir_not_found		Directory not found
sec_rgy_dir_not_empty		Directory not empty
sec_rgy_bad_name		Illegal PGO or directory name
sec_rgy_dir_could_not_create	Unable to create directory
sec_rgy_dir_move_illegal	Directory move not allowed
sec_rgy_quota_exhausted		Principal quota exhausted
sec_rgy_foreign_quota_exhausted	Foreign quota for realm exhausted
sec_rgy_no_more_unix_ids	Unix id space for domain has been exhausted
sec_rgy_uuid_bad_version	Uuid version invalid
sec_rgy_key_bad_version		key version number out of range
sec_rgy_key_version_in_use	key version number currently in use
sec_rgy_key_bad_type		key type not supported
sec_rgy_crypt_bad_type		(de)encryption	type not supported
sec_rgy_bad_scope		scope doesn't name existing directory or pgo
sec_rgy_object_not_in_scope	object found was not in scope
sec_rgy_cant_authenticate	Cant establish authentication to security server
sec_rgy_alias_not_allowed	Cant add alias for this name or principal (e.g. krbtgt)
sec_rgy_bad_chksum_type		Checksum type not supported
sec_rgy_bad_integrity		Data integrity error
sec_rgy_key_bad_size		Invalid size for key data
sec_rgy_mkey_cant_read_stored	Can't read stored master key
sec_rgy_mkey_bad_stored		Stored master key is bad
sec_rgy_mkey_bad		Supplied master key is bad
sec_rgy_bad_handle		bad security context handle
sec_rgy_s_pgo_is_required	PGO/account is required and can't be deleted
sec_rgy_host_context_not_avail  Login context of local host principal not available
sec_rgy_mkey_file_io_failed     Master_key file I/O operation failed
sec_rgy_tower_rebind_failed	No usable tower entries
sec_rgy_site_not_absolute	Registry site name must be absolute
sec_rgy_bad_nameservice_name    Invalid nameservice name
sec_rgy_log_entry_out_of_range  Invalid log entry module or operation
sec_rgy_era_pwd_mgmt_auth_type  pwd_mgmt_binding ERA binding auth type cannot be none
sec_rgy_passwd_too_short        Password is too short
sec_rgy_passwd_non_alpha        Passwords must contain at least one non-alphanumeric character
sec_rgy_passwd_spaces           Passwords must contain at least one non-blank character
sec_rgy_rep_pgmerr		replication program error
sec_rgy_rep_bad_db_version	bad database version
sec_rgy_rep_cannot_create_db	cannot create database
sec_rgy_rep_cannot_open_db	cannot open database
sec_rgy_rep_cannot_read_db	cannot read database
sec_rgy_rep_cannot_save_db	cannot save database
sec_rgy_rep_cannot_rename_db	cannot rename database
sec_rgy_rep_master_not_found	cannot find master
sec_rgy_rep_master		Replica is the master
sec_rgy_rep_not_master		Replica is not the master
sec_rgy_rep_not_from_master	not from master
sec_rgy_rep_bad_state		bad state
sec_rgy_rep_name_unavailable	name unavailable
sec_rgy_rep_bad_binding		bad binding
sec_rgy_rep_deleted		replica deleted
sec_rgy_rep_db_locked		database locked
sec_rgy_rep_clock_skew		clock skewed
sec_rgy_rep_update_seqno_high	slave must have missed/lost some update from master
sec_rgy_rep_update_seqno_low	slave received an old update from master
sec_rgy_rep_doppelganger	Another replica with the same name or id exists
sec_rgy_rep_babel		Cannot communicate with all slaves
sec_rgy_rep_not_on_replist	The server that greeted the master is not on the replica list
sec_rgy_rep_prop_complete	All non-zombie replicas have received the specified update
sec_rgy_rep_prop_busy		All non-zombie replicas are either busy or have received the specified update
sec_rgy_rep_prop_from_rep	Server will not accept propagations now because it is serving as initializer ('from_rep') to a new slave
sec_rgy_rep_bad_arg		bad argument
sec_rgy_rep_no_default_replica	no default replica
sec_rgy_rep_invalid_entry       invalid replica entry
sec_rgy_rep_init_ekey_invalid   initialization encryption key not valid
sec_rgy_rep_bad_sw_vers         bad software version
sec_rgy_rep_marked_for_init     replica already marked for initialization
sec_rgy_rep_bad_init_id         init_id from slave doesn't match master's init_id for the replica
sec_rgy_rep_already_inited      slave already initialized
sec_rgy_rep_bad_prop_type       bad propagation type after prop operation
sec_rgy_rep_master_bad_sw_vers  master is running a bad software version
sec_rgy_rep_slave_bad_sw_vers   slave is running a bad software version
sec_rgy_rep_master_dup		duplicate masters
sec_rgy_rep_must_init_slave	Slave wants init to re-sync with master
sec_rgy_rep_bad_master_seqno	Master sequence number is invalid
sec_rgy_rep_PADc		sec_rgy_rep_PADc
sec_rgy_rep_PADd		sec_rgy_rep_PADd
sec_rgy_rep_PADe		sec_rgy_rep_PADe
sec_rgy_rep_PADf		sec_rgy_rep_PADf
sec_id_e_name_too_long		Name is too long for current implementation
sec_id_e_bad_cell_uuid		Cell UUID is not a valid cell name
sec_id_e_foreign_cell_referral	Global name yields a principal in foreign cell, use referral
sec_id_e_no_at_hack		cannot obtain uuids of name in princ@cell form.
sec_id_e_PAD1		sec_id_e_PAD1
sec_id_e_PAD2		sec_id_e_PAD2
sec_id_e_PAD3		sec_id_e_PAD3
sec_id_e_PAD4		sec_id_e_PAD4
sec_id_e_PAD5		sec_id_e_PAD5
sec_id_e_PAD6		sec_id_e_PAD6
sec_id_e_PAD7		sec_id_e_PAD7
sec_id_e_PAD8		sec_id_e_PAD8
sec_id_e_PAD9		sec_id_e_PAD9
sec_id_e_PADa		sec_id_e_PADa
sec_id_e_PADb		sec_id_e_PADb
sec_id_e_PADc		sec_id_e_PADc
sec_id_e_PADd		sec_id_e_PADd
sec_id_e_PADe		sec_id_e_PADe
sec_id_e_PADf		sec_id_e_PADf
sec_login_s_not_implemented		Operation not yet implemented
sec_login_s_no_memory			No memory available
sec_login_s_auth_local			Operation not valid on local context
sec_login_s_handle_invalid		Context handle not valid
sec_login_s_context_invalid		Context has not been validated
sec_login_s_no_current_context		No currently established network identity for which context exists
sec_login_s_groupset_invalid		Groupset not valid
sec_login_s_info_not_avail		Information not available
sec_login_s_already_valid       	login context has already been validated
sec_login_s_default_use			illegal use of default sec login handle
sec_login_s_privileged			privileged operation invoked in unprivileged process
sec_login_s_not_certified		login context has not been certified
sec_login_s_config			host configuration info not available
sec_login_s_internal_error		internal error in sec_login
sec_login_s_no_override_info		no override information available
sec_login_s_acct_invalid                account not valid for login
sec_login_s_null_password		cannot log in with zero-length password
sec_login_s_unsupp_passwd_type		unsupported password type.
sec_login_s_no_identity			no identity supplied
sec_login_s_refresh_ident_bad   	identity to be refreshed is no longer valid
sec_login_s_override_failure            Unable to determine if override exists
sec_login_s_ovrd_ent_not_found          No matching override entry found.
sec_login_s_invalid_password		Invalid password.
sec_login_s_incomplete_ovrd_ent         Incomplete override entry, cannot proceed.
sec_login_s_invalid_deleg_type          Invalid delegation type selection.
sec_login_s_compound_delegate           Login context already specifies a delegation chain.
sec_login_s_invalid_compat_mode	        Invalid compatibility mode selection.
sec_login_s_deleg_not_enabled           Delegation has not been enabled.
sec_login_s_preauth_failed              Preauthentication failure.
sec_login_s_PADe		sec_login_s_PADe
sec_login_s_PADf		sec_login_s_PADf
sec_kdc_s_response_too_long             output buffer not big enough
sec_kdc_s_PAD0		sec_kdc_s_PAD0
sec_kdc_s_PAD1		sec_kdc_s_PAD1
sec_kdc_s_PAD2		sec_kdc_s_PAD2
sec_kdc_s_PAD3		sec_kdc_s_PAD3
sec_kdc_s_PAD4		sec_kdc_s_PAD4
sec_kdc_s_PAD5		sec_kdc_s_PAD5
sec_kdc_s_PAD6		sec_kdc_s_PAD6
sec_kdc_s_PAD7		sec_kdc_s_PAD7
sec_kdc_s_PAD8		sec_kdc_s_PAD8
sec_kdc_s_PAD9		sec_kdc_s_PAD9
sec_kdc_s_PADa		sec_kdc_s_PADa
sec_kdc_s_PADb		sec_kdc_s_PADb
sec_kdc_s_PADc		sec_kdc_s_PADc
sec_kdc_s_PADd		sec_kdc_s_PADd
sec_kdc_s_PADe		sec_kdc_s_PADe
sec_kdc_s_PADf		sec_kdc_s_PADf
sec_lrgy_s_max_lt_num_entries           max_entries must be at least as large as num_entries
sec_lrgy_s_not_found                    cannot find local registry
sec_lrgy_s_cannot_create                cannot create local registry
sec_lrgy_s_no_access                    cannot access local registry
sec_lrgy_s_internal_error               internal local registry error
sec_lrgy_s_no_matching_entry            no matching local registry account entry
sec_lrgy_s_no_matching_tgt              no matching local registry TGT entry
sec_lrgy_s_no_more_entries              no more entries available
sec_lrgy_s_PAD1		                sec_lrgy_s_PAD1
sec_lrgy_s_PAD2		                sec_lrgy_s_PAD2
sec_lrgy_s_PAD3		                sec_lrgy_s_PAD3
sec_lrgy_s_PAD4		                sec_lrgy_s_PAD4
sec_lrgy_s_PAD5		                sec_lrgy_s_PAD5
sec_lrgy_s_PAD6		                sec_lrgy_s_PAD6
sec_lrgy_s_PAD7		                sec_lrgy_s_PAD7
sec_lrgy_s_PAD8		                sec_lrgy_s_PAD8
sec_lrgy_s_PAD9		                sec_lrgy_s_PAD9
sec_lrgy_s_PADa		                sec_lrgy_s_PADa
sec_lrgy_s_PADb		                sec_lrgy_s_PADb
sec_lrgy_s_PADc		                sec_lrgy_s_PADc
sec_lrgy_s_PADd		                sec_lrgy_s_PADd
sec_lrgy_s_PADe		                sec_lrgy_s_PADe
sec_lrgy_s_PADf		                sec_lrgy_s_PADf
sec_cred_s_no_more_entries              no more entries available
sec_cred_s_invalid_auth_handle		invalid credential handle
sec_cred_s_invalid_pa_handle            invalid privilege attribute handle
sec_cred_s_invalid_cursor               invalid credential cursor
sec_cred_s_authz_cannot_comply      authz service cannot supply the requested credentials
sec_cred_s_PAD0				sec_cred_s_PAD0
sec_cred_s_PAD1				sec_cred_s_PAD1
sec_cred_s_PAD2				sec_cred_s_PAD2
sec_cred_s_PAD3				sec_cred_s_PAD3
sec_cred_s_PAD4				sec_cred_s_PAD4
sec_cred_s_PAD5				sec_cred_s_PAD5
sec_cred_s_PAD6				sec_cred_s_PAD6
sec_cred_s_PAD7				sec_cred_s_PAD7
sec_cred_s_PAD8				sec_cred_s_PAD8
sec_cred_s_PAD9				sec_cred_s_PAD9
sec_cred_s_PADa				sec_cred_s_PADa
sec_cred_s_PADb				sec_cred_s_PADb
sec_cred_s_PADc				sec_cred_s_PADc
sec_cred_s_PADd				sec_cred_s_PADd
sec_cred_s_PADe				sec_cred_s_PADe
sec_cred_s_PADf				sec_cred_s_PADf
sec_attr_sch_entry_not_found		schema entry not found
sec_attr_inst_not_found			attribute instance not found
sec_attr_not_all_avail			warning: some of the requested attributes do not exist on the object
sec_attr_set_member_missing		warning: one or more members of the attribute set do not exist on the object
sec_attr_rgy_obj_not_found		registry object not found
sec_attr_inst_exists			attribute instance already exists
sec_attr_unauthorized			unauthorized to perform this operation
sec_attr_svr_read_only			server is read only
sec_attr_svr_unavailable		server is unavailable
sec_attr_trig_svr_unavailable		trigger server is unavailable
sec_attr_name_exists			attribute name already exists
sec_attr_type_id_exists			attribute type id already exists
sec_attr_field_no_update		field not modifiable
sec_attr_bad_type			invalid or unsupported attribute type
sec_attr_bad_acl_mgr_set		invalid acl_mgr_set specified
sec_attr_bad_acl_mgr_type		invalid acl manager type
sec_attr_bad_bind_info			invalid binding information
sec_attr_bad_permset			invalid permission set
sec_attr_no_memory			unable to allocate memory
sec_attr_not_unique			attribute value is not unique
sec_attr_bad_name			invalid attribute name specified
sec_attr_bad_encoding_type		invalid encoding type specified
sec_attr_bad_scope			invalid scope specified
sec_attr_bad_comment			invalid comment text specified
sec_attr_bad_intercell_action		invalid intercell action specified
sec_attr_bad_trig_type			invalid trigger type specified
sec_attr_trig_bind_info_missing		trigger binding info must be specified
sec_attr_bad_uniq_query_accept		invalid combination of unique_flag=true, query trigger, and intercell_action=accept
sec_attr_bad_bind_svr_name		invalid server name specified in binding auth_info
sec_attr_bad_bind_prot_level		invalid protection level specified in binding auth_info
sec_attr_bad_bind_authn_svc		invalid authentication service specified in binding auth_info
sec_attr_bad_bind_authz_svc		invalid authorization service specified in binding auth_info
sec_attr_bad_cursor			invalid cursor
sec_attr_not_implemented		this operation not implemented
sec_attr_trig_query_not_sup		query trigger not supported for this operation
sec_attr_bad_object_type		operation not supported on this object type
sec_attr_not_multi_valued		this attribute type does not support multi-valued updates
sec_attr_val_printstring_bad		attribute value printstring has bad format
sec_attr_val_string_array_bad		attribute value string array has bad format
sec_attr_val_bytes_bad			attribute value bytes/confidential_bytes/i18n_data has bad format
sec_attr_val_attr_set_bad		attribute value attr_set has bad format
sec_attr_no_more_entries		no more entries (attribute instances or schema entries) found
sec_attr_bad_param			bad parameter for schema or attribute operation
sec_attr_PAD8				sec_attr_PAD8
sec_attr_PAD9				sec_attr_PAD9
sec_attr_PADa				sec_attr_PADa
sec_attr_PADb				sec_attr_PADb
sec_attr_PADc				sec_attr_PADc
sec_attr_PADd				sec_attr_PADd
sec_attr_PADe				sec_attr_PADe
sec_attr_PADf				sec_attr_PADf
sec_pwd_mgmt_str_check_failed           password failed password strength server checking policy
sec_pwd_mgmt_not_authorized             unauthorized to call password management server
sec_pwd_mgmt_svr_error                  password management server generic error
sec_pwd_mgmt_svr_unavail                password management server is unavailable
sec_authn_s_missing_epac			EPAC missing after authenticator
sec_authn_s_no_seal			can't find appropriate seal for EPAC
sec_authn_s_bad_seal			integrity error: EPAC seal mismatch.
sec_pwd_mgmt_proxy_req                  a proxy agent is required for secure transmission of data
sec_pwd_mgmt_s_PAD0                     sec_pwd_mgmt_s_PAD0
sec_pwd_mgmt_s_PAD1                     sec_pwd_mgmt_s_PAD1
sec_pwd_mgmt_s_PAD2                     sec_pwd_mgmt_s_PAD2
sec_pwd_mgmt_s_PAD3                     sec_pwd_mgmt_s_PAD3
sec_pwd_mgmt_s_PAD4                     sec_pwd_mgmt_s_PAD4
sec_pwd_mgmt_s_PAD5                     sec_pwd_mgmt_s_PAD5
sec_pwd_mgmt_s_PAD6                     sec_pwd_mgmt_s_PAD6
sec_pwd_mgmt_s_PAD7                     sec_pwd_mgmt_s_PAD7
sec_pwd_mgmt_s_PAD8                     sec_pwd_mgmt_s_PAD8
sec_pwd_mgmt_s_PAD9                     sec_pwd_mgmt_s_PAD9
sec_pwd_mgmt_s_PADa                     sec_pwd_mgmt_s_PADa
sec_pwd_mgmt_s_PADb                     sec_pwd_mgmt_s_PADb
sec_pwd_mgmt_s_PADc                     sec_pwd_mgmt_s_PADc
sec_pwd_mgmt_s_PADd                     sec_pwd_mgmt_s_PADd
sec_pwd_mgmt_s_PADe                     sec_pwd_mgmt_s_PADe
sec_pwd_mgmt_s_PADf                     sec_pwd_mgmt_s_PADf
