/*
 * @OSF_COPYRIGHT@
 * COPYRIGHT NOTICE
 * Copyright (c) 1996 Open Software Foundation, Inc.
 * ALL RIGHTS RESERVED (DCE).  See the file named COPYRIGHT.DCE for
 * the full copyright text.
 * 
 */
/*
 * HISTORY
 * $Log: sec_login_base.idl,v $
 * Revision 1.1.2.2  1996/03/09  20:45:34  marty
 * 	Add OSF copyright
 * 	[1996/03/09  20:25:02  marty]
 *
 * Revision 1.1.2.1  1995/12/08  17:37:49  root
 * 	Submit OSF/DCE 1.2.1
 * 
 * 	HP revision /main/HPDCE02/1  1995/04/03  22:07 UTC  mullan_s
 * 	Binary Compatibility Merge
 * 	[1995/12/08  16:56:09  root]
 * 
 * $EndLog$
 */
/*
 * Copyright (c) Hewlett-Packard Company 1995
 * Unpublished work. All Rights Reserved.
 *
 * sec_login_base.idl
 * Base (shared) sec_login data types and definitions
 */

interface sec_login_base {

    import "dce/rgynbase.idl";

    /* sec_login_tkt_flags_t
     *
     * These are options used to request various attributes
     * associated with tickets.
     */
    typedef unsigned32 sec_login_tkt_flags_t;
        /*
         * request renewable ticket
         */
        const unsigned32 sec_login_tkt_renewable        = 0x1;

        /*
         * request postdated ticket
         */
        const unsigned32 sec_login_tkt_postdated        = 0x2;

        /*
         * allow postdated tickets
         */
        const unsigned32 sec_login_tkt_allow_postdate   = 0x4;

        /*
         * allow proxiable tickets
         */
        const unsigned32 sec_login_tkt_proxiable        = 0x8;

        /*
         * request forwardable ticket
         */
        const unsigned32 sec_login_tkt_forwardable      = 0x10;

        /*
         * accept renewable ticket if real ticket cannot be granted
         */
        const unsigned32 sec_login_tkt_renewable_ok     = 0x20;

        /*
         * request non-default ticket lifetime
         */
        const unsigned32 sec_login_tkt_lifetime         = 0x40;


    /* sec_login_tkt_info_t
     *
     * The structure of optional AS ticket request flags
     * and associated data.
     */
    typedef struct {
        sec_login_tkt_flags_t    options;
        sec_timeval_period_t     postdated_dormanttime;
        sec_timeval_period_t     renewable_lifetime;
        sec_timeval_period_t     lifetime;
    } sec_login_tkt_info_t;

}
