/*
 * @OSF_COPYRIGHT@
 * COPYRIGHT NOTICE
 * Copyright (c) 1990, 1991, 1992, 1993, 1996 Open Software Foundation, Inc.
 * ALL RIGHTS RESERVED (DCE).  See the file named COPYRIGHT.DCE in the
 * src directory for the full copyright text.
 */
/*
 * HISTORY
 * $Log: sec_cert.idl,v $
 * Revision 1.1.4.2  1996/03/09  23:29:10  marty
 * 	Update OSF copyright year
 * 	[1996/03/09  22:44:34  marty]
 *
 * Revision 1.1.4.1  1995/12/08  17:37:25  root
 * 	Submit OSF/DCE 1.2.1
 * 	[1995/12/08  16:56:04  root]
 * 
 * Revision 1.1.2.2  1992/12/29  13:54:04  zeliff
 * 	Embedding copyright notice
 * 	[1992/12/28  20:22:14  zeliff]
 * 
 * Revision 1.1  1992/01/19  14:55:21  devrcs
 * 	Initial revision
 * 
 * $EndLog$
 */
/*
*/

/*  sec_cert.idl V=2 08/16/91 //littl/prgy/src/idl
**
** Copyright (c) Hewlett-Packard Company 1991
** Unpublished work. All Rights Reserved.
**
*/
/*  sec_cert.idl - sec_cert(ify) interface
** 
*/

[
    local
]

interface sec_cert { 

    import "dce/sec_login.idl";

    /*
     * sec_login_validate_cert_auth
     *      Validate Certification Authority, by making sure the client can
     *      make an authenticated call.  Presently, the fact that the caller
     *      was able to make the authenticated call is enough, but there is
     *      a status parameter in the signature so that future implementations
     *      may make additional checks if necessary.
     */
    void sec_login_validate_cert_auth (
        [in]        sec_login_handle_t          login_context,
        [out]       error_status_t              *status
    );
}

