/*
 * @OSF_COPYRIGHT@
 * COPYRIGHT NOTICE
 * Copyright (c) 1990, 1991, 1992, 1993, 1994, 1996 Open Software Foundation, Inc.
 * ALL RIGHTS RESERVED (DCE).  See the file named COPYRIGHT.DCE for
 * the full copyright text.
 */
/*
 * HISTORY
 * $Log: sec_rgy_login_activity.idl,v $
 * Revision 1.1.10.3  1996/03/09  23:29:23  marty
 * 	Update OSF copyright year
 * 	[1996/03/09  22:44:45  marty]
 *
 * Revision 1.1.10.2  1995/12/08  17:38:24  root
 * 	Submit OSF/DCE 1.2.1
 * 	[1995/12/08  16:56:16  root]
 * 
 * Revision 1.1.6.1  1994/10/26  20:00:42  hondo
 * 	changes for propagation of login activity
 * 	[1994/10/24  22:24:39  hondo]
 * 
 * Revision 1.1.2.3  1994/08/29  15:51:37  hondo
 * 	OT 11919 --login activity idl change to support different address types
 * 	[1994/08/28  21:49:34  hondo]
 * 
 * Revision 1.1.2.2  1994/08/10  19:21:56  annie
 * 	expand copyright with OSF copyright text
 * 	[1994/08/10  17:16:12  annie]
 * 
 * Revision 1.1.2.1  1994/07/15  15:00:25  mdf
 * 	Hewlett Packard Security Code Drop
 * 	[1994/07/14  17:59:58  mdf]
 * 
 * $EndLog$
 */
/*
** Copyright (c) Hewlett-Packard Company 1994
** Unpublished work. All Rights Reserved.
**
**
**
*/

[
    local
]

interface sec_rgy_login_act {

    import "dce/rgybase.idl";
    import "dce/rs_login_base.idl";



    /* s e c _ r g y _ l o g i n _ a c t i v i t y _ l o o k u p
     *
     *   retrieve login_activity data 
     *
     *	In Parameters:
     *			login_name -- principal name
     *			
     *	Out Parameters:
     *
     *			login_part -- login activity data for named principal
     *			status 
     *
     * Errors:
     *          Object not found
     */
     
    void sec_rgy_login_activity_lookup (
	[in]		sec_rgy_handle_t	        context,
	[in]		sec_rgy_login_name_t	        *login_name,
	[out,ref]	sec_rgy_login_activity_t	*login_part,
	[out]		error_status_t	        	*st_p
	);
     
    /* s e c _ r g y _ l o g i n _ a c t i v i t y _ u p d a t e
     *
     *   allows resetting of login_activity data ...of particular
     *   interest is resetting the disable_time to reset an account
     *   that has been locked out
     */
     
    void sec_rgy_login_activity_update (
	[in]		sec_rgy_handle_t	        context,
	[in]		sec_rgy_login_name_t	        *login_name,
	[in]		sec_rgy_login_activity_t	*login_part,
	[in]		uuid_t				*client,
	[out]		error_status_t	        	*st_p
	);
     
}
