# @OSF_COPYRIGHT@
# COPYRIGHT NOTICE
# Copyright (c) 1990, 1991, 1992, 1993, 1994, 1996 Open Software Foundation, Inc.
# ALL RIGHTS RESERVED (DCE).  See the file named COPYRIGHT.DCE for
# the full copyright text.
# 
# HISTORY
# $Log: Makefile,v $
# Revision 1.1.5.2  1996/03/11  01:37:15  marty
# 	Update copyright years
# 	[1996/03/10  19:40:02  marty]
#
# Revision 1.1.5.1  1995/12/11  16:54:47  root
# 	Submit
# 	[1995/12/11  16:39:18  root]
# 
# Revision 1.1.2.5  1994/07/20  14:06:35  marrek
# 	ILIST extended by config.* used in <dce_config> command
# 	[1994/07/20  12:14:11  marrek]
# 
# Revision 1.1.2.4  1994/07/06  15:12:10  marrek
# 	July 1994 code drop.
# 	[1994/07/06  12:03:43  marrek]
# 
# Revision 1.1.2.3  1994/06/10  20:24:04  devsrc
# 	cr10872 - fixed copyright
# 	[1994/06/10  17:00:37  devsrc]
# 
# Revision 1.1.2.2  1994/05/11  19:48:31  sally
# 	This fixes cf 10605 - vpath was wrong for install
# 	[1994/05/11  19:47:20  sally]
# 
# Revision 1.1.2.1  1994/05/10  14:37:58  marrek
# 	Fixes for April 1994 submission.
# 	[1994/05/06  11:25:52  marrek]
# 
# 	Created in April 1994 submission.
# 	[1994/05/03  12:17:18  marrek]
# 
# $EndLog$
#
# $RCSfile: Makefile,v $ $Revision: 1.1.5.2 $ $Date: 1996/03/11 01:37:15 $
#

IDIR    = /test/tet/functional/directory/xds/ts/config/
IMODE           = 755

VPATH		= ../../../gds/ts/config

ILIST           = 	t.cacheinit125.sed \
			t.3cacheinit1.sed \
			t.4cacheinit1.sed \
			dsa.chmaster \
			dsa.dsa1.sed \
			dsa.dsa2.sed \
			two_dsas.sed \
			config_gds-admin_cache.sed \
			config.cmd \
			config.env.sed

.include <${RULES_MK}>

