/*
 * @OSF_COPYRIGHT@
 * COPYRIGHT NOTICE
 * Copyright (c) 1990, 1991, 1992, 1993, 1994, 1996 Open Software Foundation, Inc.
 * ALL RIGHTS RESERVED (DCE).  See the file named COPYRIGHT.DCE for
 * the full copyright text.
 * 
 */
/*
 * HISTORY
 * $Log: dcdrel001a.idl,v $
 * Revision 1.1.4.2  1996/03/11  02:38:17  marty
 * 	Update OSF copyright years
 * 	[1996/03/10  20:05:18  marty]
 *
 * Revision 1.1.4.1  1995/12/11  21:55:25  root
 * 	Submit OSF/DCE 1.2.1
 * 	[1995/12/11  20:55:26  root]
 * 
 * Revision 1.1.2.1  1994/07/21  21:27:10  fadden
 * 	Initial version after renaming
 * 	[1994/07/21  20:37:38  fadden]
 * 
 * $EndLog$
 */
/* 
 * NAME
 * 
 *   dcdrel001a.idl  
 *
 * COMPONENT
 *   
 *   DCE dced system test
 *   
 * ABSTRACT
 *
 *   This module defines an interface for a set of server routines which
 *   are used in the DCDREL001 system test.
 *
 */

[
uuid(0056f9a1-f26a-1d91-8e95-0000c06ad04c),
version(1.0)
]

interface dcdrel001a 
{
    typedef 
        [string] char uuidst_a [37];

    /* define a structure containing a conformant array, which is 
     * compatible with uuid_vector_t
     */

    typedef struct 
    {
	unsigned32 count;
	[size_is(count)] uuid_p_t   uuid[];
    }  uuid_vec_a_t;   
    

/* ______________________________________________________________ */

    /* register_uuid_all_protseqs_a - registers an obj with specified uuid */
    [idempotent] void register_uuid_all_protseqs_a(
	[in]		handle_t	h,
	[in,string]	uuidst_a        ustring,
	[out]		error_status_t	*st
    );

    /* unregister_uuid_all_protseqs_a - unregisters an obj with specified uuid */
    [idempotent] void unregister_uuid_all_protseqs_a(
	[in]		handle_t	h,
	[in,string]	uuidst_a        ustring,
	[out]		error_status_t	*st
    );

    /* register_uuid_vec_all_protseqsa - request server to register with the
     * endpoint mapper a uuid vector (passed as a conformant array) 
     * with all current protseqs 
     */ 
    [idempotent] void register_uuid_vec_all_protseqsa(
	[in]		handle_t	h,
	[in]		uuid_vec_a_t    *obj_vec,
	[out]		error_status_t	*st
    );

    /* unregister_obj_all_protseqs_a  - get object uuid from this binding 
     *                  and unregister it
     */
    [idempotent] void unregister_obj_all_protseqs_a(
	[in]		handle_t	h,
	[out]		error_status_t	*st
    );

}
