# @OSF_COPYRIGHT@
# COPYRIGHT NOTICE
# Copyright (c) 1990, 1991, 1992, 1993, 1994, 1996 Open Software Foundation, Inc.
# ALL RIGHTS RESERVED (DCE).  See the file named COPYRIGHT.DCE for
# the full copyright text.
# 
# HISTORY
# $Log: Makefile,v $
# Revision 1.1.4.2  1996/03/11  01:57:19  marty
# 	Update OSF copyright years
# 	[1996/03/10  19:45:18  marty]
#
# Revision 1.1.4.1  1995/12/11  18:05:30  root
# 	Submit OSF/DCE 1.2.1
# 	[1995/12/11  17:48:50  root]
# 
# Revision 1.1.2.3  1994/07/06  15:12:54  marrek
# 	July 1994 code drop.
# 	[1994/07/06  12:04:40  marrek]
# 
# Revision 1.1.2.2  1994/06/10  20:34:27  devsrc
# 	cr10872 - fixed copyright
# 	[1994/06/10  17:05:50  devsrc]
# 
# Revision 1.1.2.1  1994/05/10  15:04:59  marrek
# 	Created in April 1994 submission.
# 	[1994/05/03  12:19:13  marrek]
# 
# $EndLog$
#
# $RCSfile: Makefile,v $ $Revision: 1.1.4.2 $ $Date: 1996/03/11 01:57:19 $
#

IDIR = /test/tet/functional/directory/xds/ts/xoms/lib/threads_af/

DATAFILES	=					\
			BODYextract1i			\
			BODYextract_attr1i		\
			BODYobj_to_str002i		\
			BODYstr_to_attr034i		\
			BODYstr_to_attr050i		\
			BODYstr_to_filter003i		\
			BODYstr_to_name004i		\
			BODYstr_to_name029i		\
			BODYstr_to_rdn011i		\
			SHUTDOWNextract1i		\
			SHUTDOWNextract_attr1i		\
			SHUTDOWNobj_to_str002i		\
			SHUTDOWNstr_to_attr034i		\
			SHUTDOWNstr_to_attr050i		\
			SHUTDOWNstr_to_filter003i	\
			SHUTDOWNstr_to_name004i		\
			SHUTDOWNstr_to_name029i		\
			SHUTDOWNstr_to_rdn011i		\
			STARTextract1i			\
			STARTextract_attr1i		\
			STARTobj_to_str002i		\
			STARTstr_to_attr034i		\
			STARTstr_to_attr050i		\
			STARTstr_to_filter003i		\
			STARTstr_to_name004i		\
			STARTstr_to_name029i		\
			STARTstr_to_rdn011i		\
			T10extract1i			\
			T10extract_attr1i		\
			T10obj_to_str002i		\
			T10str_to_attr034i		\
			T10str_to_attr050i		\
			T10str_to_filter003i		\
			T10str_to_name004i		\
			T10str_to_name029i		\
			T10str_to_rdn011i

ILIST		= ${DATAFILES}

.include <${RULES_MK}>
