/*
 * @OSF_COPYRIGHT@
 * COPYRIGHT NOTICE
 * Copyright (c) 1990, 1991, 1992, 1993, 1996 Open Software Foundation, Inc.
 * ALL RIGHTS RESERVED (DCE).  See the file named COPYRIGHT.DCE in the
 * src directory for the full copyright text.
 */
/*
 * HISTORY
 * $Log: outrefs.idl,v $
 * Revision 1.1.4.2  1996/03/11  02:16:10  marty
 * 	Update OSF copyright years
 * 	[1996/03/10  19:54:17  marty]
 *
 * Revision 1.1.4.1  1995/12/11  19:26:41  root
 * 	Submit OSF/DCE 1.2.1
 * 	[1995/12/11  19:14:25  root]
 * 
 * Revision 1.1.2.3  1993/01/13  21:49:34  bbelch
 * 	Embedding copyright notice
 * 	[1993/01/06  13:37:49  bbelch]
 * 
 * Revision 1.1  1992/01/19  03:25:57  devrcs
 * 	Initial revision
 * 
 * $EndLog$
 */
/*
*/
[uuid(58124100-3c3f-11c9-b22e-08002b13d56d), version(0)]
interface outrefs
{
    typedef struct r4p {
        [ref] char *r4p_1;
        [ref] char *r4p_2;
        [ref] char *r4p_3;
        [ref] char *r4p_4;
    } r4p;

    typedef struct r3p {
        [ref] r4p *r3p_1;
        [ref] r4p *r3p_2;
        [ref] r4p *r3p_3;
    } r3p;

    typedef struct r2p {
        [ref] r3p *r2p_1;
        [ref] r3p *r2p_2;
    } r2p;

    void op0 (
        [in] handle_t h,
        [out] r2p *r2param
    );

    typedef [ref] r4p *r4pp;

    void op1 (
        [in] handle_t h,
        [in,out] long *f,
        [in,out] long *l,
        [in,out,first_is(*f),last_is(*l)] r4pp a[10]
    );

    typedef [ref] unsigned short *rusp_t;
    
    typedef struct confrusp_t {
        short s;
        [size_is(s)] rusp_t rusps[];
    } confrusp_t;

    typedef [ref] confrusp_t *crp_t;

    void op2 (
        [in] handle_t h,
        [in,out] crp_t *p_crp
    );

    void op3 (
        [in] handle_t h,
        [in] long s,
        [out,size_is(s)] rusp_t rusps[]
    );

}
