/*
 * @OSF_COPYRIGHT@
 * COPYRIGHT NOTICE
 * Copyright (c) 1996 Open Software Foundation, Inc.
 * ALL RIGHTS RESERVED (DCE).  See the file named COPYRIGHT.DCE for
 * the full copyright text.
 * 
 */
/*
 * HISTORY
 * $Log: matrix.idl,v $
 * Revision 1.1.2.2  1996/03/09  20:49:34  marty
 * 	Add OSF copyright
 * 	[1996/03/09  20:27:55  marty]
 *
 * Revision 1.1.2.1  1995/12/11  19:35:18  root
 * 	Submit OSF/DCE 1.2.1
 * 	[1995/12/11  19:18:33  root]
 * 
 * $EndLog$
 */
[
    uuid(C664B260-A5DB-11CB-832C-08002B2A1BCA)
] interface Matrix
{
    /* Create a 2x2 matrix  */
    Matrix * new2x2(
	[in] double v11,
	[in] double v12,
	[in] double v21,
	[in] double v22
    );

    void invert(
	[out] Matrix **m
    );

    void add(
	[in, out] Matrix **m
    );

    /* Set a new value in the matrix */
    void set(
	[in] long row,
	[in] long col,
	[in] double value
	);

    /* Get a value from the matrix */
    double get(
	[in] long row,
	[in] long col
	);

    /* Get a count of Object Table entries */ 
    long getNumOTentries();

}
