# @OSF_COPYRIGHT@
# COPYRIGHT NOTICE
# Copyright (c) 1990, 1991, 1992, 1993, 1994, 1996 Open Software Foundation, Inc.
# ALL RIGHTS RESERVED (DCE).  See the file named COPYRIGHT.DCE for
# the full copyright text.
# 
# HISTORY
# $Log: Makefile,v $
# Revision 1.1.4.2  1996/03/11  02:00:41  marty
# 	Update copyright years
# 	[1996/03/10  19:54:08  marty]
#
# Revision 1.1.4.1  1995/12/11  17:26:35  root
# 	Submit OSF/DCE 1.2.1
# 	[1995/12/11  17:06:51  root]
# 
# Revision 1.1.2.3  1994/07/06  15:12:35  marrek
# 	July 1994 code drop.
# 	[1994/07/06  12:04:23  marrek]
# 
# Revision 1.1.2.2  1994/06/10  20:25:56  devsrc
# 	cr10872 - fixed copyright
# 	[1994/06/10  17:01:22  devsrc]
# 
# Revision 1.1.2.1  1994/05/10  14:52:40  marrek
# 	Created in April 1994 submission.
# 	[1994/05/03  12:18:45  marrek]
# 
# $EndLog$
#
# $RCSfile: Makefile,v $ $Revision: 1.1.4.2 $ $Date: 1996/03/11 02:00:41 $
#

IDIR = /test/tet/functional/directory/xds/ts/xds/lib/tree/

DATAFILES	=		\
		Testcases	\
		build_tree1	\
		build_tree10	\
		build_tree11	\
		build_tree2	\
		build_tree3	\
		build_tree4	\
		build_tree5	\
		build_tree6	\
		build_tree7	\
		build_tree8	\
		build_tree9	\
		delete_tree1	\
		delete_tree10	\
		delete_tree11	\
		delete_tree2	\
		delete_tree3	\
		delete_tree4	\
		delete_tree5	\
		delete_tree6	\
		delete_tree7	\
		delete_tree8	\
		delete_tree9	\
		zap_tree


ILIST		= ${DATAFILES}

.include <${RULES_MK}>
