/*
 * @OSF_COPYRIGHT@
 * COPYRIGHT NOTICE
 * Copyright (c) 1990, 1991, 1992, 1993, 1996 Open Software Foundation, Inc.
 * ALL RIGHTS RESERVED (DCE).  See the file named COPYRIGHT.DCE in the
 * src directory for the full copyright text.
 */
/*
 * HISTORY
 * $Log: es_attr_encode.idl,v $
 * Revision 1.1.4.2  1996/03/11  02:13:27  marty
 * 	Update OSF copyright years
 * 	[1996/03/10  19:53:07  marty]
 *
 * Revision 1.1.4.1  1995/12/11  20:05:06  root
 * 	Submit OSF/DCE 1.2.1
 * 	[1995/12/11  19:31:13  root]
 * 
 * Revision 1.1.2.1  1994/05/10  18:03:34  tom
 * 	Test for ecoding services get/set attribute.
 * 	[1994/05/10  16:02:53  tom]
 * 
 * $EndLog$
 */
/*
*/
[uuid(20aac780-5398-11c9-b996-08002b13d56d), version(0)]
interface es_attr_encode
{
    const long N = 5000;

    void in_array_op1([in] handle_t h, [in] long arr[N]);
}
