/*
 * @OSF_COPYRIGHT@
 * COPYRIGHT NOTICE
 * Copyright (c) 1990, 1991, 1992, 1993, 1996 Open Software Foundation, Inc.
 * ALL RIGHTS RESERVED (DCE).  See the file named COPYRIGHT.DCE in the
 * src directory for the full copyright text.
 */
/*
 * HISTORY
 * $Log: es_attr_decode.idl,v $
 * Revision 1.1.4.2  1996/03/11  02:13:22  marty
 * 	Update OSF copyright years
 * 	[1996/03/10  19:53:05  marty]
 *
 * Revision 1.1.4.1  1995/12/11  20:05:00  root
 * 	Submit OSF/DCE 1.2.1
 * 	[1995/12/11  19:31:07  root]
 * 
 * Revision 1.1.2.2  1994/05/11  22:03:49  tom
 * 	Make decode version 1 so it doesn't match encode.
 * 	[1994/05/11  22:02:37  tom]
 * 
 * Revision 1.1.2.1  1994/05/10  18:03:32  tom
 * 	Test for ecoding services get/set attribute.
 * 	[1994/05/10  16:02:51  tom]
 * 
 * $EndLog$
 */

[uuid(00032cbd-8282-1dce-a176-0000c044d04c), version(1)]
interface es_attr_decode
{
    const long N = 5000;
    void out_array_op1([in] handle_t h, [out] long arr[N]);
}
