/*
 * @OSF_COPYRIGHT@
 * COPYRIGHT NOTICE
 * Copyright (c) 1990, 1991, 1992, 1993, 1994, 1996 Open Software Foundation, Inc.
 * ALL RIGHTS RESERVED (DCE).  See the file named COPYRIGHT.DCE for
 * the full copyright text.
 */
/*
 * HISTORY
 * $Log: rpc_cds_3.idl,v $
 * Revision 1.1.43.2  1996/03/11  02:46:06  marty
 * 	Update OSF copyright years
 * 	[1996/03/10  20:08:12  marty]
 *
 * Revision 1.1.43.1  1995/12/11  22:43:11  root
 * 	Submit OSF/DCE 1.2.1
 * 
 * 	HP revision /main/HPDCE02/1  1995/08/10  16:05 UTC  bissen
 * 	fix for joe
 * 
 * 	HP revision /main/HPDCE02/1  1995/08/10  16:00 UTC  jss
 * 	Change uuid back to OSF 1.0.3 version for backward interop testing.
 * 	[1995/12/11  22:20:13  root]
 * 
 * Revision 1.1.99.99 1995/01/01  00:00:00  mcg
 * 	     Changed the interface UUID.  Now already built dce 1.0.x versions
 * 	     of the test can interoperate with the new dce 1.1 versions
 * 	     [1995/01/01  00:00:00  mcg]
 * 
 * Revision 1.1.38.2  1994/06/10  20:50:47  devsrc
 * 	cr10872 - fixed copyright
 * 	[1994/06/10  17:19:50  devsrc]
 * 
 * Revision 1.1.38.1  1993/12/22  20:51:27  mhickey
 * 	no_changes
 * 	[1993/12/22  20:50:40  mhickey]
 * 
 * 	Changed the interface UUID.  It was the same as the
 * 	UUID from rpc.sec.2, so the two could not be reliably
 * 	run on the same system.
 * 	[1993/12/15  17:51:10  mhickey]
 * 
 * Revision 1.1.2.2  1993/03/12  04:28:46  mhickey
 * 	Inital check in for the rpc.cds.3 system test.
 * 	[1993/01/29  20:35:54  mhickey]
 * 
 * 	Initial check submit for rpc.sec.2 system test.
 * 
 * 	Defect 5887.
 * 	[1992/12/03  15:44:15  mhickey]
 * 
 * 	Version 1.1 of the interface.  Added definitions for a struct
 * 	containing a conformant array of longs, and a function call
 * 	tstrpc_cnf_str().
 * 	[1992/10/10  03:08:22  mhickey]
 * 
 * 	Initial checkin for base for rpc.security.2
 * 	[1992/10/06  17:28:32  mhickey]
 * 
 * $EndLog$
 */

/*---*
 *---* rpc.sec.2.idl - IDL file for the rpc.sec.2 System test
 *---*
 *---* ASSOCIATION
 *---*    This file is part of the rpc.sec.2 DCE System Test
 *---*
 *---*    The rpc.sec.2 system test corresponds to test rpc.sec.2 in the 
 *---*    DCE1.0.2 Core Component System Test plan.  For more information on 
 *---*    the operation and goals of the rpc.sec.2 system test, see the test 
 *---*    plan, or the README file in this directory.
 *---* 
 *---* FUNCTION
 *---*    Declares the interface UUID, interface signature and data structures
 *---*    used by calls to the interface for system test rpc.sec.2.
 *---* 
 *---* CALLED BY
 *---*    Referenced during build of the client and server programs.
 *---* 
 *---* CALLS INTO 
 *---*    Nothing.
 *---*
 *---* PREREQUISITES
 *---*    None.
 *---*
 *---*/

/*---* Interface UUID (from uuidgen) *---*/

[
uuid(00868D82-3B6F-1ABF-A630-08002B14B387),
pointer_default(ptr),
version(1.0)
]

interface rpccds3
{

   /*---* 
    *---* string pointer typedef 
    *---*/
   typedef [ref, string] char *str_p;

   /*---* define the struct containing the conformant array *---*/
   typedef struct
           {
             [ref,string] char *cal_name;
             long int cal_nlines;
             [size_is(cal_nlines)] str_p cal_lines[];
           } calndr_data_t, *calndr_data_p_t;
             

   void rpccds3_nop(
     [in,out] error_status_t *fstat,
     [in,out] error_status_t *cstat);

   calndr_data_t *rpccds3_send_cal(
     [in,out] long           *stat,         /*---* function return    *---*/
     [in,out] error_status_t *fstat,        /*---* fault status       *---*/
     [in,out] error_status_t *cstat);       /*---* comm status        *---*/
}



