# @OSF_COPYRIGHT@
# COPYRIGHT NOTICE
# Copyright (c) 1990, 1991, 1992, 1993, 1994, 1996 Open Software Foundation, Inc.
# ALL RIGHTS RESERVED (DCE).  See the file named COPYRIGHT.DCE for
# the full copyright text.
# 
# HISTORY
# $Log: Makefile,v $
# Revision 1.1.4.2  1996/03/11  02:00:14  marty
# 	Update copyright years
# 	[1996/03/10  19:53:58  marty]
#
# Revision 1.1.4.1  1995/12/11  17:26:19  root
# 	Submit OSF/DCE 1.2.1
# 	[1995/12/11  17:06:35  root]
# 
# Revision 1.1.2.3  1994/07/06  15:12:35  marrek
# 	July 1994 code drop.
# 	[1994/07/06  12:04:21  marrek]
# 
# Revision 1.1.2.2  1994/06/10  20:25:55  devsrc
# 	cr10872 - fixed copyright
# 	[1994/06/10  17:01:21  devsrc]
# 
# Revision 1.1.2.1  1994/05/10  14:52:24  marrek
# 	Created in April 1994 submission.
# 	[1994/05/03  12:18:43  marrek]
# 
# $EndLog$
#
# $RCSfile: Makefile,v $ $Revision: 1.1.4.2 $ $Date: 1996/03/11 02:00:14 $
#

IDIR = /test/tet/functional/directory/xds/ts/xds/lib/threads_up/

DATAFILES	=		\
			BODYadd_entry32v \
			BODYread1up \
			BODYread1up_unbind \
			SHUTDOWNadd_entry32v \
			SHUTDOWNinit6 \
			SHUTDOWNread1up \
			STARTadd_entry32v \
			STARTread1up \
			T10add_entry32v \
			T11read1up \
			T19read1up \
			T20read1up

ILIST		= ${DATAFILES}

.include <${RULES_MK}>
