/*
 * @OSF_COPYRIGHT@
 * COPYRIGHT NOTICE
 * Copyright (c) 1990, 1991, 1992, 1993, 1994, 1996 Open Software Foundation, Inc.
 * ALL RIGHTS RESERVED (DCE).  See the file named COPYRIGHT.DCE for
 * the full copyright text.
 * 
 */
/*
 * HISTORY
 * $Log: acl_test_db.idl,v $
 * Revision 1.1.4.2  1996/03/11  01:43:19  marty
 * 	Update OSF copyright years
 * 	[1996/03/10  19:14:30  marty]
 *
 * Revision 1.1.4.1  1995/12/08  22:06:48  root
 * 	Submit OSF/DCE 1.2.1
 * 	[1995/12/08  21:42:40  root]
 * 
 * Revision 1.1.2.3  1994/06/10  20:18:27  devsrc
 * 	cr10872 - fixed copyright
 * 	[1994/06/10  16:57:44  devsrc]
 * 
 * Revision 1.1.2.2  1994/05/19  14:46:34  baum
 * 	Resync with DB & ACL API changes
 * 	[1994/05/19  14:46:07  baum]
 * 
 * Revision 1.1.2.1  1994/04/22  06:19:27  baum
 * 	Initial Checkin
 * 	[1994/04/22  06:18:47  baum]
 * 
 * $EndLog$
 */

[ uuid(649e3fc0-bc27-11cc-b26c-08000925634d),
version(1.0) ]

interface acl_test_db
{
    import "dce/database.idl";
    import "acl_test.idl";

    /* ______________________________________________________________ */

    void acl_test_data_convert(
	[in]		handle_t	h,
	[in,out]	acl_test_data_t	*data,
	[in,out]	error_status_t	*st
    );

    void uu_convert(
	[in]		handle_t	h,
	[in,out]	uuid_t		*u,
	[in,out]	error_status_t	*st
    );

}

