/*
 * @OSF_COPYRIGHT@
 * COPYRIGHT NOTICE
 * Copyright (c) 1990, 1991, 1992, 1993, 1994, 1996 Open Software Foundation, Inc.
 * ALL RIGHTS RESERVED (DCE).  See the file named COPYRIGHT.DCE for
 * the full copyright text.
 * 
 */
/*
 * HISTORY
 * $Log: acl_test.idl,v $
 * Revision 1.1.4.2  1996/03/11  01:43:14  marty
 * 	Update OSF copyright years
 * 	[1996/03/10  19:14:27  marty]
 *
 * Revision 1.1.4.1  1995/12/08  22:06:42  root
 * 	Submit OSF/DCE 1.2.1
 * 	[1995/12/08  21:42:37  root]
 * 
 * Revision 1.1.2.3  1994/06/10  20:18:25  devsrc
 * 	cr10872 - fixed copyright
 * 	[1994/06/10  16:57:42  devsrc]
 * 
 * Revision 1.1.2.2  1994/05/19  14:46:33  baum
 * 	Resync with DB & ACL API changes
 * 	[1994/05/19  14:46:06  baum]
 * 
 * Revision 1.1.2.1  1994/04/22  06:19:23  baum
 * 	Initial Checkin
 * 	[1994/04/22  06:18:46  baum]
 * 
 * $EndLog$
 */

[ uuid(649e3fc0-bc27-11cc-b26c-08000925634c),
version(1.0)
]

interface acl_test
{
    import "dce/database.idl";

    typedef struct acl_test_record_s_t 
    {
	[string,ptr] char	*st1;
	[string,ptr] char	*st2;
	[string,ptr] char	*st3;
	[string,ptr] char	*st4;
    } acl_test_record_t;

    typedef struct 
    {
	unsigned32	count;
	[ptr,size_is(count)]	acl_test_record_t	*entry;
    } acl_test_record_array_t;

    typedef struct acl_test_data_s_t 
    {
	dce_db_header_t	h;
	acl_test_record_t	ph;
    } acl_test_data_t;


    [idempotent] void acl_inq_client_creds_ok_fvt (
	[in]		handle_t	h,
	[in]		uuid_t		client_principal,
	[out]		error_status_t	*st
    );

    [idempotent] void acl_inq_client_permset_ok_fvt (
	[in]		handle_t	h,
	[out]		error_status_t	*st
    );

    [idempotent] void acl_is_client_authorized_ok_fvt (
	[in]		handle_t	h,
	[out]		error_status_t	*st
    );

    [idempotent] void acl_inq_client_p_and_g_ok_fvt (
	[in]		handle_t	h,
	[in]		uuid_t		client_principal,
	[in]		uuid_t		client_group,
	[out]		error_status_t	*st
    );

    [idempotent] void acl_inq_prmset_for_creds_ok_fvt (
	[in]		handle_t	h,
	[out]		error_status_t	*st
    );

}

