# 
# @OSF_COPYRIGHT@
# COPYRIGHT NOTICE
# Copyright (c) 1990, 1991, 1992, 1993, 1994, 1996 Open Software Foundation, Inc.
# ALL RIGHTS RESERVED (DCE).  See the file named COPYRIGHT.DCE for
# the full copyright text.
# 
# 
# HISTORY
# $Log: Makefile,v $
# Revision 1.1.4.2  1996/03/11  02:06:51  marty
# 	Update OSF copyright years
# 	[1996/03/10  19:50:28  marty]
#
# Revision 1.1.4.1  1995/12/11  19:52:14  root
# 	Submit OSF/DCE 1.2.1
# 	[1995/12/11  19:26:42  root]
# 
# 	Submit OSF/DCE 1.2.1
# 	[1995/12/11  18:18:08  root]
# 
# Revision 1.1.2.2  1994/10/06  20:31:27  agd
# 	expand copyright
# 	[1994/10/06  14:28:36  agd]
# 
# Revision 1.1.2.1  1994/08/04  16:15:15  mdf
# 	Initial checkin
# 	[1994/08/04  14:11:25  mdf]
# 
# $EndLog$
# 
SCRIPTS=update_tet_scen
.include <${RULES_MK}>
