#
# @OSF_COPYRIGHT@
# COPYRIGHT NOTICE
# Copyright (c) 1990, 1991, 1992, 1993, 1996 Open Software Foundation, Inc.
# ALL RIGHTS RESERVED (DCE).  See the file named COPYRIGHT.DCE in the
# src directory for the full copyright text.
#
# HISTORY
# $Log: Makefile,v $
# Revision 1.1.5.2  1996/03/11  02:37:21  marty
# 	Update OSF copyright years
# 	[1996/03/10  20:04:53  marty]
#
# Revision 1.1.5.1  1995/12/11  21:54:13  root
# 	Submit OSF/DCE 1.2.1
# 	[1995/12/11  20:54:49  root]
# 
# Revision 1.1.2.3  1993/02/05  15:17:02  cjd
# 	Embedded copyright notice
# 	[1993/02/05  14:36:01  cjd]
# 
# Revision 1.1.3.2  1993/02/04  21:44:33  cjd
# 	Embedded copyright notice
# 
# Revision 1.1.2.2  1992/12/26  21:39:06  pellis
# 	Initial version of test.
# 	[1992/12/26  21:34:43  pellis]
# 
# $EndLog$
#
SUBDIRS = tests

.include <${RULES_MK}>

