# @OSF_COPYRIGHT@
# COPYRIGHT NOTICE
# Copyright (c) 1990, 1991, 1992, 1993, 1994, 1996 Open Software Foundation, Inc.
# ALL RIGHTS RESERVED (DCE).  See the file named COPYRIGHT.DCE for
# the full copyright text.
# 
# HISTORY
# $Log: Makefile,v $
# Revision 1.1.4.2  1996/03/11  01:55:38  marty
# 	Update copyright years
# 	[1996/03/10  19:51:22  marty]
#
# Revision 1.1.4.1  1995/12/11  17:22:40  root
# 	Submit OSF/DCE 1.2.1
# 	[1995/12/11  17:04:07  root]
# 
# Revision 1.1.2.3  1994/07/06  15:12:32  marrek
# 	July 1994 code drop.
# 	[1994/07/06  12:04:17  marrek]
# 
# Revision 1.1.2.2  1994/06/10  20:25:31  devsrc
# 	cr10872 - fixed copyright
# 	[1994/06/10  17:01:18  devsrc]
# 
# Revision 1.1.2.1  1994/05/10  14:49:37  marrek
# 	Created in April 1994 submission.
# 	[1994/05/03  12:18:37  marrek]
# 
# $EndLog$
#
# $RCSfile: Makefile,v $ $Revision: 1.1.4.2 $ $Date: 1996/03/11 01:55:38 $
#

IDIR = /test/tet/functional/directory/xds/ts/xds/lib/threads_as/

DATAFILES	=		\
			BODYbu1 \
			BODYcompare12v \
			BODYcompare1b \
			BODYis1 \
			BODYis2 \
			BODYivbu1 \
			BODYivbu2 \
			BODYivbus1 \
			BODYivbus2 \
			BODYlist1b \
			BODYlist8v \
			BODYread17v \
			BODYread1b \
			BODYread25v \
			BODYread26v \
			BODYread28v \
			BODYsearch17v \
			BODYsearch1b \
			BODYshutdown1 \
			BODYshutdown2 \
			BODYversion1 \
			SHUTDOWNbu1_is2 \
			SHUTDOWNcompare12v \
			SHUTDOWNcompare1b \
			SHUTDOWNdummy \
			SHUTDOWNlist1b \
			SHUTDOWNlist8v \
			SHUTDOWNread17v \
			SHUTDOWNread1b \
			SHUTDOWNread25v \
			SHUTDOWNread26v \
			SHUTDOWNread28v \
			SHUTDOWNsearch17v \
			SHUTDOWNsearch1b \
			SHUTDOWNv1_is2 \
			STARTbu1_is2 \
			STARTcompare12v \
			STARTcompare1b \
			STARTdummy \
			STARTlist1b \
			STARTlist8v \
			STARTread17v \
			STARTread1b \
			STARTread25v \
			STARTread26v \
			STARTread28v \
			STARTsearch17v \
			STARTsearch1b \
			STARTshutdown1_2 \
			STARTv1_is2 \
			T10compare12v \
			T10compare1b \
			T10list1b \
			T10list8v \
			T10read17v \
			T10read1b \
			T10read25v \
			T10read26v \
			T10read28v \
			T10search17v \
			T10search1b \
			T2bu1_is2_as \
			T2is1_2_as \
			T2ivbu1_2_as \
			T2ivbus1_2_as \
			T2shutdown1_2_as \
			T2v1_is2_as

ILIST		= ${DATAFILES}

.include <${RULES_MK}>
