/*
 * @OSF_COPYRIGHT@
 * COPYRIGHT NOTICE
 * Copyright (c) 1990, 1991, 1992, 1993, 1996 Open Software Foundation, Inc.
 * ALL RIGHTS RESERVED (DCE).  See the file named COPYRIGHT.DCE in the
 * src directory for the full copyright text.
 */
/*
 * HISTORY
 * $Log: primes.idl,v $
 * Revision 1.1.4.2  1996/03/11  02:17:25  marty
 * 	Update OSF copyright years
 * 	[1996/03/10  19:54:56  marty]
 *
 * Revision 1.1.4.1  1995/12/11  19:28:22  root
 * 	Submit OSF/DCE 1.2.1
 * 	[1995/12/11  19:15:08  root]
 * 
 * Revision 1.1.2.2  1993/01/07  20:43:52  bbelch
 * 	Embedding copyright notice
 * 	[1993/01/06  13:40:59  bbelch]
 * 
 * Revision 1.1  1992/01/19  03:29:59  devrcs
 * 	Initial revision
 * 
 * $EndLog$
 */
/*
*/
[uuid(0a5b6900-2ba9-11c9-a1d2-08002b13d56d),
 version(0)]
interface primes
{


/*
 the first element of values[] will be used to
                           hold an input parameter 
*/
    [idempotent] void primes_gen
    (
        [in] handle_t h,
        [in, out] long *last,
        [in] long max,
        [out] error_status_t *st,
        [in, out, v1_array, last_is(*last), max_is(max)] long values[]
    );
}
