#
# @OSF_COPYRIGHT@
# COPYRIGHT NOTICE
# Copyright (c) 1990, 1991, 1992, 1993, 1996 Open Software Foundation, Inc.
# ALL RIGHTS RESERVED (DCE).  See the file named COPYRIGHT.DCE in the
# src directory for the full copyright text.
#
#
# HISTORY
# $Log: Makefile,v $
# Revision 1.1.4.2  1996/03/11  02:50:20  marty
# 	Update OSF copyright years
# 	[1996/03/10  20:10:55  marty]
#
# Revision 1.1.4.1  1995/12/11  23:05:12  root
# 	Submit OSF/DCE 1.2.1
# 	[1995/12/11  22:37:00  root]
# 
# Revision 1.1.2.4  1993/01/08  22:13:14  tom
# 	Added hand-tests document.
# 	[1993/01/08  17:00:46  tom]
# 
# Revision 1.1.2.3  1992/12/31  20:35:01  htf
# 	Embedded copyright notice
# 	[1992/12/31  20:28:18  htf]
# 
# Revision 1.1.2.2  1992/11/02  15:39:01  root
# 	Added 'control' to the SUBDIRS list for install pass
# 	[1992/10/28  20:42:01  root]
# 
# Revision 1.1  1992/01/19  14:38:11  devrcs
# 	Initial revision
# 
# $EndLog$
#
SUBDIRS = common service control
DATAFILES	= hand-tests

ILIST	= ${DATAFILES}

.include <${RULES_MK}>

