# @OSF_COPYRIGHT@
# COPYRIGHT NOTICE
# Copyright (c) 1990, 1991, 1992, 1993, 1994, 1996 Open Software Foundation, Inc.
# ALL RIGHTS RESERVED (DCE).  See the file named COPYRIGHT.DCE for
# the full copyright text.
# 
# HISTORY
# $Log: Makefile,v $
# Revision 1.1.4.2  1996/03/11  01:48:13  marty
# 	Update copyright years
# 	[1996/03/10  19:47:45  marty]
#
# Revision 1.1.4.1  1995/12/11  17:17:05  root
# 	Submit OSF/DCE 1.2.1
# 	[1995/12/11  17:01:22  root]
# 
# Revision 1.1.2.3  1994/07/06  15:12:29  marrek
# 	July 1994 code drop.
# 	[1994/07/06  12:04:11  marrek]
# 
# Revision 1.1.2.2  1994/06/10  20:25:27  devsrc
# 	cr10872 - fixed copyright
# 	[1994/06/10  17:01:15  devsrc]
# 
# Revision 1.1.2.1  1994/05/10  14:46:38  marrek
# 	Created in April 1994 submission.
# 	[1994/05/03  12:18:28  marrek]
# 
# $EndLog$
#
# $RCSfile: Makefile,v $ $Revision: 1.1.4.2 $ $Date: 1996/03/11 01:48:13 $
#

IDIR = /test/tet/functional/directory/xds/ts/xds/lib/basic/

DATAFILES	=		\
		Testcases	\
		abandon1b	\
		add_entry1b	\
		bind1b		\
		compare1b	\
		init1b		\
		list1b		\
		mod_entry1b	\
		mod_rdn1b	\
		read1b		\
		recv_res1b	\
		rem_entry1b	\
		search1b	\
		shutdown1b	\
		unbind1b	\
		version1b


ILIST		= ${DATAFILES}

.include <${RULES_MK}>
