/*
 * @OSF_COPYRIGHT@
 * COPYRIGHT NOTICE
 * Copyright (c) 1990, 1991, 1992, 1993, 1996 Open Software Foundation, Inc.
 * ALL RIGHTS RESERVED (DCE).  See the file named COPYRIGHT.DCE in the
 * src directory for the full copyright text.
 */
/*
 * HISTORY
 * $Log: xt_export.h,v $
 * Revision 1.1.12.2  1996/02/18  23:04:07  marty
 * 	Update OSF copyright years
 * 	[1996/02/18  22:22:52  marty]
 *
 * Revision 1.1.12.1  1995/12/08  22:13:24  root
 * 	Submit OSF/DCE 1.2.1
 * 	[1995/12/08  21:45:47  root]
 * 
 * Revision 1.1.10.2  1994/06/21  14:28:46  marrek
 * 	June 1994 code submission.
 * 	[1994/06/16  07:47:32  marrek]
 * 
 * Revision 1.1.10.1  1994/02/22  19:15:48  marrek
 * 	Code drop for dce1.1.
 * 	[1994/02/07  13:28:52  marrek]
 * 
 * Revision 1.1.8.1  1993/10/14  19:28:45  keutel
 * 	October 1993 code drop
 * 	[1993/10/14  19:27:05  keutel]
 * 
 * 	October 1993 code drop
 * 	[1993/10/11  12:54:19  keutel]
 * 
 * Revision 1.1.6.2  1993/08/12  12:21:13  marrek
 * 	July 1993 code drop.
 * 	[1993/08/03  12:26:07  marrek]
 * 
 * Revision 1.1.4.2  1993/01/05  20:34:14  htf
 * 	Embedding copyright notice
 * 	[1993/01/05  18:48:29  htf]
 * 
 * Revision 1.1.2.3  1992/07/01  03:27:43  melman
 * 	GDS drop of 6/16/92
 * 	[1992/06/30  23:07:37  melman]
 * 
 * Revision 1.1.2.2  1992/06/11  20:00:44  melman
 * 	 gds drop
 * 	[1992/06/11  19:23:24  melman]
 * 
 * $EndLog$
 */
#ifndef _XT_EXPORT_H
#define _XT_EXPORT_H

#if !defined(lint) && defined(GDS_RCS_ID)
static char xt_export_rcsid[] = "@(#)$RCSfile: xt_export.h,v $ $Revision: 1.1.12.2 $ $Date: 1996/02/18 23:04:07 $";
#endif

/***************************************************************
*                                                              *
*  COPYRIGHT (C) SIEMENS NIXDORF INFORMATIONSSYSTEME AG 1991   *
*                ALL RIGHTS RESERVED                           *
*                                                              *
***************************************************************/

/****************************************************************************/
/*                                                                          */
/*   Defines for OIDs used by the test-tool.                                */
/*                                                                          */
/****************************************************************************/

/* from:  xds.h */

OM_EXPORT (DS_SERVICE_PKG)
OM_EXPORT (DS_C_ABANDON_FAILED)
OM_EXPORT (DS_C_ACCESS_POINT)
OM_EXPORT (DS_C_ADDRESS)
OM_EXPORT (DS_C_ATTRIBUTE)
OM_EXPORT (DS_C_ATTRIBUTE_ERROR)
OM_EXPORT (DS_C_ATTRIBUTE_LIST)
OM_EXPORT (DS_C_ATTRIBUTE_PROBLEM)
OM_EXPORT (DS_C_AVA)
OM_EXPORT (DS_C_COMMON_RESULTS)
OM_EXPORT (DS_C_COMMUNICATIONS_ERROR)
OM_EXPORT (DS_C_COMPARE_RESULT)
OM_EXPORT (DS_C_CONTEXT)
OM_EXPORT (DS_C_CONTINUATION_REF)
OM_EXPORT (DS_C_DS_DN)
OM_EXPORT (DS_C_DS_RDN)
OM_EXPORT (DS_C_ENTRY_INFO)
OM_EXPORT (DS_C_ENTRY_INFO_SELECTION)
OM_EXPORT (DS_C_ENTRY_MOD)
OM_EXPORT (DS_C_ENTRY_MOD_LIST)
OM_EXPORT (DS_C_ERROR)
OM_EXPORT (DS_C_EXT)
OM_EXPORT (DS_C_FILTER)
OM_EXPORT (DS_C_FILTER_ITEM)
OM_EXPORT (DS_C_LIBRARY_ERROR)
OM_EXPORT (DS_C_LIST_INFO)
OM_EXPORT (DS_C_LIST_INFO_ITEM)
OM_EXPORT (DS_C_LIST_RESULT)
OM_EXPORT (DS_C_NAME)
OM_EXPORT (DS_C_NAME_ERROR)
OM_EXPORT (DS_C_OPERATION_PROGRESS)
OM_EXPORT (DS_C_PARTIAL_OUTCOME_QUAL)
OM_EXPORT (DS_C_PRESENTATION_ADDRESS)
OM_EXPORT (DS_C_READ_RESULT)
OM_EXPORT (DS_C_REFERRAL)
OM_EXPORT (DS_C_RELATIVE_NAME)
OM_EXPORT (DS_C_SEARCH_INFO)
OM_EXPORT (DS_C_SEARCH_RESULT)
OM_EXPORT (DS_C_SECURITY_ERROR)
OM_EXPORT (DS_C_SERVICE_ERROR)
OM_EXPORT (DS_C_SESSION)
OM_EXPORT (DS_C_SYSTEM_ERROR)
OM_EXPORT (DS_C_UPDATE_ERROR)


/* from:  xdsbdcp.h */

OM_EXPORT (DS_BASIC_DIR_CONTENTS_PKG)
OM_EXPORT (DS_C_SEARCH_GUIDE)
OM_EXPORT (DS_C_POSTAL_ADDRESS)
OM_EXPORT (DS_C_TELEX_NBR)
OM_EXPORT (DS_C_TELETEX_TERM_IDENT)
OM_EXPORT (DS_C_FACSIMILE_PHONE_NBR)
OM_EXPORT (DS_C_SEARCH_CRITERION)
OM_EXPORT (DS_A_ALIASED_OBJECT_NAME)
OM_EXPORT (DS_A_BUSINESS_CATEGORY)
OM_EXPORT (DS_A_COMMON_NAME)
OM_EXPORT (DS_A_COUNTRY_NAME)
OM_EXPORT (DS_A_DESCRIPTION)
OM_EXPORT (DS_A_DEST_INDICATOR)
OM_EXPORT (DS_A_FACSIMILE_PHONE_NBR)
OM_EXPORT (DS_A_INTERNAT_ISDN_NBR)
OM_EXPORT (DS_A_KNOWLEDGE_INFO)
OM_EXPORT (DS_A_LOCALITY_NAME)
OM_EXPORT (DS_A_MEMBER)
OM_EXPORT (DS_A_OBJECT_CLASS)
OM_EXPORT (DS_A_ORG_NAME)
OM_EXPORT (DS_A_ORG_UNIT_NAME)
OM_EXPORT (DS_A_OWNER)
OM_EXPORT (DS_A_PHYS_DELIV_OFF_NAME)
OM_EXPORT (DS_A_POST_OFFICE_BOX)
OM_EXPORT (DS_A_POSTAL_ADDRESS)
OM_EXPORT (DS_A_POSTAL_CODE)
OM_EXPORT (DS_A_PREF_DELIV_METHOD)
OM_EXPORT (DS_A_PRESENTATION_ADDRESS)
OM_EXPORT (DS_A_REGISTERED_ADDRESS)
OM_EXPORT (DS_A_ROLE_OCCUPANT)
OM_EXPORT (DS_A_SEARCH_GUIDE)
OM_EXPORT (DS_A_SEE_ALSO)
OM_EXPORT (DS_A_SERIAL_NBR)
OM_EXPORT (DS_A_STATE_OR_PROV_NAME)
OM_EXPORT (DS_A_STREET_ADDRESS)
OM_EXPORT (DS_A_SUPPORT_APPLIC_CONTEXT)
OM_EXPORT (DS_A_SURNAME)
OM_EXPORT (DS_A_PHONE_NBR)
OM_EXPORT (DS_A_TELETEX_TERM_IDENT)
OM_EXPORT (DS_A_TELEX_NBR)
OM_EXPORT (DS_A_TITLE)
OM_EXPORT (DS_A_USER_PASSWORD)
OM_EXPORT (DS_A_X121_ADDRESS)
OM_EXPORT (DS_O_ALIAS)
OM_EXPORT (DS_O_APPLIC_ENTITY)
OM_EXPORT (DS_O_APPLIC_PROCESS)
OM_EXPORT (DS_O_COUNTRY)
OM_EXPORT (DS_O_DEVICE)
OM_EXPORT (DS_O_DSA)
OM_EXPORT (DS_O_GROUP_OF_NAMES)
OM_EXPORT (DS_O_LOCALITY)
OM_EXPORT (DS_O_ORG)
OM_EXPORT (DS_O_ORG_PERSON)
OM_EXPORT (DS_O_ORG_ROLE)
OM_EXPORT (DS_O_ORG_UNIT)
OM_EXPORT (DS_O_PERSON)
OM_EXPORT (DS_O_RESIDENTIAL_PERSON)
OM_EXPORT (DS_O_TOP)


/* from:  xdsgds.h */

OM_EXPORT (DSX_GDS_PKG)
OM_EXPORT (DSX_O_SCHEMA)
OM_EXPORT (DSX_A_MASTER_KNOWLEDGE)
OM_EXPORT (DSX_A_ACL)
OM_EXPORT (DSX_A_TIME_STAMP)
OM_EXPORT (DSX_A_SHADOWED_BY)
OM_EXPORT (DSX_A_SRT)
OM_EXPORT (DSX_A_OCT)
OM_EXPORT (DSX_A_AT)
OM_EXPORT (DSX_A_DEFAULT_DSA)
OM_EXPORT (DSX_A_LOCAL_DSA)
OM_EXPORT (DSX_A_CLIENT)
OM_EXPORT (DSX_A_DNLIST)
OM_EXPORT (DSX_A_SHADOWING_JOB)
OM_EXPORT (DSX_C_GDS_SESSION)
OM_EXPORT (DSX_C_GDS_CONTEXT)
OM_EXPORT (DSX_C_GDS_ACL)
OM_EXPORT (DSX_C_GDS_ACL_ITEM)


/* from:  xdscds.h */

OM_EXPORT (DSX_A_CDS_CTS)
OM_EXPORT (DSX_A_CDS_UTS)
OM_EXPORT (DSX_A_CDS_Class)
OM_EXPORT (DSX_A_CDS_ClassVersion)
OM_EXPORT (DSX_A_CDS_ObjectUUID)
OM_EXPORT (DSX_A_CDS_Address)
OM_EXPORT (DSX_A_CDS_Replicas)
OM_EXPORT (DSX_A_CDS_AllUpTo)
OM_EXPORT (DSX_A_CDS_Convergence)
OM_EXPORT (DSX_A_CDS_InCHName)
OM_EXPORT (DSX_A_CDS_ParentPointer)
OM_EXPORT (DSX_A_CDS_DirectoryVersion)
OM_EXPORT (DSX_A_CDS_UpgradeTo)
OM_EXPORT (DSX_A_CDS_LinkTarget)
OM_EXPORT (DSX_A_CDS_LinkTimeout)
OM_EXPORT (DSX_A_CDS_Towers)
OM_EXPORT (DSX_UUID)
OM_EXPORT (DSX_TYPELESS_RDN)
OM_EXPORT (DSX_NORMAL_SIMPLE_NAME)
OM_EXPORT (DSX_BINARY_SIMPLE_NAME)

/* from:  xom.h */

OM_EXPORT (OM_C_ENCODING)
OM_EXPORT (OM_C_EXTERNAL)


/* from:  xdsmdup.h */

OM_EXPORT (DS_C_DL_SUBMIT_PERMS)
OM_EXPORT (DS_A_DELIV_CONTENT_LENGTH)
OM_EXPORT (DS_A_DELIV_CONTENT_TYPES)
OM_EXPORT (DS_A_DELIV_EITS)
OM_EXPORT (DS_A_DL_MEMBERS)
OM_EXPORT (DS_A_DL_SUBMIT_PERMS)
OM_EXPORT (DS_A_MESSAGE_STORE)
OM_EXPORT (DS_A_OR_ADDRESSES)
OM_EXPORT (DS_A_PREF_DELIV_METHODS)
OM_EXPORT (DS_A_SUPP_AUTO_ACTIONS)
OM_EXPORT (DS_A_SUPP_CONTENT_TYPES)
OM_EXPORT (DS_A_SUPP_OPT_ATTRIBUTES)
OM_EXPORT (DS_O_MHS_DISTRIBUTION_LIST)
OM_EXPORT (DS_O_MHS_MESSAGE_STORE)
OM_EXPORT (DS_O_MHS_MESSAGE_TRANS_AG)
OM_EXPORT (DS_O_MHS_USER)
OM_EXPORT (DS_O_MHS_USER_AG)


/* from:  xmhp.h */

OM_EXPORT (MH_C_OR_ADDRESS)
OM_EXPORT (MH_C_OR_NAME)
OM_EXPORT (MH_CTO_INNER_MESSAGE)
OM_EXPORT (MH_CTO_UNIDENTIFIED)
OM_EXPORT (MH_EE_G3_FAX)
OM_EXPORT (MH_EE_G4_CLASS_1)
OM_EXPORT (MH_EE_IA5_TEXT)
OM_EXPORT (MH_EE_MIXED_MODE)
OM_EXPORT (MH_EE_TELETEX)
OM_EXPORT (MH_EE_TELEX)
OM_EXPORT (MH_EE_UNDEFINED)
OM_EXPORT (MH_EE_VIDEOTEX)
OM_EXPORT (MH_RA_BASIC_RENDITION)


/* from:  xmsga.h */

OM_EXPORT (MS_A_CHILD_SEQUENCE_NUMBERS)
OM_EXPORT (MS_A_CONTENT)
OM_EXPORT (MS_A_CONTENT_CONFIDENTL_ALGM_ID)
OM_EXPORT (MS_A_CONTENT_CORRELATOR)
OM_EXPORT (MS_A_CONTENT_IDENTIFIER)
OM_EXPORT (MS_A_CONTENT_INTEGRITY_CHECK)
OM_EXPORT (MS_A_CONTENT_LENGTH)
OM_EXPORT (MS_A_CONTENT_RETURNED)
OM_EXPORT (MS_A_CONTENT_TYPE)
OM_EXPORT (MS_A_CONVERSION_LOSS_PROHIBITED)
OM_EXPORT (MS_A_CONVERTED_EITS)
OM_EXPORT (MS_A_CREATION_TIME)
OM_EXPORT (MS_A_DELIVERED_EITS)
OM_EXPORT (MS_A_DELIVERY_FLAGS)
OM_EXPORT (MS_A_DL_EXPANSION_HISTORY)
OM_EXPORT (MS_A_ENTRY_STATUS)
OM_EXPORT (MS_A_ENTRY_TYPE)
OM_EXPORT (MS_A_INTENDED_RECIPIENT_NAME)
OM_EXPORT (MS_A_MESSAGE_DELIVERY_ENVELOPE)
OM_EXPORT (MS_A_MESSAGE_DELIVERY_ID)
OM_EXPORT (MS_A_MESSAGE_DELIVERY_TIME)
OM_EXPORT (MS_A_MESSAGE_ORIGIN_AUTHEN_CHK)
OM_EXPORT (MS_A_MESSAGE_SECURITY_LABEL)
OM_EXPORT (MS_A_MESSAGE_SUBMISSION_TIME)
OM_EXPORT (MS_A_MESSAGE_TOKEN)
OM_EXPORT (MS_A_ORIGINAL_EITS)
OM_EXPORT (MS_A_ORIGINATOR_CERTIFICATE)
OM_EXPORT (MS_A_ORIGINATOR_NAME)
OM_EXPORT (MS_A_OTHER_RECIPIENT_NAMES)
OM_EXPORT (MS_A_PARENT_SEQUENCE_NUMBER)
OM_EXPORT (MS_A_PERRECIP_REPORT_DELIV_FLDS)
OM_EXPORT (MS_A_PRIORITY)
OM_EXPORT (MS_A_PROOF_OF_DELIVERY_REQUEST)
OM_EXPORT (MS_A_REDIRECTION_HISTORY)
OM_EXPORT (MS_A_REPORT_DELIVERY_ENVELOPE)
OM_EXPORT (MS_A_REPORT_ORIGIN_AUTHEN_CHK)
OM_EXPORT (MS_A_REPORTING_DL_NAME)
OM_EXPORT (MS_A_REPORTING_MTA_CERTIFICATE)
OM_EXPORT (MS_A_SECURITY_CLASSIFICATION)
OM_EXPORT (MS_A_SEQUENCE_NUMBER)
OM_EXPORT (MS_A_SUBJECT_SUBMISSION_ID)
OM_EXPORT (MS_A_THIS_RECIPIENT_NAME)

/* from xdsdme.h */

OM_EXPORT (DSX_O_DME_NMO_AGENT)
OM_EXPORT (DSX_A_ALTERNATE_ADDRESS)

/* from xdssap.h */

OM_EXPORT (DS_A_AUTHORITY_REVOC_LIST)
OM_EXPORT (DS_A_CA_CERT)
OM_EXPORT (DS_A_CERT_REVOC_LIST)
OM_EXPORT (DS_A_CROSS_CERT_PAIR)
OM_EXPORT (DS_A_USER_CERT)
OM_EXPORT (DS_O_CERT_AUTHORITY)
OM_EXPORT (DS_O_STRONG_AUTHENT_USER)
OM_EXPORT (DS_C_ALGORITHM_IDENT)
OM_EXPORT (DS_C_CERT)
OM_EXPORT (DS_C_CERT_LIST)
OM_EXPORT (DS_C_CERT_PAIR)
OM_EXPORT (DS_C_CERT_SUBLIST)
OM_EXPORT (DS_C_SIGNATURE)

#endif /* _XT_EXPORT_H */
