/*
 * @OSF_COPYRIGHT@
 * COPYRIGHT NOTICE
 * Copyright (c) 1990, 1991, 1992, 1993, 1994 Open Software Foundation, Inc.
 * ALL RIGHTS RESERVED (DCE).  See the file named COPYRIGHT.DCE for
 * the full copyright text.
 */
/*
 * HISTORY
 * $Log: authtest.idl,v $
 * Revision 1.1.9.1  1996/10/02  20:58:36  damon
 * 	Newest DFS from Transarc
 * 	[1996/10/01  18:47:10  damon]
 *
 * Revision 1.1.4.1  1994/06/09  14:19:13  annie
 * 	fixed copyright in src/file
 * 	[1994/06/09  13:31:12  annie]
 * 
 * Revision 1.1.2.2  1993/01/21  15:18:38  cjd
 * 	embedded copyright notice
 * 	[1993/01/20  15:56:10  cjd]
 * 
 * Revision 1.1  1992/01/19  02:51:57  devrcs
 * 	Initial revision
 * 
 * $EndLog$
 */
/*
*/
/*
 * authtest.idl -- simple interface for testing auth rpc
 *
 *	Copyright (C) 1991 Transarc Corporation
 *	All rights reserved.
 */

[
 uuid(5cf70b66-1771-11ca-a1d4-02608c2ebaac),
 version(0),
 pointer_default(ref)
]
interface AUTH
{
  long int AUTH_ServerPlaceHolder (
				   [in] handle_t		authtestBinding,
				   [out] error_status_t *	theCommStatus
				  );
  long int AUTH_ServerKill (
			    [in] handle_t		authtestBinding,
			    [out] error_status_t *	theCommStatus
			   );
  long int AUTH_ServerSetDebug (
				[in] handle_t		authtestBinding,
				[in] long int		newValue,
				[out] long int *	oldValueP,
				[out] error_status_t *	theCommStatus
				);
  long int AUTH_ServerGetDebug (
				[in] handle_t		authtestBinding,
				[out] long int *	currentValueP,
				[out] error_status_t *	theCommStatus
				);
}
