/*
 * @OSF_COPYRIGHT@
 * COPYRIGHT NOTICE
 * Copyright (c) 1990, 1991, 1992, 1993, 1994, 1996 Open Software Foundation, Inc.
 * ALL RIGHTS RESERVED (DCE).  See the file named COPYRIGHT.DCE for
 * the full copyright text.
 * 
 */
/*
 * HISTORY
 * $Log: dced_aclbits.idl,v $
 * Revision 1.1.4.2  1996/03/09  23:06:54  marty
 * 	Update OSF copyright year
 * 	[1996/03/09  22:25:42  marty]
 *
 * Revision 1.1.4.1  1995/12/08  21:27:18  root
 * 	Submit OSF/DCE 1.2.1
 * 	[1995/12/08  17:59:32  root]
 * 
 * Revision 1.1.2.4  1994/09/12  17:48:18  rsalz
 * 	Add insert_priv ACL bit (part of OT CR 12032).
 * 	[1994/09/09  18:43:19  rsalz]
 * 
 * Revision 1.1.2.3  1994/06/09  16:03:02  devsrc
 * 	cr10892 - fix copyright
 * 	[1994/06/09  15:48:40  devsrc]
 * 
 * Revision 1.1.2.2  1994/04/06  15:12:09  bowe
 * 	Fix ACL bits for srvrexec
 * 	[1994/04/06  15:09:43  bowe]
 * 
 * Revision 1.1.2.1  1994/03/18  19:57:19  rsalz
 * 	Put permset bits in dced_aclbits.idl (OT CR 9768)
 * 	[1994/03/18  19:55:39  rsalz]
 * 
 * $EndLog$
 */


/*
**  D C E D _ A C L B I T S
**  Definitions for the ACL permission bits as used by dced.
*/
interface dced_aclbits
{
	/* For sec_acl_perm_XXX values: */
    import "dce/aclbase.idl";

    const unsigned32 dced_perm_read	= sec_acl_perm_read;
    const unsigned32 dced_perm_write	= sec_acl_perm_write;
    const unsigned32 dced_perm_execute	= sec_acl_perm_execute;
    const unsigned32 dced_perm_control	= sec_acl_perm_control;
    const unsigned32 dced_perm_insert	= sec_acl_perm_insert;
    const unsigned32 dced_perm_delete	= sec_acl_perm_delete;
    const unsigned32 dced_perm_test	= sec_acl_perm_test;
    const unsigned32 dced_perm_append	= sec_acl_perm_unused_00000080;
    const unsigned32 dced_perm_expunge	= sec_acl_perm_unused_00000100;
    const unsigned32 dced_perm_flag	= sec_acl_perm_unused_00000200;
    const unsigned32 dced_perm_purge	= sec_acl_perm_unused_00000400;
    const unsigned32 dced_perm_stop	= sec_acl_perm_unused_00000800;
    const unsigned32 dced_perm_update	= sec_acl_perm_unused_00001000;
    const unsigned32 dced_perm_insertpriv=sec_acl_perm_unused_00002000;

    const unsigned32 dced_hd_all_perms	=
	    ( dced_perm_control | dced_perm_delete | dced_perm_purge
	    | dced_perm_read | dced_perm_write );
    const unsigned32 dced_km_all_perms	=
	    ( dced_perm_append | dced_perm_control | dced_perm_delete
	    | dced_perm_expunge | dced_perm_purge | dced_perm_read );
    const unsigned32 dced_sc_all_perms	=
	    ( dced_perm_control | dced_perm_delete | dced_perm_flag
	    | dced_perm_read | dced_perm_write | dced_perm_execute );
    const unsigned32 dced_sv_all_perms	=
	    ( dced_perm_control | dced_perm_stop | dced_perm_update
	    | dced_perm_execute );
    const unsigned32 dced_sx_all_perms	=
	    ( dced_perm_control | dced_perm_read | dced_perm_write
	    | dced_perm_stop );
    const unsigned32 dced_as_all_perms	=
	    ( dced_perm_control | dced_perm_read | dced_perm_write
	    | dced_perm_delete );
    const unsigned32 dced_cont_all_perms=
	    ( dced_perm_control | dced_perm_read | dced_perm_insert
	    | dced_perm_insertpriv );
}
