/*
 * @OSF_COPYRIGHT@
 * COPYRIGHT NOTICE
 * Copyright (c) 1996 Open Software Foundation, Inc.
 * ALL RIGHTS RESERVED (DCE).  See the file named COPYRIGHT.DCE for
 * the full copyright text.
 * 
 */
/*
 * HISTORY
 * $Log: rutc.idl,v $
 * Revision 1.1.2.2  1996/03/09  20:43:53  marty
 * 	Add OSF copyright
 * 	[1996/03/09  20:23:51  marty]
 *
 * Revision 1.1.2.1  1995/12/08  21:27:39  root
 * 	Submit OSF/DCE 1.2.1
 * 
 * 	HP revision /main/HPDCE02/2  1994/12/07  16:51 UTC  mk
 * 	Merge in changes from mk_mothra_dced/2.
 * 
 * 	HP revision /main/mk_mothra_dced/2  1994/12/07  16:49 UTC  mk
 * 	Add history and log keywords.
 * 	[1995/12/08  17:59:46  root]
 * 
 * $EndLog$
 */

/*
**  Copyright (c) 1994 by
**	Hewlett-Packard Company, Palo Alto, Ca.
*/

/*
**  Operations for the Remote UTC (RUTC) interface.
*/
[
    uuid(af63cdce-fd9c-11cd-b0b4-080009357989),
    version(0)
]
interface rutc
{
    import "dce/utctypes.idl";

    [idempotent]
    long int
    rutc_gettime(
        [in]    handle_t                h,
	[out]	utc_t			*utc
    );
}
