#
# @OSF_COPYRIGHT@
# COPYRIGHT NOTICE
# Copyright (c) 1990, 1991, 1992, 1993, 1996 Open Software Foundation, Inc.
# ALL RIGHTS RESERVED (DCE).  See the file named COPYRIGHT.DCE in the
# src directory for the full copyright text.
#
#
# HISTORY
# $Log: Makefile,v $
# Revision 1.1.4.2  1996/03/11  02:36:23  marty
# 	Update OSF copyright years
# 	[1996/03/10  20:04:24  marty]
#
# Revision 1.1.4.1  1995/12/11  21:52:19  root
# 	Submit OSF/DCE 1.2.1
# 	[1995/12/11  20:54:04  root]
# 
# Revision 1.1.2.2  1992/12/31  17:35:34  htf
# 	Embedding copyright notice
# 	[1992/12/31  16:59:36  htf]
# 
# Revision 1.1  1992/01/19  04:08:48  devrcs
# 	Initial revision
# 
# $EndLog$
#
#
# DCE Security Services 
# test/security/commands Makefile
#

# Subdirectories that build programs
SUBDIRS = rgy

.include <${RULES_MK}>
