TEST CASES FOR STRUCTURED OUTPUT
--------------------------------
Initializing ...
x500obj create /c=de -attribute ocl=c
-----------------------------------------------------------------------------
x500obj create /c=de/o=sni -attribute ocl=org
-----------------------------------------------------------------------------
x500obj create /c=de/o=sni/ou=ap11 -attribute ocl=ou
-----------------------------------------------------------------------------
x500obj create /c=de/o=sni/ou=ap11/cn=naik -attribute ocl=orp sn=naik "tn=12345;369072;576268" up=naik
-----------------------------------------------------------------------------
x500obj create /c=de/o=sni/ou=ap11/cn=naik,ou=ap11 -attribute ocl=orp sn=naik tn=99999
-----------------------------------------------------------------------------
x500obj create /c=de/o=sni/ou=ap11/cn=muller -attribute {ocl=orp sn=John {dsc=Software Professional}}
-----------------------------------------------------------------------------
x500obj create /c=de/o=sni/ou=ap11/cn=miller -attribute ocl=orp sn=Peter dsc=Engineer
-----------------------------------------------------------------------------
x500obj create /c=de/o=sni/ou=ap11/cn=mueller -attribute ocl=orp sn=Henry dsc=Engineer
-----------------------------------------------------------------------------
x500obj create /c=de/o=sni/ou=ap11/cn=meller -attribute ocl=orp sn=John
-----------------------------------------------------------------------------
x500obj create /c=de/o=sni/ou=ap11/cn=mail1 -attribute ocl=mdl {{mds={pt=0, ind={dn={/c=de/o=sni}, admd=admd, cn='common name', c=de,dt1=dt1,dt2=dt2,dt3=dt3,dt4=dt4,dv1=dv1,dv2=dv2,dv3=dv3,dv4=dv4,gen=gen,gn=given,ini=init,o=orgname,ou1=ou1,ou2=ou2,ou3=ou3,ou4=ou4,prmd=prmd,sn=surname}}}} moa={admd=admd,c=de,prmd=prmd}
-----------------------------------------------------------------------------
x500obj create /c=de/o=sni/ou=ap11/cn=mail2 -attribute ocl=mdl {{mds={pt=0, ind={dn={/c=de/o=sni/ou=ap11/cn=ind1}, admd=admd, c=de,o=orgname,prmd=prmd}};{pt=0,ind={dn={/c=de/o=sni/ou=ap11/cn=Submit},admd=admd,c=de,o=orgname,prmd=prmd}}}} "moa={admd=admd,c=de,o=orgname,ou1=ou1,ou2=ou2,prmd=prmd}" "mdm={dn={/c=de/o=sni/ou=ap11},admd=admd,c=de,prmd=prmd}"
-----------------------------------------------------------------------------
x500obj create /c=de/o=sni/ou=ap11/cn=Brown -attribute ocl=mdl {{dsc=Software Consultant}} {{mds={pt=0, ind={dn={/c=de/o=sni}, c=de, admd=dbp, prmd=sni, o=Siemens Nixdorf, ou1=Munich, ou2=P1, ou3=P4, ou4=ap113, cn=Alfred Brown, gn=Alfred, ini=P., sn=Brown, gen=396, dt1=MS MAIL, dv1=Brown}}}} moa={admd=admd,c=de,prmd=prmd}
-----------------------------------------------------------------------------
x500obj create /c=de/o=sni/ou=ap11/cn=Andrews -attribute ocl=mdl {{dsc=Project Leader}} {{mds={pt=0, ind={dn={/c=de/o=sni}, c=de, admd=dbp, prmd=sni, o=Siemens Nixdorf, ou1=Munich, ou2=P1, ou3=P4, ou4=ap113, cn=Peter Andrews, gn=Peter, ini=P., sn=Andrews, gen=396, dt1=MS MAIL, dv1=Peter}}}} moa={admd=admd,c=de,prmd=prmd}
-----------------------------------------------------------------------------
x500obj create /c=de/o=sni/ou=ap11/cn=dsa -attribute ocl=app
-----------------------------------------------------------------------------
x500obj create /c=de/o=sni/ou=ap11/cn=dsa/cn=dsa15 -attribute ocl=ape "PSA={NA='TCP/IP!internet=127.0.0.1+port=25015',TS=Server}"
-----------------------------------------------------------------------------

VALID TEST CASES FOR x500obj LIST
---------------------------------
x500obj list / -pretty
 1) /CN=Schema
 2) /C=de
-----------------------------------------------------------------------------
set gdscp_cwo /c=de/o=sni/ou=ap11
/c=de/o=sni/ou=ap11
-----------------------------------------------------------------------------
x500obj l -pretty
 1) /C=de/O=sni/OU=ap11/CN=naik
 2) /C=de/O=sni/OU=ap11/CN=muller
 3) /C=de/O=sni/OU=ap11/CN=miller
 4) /C=de/O=sni/OU=ap11/CN=mueller
 5) /C=de/O=sni/OU=ap11/CN=meller
 6) /C=de/O=sni/OU=ap11/CN=mail1
 7) /C=de/O=sni/OU=ap11/CN=mail2
 8) /C=de/O=sni/OU=ap11/CN=Brown
 9) /C=de/O=sni/OU=ap11/CN=Andrews
10) /C=de/O=sni/OU=ap11/CN=dsa
11) /C=de/O=sni/OU=ap11/CN=naik,OU=ap11
-----------------------------------------------------------------------------
set gdscp_cwo /c=de/o=sni
/c=de/o=sni
-----------------------------------------------------------------------------
x500obj li ou=ap11 -pretty
 1) /C=de/O=sni/OU=ap11/CN=naik
 2) /C=de/O=sni/OU=ap11/CN=muller
 3) /C=de/O=sni/OU=ap11/CN=miller
 4) /C=de/O=sni/OU=ap11/CN=mueller
 5) /C=de/O=sni/OU=ap11/CN=meller
 6) /C=de/O=sni/OU=ap11/CN=mail1
 7) /C=de/O=sni/OU=ap11/CN=mail2
 8) /C=de/O=sni/OU=ap11/CN=Brown
 9) /C=de/O=sni/OU=ap11/CN=Andrews
10) /C=de/O=sni/OU=ap11/CN=dsa
11) /C=de/O=sni/OU=ap11/CN=naik,OU=ap11
-----------------------------------------------------------------------------
list /c=de -pretty
 1) /C=de/O=sni
-----------------------------------------------------------------------------
x500obj list /c=de/o=sni -p
 1) /C=de/O=sni/OU=ap11
-----------------------------------------------------------------------------
list /c=de/o=sni/ou=ap11 -pre
 1) /C=de/O=sni/OU=ap11/CN=naik
 2) /C=de/O=sni/OU=ap11/CN=muller
 3) /C=de/O=sni/OU=ap11/CN=miller
 4) /C=de/O=sni/OU=ap11/CN=mueller
 5) /C=de/O=sni/OU=ap11/CN=meller
 6) /C=de/O=sni/OU=ap11/CN=mail1
 7) /C=de/O=sni/OU=ap11/CN=mail2
 8) /C=de/O=sni/OU=ap11/CN=Brown
 9) /C=de/O=sni/OU=ap11/CN=Andrews
10) /C=de/O=sni/OU=ap11/CN=dsa
11) /C=de/O=sni/OU=ap11/CN=naik,OU=ap11
-----------------------------------------------------------------------------
set gdscp_cwo /
/
-----------------------------------------------------------------------------

VALID TEST CASES FOR x500obj SEARCH
-----------------------------------
x500obj search / -filter cn=naik -subtree -p
 1) /C=de/O=sni/OU=ap11/CN=naik
 2) /C=de/O=sni/OU=ap11/CN=naik,OU=ap11
-----------------------------------------------------------------------------
x500obj search /c=de/o=sni/ou=ap11/cn=mueller -b -pret
 1) /C=de/O=sni/OU=ap11/CN=mueller
-----------------------------------------------------------------------------
x500obj search /c=de/o=sni/ou=ap11 -f {{cn=mue* || cn=mi*}} -subtree -types -pretty
 1) /C=de/O=sni/OU=ap11/CN=miller
    Object-Class
    Common-Name
    Surname
    Description
 2) /C=de/O=sni/OU=ap11/CN=mueller
    Object-Class
    Common-Name
    Surname
    Description
-----------------------------------------------------------------------------
set gdscp_cwo /c=de
/c=de
-----------------------------------------------------------------------------
x500obj se -subtree -pretty
 1) /C=de
 2) /C=de/O=sni/OU=ap11/CN=dsa/CN=dsa15
 3) /C=de/O=sni/OU=ap11/CN=naik
 4) /C=de/O=sni/OU=ap11/CN=muller
 5) /C=de/O=sni/OU=ap11/CN=miller
 6) /C=de/O=sni/OU=ap11/CN=mueller
 7) /C=de/O=sni/OU=ap11/CN=meller
 8) /C=de/O=sni/OU=ap11/CN=mail1
 9) /C=de/O=sni/OU=ap11/CN=mail2
10) /C=de/O=sni/OU=ap11/CN=Brown
11) /C=de/O=sni/OU=ap11/CN=Andrews
12) /C=de/O=sni/OU=ap11/CN=dsa
13) /C=de/O=sni/OU=ap11/CN=naik,OU=ap11
14) /C=de/O=sni
15) /C=de/O=sni/OU=ap11
-----------------------------------------------------------------------------
x500obj sear -filter cn=n* -subtree -pretty
 1) /C=de/O=sni/OU=ap11/CN=naik
 2) /C=de/O=sni/OU=ap11/CN=naik,OU=ap11
-----------------------------------------------------------------------------
x500obj search /c=de/o=sni/ou=ap11/cn=mueller -n -t -subtree -pretty
 1) /C=de/O=sni/OU=ap11/CN=mueller
    Object-Class
    Common-Name
    Surname
    Description
-----------------------------------------------------------------------------
x500obj search /c=de/o=sni/ou=ap11/cn=mueller -at ocl -subtree -pretty
 1) /C=de/O=sni/OU=ap11/CN=mueller
    Object-Class : Organizational-Person
                 : Person
                 : Top
-----------------------------------------------------------------------------
x500obj search /c=de/o=sni/ou=ap11/cn=mueller -allattr -subtree -pretty
 1) /C=de/O=sni/OU=ap11/CN=mueller
    Object-Class : Organizational-Person
                 : Person
                 : Top
    Common-Name  : mueller
    Surname      : Henry
    Description  : Engineer
-----------------------------------------------------------------------------
x500obj search /c=de/o=sni/ou=ap11/cn=mueller -attribute sn dsc -subtree -pretty
 1) /C=de/O=sni/OU=ap11/CN=mueller
    Surname     : Henry
    Description : Engineer
-----------------------------------------------------------------------------
x500obj search /c=de/o=sni/ou=ap11/cn=mueller -attribute {sn dsc} -subtree -pretty
 1) /C=de/O=sni/OU=ap11/CN=mueller
    Surname     : Henry
    Description : Engineer
-----------------------------------------------------------------------------
search /c=de/o=sni/ou=ap11 -filter {{cn=m*  && dsc=*}} -subtree -pretty
 1) /C=de/O=sni/OU=ap11/CN=miller
 2) /C=de/O=sni/OU=ap11/CN=mueller
 3) /C=de/O=sni/OU=ap11/CN=muller
-----------------------------------------------------------------------------
search /c=de/o=sni/ou=ap11 -allattr -subtree -pretty
 1) /C=de/O=sni/OU=ap11
    Object-Class              : Organizational-Unit
                              : Top
    Organizational-Unit-Name  : ap11
 2) /C=de/O=sni/OU=ap11/CN=dsa/CN=dsa15
    Object-Class              : Application-Entity
                              : Top
    Common-Name               : dsa15
    Presentation-Address
      Network-Address         : TCP/IP!internet=127.0.0.1+port=25015
      T-Selector              : Server
 3) /C=de/O=sni/OU=ap11/CN=naik
    Object-Class              : Organizational-Person
                              : Person
                              : Top
    Common-Name               : naik
    Surname                   : naik
    Telephone-Number          : 12345
                              : 369072
                              : 576268
    User-Password             : \x6e\x61\x69\x6b
 4) /C=de/O=sni/OU=ap11/CN=muller
    Object-Class              : Organizational-Person
                              : Person
                              : Top
    Common-Name               : muller
    Surname                   : John
    Description               : Software Professional
 5) /C=de/O=sni/OU=ap11/CN=miller
    Object-Class              : Organizational-Person
                              : Person
                              : Top
    Common-Name               : miller
    Surname                   : Peter
    Description               : Engineer
 6) /C=de/O=sni/OU=ap11/CN=mueller
    Object-Class              : Organizational-Person
                              : Person
                              : Top
    Common-Name               : mueller
    Surname                   : Henry
    Description               : Engineer
 7) /C=de/O=sni/OU=ap11/CN=meller
    Object-Class              : Organizational-Person
                              : Person
                              : Top
    Common-Name               : meller
    Surname                   : John
 8) /C=de/O=sni/OU=ap11/CN=mail1
    Object-Class              : MHS-Distribution-List
                              : Top
    Common-Name               : mail1
    MHS-DL-Submit-Permission
      Permission-Type         : 0
      Individual
        Directory-Name        : /C=de/O=sni
        ADMD-Name             : admd
        Common-Name           : common name
        Country-Name          : de
        Domain-Type-1         : dt1
        Domain-Type-2         : dt2
        Domain-Type-3         : dt3
        Domain-Type-4         : dt4
        Domain-Value-1        : dv1
        Domain-Value-2        : dv2
        Domain-Value-3        : dv3
        Domain-Value-4        : dv4
        Generation            : gen
        Given-Name            : given
        Initials              : init
        Organization          : orgname
        Organizational-Unit-1 : ou1
        Organizational-Unit-2 : ou2
        Organizational-Unit-3 : ou3
        Organizational-Unit-4 : ou4
        PRMD-Name             : prmd
        Surname               : surname
    MHS-OR-Address
      ADMD-Name               : admd
      Country-Name            : de
      PRMD-Name               : prmd
 9) /C=de/O=sni/OU=ap11/CN=mail2
    Object-Class              : MHS-Distribution-List
                              : Top
    Common-Name               : mail2
    MHS-DL-Submit-Permission
      Permission-Type         : 0
      Individual
        Directory-Name        : /C=de/O=sni/OU=ap11/CN=ind1
        ADMD-Name             : admd
        Country-Name          : de
        Organization          : orgname
        PRMD-Name             : prmd
      Permission-Type         : 0
      Individual
        Directory-Name        : /C=de/O=sni/OU=ap11/CN=Submit
        ADMD-Name             : admd
        Country-Name          : de
        Organization          : orgname
        PRMD-Name             : prmd
    MHS-OR-Address
      ADMD-Name               : admd
      Country-Name            : de
      Organization            : orgname
      Organizational-Unit-1   : ou1
      Organizational-Unit-2   : ou2
      PRMD-Name               : prmd
    MHS-DL-Members
      Directory-Name          : /C=de/O=sni/OU=ap11
      ADMD-Name               : admd
      Country-Name            : de
      PRMD-Name               : prmd
10) /C=de/O=sni/OU=ap11/CN=Brown
    Object-Class              : MHS-Distribution-List
                              : Top
    Common-Name               : Brown
    MHS-DL-Submit-Permission
      Permission-Type         : 0
      Individual
        Directory-Name        : /C=de/O=sni
        ADMD-Name             : dbp
        Common-Name           : Alfred Brown
        Country-Name          : de
        Domain-Type-1         : MS MAIL
        Domain-Value-1        : Brown
        Generation            : 396
        Given-Name            : Alfred
        Initials              : P.
        Organization          : Siemens Nixdorf
        Organizational-Unit-1 : Munich
        Organizational-Unit-2 : P1
        Organizational-Unit-3 : P4
        Organizational-Unit-4 : ap113
        PRMD-Name             : sni
        Surname               : Brown
    MHS-OR-Address
      ADMD-Name               : admd
      Country-Name            : de
      PRMD-Name               : prmd
    Description               : Software Consultant
11) /C=de/O=sni/OU=ap11/CN=Andrews
    Object-Class              : MHS-Distribution-List
                              : Top
    Common-Name               : Andrews
    MHS-DL-Submit-Permission
      Permission-Type         : 0
      Individual
        Directory-Name        : /C=de/O=sni
        ADMD-Name             : dbp
        Common-Name           : Peter Andrews
        Country-Name          : de
        Domain-Type-1         : MS MAIL
        Domain-Value-1        : Peter
        Generation            : 396
        Given-Name            : Peter
        Initials              : P.
        Organization          : Siemens Nixdorf
        Organizational-Unit-1 : Munich
        Organizational-Unit-2 : P1
        Organizational-Unit-3 : P4
        Organizational-Unit-4 : ap113
        PRMD-Name             : sni
        Surname               : Andrews
    MHS-OR-Address
      ADMD-Name               : admd
      Country-Name            : de
      PRMD-Name               : prmd
    Description               : Project Leader
12) /C=de/O=sni/OU=ap11/CN=dsa
    Object-Class              : Application-Process
                              : Top
    Common-Name               : dsa
13) /C=de/O=sni/OU=ap11/CN=naik,OU=ap11
    Object-Class              : Organizational-Person
                              : Person
                              : Top
    Common-Name               : naik
    Surname                   : naik
    Organizational-Unit-Name  : ap11
    Telephone-Number          : 99999
-----------------------------------------------------------------------------
search /c=de/o=sni -allattr -o -pretty
 1) /C=de/O=sni/OU=ap11
    Object-Class             : Organizational-Unit
                             : Top
    Organizational-Unit-Name : ap11
-----------------------------------------------------------------------------
search /c=de/o=sni -allattr -baseobject -pretty
 1) /C=de/O=sni
    Object-Class      : Organization
                      : Top
    Organization-Name : sni
-----------------------------------------------------------------------------
search /c=de/o=sni -allattr -s -pretty
 1) /C=de/O=sni
    Object-Class              : Organization
                              : Top
    Organization-Name         : sni
 2) /C=de/O=sni/OU=ap11/CN=dsa/CN=dsa15
    Object-Class              : Application-Entity
                              : Top
    Common-Name               : dsa15
    Presentation-Address
      Network-Address         : TCP/IP!internet=127.0.0.1+port=25015
      T-Selector              : Server
 3) /C=de/O=sni/OU=ap11/CN=naik
    Object-Class              : Organizational-Person
                              : Person
                              : Top
    Common-Name               : naik
    Surname                   : naik
    Telephone-Number          : 12345
                              : 369072
                              : 576268
    User-Password             : \x6e\x61\x69\x6b
 4) /C=de/O=sni/OU=ap11/CN=muller
    Object-Class              : Organizational-Person
                              : Person
                              : Top
    Common-Name               : muller
    Surname                   : John
    Description               : Software Professional
 5) /C=de/O=sni/OU=ap11/CN=miller
    Object-Class              : Organizational-Person
                              : Person
                              : Top
    Common-Name               : miller
    Surname                   : Peter
    Description               : Engineer
 6) /C=de/O=sni/OU=ap11/CN=mueller
    Object-Class              : Organizational-Person
                              : Person
                              : Top
    Common-Name               : mueller
    Surname                   : Henry
    Description               : Engineer
 7) /C=de/O=sni/OU=ap11/CN=meller
    Object-Class              : Organizational-Person
                              : Person
                              : Top
    Common-Name               : meller
    Surname                   : John
 8) /C=de/O=sni/OU=ap11/CN=mail1
    Object-Class              : MHS-Distribution-List
                              : Top
    Common-Name               : mail1
    MHS-DL-Submit-Permission
      Permission-Type         : 0
      Individual
        Directory-Name        : /C=de/O=sni
        ADMD-Name             : admd
        Common-Name           : common name
        Country-Name          : de
        Domain-Type-1         : dt1
        Domain-Type-2         : dt2
        Domain-Type-3         : dt3
        Domain-Type-4         : dt4
        Domain-Value-1        : dv1
        Domain-Value-2        : dv2
        Domain-Value-3        : dv3
        Domain-Value-4        : dv4
        Generation            : gen
        Given-Name            : given
        Initials              : init
        Organization          : orgname
        Organizational-Unit-1 : ou1
        Organizational-Unit-2 : ou2
        Organizational-Unit-3 : ou3
        Organizational-Unit-4 : ou4
        PRMD-Name             : prmd
        Surname               : surname
    MHS-OR-Address
      ADMD-Name               : admd
      Country-Name            : de
      PRMD-Name               : prmd
 9) /C=de/O=sni/OU=ap11/CN=mail2
    Object-Class              : MHS-Distribution-List
                              : Top
    Common-Name               : mail2
    MHS-DL-Submit-Permission
      Permission-Type         : 0
      Individual
        Directory-Name        : /C=de/O=sni/OU=ap11/CN=ind1
        ADMD-Name             : admd
        Country-Name          : de
        Organization          : orgname
        PRMD-Name             : prmd
      Permission-Type         : 0
      Individual
        Directory-Name        : /C=de/O=sni/OU=ap11/CN=Submit
        ADMD-Name             : admd
        Country-Name          : de
        Organization          : orgname
        PRMD-Name             : prmd
    MHS-OR-Address
      ADMD-Name               : admd
      Country-Name            : de
      Organization            : orgname
      Organizational-Unit-1   : ou1
      Organizational-Unit-2   : ou2
      PRMD-Name               : prmd
    MHS-DL-Members
      Directory-Name          : /C=de/O=sni/OU=ap11
      ADMD-Name               : admd
      Country-Name            : de
      PRMD-Name               : prmd
10) /C=de/O=sni/OU=ap11/CN=Brown
    Object-Class              : MHS-Distribution-List
                              : Top
    Common-Name               : Brown
    MHS-DL-Submit-Permission
      Permission-Type         : 0
      Individual
        Directory-Name        : /C=de/O=sni
        ADMD-Name             : dbp
        Common-Name           : Alfred Brown
        Country-Name          : de
        Domain-Type-1         : MS MAIL
        Domain-Value-1        : Brown
        Generation            : 396
        Given-Name            : Alfred
        Initials              : P.
        Organization          : Siemens Nixdorf
        Organizational-Unit-1 : Munich
        Organizational-Unit-2 : P1
        Organizational-Unit-3 : P4
        Organizational-Unit-4 : ap113
        PRMD-Name             : sni
        Surname               : Brown
    MHS-OR-Address
      ADMD-Name               : admd
      Country-Name            : de
      PRMD-Name               : prmd
    Description               : Software Consultant
11) /C=de/O=sni/OU=ap11/CN=Andrews
    Object-Class              : MHS-Distribution-List
                              : Top
    Common-Name               : Andrews
    MHS-DL-Submit-Permission
      Permission-Type         : 0
      Individual
        Directory-Name        : /C=de/O=sni
        ADMD-Name             : dbp
        Common-Name           : Peter Andrews
        Country-Name          : de
        Domain-Type-1         : MS MAIL
        Domain-Value-1        : Peter
        Generation            : 396
        Given-Name            : Peter
        Initials              : P.
        Organization          : Siemens Nixdorf
        Organizational-Unit-1 : Munich
        Organizational-Unit-2 : P1
        Organizational-Unit-3 : P4
        Organizational-Unit-4 : ap113
        PRMD-Name             : sni
        Surname               : Andrews
    MHS-OR-Address
      ADMD-Name               : admd
      Country-Name            : de
      PRMD-Name               : prmd
    Description               : Project Leader
12) /C=de/O=sni/OU=ap11/CN=dsa
    Object-Class              : Application-Process
                              : Top
    Common-Name               : dsa
13) /C=de/O=sni/OU=ap11/CN=naik,OU=ap11
    Object-Class              : Organizational-Person
                              : Person
                              : Top
    Common-Name               : naik
    Surname                   : naik
    Organizational-Unit-Name  : ap11
    Telephone-Number          : 99999
14) /C=de/O=sni/OU=ap11
    Object-Class              : Organizational-Unit
                              : Top
    Organizational-Unit-Name  : ap11
-----------------------------------------------------------------------------
search -filter {{(cn~=mueller) && ((OCL=ORP) || OCL=REP) && !(sn=henry) && (dsc=*) }} -subtree -pretty
 1) /C=de/O=sni/OU=ap11/CN=muller
 2) /C=de/O=sni/OU=ap11/CN=miller
-----------------------------------------------------------------------------
search /c=de/o=sni/ou=ap11 -filter {{cn=dsa || cn=mail1 || (cn=naik && tn=12345)}} -allattr -onelevel -pretty
 1) /C=de/O=sni/OU=ap11/CN=naik
    Object-Class              : Organizational-Person
                              : Person
                              : Top
    Common-Name               : naik
    Surname                   : naik
    Telephone-Number          : 12345
                              : 369072
                              : 576268
    User-Password             : \x6e\x61\x69\x6b
 2) /C=de/O=sni/OU=ap11/CN=mail1
    Object-Class              : MHS-Distribution-List
                              : Top
    Common-Name               : mail1
    MHS-DL-Submit-Permission
      Permission-Type         : 0
      Individual
        Directory-Name        : /C=de/O=sni
        ADMD-Name             : admd
        Common-Name           : common name
        Country-Name          : de
        Domain-Type-1         : dt1
        Domain-Type-2         : dt2
        Domain-Type-3         : dt3
        Domain-Type-4         : dt4
        Domain-Value-1        : dv1
        Domain-Value-2        : dv2
        Domain-Value-3        : dv3
        Domain-Value-4        : dv4
        Generation            : gen
        Given-Name            : given
        Initials              : init
        Organization          : orgname
        Organizational-Unit-1 : ou1
        Organizational-Unit-2 : ou2
        Organizational-Unit-3 : ou3
        Organizational-Unit-4 : ou4
        PRMD-Name             : prmd
        Surname               : surname
    MHS-OR-Address
      ADMD-Name               : admd
      Country-Name            : de
      PRMD-Name               : prmd
 3) /C=de/O=sni/OU=ap11/CN=dsa
    Object-Class              : Application-Process
                              : Top
    Common-Name               : dsa
-----------------------------------------------------------------------------
set gdscp_cwo /
/
-----------------------------------------------------------------------------

VALID TEST CASES FOR x500obj SHOW
---------------------------------
set gdscp_cwo /c=de/o=sni/ou=ap11/cn=naik
/c=de/o=sni/ou=ap11/cn=naik
-----------------------------------------------------------------------------
x500obj show -attribute cn -pretty
 1) /C=de/O=sni/OU=ap11/CN=naik
    Common-Name : naik
-----------------------------------------------------------------------------
x500obj show -attribute {cn tn} -pretty
 1) /C=de/O=sni/OU=ap11/CN=naik
    Common-Name      : naik
    Telephone-Number : 12345
                     : 369072
                     : 576268
-----------------------------------------------------------------------------
x500obj show -p
 1) /C=de/O=sni/OU=ap11/CN=naik
    Object-Class     : Organizational-Person
                     : Person
                     : Top
    Common-Name      : naik
    Surname          : naik
    Telephone-Number : 12345
                     : 369072
                     : 576268
    User-Password    : \x6e\x61\x69\x6b
-----------------------------------------------------------------------------
x500obj sh /c=de/o=sni/ou=ap11/cn=naik -pretty
 1) /C=de/O=sni/OU=ap11/CN=naik
    Object-Class     : Organizational-Person
                     : Person
                     : Top
    Common-Name      : naik
    Surname          : naik
    Telephone-Number : 12345
                     : 369072
                     : 576268
    User-Password    : \x6e\x61\x69\x6b
-----------------------------------------------------------------------------
x500obj sho /c=de/o=sni/ou=ap11/cn=naik -types -pretty
 1) /C=de/O=sni/OU=ap11/CN=naik
    Object-Class
    Common-Name
    Surname
    Telephone-Number
    User-Password
-----------------------------------------------------------------------------
show /c=de/o=sni/ou=ap11/cn=naik -attr tn sn ocl up -pret
 1) /C=de/O=sni/OU=ap11/CN=naik
    Telephone-Number : 12345
                     : 369072
                     : 576268
    Surname          : naik
    Object-Class     : Organizational-Person
                     : Person
                     : Top
    User-Password    : \x6e\x61\x69\x6b
-----------------------------------------------------------------------------
show /c=de/o=sni/ou=ap11/cn=mail1 -pretty
 1) /C=de/O=sni/OU=ap11/CN=mail1
    Object-Class              : MHS-Distribution-List
                              : Top
    Common-Name               : mail1
    MHS-DL-Submit-Permission
      Permission-Type         : 0
      Individual
        Directory-Name        : /C=de/O=sni
        ADMD-Name             : admd
        Common-Name           : common name
        Country-Name          : de
        Domain-Type-1         : dt1
        Domain-Type-2         : dt2
        Domain-Type-3         : dt3
        Domain-Type-4         : dt4
        Domain-Value-1        : dv1
        Domain-Value-2        : dv2
        Domain-Value-3        : dv3
        Domain-Value-4        : dv4
        Generation            : gen
        Given-Name            : given
        Initials              : init
        Organization          : orgname
        Organizational-Unit-1 : ou1
        Organizational-Unit-2 : ou2
        Organizational-Unit-3 : ou3
        Organizational-Unit-4 : ou4
        PRMD-Name             : prmd
        Surname               : surname
    MHS-OR-Address
      ADMD-Name               : admd
      Country-Name            : de
      PRMD-Name               : prmd
-----------------------------------------------------------------------------
show /c=de/o=sni/ou=ap11/cn=mail2 -pretty
 1) /C=de/O=sni/OU=ap11/CN=mail2
    Object-Class             : MHS-Distribution-List
                             : Top
    Common-Name              : mail2
    MHS-DL-Submit-Permission
      Permission-Type        : 0
      Individual
        Directory-Name       : /C=de/O=sni/OU=ap11/CN=ind1
        ADMD-Name            : admd
        Country-Name         : de
        Organization         : orgname
        PRMD-Name            : prmd
      Permission-Type        : 0
      Individual
        Directory-Name       : /C=de/O=sni/OU=ap11/CN=Submit
        ADMD-Name            : admd
        Country-Name         : de
        Organization         : orgname
        PRMD-Name            : prmd
    MHS-OR-Address
      ADMD-Name              : admd
      Country-Name           : de
      Organization           : orgname
      Organizational-Unit-1  : ou1
      Organizational-Unit-2  : ou2
      PRMD-Name              : prmd
    MHS-DL-Members
      Directory-Name         : /C=de/O=sni/OU=ap11
      ADMD-Name              : admd
      Country-Name           : de
      PRMD-Name              : prmd
-----------------------------------------------------------------------------
set gdscp_cwo /
/
-----------------------------------------------------------------------------

VALID TEST CASES FOR PARTIAL RESULTS DUE TO SIZE LIMIT
------------------------------------------------------
x500svc modify -sizelimit 1
-----------------------------------------------------------------------------
search / -subtree -pretty
 1) /C=de/O=sni/OU=ap11/CN=dsa/CN=dsa15
Incomplete operation - Insufficient size limit.
-----------------------------------------------------------------------------
list /c=de/o=sni/ou=ap11 -pretty
 1) /C=de/O=sni/OU=ap11/CN=naik
Incomplete operation - Insufficient size limit.
-----------------------------------------------------------------------------
x500svc modify -default
-----------------------------------------------------------------------------

VALID TEST CASES FOR x500svc MODIFY & SHOW
------------------------------------------
x500svc modify -default
-----------------------------------------------------------------------------
x500svc show -pretty
Automatic Continuation          - TRUE
Cache Class                     - NONE
Chaining Prohibited             - TRUE
Don't Dereference Alias         - FALSE
Don't Use Copy                  - TRUE
Use DUA Cache                   - FALSE
Read DUA Cache First            - FALSE
Local Scope                     - FALSE
Prefer Administration Functions - FALSE
Prefer Chaining                 - FALSE
Priority Of Request             - MEDIUM
Scope Of Referral               - UNLIMITED
Size Limit                      - INFINITE
Time Limit                      - INFINITE
Use DSA                         - TRUE
-----------------------------------------------------------------------------
x500svc modify -timelimit INFINITE
-----------------------------------------------------------------------------
x500svc show -pretty
Automatic Continuation          - TRUE
Cache Class                     - NONE
Chaining Prohibited             - TRUE
Don't Dereference Alias         - FALSE
Don't Use Copy                  - TRUE
Use DUA Cache                   - FALSE
Read DUA Cache First            - FALSE
Local Scope                     - FALSE
Prefer Administration Functions - FALSE
Prefer Chaining                 - FALSE
Priority Of Request             - MEDIUM
Scope Of Referral               - UNLIMITED
Size Limit                      - INFINITE
Time Limit                      - INFINITE
Use DSA                         - TRUE
-----------------------------------------------------------------------------
x500svc modify -sizelimit INFINITE
-----------------------------------------------------------------------------
x500svc show -pretty
Automatic Continuation          - TRUE
Cache Class                     - NONE
Chaining Prohibited             - TRUE
Don't Dereference Alias         - FALSE
Don't Use Copy                  - TRUE
Use DUA Cache                   - FALSE
Read DUA Cache First            - FALSE
Local Scope                     - FALSE
Prefer Administration Functions - FALSE
Prefer Chaining                 - FALSE
Priority Of Request             - MEDIUM
Scope Of Referral               - UNLIMITED
Size Limit                      - INFINITE
Time Limit                      - INFINITE
Use DSA                         - TRUE
-----------------------------------------------------------------------------
x500svc m -cacheclass NONE
-----------------------------------------------------------------------------
x500svc s -pretty
Automatic Continuation          - TRUE
Cache Class                     - NONE
Chaining Prohibited             - TRUE
Don't Dereference Alias         - FALSE
Don't Use Copy                  - TRUE
Use DUA Cache                   - FALSE
Read DUA Cache First            - FALSE
Local Scope                     - FALSE
Prefer Administration Functions - FALSE
Prefer Chaining                 - FALSE
Priority Of Request             - MEDIUM
Scope Of Referral               - UNLIMITED
Size Limit                      - INFINITE
Time Limit                      - INFINITE
Use DSA                         - TRUE
-----------------------------------------------------------------------------
x500svc mod -scopeofreferral UNLIMITED
-----------------------------------------------------------------------------
x500svc sh -pretty
Automatic Continuation          - TRUE
Cache Class                     - NONE
Chaining Prohibited             - TRUE
Don't Dereference Alias         - FALSE
Don't Use Copy                  - TRUE
Use DUA Cache                   - FALSE
Read DUA Cache First            - FALSE
Local Scope                     - FALSE
Prefer Administration Functions - FALSE
Prefer Chaining                 - FALSE
Priority Of Request             - MEDIUM
Scope Of Referral               - UNLIMITED
Size Limit                      - INFINITE
Time Limit                      - INFINITE
Use DSA                         - TRUE
-----------------------------------------------------------------------------
x500svc modify -timelimit 100
-----------------------------------------------------------------------------
x500svc show -pretty
Automatic Continuation          - TRUE
Cache Class                     - NONE
Chaining Prohibited             - TRUE
Don't Dereference Alias         - FALSE
Don't Use Copy                  - TRUE
Use DUA Cache                   - FALSE
Read DUA Cache First            - FALSE
Local Scope                     - FALSE
Prefer Administration Functions - FALSE
Prefer Chaining                 - FALSE
Priority Of Request             - MEDIUM
Scope Of Referral               - UNLIMITED
Size Limit                      - INFINITE
Time Limit                      - 100
Use DSA                         - TRUE
-----------------------------------------------------------------------------
x500svc modify -timelimit INFINITE
-----------------------------------------------------------------------------
x500svc show -pretty
Automatic Continuation          - TRUE
Cache Class                     - NONE
Chaining Prohibited             - TRUE
Don't Dereference Alias         - FALSE
Don't Use Copy                  - TRUE
Use DUA Cache                   - FALSE
Read DUA Cache First            - FALSE
Local Scope                     - FALSE
Prefer Administration Functions - FALSE
Prefer Chaining                 - FALSE
Priority Of Request             - MEDIUM
Scope Of Referral               - UNLIMITED
Size Limit                      - INFINITE
Time Limit                      - INFINITE
Use DSA                         - TRUE
-----------------------------------------------------------------------------
x500svc modify -sizelimit 100
-----------------------------------------------------------------------------
x500svc show -pretty
Automatic Continuation          - TRUE
Cache Class                     - NONE
Chaining Prohibited             - TRUE
Don't Dereference Alias         - FALSE
Don't Use Copy                  - TRUE
Use DUA Cache                   - FALSE
Read DUA Cache First            - FALSE
Local Scope                     - FALSE
Prefer Administration Functions - FALSE
Prefer Chaining                 - FALSE
Priority Of Request             - MEDIUM
Scope Of Referral               - UNLIMITED
Size Limit                      - 100
Time Limit                      - INFINITE
Use DSA                         - TRUE
-----------------------------------------------------------------------------
x500svc modify -sizelimit INFINITE
-----------------------------------------------------------------------------
x500svc show -pretty
Automatic Continuation          - TRUE
Cache Class                     - NONE
Chaining Prohibited             - TRUE
Don't Dereference Alias         - FALSE
Don't Use Copy                  - TRUE
Use DUA Cache                   - FALSE
Read DUA Cache First            - FALSE
Local Scope                     - FALSE
Prefer Administration Functions - FALSE
Prefer Chaining                 - FALSE
Priority Of Request             - MEDIUM
Scope Of Referral               - UNLIMITED
Size Limit                      - INFINITE
Time Limit                      - INFINITE
Use DSA                         - TRUE
-----------------------------------------------------------------------------
x500svc modify -cacheclass PRIVILEGE
-----------------------------------------------------------------------------
x500svc show -pretty
Automatic Continuation          - TRUE
Cache Class                     - PRIVILEGE
Chaining Prohibited             - TRUE
Don't Dereference Alias         - FALSE
Don't Use Copy                  - TRUE
Use DUA Cache                   - FALSE
Read DUA Cache First            - FALSE
Local Scope                     - FALSE
Prefer Administration Functions - FALSE
Prefer Chaining                 - FALSE
Priority Of Request             - MEDIUM
Scope Of Referral               - UNLIMITED
Size Limit                      - INFINITE
Time Limit                      - INFINITE
Use DSA                         - TRUE
-----------------------------------------------------------------------------
x500svc modify -ca NONE
-----------------------------------------------------------------------------
x500svc show -pretty
Automatic Continuation          - TRUE
Cache Class                     - NONE
Chaining Prohibited             - TRUE
Don't Dereference Alias         - FALSE
Don't Use Copy                  - TRUE
Use DUA Cache                   - FALSE
Read DUA Cache First            - FALSE
Local Scope                     - FALSE
Prefer Administration Functions - FALSE
Prefer Chaining                 - FALSE
Priority Of Request             - MEDIUM
Scope Of Referral               - UNLIMITED
Size Limit                      - INFINITE
Time Limit                      - INFINITE
Use DSA                         - TRUE
-----------------------------------------------------------------------------
x500svc modify -scopeofreferral COUNTRY
-----------------------------------------------------------------------------
x500svc show -pretty
Automatic Continuation          - TRUE
Cache Class                     - NONE
Chaining Prohibited             - TRUE
Don't Dereference Alias         - FALSE
Don't Use Copy                  - TRUE
Use DUA Cache                   - FALSE
Read DUA Cache First            - FALSE
Local Scope                     - FALSE
Prefer Administration Functions - FALSE
Prefer Chaining                 - FALSE
Priority Of Request             - MEDIUM
Scope Of Referral               - COUNTRY
Size Limit                      - INFINITE
Time Limit                      - INFINITE
Use DSA                         - TRUE
-----------------------------------------------------------------------------
x500svc modify -scopeofreferral {UNLIMITED}
-----------------------------------------------------------------------------
x500svc show -pretty
Automatic Continuation          - TRUE
Cache Class                     - NONE
Chaining Prohibited             - TRUE
Don't Dereference Alias         - FALSE
Don't Use Copy                  - TRUE
Use DUA Cache                   - FALSE
Read DUA Cache First            - FALSE
Local Scope                     - FALSE
Prefer Administration Functions - FALSE
Prefer Chaining                 - FALSE
Priority Of Request             - MEDIUM
Scope Of Referral               - UNLIMITED
Size Limit                      - INFINITE
Time Limit                      - INFINITE
Use DSA                         - TRUE
-----------------------------------------------------------------------------
x500svc modify -automaticcontinuation FALSE -cacheclass PRIVILEGE -chainingprohibited FALSE -dontdereferencealias TRUE -dontusecopy FALSE -duacache TRUE -duafirst TRUE -localscope TRUE -preferadmfunctions TRUE -preferchain TRUE -priority LOW -scopeofreferral DMD -timelimit 100 -sizelimit 500 -usedsa FALSE
-----------------------------------------------------------------------------
x500svc show -pretty
Automatic Continuation          - FALSE
Cache Class                     - PRIVILEGE
Chaining Prohibited             - FALSE
Don't Dereference Alias         - TRUE
Don't Use Copy                  - FALSE
Use DUA Cache                   - TRUE
Read DUA Cache First            - TRUE
Local Scope                     - TRUE
Prefer Administration Functions - TRUE
Prefer Chaining                 - TRUE
Priority Of Request             - LOW
Scope Of Referral               - DMD
Size Limit                      - 500
Time Limit                      - 100
Use DSA                         - FALSE
-----------------------------------------------------------------------------
x500svc modify -a TRUE -cacheclass NORMAL -ch TRUE -dontderef FALSE -dontuse TRUE -duac FALSE -duaf FALSE -l FALSE -preferadm FALSE -preferch FALSE -prio MEDIUM -sc UNLIMITED -t INFINITE -siz INFINITE -u TRUE
-----------------------------------------------------------------------------
x500svc show -p
Automatic Continuation          - TRUE
Cache Class                     - NORMAL
Chaining Prohibited             - TRUE
Don't Dereference Alias         - FALSE
Don't Use Copy                  - TRUE
Use DUA Cache                   - FALSE
Read DUA Cache First            - FALSE
Local Scope                     - FALSE
Prefer Administration Functions - FALSE
Prefer Chaining                 - FALSE
Priority Of Request             - MEDIUM
Scope Of Referral               - UNLIMITED
Size Limit                      - INFINITE
Time Limit                      - INFINITE
Use DSA                         - TRUE
-----------------------------------------------------------------------------
x500svc modify -def
-----------------------------------------------------------------------------
x500svc show -pret
Automatic Continuation          - TRUE
Cache Class                     - NONE
Chaining Prohibited             - TRUE
Don't Dereference Alias         - FALSE
Don't Use Copy                  - TRUE
Use DUA Cache                   - FALSE
Read DUA Cache First            - FALSE
Local Scope                     - FALSE
Prefer Administration Functions - FALSE
Prefer Chaining                 - FALSE
Priority Of Request             - MEDIUM
Scope Of Referral               - UNLIMITED
Size Limit                      - INFINITE
Time Limit                      - INFINITE
Use DSA                         - TRUE
-----------------------------------------------------------------------------
x500svc modify -cacheclass RESIDENT -priority HIGH
-----------------------------------------------------------------------------
x500svc show -pretty
Automatic Continuation          - TRUE
Cache Class                     - RESIDENT
Chaining Prohibited             - TRUE
Don't Dereference Alias         - FALSE
Don't Use Copy                  - TRUE
Use DUA Cache                   - FALSE
Read DUA Cache First            - FALSE
Local Scope                     - FALSE
Prefer Administration Functions - FALSE
Prefer Chaining                 - FALSE
Priority Of Request             - HIGH
Scope Of Referral               - UNLIMITED
Size Limit                      - INFINITE
Time Limit                      - INFINITE
Use DSA                         - TRUE
-----------------------------------------------------------------------------
x500svc modify -default
-----------------------------------------------------------------------------
x500svc show -pretty
Automatic Continuation          - TRUE
Cache Class                     - NONE
Chaining Prohibited             - TRUE
Don't Dereference Alias         - FALSE
Don't Use Copy                  - TRUE
Use DUA Cache                   - FALSE
Read DUA Cache First            - FALSE
Local Scope                     - FALSE
Prefer Administration Functions - FALSE
Prefer Chaining                 - FALSE
Priority Of Request             - MEDIUM
Scope Of Referral               - UNLIMITED
Size Limit                      - INFINITE
Time Limit                      - INFINITE
Use DSA                         - TRUE
-----------------------------------------------------------------------------

VALID TEST CASES FOR x500abbr SHOW
----------------------------------
x500abbr show -p
Object Class Abbreviations:
    ALI    Alias                       85.6.1
    APE    Application-Entity          85.6.12
    APP    Application-Process         85.6.11
    C      Country                     85.6.2
    CA     Certification-Authority     85.6.16
    DEV    Device                      85.6.14
    DNA    DME-NMO-Agent               43.22.2.1.2.2.1
    DSA    Directory-Service-Agent     85.6.13
    GON    Group-of-Names              85.6.9
    LOC    Locality                    85.6.3
    MDL    MHS-Distribution-List       86.5.1.0
    MMS    MHS-Message-Store           86.5.1.1
    MTA    MHS-Mess-Transfer-Agent     86.5.1.2
    MUA    MHS-User-Agent              86.5.1.4
    MUS    MHS-User                    86.5.1.3
    ORG    Organization                85.6.4
    ORP    Organizational-Person       85.6.7
    ORR    Organizational-Role         85.6.8
    OU     Organizational-Unit         85.6.5
    PER    Person                      85.6.6
    REP    Residential-Person          85.6.10
    SAU    Strong-Authentication-User  85.6.15
    SCH    Schema                      43.12.2.1107.1.3.6.0
    TOP    Top                         85.6.0
Attribute Abbreviations:
    AA     Alternate-Address           43.22.2.1.2.1.1
    ACL    Access-Control-List         43.12.2.1107.1.3.4.1
    AM     Authentication-Mechanism    43.12.2.1107.1.3.4.16
    AON    Aliased-Object-Name         85.4.1
    ARL    Authority-Revoc.-List       85.4.38
    AT     Attribute-Table             43.12.2.1107.1.3.4.6
    BC     Business-Category           85.4.15
    C      Country-Name                85.4.6
    CAC    CA-Certificate              85.4.37
    CCP    Cross-Certificate-Pair      85.4.40
    CDC    CDS-Cell                    43.12.2.1107.1.3.4.13
    CDR    CDS-Replica                 43.12.2.1107.1.3.4.14
    CL     Client                      43.12.2.1107.1.3.4.10
    CN     Common-Name                 85.4.3
    CRL    Certificate-Revoc.-List     85.4.39
    DD     Default-DSA                 43.12.2.1107.1.3.4.8
    DI     Destination-Indicator       85.4.27
    DNL    DN-List                     43.12.2.1107.1.3.4.11
    DSC    Description                 85.4.13
    FTN    Fax-Telephone-Number        85.4.23
    IIN    Internat.-ISDN-Number       85.4.25
    KNI    Knowledge-Information       85.4.2
    L      Locality-Name               85.4.7
    LD     Local-DSA                   43.12.2.1107.1.3.4.9
    MDE    MHS-Deliverable-EITs        86.5.2.2
    MDL    MHS-Deliv.-Cont.-Length     86.5.2.0
    MDM    MHS-DL-Members              86.5.2.3
    MDS    MHS-DL-Submit-Permission    86.5.2.4
    MDT    MHS-Deliv.-Cont.-Types      86.5.2.1
    MEM    Member                      85.4.31
    MK     Master-Knowledge            43.12.2.1107.1.3.4.0
    MMS    MHS-Message-Store           86.5.2.5
    MOA    MHS-OR-Address              86.5.2.6
    MPD    MHS-Pref.-Deliv.-Meth.      86.5.2.7
    MSA    MHS-Supp.-Autom.-Action     86.5.2.8
    MSC    MHS-Supp.-Content-Types     86.5.2.9
    MSO    MHS-Supp.-Optional-Attr.    86.5.2.10
    O      Organization-Name           85.4.10
    OCL    Object-Class                85.4.0
    OCT    Object-Class-Table          43.12.2.1107.1.3.4.5
    OU     Organizational-Unit-Name    85.4.11
    OWN    Owner                       85.4.32
    PA     Postal-Address              85.4.16
    PC     Postal-Code                 85.4.17
    PDM    Preferred-Delivery-Meth.    85.4.28
    PDO    Phys.-Deliv.-Office-Name    85.4.19
    PN     Principal-Name              43.12.2.1107.1.3.4.15
    POB    Post-Office-Box             85.4.18
    PSA    Presentation-Address        85.4.29
    RA     Registered-Address          85.4.26
    RO     Role-Occupant               85.4.33
    SAC    Suppl.-Applic.-Context      85.4.30
    SEA    See-Also                    85.4.34
    SER    Serial-Number               85.4.5
    SG     Search-Guide                85.4.14
    SN     Surname                     85.4.4
    SPN    State-or-Province-Name      85.4.8
    SRT    Structure-Rule-Table        43.12.2.1107.1.3.4.4
    STA    Street-Address              85.4.9
    TIT    Title                       85.4.12
    TL     Typeless-RDN-for-CDS        43.22.1.2.2
    TN     Telephone-Number            85.4.20
    TST    Time-Stamp                  43.12.2.1107.1.3.4.2
    TTI    TTX-Terminal-Identifier     85.4.22
    TXN    Telex-Number                85.4.21
    UC     User-Certificate            85.4.36
    UP     User-Password               85.4.35
    XA     X121-Address                85.4.24
Component Abbreviations for "DS_C_ALGORITHM_IDENT" class:
    AL     Algorithm
    ALP    Algorithm-Parameters
Component Abbreviations for "DS_C_CERT" class:
    IS     Issuer
    SIGA   Signature-Algorithm
    SIG    Signature-Value
    SN     Serial-Number
    SUB    Subject
    SUBA   Subject-Algorithm
    SUBK   Subject-Public-Key
    VNA    Validity-Not-After
    VNB    Validity-Not-Before
    VER    Version
Component Abbreviations for "DS_C_CERT_LIST" class:
    IS     Issuer
    SIGA   Signature-Algorithm
    SIG    Signature-Value
    LU     Last-Update
    RC     Revoked-Certificates
Component Abbreviations for "DS_C_CERT_PAIR" class:
    F      Forward
    R      Reverse
Component Abbreviations for "DS_C_CERT_SUBLIST" class:
    IS     Issuer
    SIGA   Signature-Algorithm
    SIG    Signature-Value
    RD     Revocation-Date
    SN     Serial-Numbers
Component Abbreviations for "DS_C_FACSIMILE_PHONE_NBR" class:
    PA     Parameters
    PN     Phone-Number
Component Abbreviations for "DS_C_DL_SUBMIT_PERMS" class:
    PT     Permission-Type
    IND    Individual
    MDL    Member-Of-DL
    PM     Pattern-Match
    MG     Member-Of-Group
Component Abbreviations for "DS_C_POSTAL_ADDRESS" class:
    PA     Postal-Address
Component Abbreviations for "DS_C_SEARCH_CRITERION" class:
    AT     Attribute-Type
    CR     Criteria
    FIT    Filter-Item-Type
    FT     Filter-Type
Component Abbreviations for "DS_C_SEARCH_GUIDE" class:
    OCL    Object-Class
    SC     Search-Criteria
Component Abbreviations for "DS_C_SIGNATURE" class:
    IS     Issuer
    SIGA   Signature-Algorithm
    SIG    Signature-Value
Component Abbreviations for "DS_C_TELETEX_TERM_IDENT" class:
    PAR    Parameters
    TT     Teletex-Terminal
Component Abbreviations for "DS_C_TELEX_NBR" class:
    AB     Answerback
    CC     Country-Code
    TN     Telex-Number
Component Abbreviations for "MH_C_G3_FAX_NBPS" class:
    A3W    A3-Width
    B4L    B4-Length
    B4W    B4-Width
    FR     Fine-Resolution
    TD     Two-Dimensional
    UC     Uncompressed
    UL     Unlimited-Length
Component Abbreviations for "MH_C_OR_NAME" class:
    DN     Directory-Name
    ADMD   ADMD-Name
    CN     Common-Name
    C      Country-Name
    DT1    Domain-Type-1
    DT2    Domain-Type-2
    DT3    Domain-Type-3
    DT4    Domain-Type-4
    DV1    Domain-Value-1
    DV2    Domain-Value-2
    DV3    Domain-Value-3
    DV4    Domain-Value-4
    GEN    Generation
    GN     Given-Name
    INI    Initials
    ISDN   ISDN-Number
    ISDA   ISDN-SubAddress
    UID    User-Identifier
    O      Organization
    OU1    Organizational-Unit-1
    OU2    Organizational-Unit-2
    OU3    Organizational-Unit-3
    OU4    Organizational-Unit-4
    PAD    Postal-Address-Detail
    FPA    Full-Postal-Address
    PAL    Postal-Address-Lines
    PCD    Postal-Code
    PC     Postal-Country-Name
    PDP    Delivery-Point-Name
    PDS    Delivery-System-Name
    PGA    General-Del.-Address
    PL     Postal-Locale
    PBN    Postal-Box-Number
    PON    Postal-Office-Name
    PNB    Postal-Office-Number
    PO     Postal-Organization
    PPD    Postal-Patron-Details
    PPN    Postal-Patron-Name
    PST    Postal-Street-Address
    PSA    Presentation-Address
    PRMD   PRMD-Name
    SN     Surname
    TI     Terminal-Identifier
    TT     Terminal-Type
    XA     X121-Address
Component Abbreviations for "MH_C_OR_ADDRESS" class:
    ADMD   ADMD-Name
    CN     Common-Name
    C      Country-Name
    DT1    Domain-Type-1
    DT2    Domain-Type-2
    DT3    Domain-Type-3
    DT4    Domain-Type-4
    DV1    Domain-Value-1
    DV2    Domain-Value-2
    DV3    Domain-Value-3
    DV4    Domain-Value-4
    GEN    Generation
    GN     Given-Name
    INI    Initials
    ISDN   ISDN-Number
    ISDA   ISDN-SubAddress
    UID    User-Identifier
    O      Organization
    OU1    Organizational-Unit-1
    OU2    Organizational-Unit-2
    OU3    Organizational-Unit-3
    OU4    Organizational-Unit-4
    PAD    Postal-Address-Detail
    FPA    Full-Postal-Address
    PAL    Postal-Address-Lines
    PCD    Postal-Code
    PC     Postal-Country-Name
    PDP    Delivery-Point-Name
    PDS    Delivery-System-Name
    PGA    General-Del.-Address
    PL     Postal-Locale
    PBN    Postal-Box-Number
    PON    Postal-Office-Name
    PNB    Postal-Office-Number
    PO     Postal-Organization
    PPD    Postal-Patron-Details
    PPN    Postal-Patron-Name
    PST    Postal-Street-Address
    PSA    Presentation-Address
    PRMD   PRMD-Name
    SN     Surname
    TI     Terminal-Identifier
    TT     Terminal-Type
    XA     X121-Address
Component Abbreviations for "MH_C_TELETEX_NBPS" class:
    CCS    Control-Char.-Sets
    GCS    Graphic-Char.-Sets
    MC     Misc.-Capabilities
    PF     Page-Formats
    PU     Private-Use
Component Abbreviations for "DSX_C_GDS_ACL" class:
    MPUB   Modify-Public
    RSTD   Read-Standard
    MSTD   Modify-Standard
    RSEN   Read-Sensitive
    MSEN   Modify-Sensitive
Component Abbreviations for "DSX_C_GDS_ACL_ITEM" class:
    INT    Interpretation
    USR    User
Component Abbreviations for "DSX_C_GDS_CONTEXT" class:
    AR     Aliased-RDNs
    OP     Operation-Progress
    CP     Chaining-Prohibited
    DDA    Dont-Deref.-Aliases
    DUC    Dont-Use-Copy
    LS     Local-Scope
    PC     Prefer-Chaining
    PRI    Priority
    SOR    Scope-Of-Referral
    SL     Size-Limit
    TL     Time-Limit
    AS     Asynchronous
    AC     Auto.-Continuation
    DF     DUA-Cache-First
    DS     Dont-Store-In-Cache
    NCL    Normal-Class
    PCL    Privileged-Class
    RCL    Resident-Class
    UD     Use-DSA
    DC     DUA-Cache
    SM     Sign-Mechanism
    PR     Protection-Request
Component Abbreviations for "DSX_C_GDS_SESSION" class:
    DN     DSA-Name
    DA     DSA-Address
    FD     File-Descriptor
    REQ    Requestor
    PW     Password
    DID    Dir-Id
    AM     Auth.-Mechanism
    AI     Auth.-Information
Component Abbreviations for "DS_C_AVA" class:
    AT     Attribute-Type
    AV     Attribute-Value
Component Abbreviations for "DS_C_CONTEXT" class:
    AR     Aliased-RDNs
    OP     Operation-Progress
    CP     Chaining-Prohibited
    DDA    Dont-Deref.-Aliases
    DUC    Dont-Use-Copy
    LS     Local-Scope
    PC     Prefer-Chaining
    PRI    Priority
    SOR    Scope-Of-Referral
    SL     Size-Limit
    TL     Time-Limit
    AS     Asynchronous
    AC     Auto.-Continuation
Component Abbreviations for "DS_C_DS_DN" class:
    RDN    Relative-Dist.-Names
Component Abbreviations for "DS_C_DS_RDN" class:
    AVA    Assertions
Component Abbreviations for "DS_C_ENTRY_INFO_SELECTION" class:
    AA     All-Attributes
    AS     Attributes-Selected
    IT     Information-Type
Component Abbreviations for "DS_C_OPERATION_PROGRESS" class:
    RP     Name-Resolution-Phase
    NR     Next-Resolved-RDN
Component Abbreviations for "DS_C_PRESENTATION_ADDRESS" class:
    NA     Network-Address
    PS     P-Selector
    SS     S-Selector
    TS     T-Selector
Component Abbreviations for "DS_C_SESSION" class:
    DN     DSA-Name
    DA     DSA-Address
    FD     File-Descriptor
    REQ    Requestor
-----------------------------------------------------------------------------

VALID TEST CASES FOR x500obj HELP
---------------------------------
x500obj help
bind        Binds to the specified directory server.
compare     Checks if the object has the specified attribute value.
create      Creates the specified object in the directory.
delete      Removes the specified object entry from the directory.
list        Lists all the children of the specified object.
modify      Modifies the attribute values of an object in the directory.
search      Searches for objects in the directory.
show        Reads attributes of an object in the directory.
help        Displays help text for the x500obj object and its operations.
operations  Lists the operations that can be performed on the x500obj object.
-----------------------------------------------------------------------------
x500obj help -verbose
The x500obj object represents X.500 directory objects in the DIT on which
"gdscp" performs directory operations such as create, modify, delete, etc.
You can perform SQL like search operations and also manipulate the objects
in the DUA cache.  You can specify the DIT object names and attributes easily
using strings.  The x500obj object always remembers the current object in the
DIT, so that you do not have to  specify the DIT object name with every
operation or can specify the objects names relative to the current object.
You can also specify the attribute values as T.61 strings or strings in the
local code set (ISO8859-1).
-----------------------------------------------------------------------------
x500obj help -v
The x500obj object represents X.500 directory objects in the DIT on which
"gdscp" performs directory operations such as create, modify, delete, etc.
You can perform SQL like search operations and also manipulate the objects
in the DUA cache.  You can specify the DIT object names and attributes easily
using strings.  The x500obj object always remembers the current object in the
DIT, so that you do not have to  specify the DIT object name with every
operation or can specify the objects names relative to the current object.
You can also specify the attribute values as T.61 strings or strings in the
local code set (ISO8859-1).
-----------------------------------------------------------------------------
x500obj h bind
-authentication  Specifies authentication type.
-cache           Binds to the DUA cache.
-dirid           Specifies the Directory Identifier to which bind is to be made.
-dsa             Specifies the DSA Name to which bind is to be made.
-password        Specifies the user password for bind with credentials.
-psap            Specifies PSAP Address of the DSA to which bind is to be made.
-user            Specifies user name for bind with credentials.
-----------------------------------------------------------------------------
x500obj hel compare
-attribute  Specifies attribute information to be compared.
-----------------------------------------------------------------------------
help create
-attribute  Specifies attribute information for the object to be created.
-----------------------------------------------------------------------------
help delete
-----------------------------------------------------------------------------
help help
-verbose  Displays text about the x500obj object.
-----------------------------------------------------------------------------
help list
-pretty  Displays the result in a structured format.
-----------------------------------------------------------------------------
help operations
-----------------------------------------------------------------------------
help modify
-addattr     Specifies the attribute information to be added.
-changeattr  Specifies the attribute information to be modified.
-rdn         Specifies the new RDN for the object to be modified.
-removeattr  Specifies the attribute information/types to be deleted.
-----------------------------------------------------------------------------
help search
-allattr     Specifies search request for all attributes.
-attribute   Specifies search request for specific attributes.
-baseobject  Restricts the scope of a search to base object only.
-filter      Specifies the filter condition for the search.
-onelevel    Restricts the scope of search to all children of base object.
-noaliases   Specifies that aliases are not to be dereferenced.
-pretty      Displays the result in a structured format.
-subtree     Specifies that scope of search is whole subtree of base object.
-types       Restricts the search request to attribute types and no values.
-----------------------------------------------------------------------------
help show
-attribute  Specifies read request for specific attributes.
-pretty     Displays the result in a structured format.
-types      Restricts the read request to attribute types and no values.
-----------------------------------------------------------------------------

VALID TEST CASES FOR x500svc HELP
---------------------------------
x500svc help
modify      Modifies the service controls.
show        Displays the service controls.
help        Displays help text for the x500svc object and its operations.
operations  Lists the operations that can be performed on the x500svc object.
-----------------------------------------------------------------------------
x500svc help -verbose
The x500svc object represents the service controls that are passed in a
directory operation such as search, create, etc. Whenever you perform any
directory operation, you specify the service controls which are associated
with the operation.  The service controls determine whether an operation
is to be performed on the DUA cache or the DSA, whether referrals are to
be processed automatically, what should be the time and size limit for the
operation, etc.  You can use the x500svc modify command to change one or
more of the service control settings so that all subsequent directory
operations use the revised settings.  You can also display the current
values of the service controls using the x500svc show command.
-----------------------------------------------------------------------------
x500svc h -v
The x500svc object represents the service controls that are passed in a
directory operation such as search, create, etc. Whenever you perform any
directory operation, you specify the service controls which are associated
with the operation.  The service controls determine whether an operation
is to be performed on the DUA cache or the DSA, whether referrals are to
be processed automatically, what should be the time and size limit for the
operation, etc.  You can use the x500svc modify command to change one or
more of the service control settings so that all subsequent directory
operations use the revised settings.  You can also display the current
values of the service controls using the x500svc show command.
-----------------------------------------------------------------------------
x500svc help help
-verbose  Displays text about the x500svc object.
-----------------------------------------------------------------------------
x500svc help modify
-automaticcontinuation  Processes continuation referrals automatically.
-cacheclass             Indicates the storage class of cache.
-chainingprohibited     Prohibits the use of chaining.
-default                Sets service controls to default values.
-dontdereferencealias   Do not dereference alias, if found.
-dontusecopy            Prohibits use of shadow entry of the object.
-duacache               Uses DUA Cache.
-duafirst               Uses DUA Cache first.
-localscope             Limits the operation to bind DSA.
-preferadmfunctions     Prefer administration functions.
-preferchain            Advices DSA to chain the operation.
-priority               Specifies the priority of a request.
-scopeofreferral        Indicates the scope of referrals.
-sizelimit              Sets size limit to specified value.
-timelimit              Sets time limit to specified value.
-usedsa                 Uses DSA.
-----------------------------------------------------------------------------
x500svc help operations
-----------------------------------------------------------------------------
x500svc help show
-pretty  Displays the result in a structured format.
-----------------------------------------------------------------------------

VALID TEST CASES FOR x500abbr HELP
----------------------------------
x500abbr help
show        Displays the attribute abbreviations.
help        Displays help text for the x500abbr object and its operations.
operations  Lists the operations that can be performed on the x500abbr object.
-----------------------------------------------------------------------------
x500abbr help -verbose
The x500abbr object represents the abbreviations that are used by "gdscp"
command line interface to the Directory Service. "gdscp" uses abbreviations
to represent the GDS attributes so that you can specify attributes easily.
The x500abbr object contains information about the abbreviation, full name
and object identifier for these attributes.  It also contains information
about the abbreviation, full name and object identifier of the object classes.
The x500abbr object holds information about the structured GDS attributes and
their components.  You can determine the abbreviation and other details of an
attribute by performing a "show" operation on the x500abbr object.
-----------------------------------------------------------------------------
x500abbr h -v
The x500abbr object represents the abbreviations that are used by "gdscp"
command line interface to the Directory Service. "gdscp" uses abbreviations
to represent the GDS attributes so that you can specify attributes easily.
The x500abbr object contains information about the abbreviation, full name
and object identifier for these attributes.  It also contains information
about the abbreviation, full name and object identifier of the object classes.
The x500abbr object holds information about the structured GDS attributes and
their components.  You can determine the abbreviation and other details of an
attribute by performing a "show" operation on the x500abbr object.
-----------------------------------------------------------------------------
x500abbr help help
-verbose  Displays text about the x500abbr object.
-----------------------------------------------------------------------------
x500abbr help operations
-----------------------------------------------------------------------------
x500abbr help show
-pretty  Displays the result in a structured format.
-----------------------------------------------------------------------------
Cleaning up ...
x500obj delete /c=de/o=sni/ou=ap11/cn=dsa/cn=dsa15
-----------------------------------------------------------------------------
x500obj delete /c=de/o=sni/ou=ap11/cn=dsa
-----------------------------------------------------------------------------
x500obj delete /c=de/o=sni/ou=ap11/cn=naik
-----------------------------------------------------------------------------
x500obj delete /c=de/o=sni/ou=ap11/cn=naik,ou=ap11
-----------------------------------------------------------------------------
x500obj delete /c=de/o=sni/ou=ap11/cn=muller
-----------------------------------------------------------------------------
x500obj delete /c=de/o=sni/ou=ap11/cn=miller
-----------------------------------------------------------------------------
x500obj delete /c=de/o=sni/ou=ap11/cn=mueller
-----------------------------------------------------------------------------
x500obj delete /c=de/o=sni/ou=ap11/cn=meller
-----------------------------------------------------------------------------
x500obj delete /c=de/o=sni/ou=ap11/cn=mail1
-----------------------------------------------------------------------------
x500obj delete /c=de/o=sni/ou=ap11/cn=mail2
-----------------------------------------------------------------------------
x500obj delete /c=de/o=sni/ou=ap11/cn=Brown
-----------------------------------------------------------------------------
x500obj delete /c=de/o=sni/ou=ap11/cn=Andrews
-----------------------------------------------------------------------------
x500obj delete /c=de/o=sni/ou=ap11
-----------------------------------------------------------------------------
x500obj delete /c=de/o=sni
-----------------------------------------------------------------------------
x500obj delete /c=de
-----------------------------------------------------------------------------
