#!/bin/sh
# @OSF_COPYRIGHT@
# COPYRIGHT NOTICE
# Copyright (c) 1990, 1991, 1992, 1993, 1996 Open Software Foundation, Inc.
# ALL RIGHTS RESERVED (DCE).  See the file named COPYRIGHT.DCE in the
# src directory for the full copyright text.
#
# HISTORY
# $Log: run_server,v $
# Revision 1.1.9.2  1996/03/11  02:25:23  marty
# 	Update OSF copyright years
# 	[1996/03/10  19:58:44  marty]
#
# Revision 1.1.9.1  1995/12/11  20:00:32  root
# 	Submit OSF/DCE 1.2.1
# 	[1995/12/11  19:41:48  root]
# 
# Revision 1.1.7.3  1993/06/16  21:28:52  sommerfeld
# 	Something went wrong with the submit last time..
# 	[1993/06/16  21:27:33  sommerfeld]
# 
# Revision 1.1.7.2  1993/06/16  19:15:26  sommerfeld
# 	Remove duplicate headers
# 	Allow the override of INCL.
# 	[1993/05/11  14:31:46  tatsu_s]
# 
# Revision 1.1.3.3  1993/02/01  21:33:24  hinman
# 	[hinman] - SVR4 changes
# 	[1993/02/01  21:03:44  hinman]
# 
# 	[hinman@sni] - Final merge before bsubmit
# 	[1993/01/31  16:29:39  hinman]
# 
# Revision 1.1.1.5  1993/02/01  21:04:00  hinman
# 	[hinman] - SVR4 changes
# 
# Revision 1.1.1.4  1993/01/31  16:29:47  hinman
# 	[hinman@sni] - Final merge before bsubmit
# 
# Revision 1.1.3.2  1993/01/11  22:07:30  bbelch
# 	    Embedding copyright notice
# 	    [1993/01/06  18:00:57  bbelch]
# 
# $EndLog$
#
#
# This is a shell script driver for the RPC testcases 

# Usage:  run_server  <server_directory>
#
# 
#      <server_directory> is the directory containing the server.
#            The default directory is:  ../moretests, and is used
#            if no server_directory is specified.

# The SERVERHOST environment variable is used by the server binary
SERVERHOST=`uname -n`
export SERVERHOST

# Determine which directory contains the rpc testcase "server" executable
SERVERDIR=${1:-"../moretests"}
INCL=${INCL:-/usr/include/dce}

export INCL

echo "Start idl testcase server"
$SERVERDIR/server &

echo "Start rpc_mgmt server"
$SERVERDIR/mgmt_server &

echo "Start rpc_binding_server_to_client server"
$SERVERDIR/rpc_server &

# Note: you must be authenticated as "root" for the following to work.
# Sofserv is for the authenticated RPC tests.
echo "Start sofserv server"
$SERVERDIR/sofserv -n $SERVER_NAME -p $SERVER_KEY &
exit
