/*
 * @OSF_COPYRIGHT@
 * COPYRIGHT NOTICE
 * Copyright (c) 1990, 1991, 1992, 1993, 1996 Open Software Foundation, Inc.
 * ALL RIGHTS RESERVED (DCE).  See the file named COPYRIGHT.DCE in the
 * src directory for the full copyright text.
 */
/*
 * HISTORY
 * $Log: comtest_interface_y.idl,v $
 * Revision 1.1.4.2  1996/03/11  02:26:48  marty
 * 	Update OSF copyright years
 * 	[1996/03/10  19:59:28  marty]
 *
 * Revision 1.1.4.1  1995/12/11  20:04:05  root
 * 	Submit OSF/DCE 1.2.1
 * 	[1995/12/11  19:43:04  root]
 * 
 * Revision 1.1.2.2  1993/01/11  22:12:59  bbelch
 * 	Embedding copyright notice
 * 	[1993/01/06  18:05:00  bbelch]
 * 
 * Revision 1.1  1992/01/19  03:38:39  devrcs
 * 	Initial revision
 * 
 * $EndLog$
 */
/*
**  Copyright (c) 1989 by
**      Hewlett-Packard Company, Palo Alto, Ca. & 
**      Digital Equipment Corporation, Maynard, Mass.
**
**  %a%copyright(,**  )
**
**  NAME
**
**      comtest_interface_X.idl
**
**  FACILITY:
**
**      Remote Procedure Call (RPC) 
**
**  ABSTRACT:
**
**  This file provides one of the IDL generated interface
**  specifications, interface_Y which used by the server
**  test comtest_server_register_if, and comtest_object_xfr,
**  on the client.  Two routines are provided, for emulating
**  RPC calls.
**
**  %a%private_begin
**
**  MODIFICATION HISTORY:
**
**  08-feb-91 burton    change name of interface from extraifs - interfaceY
**  02-feb-91 burton    fix the interface uuid, change to version 2
**  29-jan-91 burton    original
**
**  %a%private_end  
**
*/

/*
 * NOTE: The user will have to alter these
 * endpoints for testing on a local environment
 */

[uuid(534504e0-c2af-11c9-9391-08002b13ec4e),
    version(2),
    endpoint("ncadg_ip_udp:[2101]",
             "ncacn_ip_tcp:[2101]",
	     "ncacn_dnet_nsp:[comtest_server_y]")
]
interface interface_Y
{

/*
 * character string to pass in RPC call
 */
typedef [string] char kstring_t[];


/*
 * Receive something from the client to verify
 * RPC delivery to object.
 */

void interfaceY_op1
(
    [in]        handle_t           handle,
    [in]        unsigned long      imsg,
    [in]        kstring_t          *sp,
    [out]       unsigned long      *omsg,
    [out]       unsigned32         *status
);

void interfaceY_op2
(
    [in]        handle_t           handle,
    [in]        unsigned long      imsg,
    [in]        kstring_t          *sp,
    [out]       unsigned long      *omsg,
    [out]       unsigned32         *status
);

}





