/*
 * @OSF_COPYRIGHT@
 * COPYRIGHT NOTICE
 * Copyright (c) 1990, 1991, 1992, 1993, 1996 Open Software Foundation, Inc.
 * ALL RIGHTS RESERVED (DCE).  See the file named COPYRIGHT.DCE in the
 * src directory for the full copyright text.
 */
/*
 * HISTORY
 * $Log: ih.idl,v $
 * Revision 1.1.4.2  1996/03/11  02:27:04  marty
 * 	Update OSF copyright years
 * 	[1996/03/10  19:59:35  marty]
 *
 * Revision 1.1.4.1  1995/12/11  20:05:12  root
 * 	Submit OSF/DCE 1.2.1
 * 	[1995/12/11  19:43:21  root]
 * 
 * Revision 1.1.2.4  1993/01/25  18:04:39  bbelch
 * 	Fix duplicate log
 * 	[1993/01/25  17:36:38  bbelch]
 * 
 * Revision 1.1.2.3  1993/01/11  22:14:28  bbelch
 * 	Embedding copyright notice
 * 	[1993/01/06  18:06:33  bbelch]
 * 
 * Revision 1.1.2.2  1992/10/12  16:39:26  cuti
 * 	Remove hardcoded protocol seq and endpoint instead using all_protoseq.
 * 	[1992/10/12  14:41:55  cuti]
 * 
 * 	Remove hardcoded protocol seq and endpoint instead using all_protoseq.
 * 	[1992/10/09  17:59:07  cuti]
 * 
 * Revision 1.1  1992/01/19  03:35:13  devrcs
 * 	Initial revision
 * 
 * $EndLog$
 */
/*
#
#
# Copyright (c) 1991 by
#    Hewlett-Packard Company, Palo Alto, Ca.
#
# Permission to use, copy, modify, and distribute this
# software and its documentation for any purpose and without
# fee is hereby granted, provided that the above copyright
# notice appear in all copies and that both that copyright
# notice and this permission notice appear in supporting
# documentation, and that the name of Hewlett-Packard Company not
# be used in advertising or publicity pertaining to distribution
# of the software without specific, written prior permission.
# Hewlett-Packard Company makes no representations about the
# suitability of this software for any purpose.  It is provided
# "as is" without express or implied warranty.
#
#
# DCE API Test
#
*/



[uuid(41a23227-0000-0000-0d00-00c366000000),
version(2)
]

/*
 * This interface is for testing a NIDL compiler's handling of the
 * [implicit_handle()] interface attribute.
 */
interface implicit_test {

/*
 * a handle-less operation that will invoked through the global
 * handle variable implicit_handle_var
 */
void implicit_test_op1(
    [in] long int i,
    [out] long int *o
);

/*
 * a operation that will invoked through the global
 * handle variable implicit_handle_var notwithstanding the
 * presence of a handle_t first arg
 */
void implicit_test_op2(
    [in] handle_t h,
    [in] long int i,
    [out] long int *o
);

}
