/*
 * @OSF_COPYRIGHT@
 * COPYRIGHT NOTICE
 * Copyright (c) 1990, 1991, 1992, 1993, 1996 Open Software Foundation, Inc.
 * ALL RIGHTS RESERVED (DCE).  See the file named COPYRIGHT.DCE in the
 * src directory for the full copyright text.
 */
/*
 * HISTORY
 * $Log: string.idl,v $
 * Revision 1.1.4.2  1996/03/11  02:27:47  marty
 * 	Update OSF copyright years
 * 	[1996/03/10  19:59:53  marty]
 *
 * Revision 1.1.4.1  1995/12/11  20:10:43  root
 * 	Submit OSF/DCE 1.2.1
 * 	[1995/12/11  19:45:17  root]
 * 
 * Revision 1.1.2.4  1993/01/25  19:28:18  bbelch
 * 	Fix duplicate log
 * 	[1993/01/25  17:44:44  bbelch]
 * 
 * Revision 1.1.2.3  1993/01/11  23:40:58  bbelch
 * 	Embedding copyright notice
 * 	[1993/01/06  18:14:28  bbelch]
 * 
 * Revision 1.1.2.2  1992/10/12  17:39:18  cuti
 * 	Remove hardcoded protocol seq and endpoint instead using all_protoseq.
 * 	[1992/10/09  21:24:42  cuti]
 * 
 * Revision 1.1  1992/01/19  03:37:12  devrcs
 * 	Initial revision
 * 
 * $EndLog$
 */
/*
#
#
# Copyright (c) 1991 by
#    Hewlett-Packard Company, Palo Alto, Ca.
#
# Permission to use, copy, modify, and distribute this
# software and its documentation for any purpose and without
# fee is hereby granted, provided that the above copyright
# notice appear in all copies and that both that copyright
# notice and this permission notice appear in supporting
# documentation, and that the name of Hewlett-Packard Company not
# be used in advertising or publicity pertaining to distribution
# of the software without specific, written prior permission.
# Hewlett-Packard Company makes no representations about the
# suitability of this software for any purpose.  It is provided
# "as is" without express or implied warranty.
#
#
# DCE API Test
#
*/



[uuid(41c470b7-a000-0000-0d00-00c366000000),
 version(2)
]

interface stringtest {

typedef [string] char stringtest_t1 [100];

void stringtest_op1(
    [in] handle_t h,
    [in] stringtest_t1 i,
    [out] stringtest_t1 o
);

}
