/*
 * @OSF_COPYRIGHT@
 * COPYRIGHT NOTICE
 * Copyright (c) 1990, 1991, 1992, 1993, 1996 Open Software Foundation, Inc.
 * ALL RIGHTS RESERVED (DCE).  See the file named COPYRIGHT.DCE in the
 * src directory for the full copyright text.
 */
/*
 * HISTORY
 * $Log: tattr.idl,v $
 * Revision 1.1.4.2  1996/03/11  02:27:52  marty
 * 	Update OSF copyright years
 * 	[1996/03/10  19:59:56  marty]
 *
 * Revision 1.1.4.1  1995/12/11  20:11:26  root
 * 	Submit OSF/DCE 1.2.1
 * 	[1995/12/11  19:45:34  root]
 * 
 * Revision 1.1.2.4  1993/01/25  19:28:53  bbelch
 * 	Fix duplicate log
 * 	[1993/01/25  17:45:27  bbelch]
 * 
 * Revision 1.1.2.3  1993/01/11  23:41:40  bbelch
 * 	Embedding copyright notice
 * 	[1993/01/06  18:15:05  bbelch]
 * 
 * Revision 1.1.2.2  1992/10/12  17:47:18  cuti
 * 	Remove hardcoded protocol seq and endpoint instead using all_protoseq.
 * 	[1992/10/09  21:26:42  cuti]
 * 
 * Revision 1.1  1992/01/19  03:37:28  devrcs
 * 	Initial revision
 * 
 * $EndLog$
 */
/*
#
#
# Copyright (c) 1991 by
#    Hewlett-Packard Company, Palo Alto, Ca.
#
# Permission to use, copy, modify, and distribute this
# software and its documentation for any purpose and without
# fee is hereby granted, provided that the above copyright
# notice appear in all copies and that both that copyright
# notice and this permission notice appear in supporting
# documentation, and that the name of Hewlett-Packard Company not
# be used in advertising or publicity pertaining to distribution
# of the software without specific, written prior permission.
# Hewlett-Packard Company makes no representations about the
# suitability of this software for any purpose.  It is provided
# "as is" without express or implied warranty.
#
#
# DCE API Test
#
*/



[uuid(41248b18-5000-0000-0d00-00c366000000),
 version(2)
]

/* 
 * Interface used to test NIDL's type attributes.
 */
interface tattrtest {

typedef long int tattrtest_t2;

typedef [transmit_as(tattrtest_t2)] long int tattrtest_t1;

typedef [handle] long int tattrtest_t3;

typedef [v1_array] char astring [100];

void tattrtest_op1 (
    [in] tattrtest_t3 h,
    [in] tattrtest_t1 i,
    [out] tattrtest_t1 *o
);

void tattrtest_op2 (
    [in] handle_t h
);

boolean tattrtest_op3 (
    [in] handle_t h,
    [out] astring *msg
);

}
