/*
 * @OSF_COPYRIGHT@
 * COPYRIGHT NOTICE
 * Copyright (c) 1990, 1991, 1992, 1993, 1996 Open Software Foundation, Inc.
 * ALL RIGHTS RESERVED (DCE).  See the file named COPYRIGHT.DCE in the
 * src directory for the full copyright text.
 */
/*
 * HISTORY 
 * $Log: test_rpc_auth.idl,v $
 * Revision 1.1.4.2  1996/03/11  02:27:55  marty
 * 	Update OSF copyright years
 * 	[1996/03/10  19:59:57  marty]
 *
 * Revision 1.1.4.1  1995/12/11  20:11:46  root
 * 	Submit OSF/DCE 1.2.1
 * 	[1995/12/11  19:45:40  root]
 * 
 * Revision 1.1.2.4  1993/01/25  19:29:12  bbelch
 * 	Fix duplicate log
 * 	[1993/01/25  17:45:53  bbelch]
 * 
 * Revision 1.1.2.3  1993/01/11  23:41:59  bbelch
 * 	Embedding copyright notice
 * 	[1993/01/06  18:15:24  bbelch]
 * 
 * Revision 1.1.2.2  1992/10/14  13:27:10  cuti
 * 	Add more parameter for data checking.
 * 	[1992/10/13  21:10:44  cuti]
 * 
 * Revision 1.1  1992/01/19  03:37:37  devrcs
 * 	Initial revision
 * 
 * $EndLog$
 */
/*
**  Copyright (c) 1991 by
**      Hewlett-Packard Company, Palo Alto, Ca. &
**      Digital Equipment Corporation, Maynard, Mass. &
**	Locus Computing Corporation, Burlington, Mass.
**
**
** src/test/rpc/rtandidl/moretests/test_rpc_auth.idl, , dce_osf, dce.75d
**   
**	Extracted	1/4/92 16:54:02
**	from delta on	11/8/91 16:55:40
**
**
**
*/


[
    uuid(40e75346-1000-0000-0d00-00c366000000),
    version(1)
]

interface test_rpc_auth {


    /*  t e s t _ i n q _ a u t h _ c l i e n t
     *
     *  poke a test server to test the rpc_binding_inq_auth_client
     *  function.
     */

    void test_inq_auth_client (
        [in]        handle_t        h,
		[in]		long int 		subcase,
		[in]	    char			*server_name,
   		[in] 		unsigned32		i_authn_level,
   		[in] 		unsigned32		i_authn_svc,
   		[in]		unsigned32		i_authz_svc,
        [in, out]   error_status_t  *tstatus,
        [out]       error_status_t  *cstatus
    );

}
