/*
 * @OSF_COPYRIGHT@
 * COPYRIGHT NOTICE
 * Copyright (c) 1990, 1991, 1992, 1993, 1996 Open Software Foundation, Inc.
 * ALL RIGHTS RESERVED (DCE).  See the file named COPYRIGHT.DCE in the
 * src directory for the full copyright text.
 */
/*
 * HISTORY
 * $Log: context.idl,v $
 * Revision 1.1.4.2  1996/03/11  02:11:04  marty
 * 	Update OSF copyright years
 * 	[1996/03/10  19:52:12  marty]
 *
 * Revision 1.1.4.1  1995/12/11  20:00:20  root
 * 	Submit OSF/DCE 1.2.1
 * 	[1995/12/11  19:29:31  root]
 * 
 * Revision 1.1.2.2  1993/01/07  19:49:21  bbelch
 * 	Embedding copyright notice
 * 	[1993/01/06  13:30:05  bbelch]
 * 
 * Revision 1.1  1992/01/19  03:24:10  devrcs
 * 	Initial revision
 * 
 * $EndLog$
 */
/*
*/
[uuid(2d0a1d10-ffc4-11c8-8ae4-08002b104860), version(0)]
interface context
{
    const long BUFFSIZE = 512;

    void wr_open(
        [in] handle_t h,
        [out,context_handle] void **p_wr_ctx
    );

    void wr_write(
        [in,context_handle] void *wr_ctx,
        [in] long count,
        [in,length_is(count)] byte buffer[512]
    );

    void wr_close(
        [in,out,context_handle] void **p_wr_ctx
    );

    void rd_open(
        [in] handle_t h,
        [out,context_handle] void **p_rd_ctx
    );

    void rd_read(
        [in,context_handle] void *rd_ctx,
        [out] long *p_count,
        [out,length_is(*p_count)] byte buffer[512]
    );

    void rd_close(
        [in,out,context_handle] void **p_rd_ctx
    );

}
