#
# @OSF_COPYRIGHT@
# COPYRIGHT NOTICE
# Copyright (c) 1990, 1991, 1992, 1993, 1996 Open Software Foundation, Inc.
# ALL RIGHTS RESERVED (DCE).  See the file named COPYRIGHT.DCE in the
# src directory for the full copyright text.
#
#
# HISTORY
# $Log: Makefile,v $
# Revision 1.1.8.2  1996/03/11  02:11:01  marty
# 	Update OSF copyright years
# 	[1996/03/10  19:52:11  marty]
#
# Revision 1.1.8.1  1995/12/11  20:00:10  root
# 	Submit OSF/DCE 1.2.1
# 	[1995/12/11  19:29:28  root]
# 
# Revision 1.1.6.2  1994/03/03  22:11:32  bmw
# 	add context.h to DATAFILES
# 	[1994/03/03  22:11:10  bmw]
# 
# Revision 1.1.6.1  1993/12/28  22:09:38  pellis
# 	Updated for ODE 2.3 make
# 	[1993/12/28  21:53:20  pellis]
# 
# Revision 1.1.4.2  1993/01/07  19:49:04  bbelch
# 	Embedding copyright notice
# 	[1993/01/06  13:29:58  bbelch]
# 
# Revision 1.1  1992/01/19  03:24:14  devrcs
# 	Initial revision
# 
# $EndLog$
#

DATAFILES=RUN_ARGS context.h

IDLBASE = context
OTHER_CLIENT_FILES = client_aux.o

.include "../maketest.mk"
