#
# @OSF_COPYRIGHT@
# COPYRIGHT NOTICE
# Copyright (c) 1990, 1991, 1992, 1993, 1996 Open Software Foundation, Inc.
# ALL RIGHTS RESERVED (DCE).  See the file named COPYRIGHT.DCE in the
# src directory for the full copyright text.
#
# HISTORY
# $Log: Makefile,v $
# Revision 1.1.10.2  1996/03/09  23:14:13  marty
# 	Update OSF copyright year
# 	[1996/03/09  22:31:31  marty]
#
# Revision 1.1.10.1  1995/12/08  16:04:43  root
# 	Submit OSF/DCE 1.2.1
# 	[1995/12/08  15:15:52  root]
# 
# Revision 1.1.8.1  1994/02/22  17:41:24  marrek
# 	Code drop for dce1.1.
# 	[1994/02/08  10:55:30  marrek]
# 
# Revision 1.1.6.2  1993/08/11  15:09:56  marrek
# 	July 1993 code drop.
# 	[1993/08/02  13:02:25  marrek]
# 
# Revision 1.1.4.2  1992/12/31  20:47:29  bbelch
# 	Embedding copyright notice
# 	[1992/12/31  13:33:42  bbelch]
# 
# Revision 1.1.2.2  1992/06/01  20:59:30  melman
# 	New GDS merged drop
# 	[1992/05/28  21:51:51  melman]
# 
# Revision 1.1  1992/01/19  15:14:06  devrcs
# 	Initial revision
# 
# $EndLog$
#
# $RCSfile: Makefile,v $ $Revision: 1.1.10.2 $ $Date: 1996/03/09 23:14:13 $
#

#SUBDIRS	=	De En
SUBDIRS	=	En

.include <${RULES_MK}>
