/*
 * @OSF_COPYRIGHT@
 * COPYRIGHT NOTICE
 * Copyright (c) 1990, 1991, 1992, 1993, 1996 Open Software Foundation, Inc.
 * ALL RIGHTS RESERVED (DCE).  See the file named COPYRIGHT.DCE in the
 * src directory for the full copyright text.
 */
/*
 * HISTORY
 * $Log: stringptr.idl,v $
 * Revision 1.1.4.2  1996/03/11  02:18:53  marty
 * 	Update OSF copyright years
 * 	[1996/03/10  19:55:46  marty]
 *
 * Revision 1.1.4.1  1995/12/11  19:30:24  root
 * 	Submit OSF/DCE 1.2.1
 * 	[1995/12/11  19:16:03  root]
 * 
 * Revision 1.1.2.2  1993/01/07  23:38:41  bbelch
 * 	Embedding copyright notice
 * 	[1993/01/06  13:45:13  bbelch]
 * 
 * Revision 1.1  1992/01/19  03:28:28  devrcs
 * 	Initial revision
 * 
 * $EndLog$
 */
/*
*/
[uuid(9be09c58-5195-11c9-9ad3-08001e0218e9), version(0)]

interface stringptr
{
    const long MAXSTRINGLEN = 80;
    const long MAXSTRINGLEN0 = 81;
   
    typedef [string] char cstring_t[];
    typedef [string] char fstring_t[MAXSTRINGLEN0];

    boolean iref_to_cstring 
    (
        [in] handle_t h, 
        [in] cstring_t *sp,
        [in] long checksum
    );

    boolean ioref_to_cstring 
    (
        [in] handle_t h, 
        [in, out] cstring_t *sp,
        [in, out] long *checksum
    );

    boolean iptr_to_cstring 
    (
        [in] handle_t h, 
        [in, ptr] cstring_t *sp,
        [in] long checksum
    );

    boolean ioptr_to_cstring 
    (
        [in] handle_t h, 
        [in, out, ptr] cstring_t *sp,
        [in, out] long *checksum
    );

    boolean iref_to_fstring 
    (
        [in] handle_t h, 
        [in] fstring_t *sp,
        [in] long checksum
    );

    boolean ioref_to_fstring 
    (
        [in] handle_t h, 
        [in, out] fstring_t *sp,
        [in, out] long *checksum
    );

    boolean iptr_to_fstring 
    (
        [in] handle_t h, 
        [in, ptr] fstring_t *sp,
        [in] long checksum
    );

    boolean ioptr_to_fstring 
    (
        [in] handle_t h, 
        [in, out, ptr] fstring_t *sp,
        [in, out] long *checksum
    );

    boolean stringified_iref 
    (
        [in] handle_t h, 
        [in, string] char *cp,
        [in] long checksum
    );

    boolean stringified_null_iptr 
    (
        [in] handle_t h, 
        [in, ptr, string] char *cp,
        [in] long checksum
    );

    boolean stringified_iptr 
    (
        [in] handle_t h, 
        [in, ptr, string] char *cp,
        [in] long checksum
    );
}
