/*
 * @OSF_COPYRIGHT@
 * COPYRIGHT NOTICE
 * Copyright (c) 1990, 1991, 1992, 1993, 1996 Open Software Foundation, Inc.
 * ALL RIGHTS RESERVED (DCE).  See the file named COPYRIGHT.DCE in the
 * src directory for the full copyright text.
 */
/*
 * HISTORY
 * $Log: oolsmall.idl,v $
 * Revision 1.1.4.2  1996/03/11  02:15:36  marty
 * 	Update OSF copyright years
 * 	[1996/03/10  19:54:03  marty]
 *
 * Revision 1.1.4.1  1995/12/11  19:26:01  root
 * 	Submit OSF/DCE 1.2.1
 * 	[1995/12/11  19:14:06  root]
 * 
 * Revision 1.1.2.2  1993/01/07  20:32:42  bbelch
 * 	Embedding copyright notice
 * 	[1993/01/06  13:36:11  bbelch]
 * 
 * Revision 1.1  1992/01/19  03:25:26  devrcs
 * 	Initial revision
 * 
 * $EndLog$
 */
/*
*/
[uuid(9ae363d0-9a8d-11c9-99cc-08001e01e1e9), version(0)]
interface oolsmall
{
    const long FIXED_SIZE = 20;
    const long CONF_SIZE = 10;

    typedef [v1_array] short v1_fixed_array[FIXED_SIZE];
    typedef [v1_array] long v1_conf_array[];

    typedef [v1_struct] struct v1_vary_struct {
        long l;
        [last_is(l)] v1_fixed_array f_a;
    } v1_vary_struct;

    typedef [v1_struct] struct v1_open_struct {
        long s;
        long l;
        [size_is(s),last_is(l)] v1_conf_array c_a;
    } v1_open_struct;

    void v1_op0( [in] v1_vary_struct *p_v_s,
              [out] long *p_l,
              [out, last_is(*p_l)] v1_fixed_array f_a);

    void v1_op2( [in] v1_open_struct *p_o_s,
              [in] long s,
              [out] long *p_l,
              [out, size_is(s), last_is(*p_l)] v1_conf_array c_a);

}
