/*
 * @OSF_COPYRIGHT@
 * COPYRIGHT NOTICE
 * Copyright (c) 1990, 1991, 1992, 1993, 1996 Open Software Foundation, Inc.
 * ALL RIGHTS RESERVED (DCE).  See the file named COPYRIGHT.DCE in the
 * src directory for the full copyright text.
 */
/*
 * HISTORY
 * $Log: arraystr.idl,v $
 * Revision 1.1.4.2  1996/03/11  02:09:22  marty
 * 	Update OSF copyright years
 * 	[1996/03/10  19:51:29  marty]
 *
 * Revision 1.1.4.1  1995/12/11  19:56:32  root
 * 	Submit OSF/DCE 1.2.1
 * 	[1995/12/11  19:28:22  root]
 * 
 * Revision 1.1.2.2  1993/01/07  19:04:58  bbelch
 * 	Embedding copyright notice
 * 	[1993/01/06  13:26:26  bbelch]
 * 
 * Revision 1.1  1992/01/19  03:23:19  devrcs
 * 	Initial revision
 * 
 * $EndLog$
 */
/*
*/
[uuid(683fdb08-ffc4-11c8-8ae4-08002b104860), version(0)]
interface arraystr
{
    void op0 (
        [in]handle_t h,
        [in,out,ptr] char c_a[26],
        [in,out] long *f_l,
        [in,out] long *l_l,
        [in,out,ptr,first_is(*f_l),last_is(*l_l)] long l_a[20],
        [in] long s_s,
        [in,out,ptr,size_is(s_s)] short s_a[],
        [in] long s_u,
        [in,out] long *f_u,
        [in,out] long *l_u,
        [in,out,ptr,size_is(s_u),first_is(*f_u),last_is(*l_u)] 
                                                          unsigned long u_a[]
    );

    typedef struct {
	byte row,column;
	} PRIVATE_CHAR_16;

    typedef PRIVATE_CHAR_16 JIS_KANJI;
    
    typedef struct str_str_t {
        long s;
        [string,size_is(s),ptr] JIS_KANJI *str;
    } str_str_t;

    void op1 (
        [in]handle_t h,
        [in,string] JIS_KANJI *in,
        [out] str_str_t *p_out
    );

    void op2 (
        [in]handle_t h,
        [in,ptr,string] JIS_KANJI *in,
        [out] str_str_t *p_out
    );

}
