#
# @OSF_COPYRIGHT@
# COPYRIGHT NOTICE
# Copyright (c) 1990, 1991, 1992, 1993, 1996 Open Software Foundation, Inc.
# ALL RIGHTS RESERVED (DCE).  See the file named COPYRIGHT.DCE in the
# src directory for the full copyright text.
#
#
# HISTORY
# $Log: Makefile,v $
# Revision 1.1.8.2  1996/03/11  02:09:36  marty
# 	Update OSF copyright years
# 	[1996/03/10  19:51:35  marty]
#
# Revision 1.1.8.1  1995/12/11  19:57:08  root
# 	Submit OSF/DCE 1.2.1
# 	[1995/12/11  19:28:34  root]
# 
# Revision 1.1.6.1  1993/12/28  22:09:24  pellis
# 	Updated for ODE 2.3 make
# 	[1993/12/28  21:53:05  pellis]
# 
# Revision 1.1.4.2  1993/01/07  19:06:25  bbelch
# 	Embedding copyright notice
# 	[1993/01/06  13:27:06  bbelch]
# 
# Revision 1.1  1992/01/19  03:23:34  devrcs
# 	Initial revision
# 
# $EndLog$
#

IDLBASE = arrayv1
OTHER_CLIENT_FILES = client_aux.o

.include "../maketest.mk"
