/*
 * @OSF_COPYRIGHT@
 * 
 */
/*
 * HISTORY
 * $Log: dce_util_test_if.idl,v $
 * Revision 1.1.6.3  1996/03/11  02:29:55  marty
 * 	Update OSF copyright years
 * 	[1996/03/10  19:37:28  marty]
 *
 * Revision 1.1.6.2  1995/12/11  15:20:06  root
 * 	Submit
 * 	[1995/12/11  14:33:38  root]
 * 
 * Revision 1.1.2.1  1994/10/18  20:55:46  max
 * 	Initial submission of FVTs for dced utility API
 * 	[1994/10/18  20:47:57  max]
 * 
 * $EndLog$
 */

/*
 * @OSF_COPYRIGHT@
 * COPYRIGHT NOTICE
 * Copyright (c) 1990, 1991, 1992, 1993, 1994, 1996 Open Software Foundation, Inc.
 * ALL RIGHTS RESERVED (DCE).  See the file named COPYRIGHT.DCE for
 * the full copyright text.
 *
 */
/*
 * HISTORY
 * $EndLog$
 */


/******************************************************************************/


[
    uuid(d361c53a-dd78-11cd-9eca-000c00b4b407),
    version(1.0)
]
interface  dce_util_test_if
{

	error_status_t ping( 
		[in] handle_t		handle,
		[in] unsigned long 	x,
		[out] unsigned long 	*y
	);

	void stop_server( 
		[in] handle_t		handle,
		[out] error_status_t	*st
	);


}

