#!/bin/sh

#
# @OSF_COPYRIGHT@
# COPYRIGHT NOTICE
# Copyright (c) 1990, 1991, 1992, 1993 Open Software Foundation, Inc.
# ALL RIGHTS RESERVED (DCE).  See the file named COPYRIGHT.DCE in the
# src directory for the full copyright text.
#
# HISTORY
# $Log: test9,v $
# Revision 1.1.10.1  1996/10/17  18:30:37  damon
# 	Submitting on behalf of Transarc
# 	[1996/10/17  16:55:24  damon]
#
# Revision 1.1.4.5  1993/01/11  18:36:16  htf
# 	Embedded copyright notice
# 	[1993/01/11  17:19:38  htf]
# 
# Revision 1.1.4.4  1992/10/28  18:15:28  jaffe
# 	Transarc delta: fred-ot5472-use-testhome-variable 1.1
# 	  Selected comments:
# 	    Fixed the fs and low tests to correctly use TESTTOP.  We were setting a
# 	    variable, testhome, as the location for the test scripts and executables,
# 	    but we did not use it to execute C programs.
# 	    (I checked out some scripts which did not need this change.)
# 	    Use testhome when referencing C executables.
# 	Transarc delta: jess-add-dumpkernel-in-low-tests 1.5
# 	  Selected comments:
# 	    Add function call (icl_DumpKernel) in the test suite. In case of running
# 	    error of C programmes in the test suite the "icl_DumpKernel" function
# 	    will be called in errex() to do the kernel trace. The dump file is located
# 	    in "/tmp/prog#.kernel.dump.pid". You have to have the debug flag set to
# 	    have the dump file.
# 	    See above.
# 	    Process another C file and add "low" as dump file header.
# 	    Turn on the prog3 debug flags.
# 	    It should not create the zero length dumpfile when there is nothing wrong.
# 	Transarc delta: jess-ot5320-fix-fs-low-testhome 1.1
# 	  Selected comments:
# 	    The fs and low test shell scripts have the following if statement
# 	    if [ "$TESTTOP" = "`pwd`" ]
# 	    then
# 	    UTIL_DIR=../util
# 	    testhome=$TESTTOP
# 	    else
# 	    UTIL_DIR=$TESTTOP/util
# 	    testhome=$TESTTOP/$testSuiteType
# 	    fi
# 	    The problem is that variable testSuiteType is not defined at this time.
# 	    See above.
# 	[1992/10/28  15:00:31  jaffe]
# 
# Revision 1.1.4.3  1992/09/25  17:31:45  jaffe
# 	Transarc delta: jess-ot5196-low-test-err-redirection 1.1
# 	  Selected comments:
# 	    Redirect stderr to stdout from running programs of low/tests
# 	    same
# 	[1992/09/24  12:53:26  jaffe]
# 
# Revision 1.1.4.2  1992/08/28  18:41:44  jaffe
# 	Transarc delta: rajesh-clean-low-tests 1.5
# 	  Selected comments:
# 	    To remove make and clean options from the low test suite. To change
# 	    the scripts to use common shell functions. To create a file
# 	    fs_functionsScript with the common shell functions in the util
# 	    directory.
# 	    To remove make and clean options. To change the scripts to use common
# 	    shell functions from util/fs_functionsScript instead of inline code.
# 	    Modify scripts to follow coding standards, simplify the code, increase
# 	    readability etc.
# 	    No changes yet
# 	    More of above.
# 	    Modify the tests to give them a simpler logical structure, modularity,
# 	    readability ( one command per line) and to change then to use the
# 	    common function created earlier.
# 	    See above.
# 	    Modification of rtest1 and rtest2 to use the utility functions
# 	    correctly.
# 	[1992/08/28  12:37:21  jaffe]
# 
# Revision 1.1.2.3  1992/05/29  23:01:02  mason
# 	Transarc delta: fred-3754-change-script-name 1.1
# 	  Selected comments:
# 	    To clean up a number of defects with the tests.  In addition to defect
# 	    3754, the changes also fix defects 3750 and 3748.
# 	    Fixed setting of TESTTOP variable.
# 	[1992/05/29  13:17:48  mason]
# 
# Revision 1.1.2.2  1992/05/21  12:51:37  jaffe
# 	Transarc delta: fred-merge-tests 1.1
# 	  Selected comments:
# 	    Created this delta to merge Phil Hirsch's final DFS test code changes with
# 	    the test code that the OSF had.  Hopefully, this means we and the OSF
# 	    should be looking at the same test code.
# 	    Changes to facilitate merge of local DFS test code with the OSF's.
# 	Transarc delta: fred-remove-sys 1.1
# 	  Selected comments:
# 	    To remove dependency on the AFS sys command in the test scripts.
# 	    To remove dependency on AFS sys command.
# 	Transarc delta: rajesh-low-tests-dfs-update 1.3
# 	  Selected comments:
# 	    To fix bugs and modify the low tests for DFS.
# 	    To provide a lag time from the command line to override the default.
# 	    Change compile flag DFS to TR_DFS for rprog2.c
# 	    DCE security API call fixes
# 
# 	$TALog: test9,v $
# 	Revision 4.23  1994/11/01  22:32:39  cfe
# 	Bring over the changes that the OSF made in going from their DCE 1.0.3
# 	release to their DCE 1.1 release.
# 	[from r4.22 by delta cfe-db6109-merge-1.0.3-to-1.1-diffs, r1.1]
# 
# 	[1992/05/20  21:05:29  jaffe]
# 
# $EndLog$
#
###############################################################################
#    Copyright (C) 1990, 1992 Transarc Corporation - All rights reserved      #
###############################################################################

# This script runs a C program which tests the utime(), utimes(), stat(),
# access(), chmod(), and fchmod() calls. Files are modified in a variety
# of ways, and the times reported by stat() are checked. The utime() routines
# are used to modify times, and stat() verifies this. The times should be within 
# In case of error the C program will dump the kernel data into
# a file "/tmp/prog#.kernel.dump.pid" if the debug flag is on.

# the specified lag time. Access modes are modified using chmod() and fchmod(), 
# and access() and stat() verify this.

# Usage is:   test9 [-np #-procs] [-nt #-times] [-lt #-seconds] 
# Default is  test9 -np 1 -nt 1 -lt 1

###############################################################################

#
# PrintUsage() -
#   Prints the usage message for this script.

PrintUsage()
{
    echo "$programName tests calls to utime, utimes, stat, access, chmod, fchmod"
    echo "Usage: $programName [-np #-procs] [-nt #-times] [-lt #-seconds ]"
}

#
# Initialise some variables. UTIL_DIR is the directory containing 
# the script fs_FunctionsScript with common functions.
#

TESTTOP=${TESTTOP:="`pwd`"}
if [ "$TESTTOP" = "`pwd`" ]
then
    UTIL_DIR=../util
    testhome=$TESTTOP
else
    UTIL_DIR=$TESTTOP/util
    testhome=$TESTTOP/low
fi

. $UTIL_DIR/fs_FunctionsScript

trap '
    cd $currentDir; 
    rm -rf $programName.*.out $programName.$$.*
    echo "$programName killed; returning $scriptErrorExit" | tee -a $logFile; 
    exit $scriptErrorExit
     ' 2 3 15

fs_InitSetup low

#
# Default option argument values
#

processCount=1; 
iterationCount=1; 
lagTime=1; 

#
# Parse the command line
#

while [ "$1" != "" ]
do 
    case $1 in 
        help|-help) PrintUsage;
                    exit $successExit;
                    ;;

        np|-np)     CheckOptionValue "np" $testSuiteType $programName $*;
                    processCount=$2;
                    shift; 
                    shift;
                    ;;

        nt|-nt)     CheckOptionValue "nt" $testSuiteType $programName $*;
                    iterationCount=$2;
                    shift; 
                    shift;
                    ;;

        lt|-lt)     CheckOptionValue "lt" $testSuiteType $programName $*;
                    lagTime=$2;
                    shift; 
                    shift;
                    ;;

        *)          echo "ERROR $testSuiteType/$programName: invalid argument \"$1\"" | tee -a $logFile; 
                    exit $scriptErrExit
                    ;;
    esac
done

#
# Validate arguments
#

if [ $processCount -lt 1 ]
then 
    echo "$programName: number of processes must be >= 1" | tee -a $logFile; 
    exit $scriptErrorExit
elif [ $iterationCount -lt 1 ]
then 
    echo "$programName: number of times must be >= 1" | tee -a $logFile; 
    exit $scriptErrorExit
elif [ $lagTime -lt 0 ]
then 
    echo "$programName: lag time must be >= 0 " | tee -a $logFile; 
    exit $scriptErrorExit
fi

###############################################################################

fs_CheckBinaryExistence $testhome/$cProgramName

#
# Start test
#

(
    echo "$programName (time/mode) starting in $currentDir"; 
    echo "Host `hostname` ($fs_sysName)"; 
    date
) | tee -a $logFile
echo "$processCount processes, parent process number $$, $iterationCount times, lag time $lagTime seconds" | tee -a $logFile
fs_DetermineFSType

processNum=1
while [ $processNum -le $processCount ]
do
    echo "$programName starting process number $processNum" | tee -a $logFile
    (
        mkdir $programName.$$.$processNum; 
        cd $programName.$$.$processNum; 
        $testhome/$cProgramName $iterationCount $lagTime > $currentDir/$programName.$processNum.out 2>&1; 
        result=$?
        if [ $result -ne 0 ]
        then 
            echo "- ERROR: $cProgramName process $processNum returned $result" >> $currentDir/$programName.$processNum.out
        fi
    ) &
    processNum=`expr $processNum + 1`
done

###############################################################################

echo ""; 
wait

processNum=1
while [ $processNum -le $processCount ]
do
    echo "" | tee -a $logFile
    cat $programName.$processNum.out | tee -a $logFile
    grep -s 'ERROR' $programName.$processNum.out 2> /dev/null
    if [ $? -ne 1 ]
    then
        echo "$programName process $processNum failed" | tee -a $logFile; 
        errorCount=1
    else 
        echo "$programName process $processNum results OK" | tee -a $logFile
    fi
    processNum=`expr $processNum + 1`
done

#
# Remove temporary file created by the test. (Previously done in -clean option)
#

(
    echo "$programName cleaning up" ; 
    date 
) | tee -a $logFile

rm -rf $programName.*.out $programName.$$.* $programName.[0-9]*.[0-9]*

(
    echo ""; 
    echo "$testSuiteType/$programName returning $errorCount in $currentDir"; 
    date
) | tee -a $logFile

exit $errorCount
