/*
 * @OSF_COPYRIGHT@
 * COPYRIGHT NOTICE
 * Copyright (c) 1994, 1996 Open Software Foundation, Inc.
 * ALL RIGHTS RESERVED (DCE).  See the file named COPYRIGHT.DCE in the
 * src directory for the full copyright text.
 */
/*
 * HISTORY
 * $Log: cds_old.idl,v $
 * Revision 1.1.4.2  1996/03/09  23:12:10  marty
 * 	Update OSF copyright year
 * 	[1996/03/09  22:29:22  marty]
 *
 * Revision 1.1.4.1  1995/12/08  15:34:55  root
 * 	Submit OSF/DCE 1.2.1
 * 	[1995/12/08  14:50:52  root]
 * 
 * Revision 1.1.2.1  1994/07/25  15:15:50  proulx
 * 	Provide interface id to match old CDS exported interface id
 * 	[1994/07/25  13:53:38  proulx]
 * 
 * $EndLog$
 */
[uuid(4ea31de8-9a94-11c9-bb60-08002b0f79aa), version(3.0)]
interface cds_old
{
void null_procedure ();
}




