/*
 * @OSF_COPYRIGHT@
 * COPYRIGHT NOTICE
 * Copyright (c) 1990, 1991, 1992, 1993, 1996 Open Software Foundation, Inc.
 * ALL RIGHTS RESERVED (DCE).  See the file named COPYRIGHT.DCE in the
 * src directory for the full copyright text.
 */
/*
 * HISTORY
 * $Log: cds_solicit.idl,v $
 * Revision 1.1.4.2  1996/03/09  23:12:12  marty
 * 	Update OSF copyright year
 * 	[1996/03/09  22:29:24  marty]
 *
 * Revision 1.1.4.1  1995/12/08  15:35:03  root
 * 	Submit OSF/DCE 1.2.1
 * 	[1995/12/08  14:50:55  root]
 * 
 * Revision 1.1.2.4  1993/01/20  20:52:43  jd
 * 	Backed out the fix for #6673. It broke the nightly build on the RIOS.
 * 	[1993/01/20  20:47:47  jd]
 * 
 * Revision 1.1.2.2  1992/12/30  14:26:13  zeliff
 * 	Embedding copyright notices
 * 	[1992/12/29  23:34:27  zeliff]
 * 
 * Revision 1.1  1992/01/19  15:24:37  devrcs
 * 	Initial revision
 * 
 * $EndLog$
 */
/*
*/
/*
 * COPYRIGHT (c) DIGITAL EQUIPMENT CORPORATION 1991. ALL RIGHTS RESERVED.
 *
 * THIS SOFTWARE IS FURNISHED UNDER A LICENSE AND MAY BE USED AND  COPIED
 * ONLY  IN  ACCORDANCE  WITH  THE  TERMS  OF  SUCH  LICENSE AND WITH THE
 * INCLUSION OF THE ABOVE COPYRIGHT NOTICE.  THIS SOFTWARE OR  ANY  OTHER
 * COPIES  THEREOF MAY NOT BE PROVIDED OR OTHERWISE MADE AVAILABLE TO ANY
 * OTHER PERSON.  NO TITLE TO AND OWNERSHIP OF  THE  SOFTWARE  IS  HEREBY
 * TRANSFERRED.
 *
 * THE INFORMATION IN THIS SOFTWARE IS SUBJECT TO CHANGE  WITHOUT  NOTICE
 * AND  SHOULD  NOT  BE  CONSTRUED  AS  A COMMITMENT BY DIGITAL EQUIPMENT
 * CORPORATION.
 *
 * DIGITAL ASSUMES NO RESPONSIBILITY FOR THE USE OR  RELIABILITY  OF  ITS
 * SOFTWARE ON EQUIPMENT THAT IS NOT SUPPLIED BY DIGITAL.
 */
[uuid(d5579459-8bca-11ca-b771-08002b1c8f1f), version(1.0)]
interface cds_solicit
{
import "cds_types.idl";

typedef [ref]cds_ReplicaPointer_t *cds_ReplicaPointerP_t;

typedef struct {
    unsigned short ch_length;
    [size_is(ch_length)] cds_ReplicaPointerP_t ch_members[];
} cds_CH_t;

typedef [ptr]cds_CH_t *cds_CHP_t;

[broadcast,maybe] void cds_Solicit(
    [in] handle_t h);

[broadcast,maybe] void cds_Advertise(
    [in] handle_t h,
    [in] cds_FullName_t *cellname_p,
    [in] uuid_t  cell_diruid,
    [in] cds_CH_t *nscle_p);

[idempotent] error_status_t cds_SolicitServer(
    [in] handle_t h,
    [out] cds_FullName_t *cellname_p,
    [out] uuid_t  *cell_diruid_p,
    [in,out,ptr] cds_CHP_t *nscle_p);

}
