/*
 * @OSF_COPYRIGHT@
 * COPYRIGHT NOTICE
 * Copyright (c) 1990, 1991, 1992, 1993, 1996 Open Software Foundation, Inc.
 * ALL RIGHTS RESERVED (DCE).  See the file named COPYRIGHT.DCE in the
 * src directory for the full copyright text.
 */
/*
 * HISTORY
 * $Log: cprpc_clerk.idl,v $
 * Revision 1.1.6.2  1996/03/09  23:12:17  marty
 * 	Update OSF copyright year
 * 	[1996/03/09  22:29:29  marty]
 *
 * Revision 1.1.6.1  1995/12/08  15:35:23  root
 * 	Submit OSF/DCE 1.2.1
 * 	[1995/12/08  14:51:02  root]
 * 
 * Revision 1.1.4.1  1994/02/02  20:31:50  rousseau
 * 	Changed reference of cprpc.idl to dce/cprpc.idl for CR 9864.
 * 	[1994/02/02  20:31:19  rousseau]
 * 
 * Revision 1.1.2.2  1992/12/30  14:26:38  zeliff
 * 	Embedding copyright notices
 * 	[1992/12/29  23:34:54  zeliff]
 * 
 * Revision 1.1  1992/01/19  15:24:49  devrcs
 * 	Initial revision
 * 
 * $EndLog$
 */
/*
*/
/*
** Module: cprpc_clerk.idl
**
** COPYRIGHT (c) DIGITAL EQUIPMENT CORPORATION 1991. ALL RIGHTS RESERVED.
**
** THIS SOFTWARE IS FURNISHED UNDER A LICENSE AND MAY BE USED AND  COPIED
** ONLY  IN  ACCORDANCE  WITH  THE  TERMS  OF  SUCH  LICENSE AND WITH THE
** INCLUSION OF THE ABOVE COPYRIGHT NOTICE.  THIS SOFTWARE OR  ANY  OTHER
** COPIES  THEREOF MAY NOT BE PROVIDED OR OTHERWISE MADE AVAILABLE TO ANY
** OTHER PERSON.  NO TITLE TO AND OWNERSHIP OF  THE  SOFTWARE  IS  HEREBY
** TRANSFERRED.
**
** THE INFORMATION IN THIS SOFTWARE IS SUBJECT TO CHANGE  WITHOUT  NOTICE
** AND  SHOULD  NOT  BE  CONSTRUED  AS  A COMMITMENT BY DIGITAL EQUIPMENT
** CORPORATION.
**
** DIGITAL ASSUMES NO RESPONSIBILITY FOR THE USE OR  RELIABILITY  OF  ITS
** SOFTWARE ON EQUIPMENT THAT IS NOT SUPPLIED BY DIGITAL.
**
**
** ABSTRACT:
**
** Interface Definition Language file for DNS Control Program Clerk
**
**
** MODIFICATION HISTORY:
**
** 05-apr-1991 mbs original version
** 12-apr-1991 mbs changes for SERVER CREATE CLEARINGHOUSE
** 02-may-1991 mbs double-indirection for clearinghouse info
** 09-may-1991 mbs fiddling with pointers
** 19-jul-1991 mbs change to unspecified endpoint
** 22-jul-1991 plk add no-op rpc for (temporary) authentication
** 23-aug-1991 mbs add nameserver information parameter
**
*/

[uuid(6c8620b9-c6d3-11ca-bb96-08002b1c8f1f),
 pointer_default(ptr),
 version(1.0)
]
interface DNScpClerk
{
    import "dce/cprpc.idl";
    error_status_t dnscp_clerk
    (
	[in]	 handle_t h,            /* rpc handle */
	[in]     long command,          /* Command: Show,set,add,remove...*/
	[in]     long caller_id,        /* caller's user id */
                                        /* clerk attributes list */
        [in,out,ptr] cprpc_attr_list_t *attr_list_p,
                                        /* ptr to ptr to clearinghouse list */
        [in,out,ptr] clh_info_list_p_t *clh_info_pp,
                                        /* ptr to ptr to nameserver list */
        [in,out,ptr] ns_info_list_p_t *ns_info_pp,
                                        /* returned command status */
	[out] command_status_t *command_status
    );
}

