/*
 * @OSF_COPYRIGHT@
 * COPYRIGHT NOTICE
 * Copyright (c) 1990, 1991, 1992, 1993, 1994, 1996 Open Software Foundation, Inc.
 * ALL RIGHTS RESERVED (DCE).  See the file named COPYRIGHT.DCE for
 * the full copyright text.
 *
 */
/*
 * HISTORY
 * $Log: cprpc_hcell.idl,v $
 * Revision 1.1.4.2  1996/03/09  23:12:19  marty
 * 	Update OSF copyright year
 * 	[1996/03/09  22:29:31  marty]
 *
 * Revision 1.1.4.1  1995/12/08  15:35:31  root
 * 	Submit OSF/DCE 1.2.1
 * 	[1995/12/08  14:51:05  root]
 * 
 * Revision 1.1.2.3  1994/07/12  19:36:11  zee
 * 	Modify import files to use dce/ prefix.
 * 	[1994/07/12  15:51:24  zee]
 * 
 * Revision 1.1.2.2  1994/06/09  18:44:25  devsrc
 * 	cr10871 - expand copyright
 * 	[1994/06/09  18:17:06  devsrc]
 * 
 * Revision 1.1.2.1  1994/03/22  20:00:44  griffin
 * 	HCell BL3 support: New Module
 * 	[1994/03/22  18:23:08  griffin]
 * 
 * $EndLog$
 */
/*
 * COPYRIGHT (c) DIGITAL EQUIPMENT CORPORATION 1994. ALL RIGHTS RESERVED.
 *
 * THIS SOFTWARE IS FURNISHED UNDER A LICENSE AND MAY BE USED AND  COPIED
 * ONLY  IN  ACCORDANCE  WITH  THE  TERMS  OF  SUCH  LICENSE AND WITH THE
 * INCLUSION OF THE ABOVE COPYRIGHT NOTICE.  THIS SOFTWARE OR  ANY  OTHER
 * COPIES  THEREOF MAY NOT BE PROVIDED OR OTHERWISE MADE AVAILABLE TO ANY
 * OTHER PERSON.  NO TITLE TO AND OWNERSHIP OF  THE  SOFTWARE  IS  HEREBY
 * TRANSFERRED.
 *
 * THE INFORMATION IN THIS SOFTWARE IS SUBJECT TO CHANGE  WITHOUT  NOTICE
 * AND  SHOULD  NOT  BE  CONSTRUED  AS  A COMMITMENT BY DIGITAL EQUIPMENT
 * CORPORATION.
 *
 * DIGITAL ASSUMES NO RESPONSIBILITY FOR THE USE OR  RELIABILITY  OF  ITS
 * SOFTWARE ON EQUIPMENT THAT IS NOT SUPPLIED BY DIGITAL.
 */
[uuid(87aabdc0-1b4c-11cd-a6be-08002b39950e), version(1.0)]

interface cprpc_hcell

{
import "dce/cds_types.idl";
import "dce/cprpc.idl";
import "dce/id_base.idl";

error_status_t cp_AddCellname(
    [in] handle_t h,
    [in] cds_FullName_t *cellname_p,
    [in] unsigned32 how,
    [in] uuid_t *chid_p,
    [out] command_status_t *cmd_status_p
    );

error_status_t cp_RemoveCellname(
    [in] handle_t h,
    [in] cds_FullName_t *cellname_p,
    [in] uuid_t *chid_p,
    [out] command_status_t *cmd_status_p
    );


}
