/*
 * @OSF_COPYRIGHT@
 * COPYRIGHT NOTICE
 * Copyright (c) 1990, 1991, 1992, 1993, 1996 Open Software Foundation, Inc.
 * ALL RIGHTS RESERVED (DCE).  See the file named COPYRIGHT.DCE in the
 * src directory for the full copyright text.
 */
/*
 * HISTORY
 * $Log: rgy_test.idl,v $
 * Revision 1.1.66.2  1996/03/11  02:48:36  marty
 * 	Update OSF copyright years
 * 	[1996/03/10  20:09:23  marty]
 *
 * Revision 1.1.66.1  1995/12/11  22:46:54  root
 * 	Submit OSF/DCE 1.2.1
 * 	[1995/12/11  22:22:14  root]
 * 
 * Revision 1.1.64.1  1993/09/09  19:56:18  cmckeen
 * 	 HP's TET'ized version
 * 	[1993/09/09  19:51:06  cmckeen]
 * 
 * Revision 1.1.5.2  1993/07/02  16:36:40  eheller
 * 	GAMMERA version which runs under TET.
 * 	[1993/07/02  16:16:31  eheller]
 * 
 * Revision 1.1.3.2  1993/05/04  20:41:31  sekhar
 * 	1. Removed unused parameters from add_acct() call.
 * 	2. Removed [ref] attribute on name_t (this was causing
 * 	   the server to segfault on hp-ux) .
 * 	3. redefined types to reflect the correct sizes.
 * 	[1993/05/04  19:11:29  sekhar]
 * 
 * 	Removed the bye_server operation
 * 	[1993/03/11  00:11:19  eperkins]
 * 
 * 	Embedded copyright notice
 * 	[1993/02/05  14:46:54  cjd]
 * 
 * 	Initial version 1.0.2 sec.rgy.7 system test
 * 	[1993/01/04  18:35:24  eperkins]
 * 
 * Revision 1.1.1.4  1993/04/21  20:28:23  root
 * 	    Loading drop DCE1_0_2B23
 * 
 * Revision 1.1.3.2  1993/02/04  22:17:56  cjd
 * 	Embedded copyright notice
 * 
 * $EndLog$
 */
[
    uuid(40e75346-1000-0000-0d00-00c366000000),
    version(1)
]


interface rgy_test {

   import "dce/rsbase.idl";

   const unsigned32 MAX_MSG_SIZE  = 81;
   const unsigned32 MAX_CDS_NAME  = 1024;
   const unsigned32 MAX_PASSWD    = 512;
	
   typedef [string] char name_t [MAX_CDS_NAME];
   typedef [string] char line_t [MAX_MSG_SIZE];
   typedef [string] char pwname_t [MAX_PASSWD];
   typedef pipe char pipe_of_chars;

    error_status_t rgy_test_login (
		[in]	handle_t	handle,	
		[in]	    name_t	name,
		[in]	    pwname_t	pw,
		[in]	    long	id,
		[in]	    long	expire,
		[in]	    long	item,
		[in]        long	valcertflag,		
	    [in, out]	line_t		msg,
    	    [in, out]   error_status_t  *tstatus
    );

    void override_snd (
		[in]	handle_t	h,
		[in]	pipe_of_chars	in_pipe, 
	   [in, out]	line_t		msg
    );

    error_status_t  get_pwent(
		[in] 	handle_t	handle,
		[in]	name_t		name,
		[in]	pwname_t	pw,
	    [in, out]  	line_t		msg,
    	    [in, out]   error_status_t  *tstatus
    );

    error_status_t  add_acct(
		[in] 		handle_t		handle,
		[in]		name_t			name,
		[in]		pwname_t		pw,
		[in]		long			number,
		[in, out]	line_t			msg,
	    	[in, out]	error_status_t		*tstatus
    );
    
    error_status_t del_acct (
                [in]            handle_t                handle,
                [in]            name_t                  name,
		[in]		long			number,
            [in, out]           line_t                  msg,
            [in, out]           error_status_t          *tstatus
    );
}






