/*
 * @OSF_COPYRIGHT@
 * COPYRIGHT NOTICE
 * Copyright (c) 1990, 1991, 1992, 1993 Open Software Foundation, Inc.
 * ALL RIGHTS RESERVED (DCE).  See the file named COPYRIGHT.DCE in the
 * src directory for the full copyright text.
 */
/*
 * HISTORY
 * $Log: utst_proc.idl,v $
 * Revision 1.1.316.1  1996/10/17  18:37:18  damon
 * 	Submitting on behalf of Transarc
 * 	[1996/10/17  16:58:17  damon]
 *
 * Revision 1.1.311.1  1994/02/04  20:47:53  devsrc
 * 	Merged from 1.0.3a to 1.1
 * 	[1994/02/04  15:25:47  devsrc]
 * 
 * Revision 1.1.309.1  1993/12/07  17:46:48  jaffe
 * 	1.0.3a update from Transarc
 * 	[1993/12/03  19:43:30  jaffe]
 * 
 * 	embedded copyright notice
 * 	[1993/01/20  14:51:05  cjd]
 * 
 * 	Change include file install directory from .../afs to .../dcedfs.
 * 	[1992/11/22  19:12:38  bolinger]
 * 
 * 	Sync with Transarc, replace missing RCS ids
 * 	[1992/08/31  15:25:32  jaffe]
 * 
 * 	Transarc delta: cfe-ot4029-portable-rpc-data-types 1.2
 * 	  Selected comments:
 * 	    If ``long'' could possibly mean ``64 bits'' any time soon, we need to keep
 * 	    our RPC interfaces from breaking.
 * 	    see above
 * 	    More of the same.  Forgot a couple of .idl files, and needed to change
 * 	    a couple of procedure signatures to match.
 * 	[1992/08/30  03:07:11  jaffe]
 * 
 * Revision 1.1  1992/01/19  02:48:05  devrcs
 * 	Initial revision
 * 
 * $EndLog$
 */
/*
*/
/*
 * Copyright (C) 1991 Transarc Corporation
 * All rights reserved.
 */

/* $Header: /u0/rcs_trees/dce/rcs/test/file/ubik/utst_proc.idl,v 1.1.316.1 1996/10/17 18:37:18 damon Exp $ */
[
uuid(4d37f2dd-ed43-0001-02c0-37cf1e000000),
version(4.0)
/*provider_version(1)*/
]

interface SAMPLE
{

import "dcedfs/common_data.idl";


const long UTST_MAXNAMELEN = 255;

typedef [string] char sampleName_t[UTST_MAXNAMELEN];

/*
 * provider_version(1)
 */
error_status_t  SAMPLE_Inc (
	[in]	handle_t	h
);

/*
 * provider_version(1)
 */
error_status_t SAMPLE_Get (
	[in]	handle_t	h,
	[out]	signed32 *		result
);

/*
 * provider_version(1)
 */
error_status_t SAMPLE_Trun (
	[in]	handle_t	h
);

/*
 * provider_version(1)
 */
error_status_t SAMPLE_Test (
	[in]	handle_t	h
);

/*
 * provider_version(1)
 */
error_status_t SAMPLE_QGet (
	[in]	handle_t	h,
	[out]	signed32 *		result
);

/*
 * provider_version(1)
 */
error_status_t SAMPLE_GetServerInterfaces (
	[in] handle_t h,
	[in, out] dfs_interfaceList *serverInterfacesP
);

}
