/*
 * @OSF_COPYRIGHT@
 * COPYRIGHT NOTICE
 * Copyright (c) 1990, 1991, 1992, 1993, 1996 Open Software Foundation, Inc.
 * ALL RIGHTS RESERVED (DCE).  See the file named COPYRIGHT.DCE in the
 * src directory for the full copyright text.
 */
/*
 * HISTORY
 * $Log: stringy.idl,v $
 * Revision 1.1.4.2  1996/03/11  02:19:03  marty
 * 	Update OSF copyright years
 * 	[1996/03/10  19:55:51  marty]
 *
 * Revision 1.1.4.1  1995/12/11  19:30:36  root
 * 	Submit OSF/DCE 1.2.1
 * 	[1995/12/11  19:16:10  root]
 * 
 * Revision 1.1.2.2  1993/01/07  23:39:14  bbelch
 * 	Embedding copyright notice
 * 	[1993/01/06  13:45:43  bbelch]
 * 
 * Revision 1.1  1992/01/19  03:28:41  devrcs
 * 	Initial revision
 * 
 * $EndLog$
 */
/*
*/
[uuid(02d262af-ffc4-11c8-8ae4-08002b104860), version(0)]
interface stringy
{
    void op0([in] handle_t h, [in, out, string] char *p);
    void op1([in] handle_t h, [in, out, string, size_is(s)] char *p,
             [in] long s);
    void op2([in] handle_t h, [in, out, ptr, string] char *p);
    void op3([in] handle_t h, [in, out, ptr, string, size_is(s)] char *p,
             [in] long s);
    void op4([in] handle_t h, [in, out, string, ptr] char a[]);
    void op5([in] handle_t h, [in, out, string, ptr, size_is(s)] char a[],
             [in] long s);
}
