# 
# @OSF_COPYRIGHT@
# COPYRIGHT NOTICE
# Copyright (c) 1990, 1991, 1992, 1993, 1994, 1996 Open Software Foundation, Inc.
# ALL RIGHTS RESERVED (DCE).  See the file named COPYRIGHT.DCE for
# the full copyright text.
# 
# 
# HISTORY
# $Log: Makefile,v $
# Revision 1.1.6.4  1996/11/14  16:10:45  arvind
# 	OSF DCE 1.2.2 Drop 5
# 	[1996/11/14  14:26:31  arvind]
#
# Revision /main/DCE_1.2.2/8  1996/11/05  22:16 UTC  arvind
# 	Merge out from DCE_1.2.2
# 	[1996/11/03  23:54 UTC  arvind  /main/DCE_1.2.2/arvind_pkss/2]
# 
# 	Correction to PKSS tests
# 	[1996/09/11  14:25 UTC  arvind  /main/DCE_1.2.2/arvind_pkss/1]
# 
# 	Add DATA_SUBDIRS.
# 	[1996/08/05  20:59 UTC  psn  /main/DCE_1.2.2/psn_bugfix/1]
# 	#
# 	Merge to DCE 1.2.2 main line.
# 	[1996/05/30  21:30 UTC  psn  /main/DCE_1.2.2/psn_fix122/1]
# 	#
# 	Add directory for krb5 tests.
# 	[1996/01/03  20:17 UTC  psn  /main/DCE_1.2/1]
# 	#
# 
# 	Merge to DCE 1.2.2 main line.
# 	[1996/05/30  21:30 UTC  psn  /main/DCE_1.2.2/psn_fix122/1]
# 
# 	merge from mb_u2u
# 	[1996/05/09  19:38 UTC  burati  /main/DCE_1.2/2]
# 
# 	Add u2u
# 	[1996/05/09  19:37 UTC  burati  /main/DCE_1.2/mb_u2u/1]
# 
# 	Add directory for krb5 tests.
# 	[1996/01/03  20:17 UTC  psn  /main/DCE_1.2/1]
# 
# 	merge back building of grp_override test
# 	[1995/10/05  20:47 UTC  bartf  /main/HPDCE02/4]
# 
# 	add grp_override back
# 	[1995/10/04  16:36 UTC  bartf  /main/HPDCE02/bartf_sec_wc.10/1]
# 
# 	add server to subdirs
# 	[1995/05/10  14:43 UTC  mothra  /main/HPDCE02/3]
# 
# 	m
# 	[1995/02/03  19:26 UTC  mdf  /main/HPDCE02/2]
# 
# 	Forget this grp_override stuff for now.
# 	[1995/02/03  19:23 UTC  mdf  /main/HPDCE02/mdf_MOTHRA_5/1]
# 
# 	Corrected the locations of the gssAPI tests.
# 	[1995/01/20  13:34 UTC  mdf  /main/HPDCE02/1]
# 
# 	[1995/01/19  18:44 UTC  mdf  /main/mdf_MOTHRA_1/1]
# 
# 	Update OSF copyright years
# 	[1996/03/10  19:50:32  marty]
# 
# 	Submit OSF/DCE 1.2.1
# 	[1995/12/11  19:26:44  root]
# 
# 	Submit OSF/DCE 1.2.1
# 	[1995/12/11  18:18:10  root]
# 
# Revision /main/DCE_1.2.2/7  1996/11/04  22:37 UTC  arvind
# 	Don't build CAPI for HP/UX
# 	[1996/10/18  15:38 UTC  arvind  /main/DCE_1.2.2/arvind_work/1]
# 
# Revision /main/DCE_1.2.2/arvind_work/4  1996/10/31  19:48 UTC  arvind
# 	Don't build CAPI tests for intl build
# 
# Revision /main/DCE_1.2.2/arvind_work/1  1996/10/18  15:38 UTC  arvind
# 	Don't build CAPI for HP/UX
# 
# Revision /main/DCE_1.2.2/5  1996/10/18  00:44 UTC  arvind
# 	Add capi to DATA_SUBDIRS.
# 	[1996/10/17  19:07 UTC  jrr  /main/DCE_1.2.2/arvind_capi/2]
# 
# 	CAPI drop from DEC
# 	[1996/10/17  00:52 UTC  arvind  /main/DCE_1.2.2/arvind_capi/1]
# 
# 	Add DATA_SUBDIRS.
# 	[1996/08/05  20:59 UTC  psn  /main/DCE_1.2.2/psn_bugfix/1]
# 	#
# 	Merge to DCE 1.2.2 main line.
# 	[1996/05/30  21:30 UTC  psn  /main/DCE_1.2.2/psn_fix122/1]
# 	#
# 	Add directory for krb5 tests.
# 	[1996/01/03  20:17 UTC  psn  /main/DCE_1.2/1]
# 	#
# 
# 	Merge to DCE 1.2.2 main line.
# 	[1996/05/30  21:30 UTC  psn  /main/DCE_1.2.2/psn_fix122/1]
# 
# 	merge from mb_u2u
# 	[1996/05/09  19:38 UTC  burati  /main/DCE_1.2/2]
# 
# 	Add u2u
# 	[1996/05/09  19:37 UTC  burati  /main/DCE_1.2/mb_u2u/1]
# 
# 	Add directory for krb5 tests.
# 	[1996/01/03  20:17 UTC  psn  /main/DCE_1.2/1]
# 
# 	merge back building of grp_override test
# 	[1995/10/05  20:47 UTC  bartf  /main/HPDCE02/4]
# 
# 	add grp_override back
# 	[1995/10/04  16:36 UTC  bartf  /main/HPDCE02/bartf_sec_wc.10/1]
# 
# 	add server to subdirs
# 	[1995/05/10  14:43 UTC  mothra  /main/HPDCE02/3]
# 
# 	m
# 	[1995/02/03  19:26 UTC  mdf  /main/HPDCE02/2]
# 
# 	Forget this grp_override stuff for now.
# 	[1995/02/03  19:23 UTC  mdf  /main/HPDCE02/mdf_MOTHRA_5/1]
# 
# 	Corrected the locations of the GSSAPI tests.
# 	[1995/01/20  13:34 UTC  mdf  /main/HPDCE02/1]
# 
# 	[1995/01/19  18:44 UTC  mdf  /main/mdf_MOTHRA_1/1]
# 
# 	Update OSF copyright years
# 	[1996/03/10  19:50:32  marty]
# 
# 	Submit OSF/DCE 1.2.1
# 	[1995/12/11  19:26:44  root]
# 
# 	Submit OSF/DCE 1.2.1
# 	[1995/12/11  18:18:10  root]
# 
# Revision /main/DCE_1.2.2/4  1996/10/09  20:47 UTC  psn
# 	Submit GG tests.
# 	[1996/10/09  18:38 UTC  psn  /main/DCE_1.2.2/psn_gg/1]
# 
# Revision /main/DCE_1.2.2/3  1996/08/06  17:35 UTC  psn
# 	Add DATA_SUBDIRS.
# 	[1996/08/05  20:59 UTC  psn  /main/DCE_1.2.2/psn_bugfix/1]
# 
# Revision /main/DCE_1.2.2/2  1996/05/30  21:32 UTC  psn
# 	Merge to DCE 1.2.2 main line.
# 
# Revision /main/DCE_1.2.2/psn_fix122/1  1996/05/30  21:30 UTC  psn
# 	merge from mb_u2u
# 	[1996/05/09  19:38 UTC  burati  /main/DCE_1.2/2]
# 
# 	Add u2u
# 	[1996/05/09  19:37 UTC  burati  /main/DCE_1.2/mb_u2u/1]
# 
# 	Update OSF copyright years
# 	[1996/03/10  19:50:32  marty]
# 	#
# 
# 	Submit OSF/DCE 1.2.1
# 	[1995/12/11  19:26:44  root]
# 
# 	Submit OSF/DCE 1.2.1
# 	[1995/12/11  18:18:10  root]
# 
# Revision /main/DCE_1.2/psn_k5_test/1  1996/05/08  21:33 UTC  psn
# 	Add directory for krb5 tests.
# 
# Revision /main/DCE_1.2/1  1996/01/03  20:17 UTC  psn
# 	merge back building of grp_override test
# 	[1995/10/05  20:47 UTC  bartf  /main/HPDCE02/4]
# 
# 	add grp_override back
# 	[1995/10/04  16:36 UTC  bartf  /main/HPDCE02/bartf_sec_wc.10/1]
# 
# 	add server to subdirs
# 	[1995/05/10  14:43 UTC  mothra  /main/HPDCE02/3]
# 
# 	m
# 	[1995/02/03  19:26 UTC  mdf  /main/HPDCE02/2]
# 
# 	Forget this grp_override stuff for now.
# 	[1995/02/03  19:23 UTC  mdf  /main/HPDCE02/mdf_MOTHRA_5/1]
# 
# 	Corrected the locations of the GSSAPI tests.
# 	[1995/01/20  13:34 UTC  mdf  /main/HPDCE02/1]
# 
# 	[1995/01/19  18:44 UTC  mdf  /main/mdf_MOTHRA_1/1]
# 
# Revision 1.1.2.2  1994/10/06  20:31:54  agd
# 	expand copyright
# 	[1994/10/06  14:28:44  agd]
# 
# Revision 1.1.2.1  1994/08/04  16:15:18  mdf
# 	Initial checkin
# 	[1994/08/03  19:21:23  mdf]
# 
# $EndLog$
# 

.if ${TARGET_MACHINE}=="HP800" || !defined(USE_DES)
SUBDIRS	= client gssapi server grp_override u2u krb5 globalgroup_suite
DATA_SUBDIRS = krb5 globalgroup_suite
.else
SUBDIRS = capi client gssapi server grp_override u2u krb5 globalgroup_suite pkss
DATA_SUBDIRS = capi krb5 globalgroup_suite
.endif
.include <${RULES_MK}>

