#
# @OSF_COPYRIGHT@
# COPYRIGHT NOTICE
# Copyright (c) 1990, 1991, 1992, 1993, 1996 Open Software Foundation, Inc.
# ALL RIGHTS RESERVED (DCE).  See the file named COPYRIGHT.DCE in the
# src directory for the full copyright text.
#
#
# HISTORY
# $Log: Makefile,v $
# Revision 1.1.20.1  1996/06/04  22:13:35  arvind
# 	Loading drop DCE1_0_2B18
# 	[1993/03/11  22:12:07  osfrcs  1.1.1.7]
#
# 	Loading drop Dce1_0_1fnl
# 	[1992/09/21  18:34:39  osfrcs  1.1.1.6]
#
# 	Merge OSF endgame to HP.
# 	[1996/02/28  23:39 UTC  psn  /main/DCE_1.2/psn_1.2_endgame/1]
#
# 	Fix OT13364 as was done during OSF 1.2.1 Endgame.
# 	[1996/01/03  20:01 UTC  psn  /main/DCE_1.2/1]
#
# 	Merge from Hpdce02_01
# 	[1994/08/23  13:11 UTC  bissen  /main/HPDCE02/2]
#
# 	Merge hpdce02 (DCE 1.1 beta) and HPDCE01 into HPDCE02
# 	[1994/06/29  14:35 UTC  bissen  /main/HPDCE02/1]
#
# 	[1994/04/12  17:20 UTC  truitt  /main/HPDCE01/3]
#
# 	install new systest tet files
# 	[1994/04/12  17:13 UTC  truitt  /main/HPDCE01/truitt_junk/2]
#
# 	Update to latest version of tet tests
# 	[1994/04/05  13:31 UTC  truitt  /main/HPDCE01/truitt_junk/1]
#
# 	merge kk and hpdce01
# 	[1994/02/01  19:36  bissen  /main/HPDCE01/1]
#
# 	Loading drop DCE1_0_2B18
# 	[1993/03/11  22:12:07  osfrcs  1.1.1.7]
#
# 	Loading drop Dce1_0_1fnl
# 	[1992/09/21  18:34:39  osfrcs  1.1.1.6]
#
# 	Add dced directory entry.
# 	[1994/05/26  20:09:06  fadden]
#
# 	Added an entry for the I18N directory.
# 	[1994/05/23  20:45:05  dassarma]
#
# 	added serviceability subdir
# 	[1994/05/13  20:15:10  hester]
#
# 	Add audit directory
# 	[1994/03/18  14:40:35  bhaim]
#
# 	SVR4 porting changes - 8596
# 	[1993/10/15  16:35:00  ohara]
#
# 	Embedded copyright notice
# 	[1993/01/22  15:32:33  pellis  1.1.5.6]
#
# 	Made many changes to prepare for moving unsupported files to the
# 	./src/nosupport/test/systest directory.
# 	[1993/01/21  22:15:30  pellis]
#
# 	Split 'OTHERS' into SUPPORTED_101 and UNSUPPORTED_101 lists.
# 	Change ILIST to take only SUPPORTED_101 and NEW_102 to the install
# 	tree.
# 	[1993/01/07  18:53:20  ramb]
#
# 	Initial version of CDS and SEC system administration scripts/checklists.
# 	[1992/12/26  21:31:04  pellis]
#
# 	Added OTHERS to include script files to move to install tree and
# 	set ILIST to include ${OTHERS}
# 	[1992/10/27  20:09:10  root]
#
# 	Added security to SUBDIRS
# 	[1992/05/14  19:04:24  kenny]
#
# 	Add test directories
# 	[1992/03/18  00:57:52  rps]
#
# 	Initial version
# 	[1992/02/13  17:38:32  eperkins]
#
# Revision 1.1.18.3  1996/03/11  02:36:36  marty
# 	Update OSF copyright years
# 	[1996/03/10  20:04:31  marty]
# 
# Revision 1.1.18.2  1996/02/23  20:31:20  root
# 	ENDGAME: Install dcetest_config profile.dcest.tet
# 	[1996/02/23  20:28:56  root]
# 
# Revision 1.1.18.1  1995/12/11  21:53:06  root
# 	Submit OSF/DCE 1.2.1
# 
# 	HP revision /main/HPDCE02/2  1994/08/23  13:11 UTC  bissen
# 	Merge from Hpdce02_01
# 	[1995/12/11  20:54:22  root]
# 
# Revision 1.1.14.6  1994/06/24  19:19:50  fadden
# 	Restore dced subdir.
# 	[1994/06/24  18:34:56  fadden]
# 
# 	HP revision /main/HPDCE02/1  1994/06/29  14:35 UTC  bissen
# 	Merge hpdce02 (DCE 1.1 beta) and HPDCE01 into HPDCE02
# 
# Revision 1.1.14.5  1994/05/31  21:17:14  pellis
# 	Removed dced subdir, it's not ready to be built.
# 	[1994/05/31  21:15:27  pellis]
# 
# 	HP revision /main/HPDCE01/3  1994/04/12  17:20 UTC  truitt
# 
# 	HP revision /main/HPDCE01/truitt_junk/2  1994/04/12  17:13 UTC  truitt
# 	install new systest tet files
# 
# 	HP revision /main/HPDCE01/truitt_junk/1  1994/04/05  13:31 UTC  truitt
# 	Update to latest version of tet tests
# 
# 	HP revision /main/HPDCE01/1  1994/02/01  19:36  bissen
# 	merge kk and hpdce01
# 
# Revision 1.1.9.3  1993/08/27  20:58:24  giza
# 	fixed IDIRs for TET
# 	[1993/08/27  20:53:20  giza]
# 	Revision 1.1.12.4  1993/09/28  14:45:56  pellis
# 	Added file and admin to SUBDIRS.
# 	[1993/09/28  14:45:42  pellis]
# 
# Revision 1.1.12.3  1993/09/17  13:42:44  qbarry
# 	Took out RUN_LOOPS.KSH as it should be in a different directory.
# 	[1993/09/13  20:42:26  qbarry]
# 
# 	Took out RUN_LOOPS.KSH as it should be in a different directory.
# 
# Revision 1.1.12.2  1993/09/10  13:12:36  cmckeen
# 	 Added directory to SUBDIRS line
# 	[1993/09/10  13:12:21  cmckeen]
# 
# Revision 1.1.12.1  1993/09/09  21:11:21  qbarry
# 	Modified this file to install the new file RUN_LOOP.KSH.
# 	[1993/09/08  20:24:17  qbarry]
# 
# Revision 1.1.10.3  1993/08/02  17:31:43  cmckeen
# 	 Changes made to reflect the new install tree
# 	[1993/08/02  17:16:50  cmckeen]
# 
# Revision 1.1.10.2  1993/07/28  19:31:39  cmckeen
# 	HP's TET'ized version of the system tests
# 	[1993/07/28  17:13:07  cmckeen]
# 
# Revision 1.1.5.7  1993/02/05  15:16:09  cjd
# 	Embedded copyright notice
# 	[1993/02/05  14:34:34  cjd]
# 
# Revision 1.1.9.2  1993/07/09  10:50:11  root
# 	Initial King Kong branch
# 	[1993/07/09  10:49:44  root]
# 
# Revision 1.1.7.4  1993/04/23  16:32:52  sekhar
# 	Merged Hp_dce1_0_1 changes
# 	[1993/04/16  14:59:00  sekhar]
# 
# Revision 1.1.7.3  1993/03/31  14:58:29  truitt
# 	Removed dcetmall test from list.
# 	[1993/03/31  14:58:12  truitt]
# 
# Revision 1.1.7.2  1993/03/30  18:50:27  mgm
# 	Merged Hp_dce1_0_1 with DCE1_0_2
# 	[1993/03/30  18:49:43  mgm]
# 
# Revision 1.1.1.7  1993/03/11  22:12:07  osfrcs
# 	    Loading drop DCE1_0_2B18
# 	Revision 1.1.5.2  1992/11/17  14:00:24  mgm
# 	DCE 1.0.1 Release
# 	[1992/11/17  13:59:28  mgm]
# 
# Revision 1.1.1.6  1992/09/21  18:34:39  osfrcs
# 	    Loading drop Dce1_0_1fnl
# 
# $EndLog$

EXPINC_SUBDIRS = tools dced
DATA_SUBDIRS = tools 
EXPLIB_SUBDIRS = tools dced
.ifdef NO_DFS
SUBDIRS = tools directory rpc threads time security audit admin svc I18N dced
.else
SUBDIRS = tools directory file rpc threads time security audit admin svc \
	  I18N dced
.endif

PROGRAMS =

.if ${TARGET_MACHINE} != "HP800"
OTHERS1 = profile.dcest.tet dcetest_config
.endif

OTHERS = profile.dcest ${OTHERS1}

SCRIPTS = tet_scen tet_code tetbuild.cfg tetclean.cfg tetexec.cfg

tet_scen_IDIR     = /tet/systest/
tet_code_IDIR     = /tet/systest/
tetbuild.cfg_IDIR = /tet/systest/
tetclean.cfg_IDIR = /tet/systest/
tetexec.cfg_IDIR  = /tet/systest/

ILIST	= ${PROGRAMS} ${OTHERS}

.include <${RULES_MK}>
