/*
 * @OSF_COPYRIGHT@
 * COPYRIGHT NOTICE
 * Copyright (c) 1996 Open Software Foundation, Inc.
 * ALL RIGHTS RESERVED (DCE).  See the file named COPYRIGHT.DCE for
 * the full copyright text.
 * 
 */
/*
 * HISTORY
 * $Log: account.idl,v $
 * Revision 1.1.2.2  1996/03/09  20:50:13  marty
 * 	Add OSF copyright
 * 	[1996/03/09  20:28:23  marty]
 *
 * Revision 1.1.2.1  1995/12/11  19:36:10  root
 * 	Submit OSF/DCE 1.2.1
 * 	[1995/12/11  19:18:58  root]
 * 
 * $EndLog$
 */
[
uuid(6c44dd20-2741-11ce-8a41-08002b3d8412)
] interface Account
{
	import "checking.idl";

	static double balanceFromServer(
		[in] handle_t bh,
		[in] Account *a
	);

	static double checkBalFromServer(
		[in] handle_t bh,
		[in] Checking *c
	);

	double getAccountBalance();
}
