/*
 * @OSF_COPYRIGHT@
 * COPYRIGHT NOTICE
 * Copyright (c) 1996 Open Software Foundation, Inc.
 * ALL RIGHTS RESERVED (DCE).  See the file named COPYRIGHT.DCE for
 * the full copyright text.
 * 
 */
/*
 * HISTORY
 * $Log: savings.idl,v $
 * Revision 1.1.2.2  1996/03/09  20:50:19  marty
 * 	Add OSF copyright
 * 	[1996/03/09  20:28:27  marty]
 *
 * Revision 1.1.2.1  1995/12/11  19:36:17  root
 * 	Submit OSF/DCE 1.2.1
 * 	[1995/12/11  19:19:03  root]
 * 
 * $EndLog$
 */
[
    uuid(7a73d900-2741-11ce-ae86-08002b3d8412)
]   interface Savings : Account
{
        import "account.idl";

	double getSavingsBalance();

	static Savings * openNOW(
		[in] handle_t bh,
		[in] double amt
	);

	static Savings * openOld(
		[in] handle_t bh,
		[in] double amt
	);

	void   setRate(
		[in] double rate
	);

	void   update();
}
