# @OSF_COPYRIGHT@
# COPYRIGHT NOTICE
# Copyright (c) 1990, 1991, 1992, 1993, 1994, 1996 Open Software Foundation, Inc.
# ALL RIGHTS RESERVED (DCE).  See the file named COPYRIGHT.DCE for
# the full copyright text.
# 
# HISTORY
# $Log: Makefile,v $
# Revision 1.1.4.2  1996/03/11  02:17:23  marty
# 	Update copyright years
# 	[1996/03/10  20:01:57  marty]
#
# Revision 1.1.4.1  1995/12/11  18:01:14  root
# 	Submit OSF/DCE 1.2.1
# 	[1995/12/11  17:43:18  root]
# 
# Revision 1.1.2.3  1994/07/06  15:12:51  marrek
# 	July 1994 code drop.
# 	[1994/07/06  12:04:35  marrek]
# 
# Revision 1.1.2.2  1994/06/10  20:26:40  devsrc
# 	cr10872 - fixed copyright
# 	[1994/06/10  17:01:46  devsrc]
# 
# Revision 1.1.2.1  1994/05/10  15:00:07  marrek
# 	Created in April 1994 submission.
# 	[1994/05/03  12:19:08  marrek]
# 
# $EndLog$
#
# $RCSfile: Makefile,v $ $Revision: 1.1.4.2 $ $Date: 1996/03/11 02:17:23 $
#

IDIR    = /test/tet/functional/directory/xds/ts/xoms/
IMODE           = 755

ILIST           = 	xoms_mt xoms_st

SUBDIRS		=	lib

.include <${RULES_MK}>

