#!/bin/ksh
#
# @OSF_COPYRIGHT@
# COPYRIGHT NOTICE
# Copyright (c) 1990, 1991, 1992, 1993, 1994, 1996 Open Software Foundation, Inc.
# ALL RIGHTS RESERVED (DCE).  See the file named COPYRIGHT.DCE for
# the full copyright text.
# 
# HISTORY
# $Log: xoms_mt,v $
# Revision 1.1.4.2  1996/03/11  02:05:40  marty
# 	Update OSF copyright years
# 	[1996/03/10  19:49:53  marty]
#
# Revision 1.1.4.1  1995/12/11  19:47:36  root
# 	Submit OSF/DCE 1.2.1
# 	[1995/12/11  19:25:05  root]
# 
# 	Submit OSF/DCE 1.2.1
# 	[1995/12/11  18:16:19  root]
# 
# Revision 1.1.2.9  1994/08/17  11:51:50  marrek
# 	Use uname -n .
# 	[1994/08/17  07:37:29  marrek]
# 
# Revision 1.1.2.8  1994/08/01  12:27:29  marrek
# 	Fixes for OT 10742, 11357, 11432.
# 	[1994/08/01  12:26:26  marrek]
# 
# Revision 1.1.2.7  1994/07/15  16:58:27  keutel
# 	OT 11316: unsetting of XDS_LOG and D2_LOG removed
# 	[1994/07/15  15:29:58  keutel]
# 
# Revision 1.1.2.6  1994/07/06  15:55:34  marrek
# 	Add version string in July 1994 code drop.
# 	[1994/07/06  15:44:58  marrek]
# 
# Revision 1.1.2.5  1994/06/21  14:29:59  marrek
# 	June 1994 code submission.
# 	[1994/06/16  07:51:28  marrek]
# 
# Revision 1.1.2.4  1994/06/10  20:42:28  devsrc
# 	cr10872 - fixed copyright
# 	[1994/06/10  17:14:50  devsrc]
# 
# Revision 1.1.2.3  1994/05/23  17:42:32  zeliff
# 	ot10728: remove extraneous cleanup operations
# 	ot10705: fix tet lock problem
# 	[1994/05/23  15:57:20  zeliff]
# 
# Revision 1.1.2.2  1994/05/18  22:10:47  zeliff
# 	Misc. fixes
# 	[1994/05/18  21:57:20  zeliff]
# 
# 	ot10647: added prefixs for script invocations
# 	[1994/05/15  21:03:20  zeliff]
# 
# Revision 1.1.2.1  1994/05/10  15:09:56  marrek
# 	Add shell interpreter in first line.
# 	[1994/05/09  09:13:45  marrek]
# 
# 	Created in April 1994 submission.
# 	[1994/05/03  12:19:19  marrek]
# 
# $EndLog$
#
# $RCSfile: xoms_mt,v $ $Revision: 1.1.4.2 $ $Date: 1996/03/11 02:05:40 $
#
#  (c) Copyright 1991-1994 Siemens-Nixdorf Information Systems
#  Munich, Germany
#  All Rights Reserved
#
# xoms_mt
# NAME xoms_mt
#
# DESC
# {
# GDS XOM/Convenience Tests (multi threaded mode)
# Each invocable component runs the 'xt_test -t' executable using as standard
# input the batch file specified in each strategy statement.
# Also, the DIT must already contain at least the two following object:
#  DSA1:        /C=de/O=dbp/OU=dap11/CN=dsa/CN=dsa-m1
#  DSA2:        /C=de/O=dbp/OU=dap11/CN=dsa/CN=dsa-m2
# }
#

TP_PATH="lib/"
_HOST_NAME=`uname -n`
        
tet_startup="Startup"                   # startup function
tet_cleanup="Cleanup"                   # cleanup function

iclist="ic1 ic2 ic3 ic4 ic5"

ic1="tp1"				# functions for ic1
ic2="tp2"				# functions for ic2
ic3="tp1"				# functions for ic1
ic4="tp4"				# functions for ic4
ic5="tp1"				# functions for ic1

tp1() {
	tet_infoline "XOM - cleantree"
	$API_SCRIPTS/cleantree "${TP_PATH}"
}

tp2() {
	tet_infoline "Convenience/XOM - threads_as/Testcases"
	$API_SCRIPTS/TTEST "${TP_PATH}"threads_as > /tmp/test_trace 2>&1
	check_ERROR_xds "${TP_PATH}threads_as.$_HOST_NAME.result" 0 12
}

tp3() {
        tet_infoline "Convenience/XOM - threads_os/Testcases"
        $API_SCRIPTS/TTEST "${TP_PATH}"threads_os > /tmp/test_trace 2>&1
        check_ERROR_xds "${TP_PATH}threads_os.$_HOST_NAME.result" 9 3
}

tp4() {
        tet_infoline "Convenience/XOM - threads_af/Testcases"
        $API_SCRIPTS/TTEST "${TP_PATH}"threads_af > /tmp/test_trace 2>&1
        check_ERROR_xds "${TP_PATH}threads_af.$_HOST_NAME.result" 0 12
}

tp5() {
        tet_infoline "Convenience/XOM - threads_stress/Testcases"
        $API_SCRIPTS/TTEST "${TP_PATH}"threads_stress > /tmp/test_trace 2>&1
        check_ERROR_xds "${TP_PATH}threads_stress.$_HOST_NAME.result" 0 12
}

Cleanup() {
        rm -f /tmp/test_trace
        if [[ -z "$KEEP_API_LOGS" ]]
        then
          find ${TET_EXECUTE}/xoms/lib/threads_as -name *.log -exec rm -f {} \;
          find ${TET_EXECUTE}/xoms/lib/threads_af -name *.log -exec rm -f {} \;
        fi
        rm -f ${TET_EXECUTE}/xoms/save*
	tet_infoline "TESTING (XOM/Convenience) with XT_TEST FINISHED"
}

Startup() {
        export XT_TEST_FLAGS="-c"
	export_paths
        rm -f ${TET_EXECUTE}/tet.log
	tet_infoline "TESTING (XOM/Convenience) with XT_TEST STARTED"
        . ${TET_EXECUTE}/config/two_dsas.sh
}

#source shell common functions
. ${TET_EXECUTE}/lib/shfuncs

#execute shell test case manager - must be last line
. ${TET_ROOT}/lib/xpg3sh/tcm.sh

