#
#
# @OSF_COPYRIGHT@
# COPYRIGHT NOTICE
# Copyright (c) 1996 Open Software Foundation, Inc.
# ALL RIGHTS RESERVED (DCE).  See the file named COPYRIGHT.DCE for
# the full copyright text.
#
# Trade Secret of Hitachi, Ltd.
# Do not disclose without written concession from Hitachi, Ltd.
# Copyright 1996 Hitachi, Ltd. All Rights Reserved.  Derechos Reservados.
#
# $Header: /u0/rcs_trees/dce/rcs/file/dfam/agent/Makefile,v 1.1.2.2 1996/03/09 20:43:58 marty Exp $
#
# HISTORY
# $Log: Makefile,v $
# Revision 1.1.2.2  1996/03/09  20:43:58  marty
# 	Add OSF copyright
# 	[1996/03/09  20:23:55  marty]
#
# Revision 1.1.2.1  1996/02/16  04:48:29  dce-sdc
# 	First Submit
# 	[1996/02/16  04:47:38  dce-sdc]
# 
# Revision 1.1.2.3  96/01/12  00:11:09  00:11:09  kishi (Y.Kishi)
# 	... ODE test ... and Change Copyright
# 	[1996/01/12  00:10:55  kishi]
# 
# Revision 1.1.2.2  1995/10/25  06:37:43  kishi
# 	Change Copyright.
# 	[1995/10/25  06:37:30  kishi]
# 
# Revision 1.1.2.1  1995/09/29  09:17:38  kishi
# 	...
# 	[1995/09/29  09:17:21  devrcs]
# 
# Revision 1.1  1995/09/04  11:12:43  sasaki
# 	Initial revision
# 
# $EndLog$
#

SUBDIRS = ${TARGET_MACHINE}

.include<${RULES_MK}>
