package main;

# Exit values from Load Drivers or Setup tool
$EXIT_SUCCESS=0;
$EXIT_USAGE_ERROR=1;
$EXIT_CONFIG_FILE_ERROR=2;
$EXIT_SETUP_ERROR=3;
$EXIT_LSD_SETUP_ERROR=4;
$EXIT_LS_FAIL=5;
$EXIT_MD_SCRIPT_ERROR=6;
$EXIT_LOAD_VALIDATION_ERROR=7;
$EXIT_LOAD_PARSE_ERROR=8;
$EXIT_LOAD_SPEC_ERROR=9;
$EXIT_LOAD_FAIL=10;

