/*
 * @OSF_COPYRIGHT@
 * COPYRIGHT NOTICE
 * Copyright (c) 1996 Open Software Foundation, Inc.
 * ALL RIGHTS RESERVED (DCE).  See the file named COPYRIGHT.DCE for
 * the full copyright text.
 * 
 */
/*
 * HISTORY
 * $Log: checking.idl,v $
 * Revision 1.1.2.2  1996/03/09  20:48:12  marty
 * 	Add OSF copyright
 * 	[1996/03/09  20:26:53  marty]
 *
 * Revision 1.1.2.1  1995/12/11  19:33:21  root
 * 	Submit OSF/DCE 1.2.1
 * 	[1995/12/11  19:17:35  root]
 * 
 * $EndLog$
 */
[
    uuid(3b2dffe0-3d31-11ce-86c2-08002b3d8412)
]   interface Checking
{
	double getCheckingBalance();

	double   withDraw(
		[in] double amt
	);
}
