# @OSF_COPYRIGHT@
# COPYRIGHT NOTICE
# Copyright (c) 1990, 1991, 1992, 1993, 1996 Open Software Foundation, Inc.
# ALL RIGHTS RESERVED (DCE).  See the file named COPYRIGHT.DCE in the
# src directory for the full copyright text.
#
#
# HISTORY
# $Log: Makefile,v $
# Revision 1.1.4.2  1996/03/09  23:29:28  marty
# 	Update OSF copyright year
# 	[1996/03/09  22:44:49  marty]
#
# Revision 1.1.4.1  1995/12/08  17:38:48  root
# 	Submit OSF/DCE 1.2.1
# 	[1995/12/08  16:56:21  root]
# 
# Revision 1.1.2.2  1992/12/29  13:54:46  zeliff
# 	Embedding copyright notice
# 	[1992/12/28  20:49:52  zeliff]
# 
# Revision 1.1  1992/01/19  14:54:06  devrcs
# 	Initial revision
# 
# $EndLog$
#

#   Makefile.ODE V=1 07/03/91 //littl/prgy/krb5/clients
#
# Copyright (c) Hewlett-Packard Company 1991
# Unpublished work. All Rights Reserved.
#
#
# DCE Security Services 
# krb5/clients Makefile
#

# Subdirectories that build programs or export files needed for build
SUBDIRS	= klist  kdestroy  kinit

.include <${RULES_MK}>
