# @OSF_COPYRIGHT@
# COPYRIGHT NOTICE
# (c) Copyright International Business Machines Corp. 1994, 1996
# Copyright (c) 1990, 1991, 1992, 1993, 1994, 1996 Open Software Foundation, Inc.
# ALL RIGHTS RESERVED (DCE).  See the file named COPYRIGHT.DCE for
# the full copyright text.
# 
# HISTORY
# $Log: Makefile,v $
# Revision 1.1.6.1  1996/07/09  15:03:36  arvind
# 	Audit for 1.2.2
# 	[1996/06/21  20:27 UTC  arvind  /main/arvind_audit122/1]
#
# 	Audit for 1.2.2
# 	[1996/03/11  02:35:52  marty  1.1.4.2]
#
# Revision 1.1.4.2  1996/03/11  02:35:52  marty
# 	Update OSF copyright years
# 	[1996/03/10  20:04:12  marty]
# 
# Revision 1.1.4.1  1995/12/11  21:50:51  root
# 	Submit OSF/DCE 1.2.1
# 	[1995/12/11  20:53:24  root]
# 
# Revision 1.1.2.5  1994/06/10  20:45:26  devsrc
# 	cr10872 - fixed copyright
# 	[1994/06/10  17:16:59  devsrc]
# 
# Revision 1.1.2.4  1994/04/29  15:26:54  weisz
# 	CR 10402: added api_filter test suite
# 	[1994/04/29  15:23:35  weisz]
# 
# Revision 1.1.2.3  1994/04/20  20:22:28  weisz
# 	added 3 more subdirectories
# 	[1994/04/20  20:21:56  weisz]
# 
# Revision 1.1.2.2  1994/04/18  19:40:24  zeliff
# 	ot10386: minor makefile cleanup
# 	[1994/04/18  19:31:30  zeliff]
# 
# Revision 1.1.2.1  1994/04/13  21:49:23  weisz
# 	CR 1027: initial submission
# 	[1994/04/13  21:49:06  weisz]
# 
# 	first submission
# 	[1994/04/13  19:12:41  weisz]
# 
# $EndLog$

IDIR	= /test/tet/functional/security/audit/ts/
IMODE		= 755

SUBDIRS         = auditd_startup \
		cp_filter \
		cp_auditd \
		auditd_acl \
                api_log \
		api_log_to_daemon \
                ecfile_filter \
                api_filter

.include <${RULES_MK}>
