#!/bin/csh
#
# @OSF_COPYRIGHT@
# COPYRIGHT NOTICE
# Copyright (c) 1990, 1991, 1992, 1993, 1994, 1996 Open Software Foundation, Inc.
# ALL RIGHTS RESERVED (DCE).  See the file named COPYRIGHT.DCE for
# the full copyright text.
# 
# HISTORY
# $Log: cleantree,v $
# Revision 1.1.4.2  1996/03/11  01:38:43  marty
# 	Update copyright years
# 	[1996/03/10  19:41:38  marty]
#
# Revision 1.1.4.1  1995/12/11  16:56:17  root
# 	Submit
# 	[1995/12/11  16:40:41  root]
# 
# Revision 1.1.2.5  1994/07/06  15:54:17  marrek
# 	Add version string in July 1994 code drop.
# 	[1994/07/06  15:42:48  marrek]
# 
# Revision 1.1.2.4  1994/06/21  14:29:41  marrek
# 	June 1994 code submission.
# 	[1994/06/16  07:50:53  marrek]
# 
# Revision 1.1.2.3  1994/06/10  20:24:50  devsrc
# 	cr10872 - fixed copyright
# 	[1994/06/10  17:00:55  devsrc]
# 
# Revision 1.1.2.2  1994/05/18  22:10:23  zeliff
# 	ot10647: supply path prefix for xt_test and test scripts
# 	[1994/05/15  20:45:25  zeliff]
# 
# Revision 1.1.2.1  1994/05/10  14:39:47  marrek
# 	Add shell interpreter in first line.
# 	[1994/05/09  09:13:31  marrek]
# 
# 	Created in April 1994 submission.
# 	[1994/05/03  12:17:53  marrek]
# 
# $EndLog$
#
# $RCSfile: cleantree,v $ $Revision: 1.1.4.2 $ $Date: 1996/03/11 01:38:43 $
#

$XT_TEST_PATH/xt_test -i "$1"tree/zap_tree >& /dev/null
