#!/bin/csh
#
# @OSF_COPYRIGHT@
# COPYRIGHT NOTICE
# Copyright (c) 1990, 1991, 1992, 1993, 1994, 1996 Open Software Foundation, Inc.
# ALL RIGHTS RESERVED (DCE).  See the file named COPYRIGHT.DCE for
# the full copyright text.
# 
# HISTORY
# $Log: TTEST,v $
# Revision 1.1.4.2  1996/03/11  01:38:39  marty
# 	Update copyright years
# 	[1996/03/10  19:41:34  marty]
#
# Revision 1.1.4.1  1995/12/11  16:56:11  root
# 	Submit
# 	[1995/12/11  16:40:37  root]
# 
# Revision 1.1.2.5  1994/07/06  15:54:14  marrek
# 	Add version string in July 1994 code drop.
# 	[1994/07/06  15:42:42  marrek]
# 
# Revision 1.1.2.4  1994/06/21  14:29:39  marrek
# 	June 1994 code submission.
# 	[1994/06/16  07:50:47  marrek]
# 
# Revision 1.1.2.3  1994/06/10  20:24:29  devsrc
# 	cr10872 - fixed copyright
# 	[1994/06/10  17:00:53  devsrc]
# 
# Revision 1.1.2.2  1994/05/18  22:10:00  zeliff
# 	ot10647: supply path prefix for xt_test and test scripts
# 	[1994/05/15  20:45:15  zeliff]
# 
# Revision 1.1.2.1  1994/05/10  14:39:37  marrek
# 	Add shell interpreter in first line.
# 	[1994/05/09  09:13:20  marrek]
# 
# 	Created in April 1994 submission.
# 	[1994/05/03  12:17:38  marrek]
# 
# $EndLog$
#
# $RCSfile: TTEST,v $ $Revision: 1.1.4.2 $ $Date: 1996/03/11 01:38:39 $
#

set dir=$1
if ("$2" != "") then
	set timeslice=$2
else
	set timeslice=100000 #quick and dirty (default on RIOS)
endif 
if (-e $dir) then
	cd $dir
	echo cleaning tree        ; $API_SCRIPTS/cleantree
	$API_SCRIPTS/_ttestall $timeslice $dir
	cd ..
else
	echo directory $dir not found
endif
