[
uuid(000cce84-f567-1f27-8561-9e620d15aa77),
version(1.2)
]
interface dce_delegate
{

	import "dce/id_epac.idl";

	const long MAX_STRING = 128;
	const long MAX_ENTRIES = 100;
	typedef [string, ptr] char *entry;
	typedef long int da_status_t;

	const long int DA_OK = 0;
	const long int DA_NO_BINDING = -1;

	da_status_t delegate_to(
		[in] handle_t handle,
		[in] sec_id_delegation_type_t delegation_type,
		[in] sec_id_compatibility_mode_t compatibility_mode,
		[in] long bind_to_entry,
		[in] long first,
		[in] long length,
		[in, first_is(first), length_is(length)] entry name[MAX_ENTRIES],
		[out] long *perms,
		[out] error_status_t *status
	);
}
