#! /bin/sh
#
# @OSF_COPYRIGHT@
# COPYRIGHT NOTICE
# Copyright (c) 1990, 1991, 1992, 1993 Open Software Foundation, Inc.
# ALL RIGHTS RESERVED (DCE).  See the file named COPYRIGHT.DCE in the
# src directory for the full copyright text.
#
# test4
#
# tests addftfamily, rmftfamily, lsftfamilies 
#
# This script exercises bak commands that do not result in
# any tape drive operations.
#
#
# HISTORY
# $Log: test4,v $
# Revision 1.1.12.1  1996/10/17  18:12:23  damon
# 	Submitting on behalf of Transarc
# 	[1996/10/17  16:47:52  damon]
#
# Revision 1.1.5.2  1993/01/11  17:36:57  htf
# 	Embedded copyright notice
# 	[1993/01/11  16:53:23  htf]
# 
# Revision 1.1.2.2  1992/05/21  12:32:23  jaffe
# 	To convert the /bin/csh backup test scripts to /bin/sh.
# 	To change the scripts to use the recommended style of variable names.
# 
# 	$TALog: test4,v $
# 	Revision 4.4  1994/06/01  17:25:12  andi
# 	None of the files existed in the configuration!  Checked them all out
# 	and added them.
# 	[added by delta andi-db5496-checkout-backup-tests, r1.1]
# 
# Revision 4.3  1993/01/14  17:32:10  jaffe
# 	revdrop of latest OSF copyright changes to these files
# 	[from r4.2 by delta osf-revdrop-01-12-92, r1.1]
# 
# 	[1992/05/20  16:13:26  jaffe]
# 
# $EndLog$
#


: ${BAK_BIN_DIR=$1}

PATH=$PATH":"$BAK_BIN_DIR
#export PATH

echo ""
echo "********************* TEST4 *********************"
echo ""
# should succeed and report no families
echo bak lsftfamilies 
bak lsftfamilies 
if [ $? -ne 0 ] 
then
  echo "Case 4.0 FAILED unexpectedly"
fi

echo ""
# should fail because mamas ftfamily does not exist
echo bak lsftfamilies -family mamas
bak lsftfamilies -family mamas
if [ $? -ne 1 ] 
then
  echo "Case 4.1 WORKED unexpectedly"
fi

echo ""
# successful
echo bak addftfamily -family simpsons
bak addftfamily -family simpsons
if [ $? -ne 0 ] 
then
  echo "Case 4.2 FAILED unexpectedly"
fi

echo ""
# successful
echo bak lsftfamilies
bak lsftfamilies

echo ""
# should fail because ftfamily already exists
echo bak addftfamily -family simpsons
bak addftfamily -family simpsons
if [ $? -ne 1 ] 
then
  echo "Case 4.3 WORKED unexpectedly"
fi

echo ""
# should succeed since the simpsons family exists.
echo bak lsftfamilies -family simpsons
bak lsftfamilies -family simpsons
if [ $? -ne 0 ] 
then
  echo "Case 4.4 FAILED unexpectedly"
fi

echo ""
# successful
echo bak rmftfamily -family simpsons
bak rmftfamily -family simpsons
if [ $? -ne 0 ] 
then
  echo "Case 4.5 FAILED unexpectedly"
fi 

echo ""
# should fail because mamas family does not exist.
echo bak rmftfamily -family mamas
bak rmftfamily -family mamas
if [ $? -ne 1 ] 
then
  echo "Case 4.6 WORKED unexpectedly"
fi

echo ""
# should succeed because no family name was given
echo bak rmftfamily 
bak rmftfamily 
if [ $? -ne 1 ] 
then
  echo "Case 4.7 WORKED unexpectedly"
fi

echo ""
echo "********************* TEST4 END  *********************"
