#! /bin/sh
#
# @OSF_COPYRIGHT@
# COPYRIGHT NOTICE
# Copyright (c) 1990, 1991, 1992, 1993 Open Software Foundation, Inc.
# ALL RIGHTS RESERVED (DCE).  See the file named COPYRIGHT.DCE in the
# src directory for the full copyright text.
#
# test6
#
# tests ftinfo, dumpinfo
#
# This script exercises bak commands that do not result in
# any tape drive operations.
#
#
# HISTORY
# $Log: test6,v $
# Revision 1.1.12.1  1996/10/17  18:12:25  damon
# 	Submitting on behalf of Transarc
# 	[1996/10/17  16:47:54  damon]
#
# Revision 1.1.5.2  1993/01/11  17:37:10  htf
# 	Embedded copyright notice
# 	[1993/01/11  16:53:32  htf]
# 
# Revision 1.1.2.2  1992/05/21  12:32:36  jaffe
# 	To convert the /bin/csh backup test scripts to /bin/sh.
# 	To change the scripts to use the recommended style of variable names.
# 
# 	$TALog: test6,v $
# 	Revision 4.4  1994/06/01  17:25:14  andi
# 	None of the files existed in the configuration!  Checked them all out
# 	and added them.
# 	[added by delta andi-db5496-checkout-backup-tests, r1.1]
# 
# Revision 4.3  1993/01/14  17:32:14  jaffe
# 	revdrop of latest OSF copyright changes to these files
# 	[from r4.2 by delta osf-revdrop-01-12-92, r1.1]
# 
# 	[1992/05/20  16:17:04  jaffe]
# 
# $EndLog$
#

: ${BAK_BIN_DIR=$1}

PATH=$PATH":"$BAK_BIN_DIR
#export PATH

echo ""
echo "**************** TEST6 *****************"
echo ""
# should fail since no fileset specified
echo bak ftinfo 
bak ftinfo 
if [ $? -ne 1 ] 
then
  echo "Case 6.0 WORKED unexpectedly"
fi

echo ""
bak ftinfo -fileset .\*
if [ $? -ne 0 ] 
then
  echo "Case 6.1 FAILED unexpectedly"
fi

echo ""
echo bak dumpinfo 
bak dumpinfo 
echo "Return status of command is $?"
echo "Case 6.2 -Verify manually based on previous actions"

echo "" 
echo bak dumpinfo -verbose
bak dumpinfo -verbose
echo "Return status of command is $?"
echo "Case 6.3 -Verify manually based on previous actions"

echo ""
echo "**************** TEST6 END *****************"









