# @OSF_COPYRIGHT@
# COPYRIGHT NOTICE
# Copyright (c) 1990, 1991, 1992, 1993, 1996 Open Software Foundation, Inc.
# ALL RIGHTS RESERVED (DCE).  See the file named COPYRIGHT.DCE in the
# src directory for the full copyright text.
# 
# HISTORY
# $Log: Makefile,v $
# Revision 1.1.4.2  1996/03/09  23:15:29  marty
# 	Update OSF copyright year
# 	[1996/03/09  22:32:43  marty]
#
# Revision 1.1.4.1  1995/12/08  20:54:51  root
# 	Submit OSF/DCE 1.2.1
# 	[1995/12/08  20:50:01  root]
# 
# Revision 1.1.2.1  1994/06/14  19:59:24  weir
# 	DCE 1.1 Beta check-in
# 	[1994/06/14  16:16:25  weir]
# 
# $EndLog$
# 
# 
#----------------------------------------------------------------------------------------
# [23.V.94]
# 
# ODE Makefile for src/examples/svc
# 
# 
# This Makefile allows you to type "build install_all" in this directory
#  and install only the serviceability demo programs.
# 
#----------------------------------------------------------------------------------------

IDIR	= /usr/examples/svc/

IMODE	= 644

SUBDIRS = timop_svc hello_svc

# The following line explicitly includes the "common makefiles". For more
#  information, see Chapter 12 of the Porting Guide...

.include <${RULES_MK}>
