/*
 * @OSF_COPYRIGHT@
 * COPYRIGHT NOTICE
 * Copyright (c) 1990, 1991, 1992, 1993, 1996 Open Software Foundation, Inc.
 * ALL RIGHTS RESERVED (DCE).  See the file named COPYRIGHT.DCE in the
 * src directory for the full copyright text.
 */
/*
 * HISTORY
 * $Log: string_tree.idl,v $
 * Revision 1.1.4.2  1996/03/11  02:18:48  marty
 * 	Update OSF copyright years
 * 	[1996/03/10  19:55:43  marty]
 *
 * Revision 1.1.4.1  1995/12/11  19:30:17  root
 * 	Submit OSF/DCE 1.2.1
 * 	[1995/12/11  19:15:59  root]
 * 
 * Revision 1.1.2.2  1993/01/07  23:38:24  bbelch
 * 	Embedding copyright notice
 * 	[1993/01/06  13:44:59  bbelch]
 * 
 * Revision 1.1  1992/01/19  03:28:17  devrcs
 * 	Initial revision
 * 
 * $EndLog$
 */
/*
*/
[uuid(d37a0e80-5d23-11c9-b199-08002b13d56d), version(0)]
interface string_tree
{
    /*
    ** Maximum length of a string in the tree
    */
    const long int st_c_name_len = 32;

    /*
    ** Definition of a node in the tree.
    */
    typedef struct node
    {
        char                    name[0..st_c_name_len];
        [ptr] struct node       *left;
        [ptr] struct node       *right;
    } st_node_t;


    /*
    ** Operation that prunes the left subtree of the specified
    ** tree and returns it as the value.
    */
    st_node_t *st_prune_left (
        [in, out] st_node_t *tree /* root of tree by ref */
        );
}
