/*
 * @OSF_COPYRIGHT@
 * COPYRIGHT NOTICE
 * Copyright (c) 1990, 1991, 1992, 1993, 1994, 1996 Open Software Foundation, Inc.
 * ALL RIGHTS RESERVED (DCE).  See the file named COPYRIGHT.DCE for
 * the full copyright text.
 * 
 */
/*
 * HISTORY
 * $Log: dcdrel002.idl,v $
 * Revision 1.1.4.2  1996/03/11  02:38:29  marty
 * 	Update OSF copyright years
 * 	[1996/03/10  20:05:22  marty]
 *
 * Revision 1.1.4.1  1995/12/11  21:55:40  root
 * 	Submit OSF/DCE 1.2.1
 * 	[1995/12/11  20:55:38  root]
 * 
 * Revision 1.1.2.2  1994/08/10  19:23:21  annie
 * 	expand copyright with OSF copyright text
 * 	[1994/08/10  17:17:37  annie]
 * 
 * Revision 1.1.2.1  1994/06/27  17:15:02  baum
 * 	Initial checkin
 * 	[1994/06/27  17:14:28  baum]
 * 
 * $EndLog$
 */
[
    uuid(00032b04-f3f0-1e0e-9ea7-0000c0dc0d4b),
    version(1.0)
]
interface dcdrel002
{
  [idempotent]
  void ping_op
  (
     [in]	handle_t	h,
     [out]	error_status_t	*st
  );

  [idempotent]
  void stop_bad_op
  (
     [in]	handle_t	h,
     [out]	error_status_t	*st
  );

  [idempotent]
  void stop_clean_op
  (
     [in]	handle_t	h,
     [out]	error_status_t	*st
  );
}

