/*
 * @OSF_COPYRIGHT@
 * COPYRIGHT NOTICE
 * Copyright (c) 1990, 1991, 1992, 1993, 1996 Open Software Foundation, Inc.
 * ALL RIGHTS RESERVED (DCE).  See the file named COPYRIGHT.DCE in the
 * src directory for the full copyright text.
 */
/*
 * HISTORY
 * $Log: strint.idl,v $
 * Revision 1.1.4.2  1996/03/11  02:19:08  marty
 * 	Update OSF copyright years
 * 	[1996/03/10  19:55:53  marty]
 *
 * Revision 1.1.4.1  1995/12/11  19:30:41  root
 * 	Submit OSF/DCE 1.2.1
 * 	[1995/12/11  19:16:13  root]
 * 
 * Revision 1.1.2.1  1994/05/03  18:51:02  tom
 * 	Initial checkin.
 * 	[1994/05/03  18:49:58  tom]
 * 
 * $EndLog$
 */

[uuid(2ede3e38-ffc4-11c8-8ae4-08002b104860), version(0)]
interface strint
/*
 * Similar to test stringts, except uses strings with integer base types.
 */
{
    typedef unsigned short PRIVATE_CHAR_16;
    typedef unsigned long PRIVATE_CHAR_32;

    void op_fixed (
        [in] handle_t h,
        [in,string] PRIVATE_CHAR_16 f_i[81],
        [in,out,string] PRIVATE_CHAR_16 f_io[81],
        [out,string] PRIVATE_CHAR_16 f_o[81]
    );

    void op_conf (
        [in] handle_t h,
        [in] small i_size,
        [in,string,size_is(i_size)] PRIVATE_CHAR_32 c_i[],
        [in] short io_size,
        [in,out,string, size_is(io_size)] PRIVATE_CHAR_32 c_io[],
        [in] long o_size,
        [out,string,size_is(o_size)] PRIVATE_CHAR_32 c_o[]
    );

    void op_self (
        [in] handle_t h,
        [in,string] PRIVATE_CHAR_16 s_i[],
        [in,out,string] PRIVATE_CHAR_16 s_io[]
    );

    typedef struct private_16 {
        [string] PRIVATE_CHAR_16 f_p_16[27];
        [string] PRIVATE_CHAR_16 s_p[];
    } private_16;

    typedef struct two_byte {
        [string] PRIVATE_CHAR_32 m_l[27];
        [string] PRIVATE_CHAR_32 p_32[];
    } two_byte;

    void op_multi (
        [in] handle_t h,
        [in,string] PRIVATE_CHAR_32 m_i[],
        [out,string] PRIVATE_CHAR_32 m_o[14],
        [in,out] private_16 *p16,
        [in,out] two_byte *tb
    );

/* Operation to check MIA bug. A.I.Hinxman 6-Aug-1992 */

    typedef struct stringptrs_t
    {
        [string,ptr] PRIVATE_CHAR_16 *astring;
        [string,ptr] PRIVATE_CHAR_16 *bstring;
    } stringptrs_t;

    void op_sp (
        [in] handle_t h,
        [in,out] stringptrs_t *p_sp
    );

/* Operations to test FORTRAN support. A.I.Hinxman 11-Aug-1992 */

    typedef [string] PRIVATE_CHAR_16 ils_t[27];
    typedef [string] PRIVATE_CHAR_32 ims_t[27];
    typedef [string] PRIVATE_CHAR_32 ius_t[27];

    void op_fas (
        [in] handle_t h,
        [in] ils_t ilsa[5],
        [out] ims_t imsa[5]
    );

    void op_fac (
        [in] handle_t h,
        [in] long s,
        [in, size_is(s)] ims_t imsa[],
        [out, size_is(s)] ius_t iusa[]
    );

    void op_selfconf (
        [in] handle_t h,
        [in,out,string] PRIVATE_CHAR_16 scs[]
    );
}
