# @OSF_COPYRIGHT@
# COPYRIGHT NOTICE
# Copyright (c) 1990, 1991, 1992, 1993, 1994, 1996 Open Software Foundation, Inc.
# ALL RIGHTS RESERVED (DCE).  See the file named COPYRIGHT.DCE for
# the full copyright text.
# 
# 
# HISTORY
# $Log: Makefile,v $
# Revision 1.1.4.3  1996/03/11  02:08:30  marty
# 	Update OSF copyright years
# 	[1996/03/10  19:27:27  marty]
#
# Revision 1.1.4.2  1995/12/13  15:23:41  root
# 	Submit OSF/DCE 1.2.1
# 
# 	HP revision /main/HPDCE02/1  1994/11/15  15:29 UTC  truitt
# 	Initial HPDCE02 branch.
# 
# 	HP revision /main/truitt_dcecp_01/1  1994/11/15  15:28 UTC  truitt
# 	Remove bogus file from build.
# 	[1995/12/11  15:50:30  root]
# 
# Revision 1.1.2.1  1994/09/28  21:36:48  melman
# 	moved admin tests to test/functional
# 	[1994/09/28  21:05:50  melman]
# 
# Revision 1.1.2.3  1994/06/10  20:01:25  devsrc
# 	cr10872 - fixed copyright
# 	[1994/06/10  16:51:56  devsrc]
# 
# Revision 1.1.2.2  1994/05/11  14:46:47  rousseau
# 	Updated to new install path and removed bad use of SCRIPTS (CR 10601).
# 	[1994/05/11  14:46:13  rousseau]
# 
# Revision 1.1.2.1  1994/02/10  23:13:44  rousseau
# 	Initial test drop.
# 	[1994/02/10  23:10:12  rousseau]
# 
# $EndLog$

TET_FILES	= tet_scen tet_code tetexec.cfg
IDIR		= /test/tet/functional/admin/dcecp/
ILIST		= ${TET_FILES}
DATAFILES	= ${TET_FILES}
IMODE 		= 755

SUBDIRS		= ts lib
DATA_SUBDIRS	= ${SUBDIRS}

.include <${RULES_MK}>
