/*
 * @OSF_COPYRIGHT@
 * COPYRIGHT NOTICE
 * Copyright (c) 1990, 1991, 1992, 1993, 1996 Open Software Foundation, Inc.
 * ALL RIGHTS RESERVED (DCE).  See the file named COPYRIGHT.DCE in the
 * src directory for the full copyright text.
 */
/*
 * HISTORY
 * $Log: sparse.idl,v $
 * Revision 1.1.4.2  1996/03/11  02:18:24  marty
 * 	Update OSF copyright years
 * 	[1996/03/10  19:55:29  marty]
 *
 * Revision 1.1.4.1  1995/12/11  19:29:49  root
 * 	Submit OSF/DCE 1.2.1
 * 	[1995/12/11  19:15:47  root]
 * 
 * Revision 1.1.2.2  1993/01/07  23:36:25  bbelch
 * 	Embedding copyright notice
 * 	[1993/01/06  13:43:33  bbelch]
 * 
 * Revision 1.1  1992/01/19  03:29:21  devrcs
 * 	Initial revision
 * 
 * $EndLog$
 */
/*
*/
[uuid(44254808-8000-0000-0d00-00feda000000), version(0), 
 endpoint("ncadg_ip_udp:[35004]", "ncadg_dds:[775]")]

interface sparse
{
    const long ARRAY_SIZE = 1000;
    const long CARRAY_SIZE = 2000;    /* worst case: twice the original size */

    /* a run-length encoded representation of an array */
    typedef struct
    {
        long last;
        [last_is(last)] long data[CARRAY_SIZE];
    } compress_t;

    /* this type will be transmitted as a more compact type */
    typedef [transmit_as(compress_t)] long compress_array[ARRAY_SIZE];

    /* this type will be transmitted as is */
    typedef long nocompress_array[ARRAY_SIZE];

    [idempotent]
        long sparse_compress_sum([in] handle_t h, [in] compress_array array);

    [idempotent]
        long sparse_nocompress_sum([in] handle_t h, [in] nocompress_array array);
}
