#
# @OSF_COPYRIGHT@
# COPYRIGHT NOTICE
# Copyright (c) 1990, 1991, 1992, 1993, 1996 Open Software Foundation, Inc.
# ALL RIGHTS RESERVED (DCE).  See the file named COPYRIGHT.DCE in the
# src directory for the full copyright text.
#
# HISTORY
# $Log: Makefile,v $
# Revision 1.1.13.2  1996/03/09  23:13:23  marty
# 	Update OSF copyright year
# 	[1996/03/09  22:30:36  marty]
#
# Revision 1.1.13.1  1995/12/08  15:31:09  root
# 	Submit OSF/DCE 1.2.1
# 	[1995/12/08  14:55:17  root]
# 
# Revision 1.1.11.3  1994/07/11  21:06:06  keutel
# 	CR 10732: asn1_attr is created during installation
# 	[1994/07/11  20:56:36  keutel]
# 
# Revision 1.1.11.2  1994/05/10  15:51:29  marrek
# 	April 1994 code submission.
# 	[1994/04/27  12:17:44  marrek]
# 
# Revision 1.1.11.1  1994/02/22  16:04:39  marrek
# 	Code drop for dce1.1.
# 	[1994/02/08  10:05:22  marrek]
# 
# Revision 1.1.9.1  1993/09/17  17:44:55  mhickey
# 	Fixed the VPATH line to correctly find the asn1_attr file
# 	in the directory/gds/dsa directory.
# 
# 	Defect 8615.
# 	[1993/09/17  17:39:00  mhickey]
# 
# Revision 1.1.7.2  1993/08/11  14:44:55  marrek
# 	July 1993 code drop.
# 	[1993/08/02  12:57:37  marrek]
# 
# Revision 1.1.5.3  1992/12/31  18:57:46  bbelch
# 	Embedding copyright notice
# 	[1992/12/31  13:16:56  bbelch]
# 
# Revision 1.1.5.2  1992/11/27  17:28:04  marrek
# 	November 1992 code drop
# 	[1992/11/17  17:51:45  marrek]
# 
# Revision 1.1.2.3  1992/06/30  20:55:24  melman
# 	GDS drop of 6/16/92
# 	[1992/06/30  20:34:33  melman]
# 
# Revision 1.1.2.2  1992/06/01  23:41:10  zeliff
# 	New version of file from GDS drop
# 	[1992/05/28  20:42:24  zeliff]
# 
# Revision 1.1  1992/01/19  15:12:57  devrcs
# 	Initial revision
# 
# $EndLog$
#
# $RCSfile: Makefile,v $ $Revision: 1.1.13.2 $ $Date: 1996/03/09 23:13:23 $
#

SUBDIRS	= ${TARGET_MACHINE}

ILIST	= ipcconf
IDIR	= /share/var/adm/directory/gds/conf/

.include <${RULES_MK}>

