#
# @OSF_COPYRIGHT@
# COPYRIGHT NOTICE
# Copyright (c) 1990, 1991, 1992, 1993, 1994, 1996 Open Software Foundation, Inc.
# ALL RIGHTS RESERVED (DCE).  See the file named COPYRIGHT.DCE for
# the full copyright text.
# 
# HISTORY
# $Log: Makefile,v $
# Revision 1.1.6.2  1996/03/11  02:41:47  marty
# 	Update OSF copyright years
# 	[1996/03/10  20:06:32  marty]
#
# Revision 1.1.6.1  1995/12/11  21:57:57  root
# 	Submit OSF/DCE 1.2.1
# 
# 	HP revision /main/HPDCE02/1  1994/06/29  19:29 UTC  bissen
# 	Merge hpdce02 (DCE 1.1 beta) and HPDCE01 into HPDCE02
# 
# 	HP revision /main/HPDCE01/1  1994/04/01  15:30 UTC  truitt
# 
# 	HP revision /main/truitt_junk/1  1994/04/01  15:22 UTC  truitt
# 	fix file _IDIR's
# 	[1995/12/11  20:57:38  root]
# 
# Revision 1.1.2.3  1993/11/03  21:50:34  mhickey
# 	Initial submit of the Makefile to get the gds_xds_str_001 test
# 	installed.
# 
# 	defect 9209.
# 	[1993/11/03  21:45:39  mhickey]
# 
# Revision 1.1.2.2  1993/10/22  18:08:55  mhickey
# 	Fixed file list
# 	[1993/10/22  18:08:44  mhickey]
# 
# Revision 1.1.1.3  1993/10/21  19:32:06  mhickey
# 	Initial checkin of Makefile
# 	for the gds_xds_str_001 system test.
# 
# 	Defect 9202.
# 
# Revision 1.1.1.2  1993/10/21  19:07:10  mhickey
# 	Initial check in of the Makefile for the gds_xds_str_001
# 	system test files.
# 
# 	Defect 9209.
# 
# $EndLog$

SHUTDOWNbX_IDIR				= /tet/gds/ts/gds_xds_str_001/
SHUTDOWNb_IDIR				= /tet/gds/ts/gds_xds_str_001/
STARTb_IDIR				= /tet/gds/ts/gds_xds_str_001/
STARTbX_IDIR				= /tet/gds/ts/gds_xds_str_001/
Tb.start_IDIR				= /tet/gds/ts/gds_xds_str_001/
Tb.shutdn_IDIR				= /tet/gds/ts/gds_xds_str_001/
TbX.start_IDIR				= /tet/gds/ts/gds_xds_str_001/
TbX.shutdn_IDIR				= /tet/gds/ts/gds_xds_str_001/
gds_xds_str_001_IDIR			= /tet/gds/ts/gds_xds_str_001/
gds_xds_str_001.data_IDIR		= /tet/gds/ts/gds_xds_str_001/
gds_xds_str_001_bXrdu_1_IDIR		= /tet/gds/ts/gds_xds_str_001/
gds_xds_str_001_bXrdu_2_IDIR		= /tet/gds/ts/gds_xds_str_001/
gds_xds_str_001_bXrdu_3_IDIR		= /tet/gds/ts/gds_xds_str_001/
gds_xds_str_001_brd1u_IDIR		= /tet/gds/ts/gds_xds_str_001/
gds_xds_str_001_brdXu_1_IDIR		= /tet/gds/ts/gds_xds_str_001/
gds_xds_str_001_brdXu_2_IDIR		= /tet/gds/ts/gds_xds_str_001/
gds_xds_str_001_brdXu_3_IDIR		= /tet/gds/ts/gds_xds_str_001/
gds_xds_str_001_brdX_bt_IDIR		= /tet/gds/ts/gds_xds_str_001/
gds_xds_str_001_brdX_dt_IDIR		= /tet/gds/ts/gds_xds_str_001/
gds_xds_str_001_bXrdschX_sch1_IDIR	= /tet/gds/ts/gds_xds_str_001/
gds_xds_str_001_bXrdschX_sch2_IDIR	= /tet/gds/ts/gds_xds_str_001/
gds_xds_str_001_bXrdschX_sch3_IDIR	= /tet/gds/ts/gds_xds_str_001/
gds_xds_str_001_bXrdschX_sch4_IDIR	= /tet/gds/ts/gds_xds_str_001/

OTHERS = SHUTDOWNbX SHUTDOWNb \
         STARTb STARTbX Tb.start Tb.shutdn \
         TbX.start TbX.shutdn \
         gds_xds_str_001 \
         gds_xds_str_001.data gds_xds_str_001_bXrdu_1 \
         gds_xds_str_001_bXrdu_2 gds_xds_str_001_bXrdu_3 \
         gds_xds_str_001_brd1u gds_xds_str_001_brdXu_1 \
         gds_xds_str_001_brdXu_2 gds_xds_str_001_brdXu_3 \
         gds_xds_str_001_brdX_bt gds_xds_str_001_brdX_dt \
         gds_xds_str_001_bXrdschX_sch1 gds_xds_str_001_bXrdschX_sch2 \
         gds_xds_str_001_bXrdschX_sch3 gds_xds_str_001_bXrdschX_sch4

ILIST = ${OTHERS}

.include <${RULES_MK}>
