/*
 * @OSF_COPYRIGHT@
 * COPYRIGHT NOTICE
 * Copyright (c) 1990, 1991, 1992, 1993, 1996 Open Software Foundation, Inc.
 * ALL RIGHTS RESERVED (DCE).  See the file named COPYRIGHT.DCE in the
 * src directory for the full copyright text.
 */
/*
 * HISTORY
 * $Log: es_array.idl,v $
 * Revision 1.1.4.2  1996/03/11  02:12:52  marty
 * 	Update OSF copyright years
 * 	[1996/03/10  19:52:52  marty]
 *
 * Revision 1.1.4.1  1995/12/11  20:03:54  root
 * 	Submit OSF/DCE 1.2.1
 * 	[1995/12/11  19:30:46  root]
 * 
 * Revision 1.1.2.2  1993/08/11  16:23:52  ganni
 * 	tests for new IDL functionality
 * 	[1993/08/11  16:13:09  ganni]
 * 
 * $EndLog$
 */
/*
*/
[uuid(20aac780-5398-11c9-b996-08002b13d56d), version(0)]
interface es_array
{
    const long N = 5000;
    const long M = 11;

    typedef struct
    {
        byte b;
        long l;
    } s_t;

    typedef struct
    {
        byte b;
        long a[7];
    } t_t;

    void in_array_op1([in] handle_t h, [in] long arr[N]);
    void out_array_op1([in] handle_t h, [out] long arr[N]);

    void array_op2([in] handle_t h, [in,out] s_t big[N]);

    void array_op3([in] handle_t h, [in,out] t_t big[N]);

    void op1([in]handle_t h);

}
