/*
 * @OSF_COPYRIGHT@
 * COPYRIGHT NOTICE
 * Copyright (c) 1990, 1991, 1992, 1993, 1996 Open Software Foundation, Inc.
 * ALL RIGHTS RESERVED (DCE).  See the file named COPYRIGHT.DCE in the
 * src directory for the full copyright text.
 */
/*
 * HISTORY
 * $Log: faultstat.idl,v $
 * Revision 1.1.4.2  1996/03/11  02:13:43  marty
 * 	Update OSF copyright years
 * 	[1996/03/10  19:53:13  marty]
 *
 * Revision 1.1.4.1  1995/12/11  20:05:37  root
 * 	Submit OSF/DCE 1.2.1
 * 	[1995/12/11  19:31:26  root]
 * 
 * Revision 1.1.2.2  1993/01/07  19:56:44  bbelch
 * 	Embedding copyright notice
 * 	[1993/01/06  13:33:38  bbelch]
 * 
 * Revision 1.1  1992/01/19  03:24:37  devrcs
 * 	Initial revision
 * 
 * $EndLog$
 */
/*
*/
[uuid(39b68dd0-981d-11c9-8cc0-08001e01e1e9), version(0)]
interface faultstat
{
    /*
     * Temp hack: return fault as status; code will ignore it.  For some reason
     * the set_fpc_csr call in the manager causes an exception that gets mapped
     * to cma_e_SIGFPE.  Should figure out why this is happening someday.
     */
    error_status_t setup([in] handle_t h);

    error_status_t fr_cr_op( [in] handle_t bad_h );
    error_status_t fp_cr_op( [in] handle_t bad_h, [out] error_status_t *fst );
    error_status_t fep_cr_op( [in] handle_t bad_h );

    error_status_t fr_cp_op( [in] handle_t bad_h, [out] error_status_t *cst );
    void fdp_cp_op( [in] handle_t bad_h, 
                    [out] error_status_t *cst,
                    [out] error_status_t *fst );
    void fsp_cp_op( [in] handle_t bad_h, [out] error_status_t *fcst );
    void fep_cp_op( [in] handle_t bad_h, [out] error_status_t *cst );

    error_status_t fr_cep_op( [in] handle_t bad_h );
    void fp_cep_op( [in] handle_t bad_h, [out] error_status_t *fst );
    void fsp_cep_op( [in] handle_t bad_h );
    void fdp_cep_op( [in] handle_t bad_h );

    error_status_t fr_cr_dz( [in] handle_t h );
    error_status_t fp_cr_dz( [in] handle_t h, [out] error_status_t *fst );
    error_status_t fep_cr_dz( [in] handle_t h );

    error_status_t fr_cp_dz( [in] handle_t h, [out] error_status_t *cst );
    void fdp_cp_dz( [in] handle_t h, 
                    [out] error_status_t *cst,
                    [out] error_status_t *fst );
    void fsp_cp_dz( [in] handle_t h, [out] error_status_t *fcst );
    void fep_cp_dz( [in] handle_t h, [out] error_status_t *cst );

    error_status_t fr_cep_dz( [in] handle_t h );
    void fp_cep_dz( [in] handle_t h, [out] error_status_t *fst );
    void fsp_cep_dz( [in] handle_t h );
    void fdp_cep_dz( [in] handle_t h );

}
