# @OSF_COPYRIGHT@
# COPYRIGHT NOTICE
# Copyright (c) 1990, 1991, 1992, 1993, 1994, 1996 Open Software Foundation, Inc.
# ALL RIGHTS RESERVED (DCE).  See the file named COPYRIGHT.DCE for
# the full copyright text.
# 
# HISTORY
# $Log: Makefile,v $
# Revision 1.1.4.2  1996/03/11  02:14:46  marty
# 	Update copyright years
# 	[1996/03/10  20:00:32  marty]
#
# Revision 1.1.4.1  1995/12/11  17:59:51  root
# 	Submit OSF/DCE 1.2.1
# 
# 	HP revision /main/HPDCE02/1  1995/05/30  13:45 UTC  bartf
# 	Make our own branch to fix missing Testcases cause the ^&*!ing lock won't let us touch the mainline
# 
# 	HP revision /main/bartf_mothra_test/1  1995/05/30  13:38 UTC  bartf
# 	Add Testcases to DATAFILES list so it gets installed.
# 	[1995/12/11  17:42:01  root]
# 
# Revision 1.1.2.5  1994/08/10  08:26:22  marrek
# 	Fix for SAP errors, OT11467.
# 	[1994/08/10  08:16:15  marrek]
# 
# Revision 1.1.2.4  1994/07/06  15:12:41  marrek
# 	July 1994 code drop.
# 	[1994/07/06  12:04:34  marrek]
# 
# Revision 1.1.2.3  1994/06/21  14:29:45  marrek
# 	June 1994 code submission.
# 	[1994/06/16  07:51:03  marrek]
# 
# Revision 1.1.2.2  1994/06/10  20:26:06  devsrc
# 	cr10872 - fixed copyright
# 	[1994/06/10  17:01:36  devsrc]
# 
# Revision 1.1.2.1  1994/05/10  14:59:29  marrek
# 	Created in April 1994 submission.
# 	[1994/05/03  12:19:02  marrek]
# 
# $EndLog$
#
# $RCSfile: Makefile,v $ $Revision: 1.1.4.2 $ $Date: 1996/03/11 02:14:46 $
#

IDIR = /test/tet/functional/directory/xds/ts/xom/lib/valid/

DATAFILES	=		\
		Testcases	\
		copy1v		\
		copy2v		\
		copy3v		\
		copy_value1v	\
		copy_value2v	\
		create1v	\
		create2v	\
		delete1v	\
		delete2v	\
		get1v		\
		get2v		\
		get3v		\
		get4v		\
		get5v		\
		get6v		\
		get7v		\
		get8v		\
		get9v		\
		instance1v	\
		instance2v	\
		instance3v	\
		put1v		\
		put2v		\
		put3v		\
		put4v		\
		put5v		\
		put6v		\
		read1v		\
		read2v		\
		remove1v	\
		write1v		\
		geti18n1v	\
		geti18n2v	\
		geti18n3v	\
		puti18n1v	\
		readi18n1v	\
		writei18n1v	\
		create3v	\
		delete3v	\
		put7v		\
		get10v		\
		get11v		\
		get12v		\
		get13v		\
		get14v		\
		put8v		\
		put9v		\
		put10v		\
		put13v		\
		put14v		\
		create4v	\
		instance4v	\
		instance5v	\
		instance6v	\
		instance7v	\
		instance8v	\
		instance9v	\
		delete4v

ILIST		= ${DATAFILES}

.include <${RULES_MK}>
