$ Trade Secret of Hitachi, Ltd.
$ Do not disclose without written concession from Hitachi, Ltd.
$ Copyright 1996 Hitachi, Ltd. All Rights Reserved.  Derechos Reservados.

$
$
$ setdfakey
$

$ setdfakey command 
1300	KDDS01300-E Failed to open Master Key File: File has no access right.\n
1301	KDDS01301-E Gateway %s is not registered with Master Key File.\n
1302	KDDS01302-E Agent Administrator is not registered with Master Key File.\n
1303	KDDS01303-E Cannot execute setdfakey command.\n
1304	KDDS01304-E Cannot execute setdfakey command due to unmatched Master Keys.\n
1305	KDDS01305-E Failed to write to Master Key File:\n            %s\n
1306	KDDS01306-E Selected Gateway %s does not exist in /etc/hosts file.\n
1307	KDDS01307-E Agent is running: Cannot execute setdfakey command.\n
1308	KDDS01308-E Unexpected error occurred to setdfakey command.\n            (%s)\n
1309	KDDS01309-E Setlocale failed, continuing with C locale.\n            %s\n
1310	KDDS01310-E Invalid option.\n

$
$ prompt
$

10000	Enter master key:
10001	Re-enter master key:
10002	Not match. Enter master key:
10003	Enter Server name:
10004	%s is not in master key file. New entry (y/n)?:
20003	usage: setdfakey [-a GATEWAY name | -d GATEWAY name | -l]\n

