/*
 * @OSF_COPYRIGHT@
 * COPYRIGHT NOTICE
 * Copyright (c) 1990, 1991, 1992, 1993, 1996 Open Software Foundation, Inc.
 * ALL RIGHTS RESERVED (DCE).  See the file named COPYRIGHT.DCE in the
 * src directory for the full copyright text.
 */
/*
 * HISTORY
 * $Log: es_arrayc.idl,v $
 * Revision 1.1.4.2  1996/03/11  02:13:13  marty
 * 	Update OSF copyright years
 * 	[1996/03/10  19:53:01  marty]
 *
 * Revision 1.1.4.1  1995/12/11  20:04:38  root
 * 	Submit OSF/DCE 1.2.1
 * 	[1995/12/11  19:31:01  root]
 * 
 * Revision 1.1.2.2  1993/08/11  16:25:25  ganni
 * 	tests for new IDL functionality
 * 	[1993/08/11  16:13:54  ganni]
 * 
 * $EndLog$
 */
/*
*/
[
uuid(2ce0a880-f4d3-11c9-b332-08002b111685),
version(0.0)
]
interface es_arrayc
{
const short AO_ARRAY_SIZE = 20;
const long ARRAY_SIZE = 12;
const long STRING_SIZE = 26;    /* Room for the alphabet */

typedef char v1_string_t[STRING_SIZE+1]; /* inline */
typedef v1_string_t array_v1_string_t[ARRAY_SIZE]; /* inline */

void fn_op([in] handle_t *h,
              [in,out] long *m,
              [in,out,max_is(*m)] array_v1_string_t a[]);

void cfmt_op([in] handle_t *h,
              [in,out] long *m,
              [in,out,max_is(*m)] char *aptr);

void open_op([in] handle_t *h,
              [in,out] long *m,
              [in,out] long *p_l,
              [in,out,max_is(*m),last_is(*p_l)] array_v1_string_t a[]);

void op1([in]handle_t h);
}
