#
# @OSF_COPYRIGHT@
# COPYRIGHT NOTICE
# Copyright (c) 1990, 1991, 1992, 1993, 1996 Open Software Foundation, Inc.
# ALL RIGHTS RESERVED (DCE).  See the file named COPYRIGHT.DCE in the
# src directory for the full copyright text.
#
#
# HISTORY
# $Log: Makefile,v $
# Revision 1.1.6.2  1996/03/11  02:13:07  marty
# 	Update OSF copyright years
# 	[1996/03/10  19:52:58  marty]
#
# Revision 1.1.6.1  1995/12/11  20:04:18  root
# 	Submit OSF/DCE 1.2.1
# 	[1995/12/11  19:30:56  root]
# 
# Revision 1.1.4.1  1993/12/28  22:10:07  pellis
# 	Updated for ODE 2.3 make
# 	[1993/12/28  21:53:41  pellis]
# 
# Revision 1.1.2.2  1993/08/11  16:24:49  ganni
# 	tests for new IDL functionality
# 	[1993/08/11  16:13:36  ganni]
# 
# $EndLog$
#

IDLBASE = es_arrayc

OTHER_CLIENT_FILES = client_aux.o client_s.o

.include "../maketest.mk"
