/*
 * @OSF_COPYRIGHT@
 * COPYRIGHT NOTICE
 * Copyright (c) 1990, 1991, 1992, 1993, 1996 Open Software Foundation, Inc.
 * ALL RIGHTS RESERVED (DCE).  See the file named COPYRIGHT.DCE in the
 * src directory for the full copyright text.
 */
/*
 * HISTORY
 * $Log: pointed.idl,v $
 * Revision 1.1.4.2  1996/03/11  02:17:19  marty
 * 	Update OSF copyright years
 * 	[1996/03/10  19:54:52  marty]
 *
 * Revision 1.1.4.1  1995/12/11  19:28:11  root
 * 	Submit OSF/DCE 1.2.1
 * 	[1995/12/11  19:15:04  root]
 * 
 * Revision 1.1.2.2  1993/01/07  20:43:21  bbelch
 * 	Embedding copyright notice
 * 	[1993/01/06  13:40:42  bbelch]
 * 
 * Revision 1.1  1992/01/19  03:26:47  devrcs
 * 	Initial revision
 * 
 * $EndLog$
 */
/*
*/
[
uuid (52817c7c-ffc4-11c8-8ae4-08002b104860),
pointer_default(ptr)
]
interface pointed
{
    typedef struct this_way_t {
        boolean *p_boolean;
        byte *p_byte;
        char *p_char;
        small *p_small;
        short *p_short;
        long *p_long;
        hyper *p_hyper;
        unsigned small *p_usmall;
        unsigned short *p_ushort;
        unsigned long *p_ulong;
        unsigned hyper *p_uhyper;
        float *p_float;
        double *p_double;
    } this_way_t;
        
    typedef struct that_way_t {
        double *p_double;
        float *p_float;
        unsigned hyper *p_uhyper;
        unsigned long *p_ulong;
        unsigned short *p_ushort;
        unsigned small *p_usmall;
        hyper *p_hyper;
        long *p_long;
        short *p_short;
        small *p_small;
        char *p_char;
        byte *p_byte;
        boolean *p_boolean;
    } that_way_t;

    void new_oper([in] handle_t h,
                  [in, ptr] this_way_t *p_this_way,
                  [in, out, ptr] that_way_t *p_that_way
                 );

}
