/*
 * @OSF_COPYRIGHT@
 * COPYRIGHT NOTICE
 * Copyright (c) 1990, 1991, 1992, 1993, 1996 Open Software Foundation, Inc.
 * ALL RIGHTS RESERVED (DCE).  See the file named COPYRIGHT.DCE in the
 * src directory for the full copyright text.
 */
/*
 * HISTORY
 * $Log: ichar2.idl,v $
 * Revision 1.1.4.2  1996/03/11  02:14:17  marty
 * 	Update OSF copyright years
 * 	[1996/03/10  19:53:30  marty]
 *
 * Revision 1.1.4.1  1995/12/11  20:07:22  root
 * 	Submit OSF/DCE 1.2.1
 * 	[1995/12/11  19:32:13  root]
 * 
 * Revision 1.1.2.2  1993/08/11  16:26:26  ganni
 * 	tests for new IDL functionality
 * 	[1993/08/11  16:14:33  ganni]
 * 
 * $EndLog$
 */
/*
*/
[
uuid(0e939504-5b87-11cc-af1d-08002b3786fb),
version(0.0)
]
interface ichar2
{
    typedef ISO_MULTI_LINGUAL two_byte;

    typedef struct {
        two_byte v;
        two_byte w;
    } tbs_t;

    void op0 ( [in] handle_t h,
               [in] unsigned long s,
               [in] unsigned long dr,
               [out] unsigned long *p_r,
               [in] two_byte x_char,
               [in, ptr] two_byte *p_char,
               [in] tbs_t *p_tbs,
               [in] long sz,
               [out, size_is(sz)] two_byte c_arr[] );

    const long IASIZE = 5;
    const long OASIZE = IASIZE + 1;

    typedef byte one_byte;

    typedef union switch (boolean is_array) arms {
        case FALSE: one_byte scalar;
        case TRUE:  one_byte array[OASIZE];
    } u_t;

    typedef one_byte a_t[IASIZE];

    void op1 ( [in] handle_t h,
               [in] unsigned long s,
               [out] unsigned long *p_r,
               [in, ptr] a_t *p_a,
               [in, out] u_t *p_u
    );

    const long A2SIZE = 7;

    typedef two_byte at_t[A2SIZE];

    typedef struct {
        long sz;
        [ptr] two_byte *p_sc;
        [unique] at_t *p_ua;
        [ref] at_t *p_ra;
        [size_is(sz)] two_byte ca[];
    } is2_t;

    typedef struct {
        [ref] two_byte *p_sc;
        [ref] at_t *p_ua;
        [ref] at_t *p_ra;
        [ref] at_t *p_ca;
    } os2_t;

    void op2 ( [in] handle_t h,
               [in] unsigned long s,
               [in] unsigned long dr,
               [out] unsigned long *p_r,
               [in] is2_t *is2,
               [out] os2_t *os2
            );

    typedef byte nc_byte;

    typedef nc_byte nc1_array_t[IASIZE];
    typedef [ref] nc1_array_t *nc_arptr_t;

    typedef [unique] nc_byte *nc_uptr_t;

    void op3 ( [in] handle_t h,
               [in] unsigned long s,
               [in, out] unsigned long *p_r,
               [in] nc_arptr_t ara[IASIZE],
               [in, out] nc_uptr_t a2u[IASIZE][IASIZE]
            );

}
