#
# @OSF_COPYRIGHT@
# COPYRIGHT NOTICE
# Copyright (c) 1996 Open Software Foundation, Inc.
# ALL RIGHTS RESERVED (DCE).  See the file named COPYRIGHT.DCE for
# the full copyright text.
#
# HISTORY
# $Log: Makefile,v $
# Revision 1.1.2.2  1996/10/03  18:42:13  arvind
# 	Add OSF copyright
# 	[1996/05/24  23:34 UTC  sommerfeld  /main/DCE_1.2.2/1]
#
# 	Merge from DCE_1.2
# 	[1996/05/24  23:34 UTC  sommerfeld  /main/DCE_1.2.2/1]
#
# Revision 1.1.2.1  1996/06/05  14:19:18  arvind
# 	Merge from DCE_1.2
# 	[1996/05/24  23:34 UTC  sommerfeld  /main/DCE_1.2.2/1]
# 
# $EndLog$
#
SUBDIRS = 1.0_to_1.1 1.1_to_1.0

.include <${RULES_MK}>
