# @OSF_COPYRIGHT@
# COPYRIGHT NOTICE
# Copyright (c) 1996 Open Software Foundation, Inc.
# ALL RIGHTS RESERVED (DCE).  See the file named COPYRIGHT.DCE for
# the full copyright text.
# 
# HISTORY
# $Log: Makefile,v $
# Revision 1.1.4.2  1996/03/09  20:46:00  marty
# 	Add OSF copyright
# 	[1996/03/09  20:25:19  marty]
#
# Revision 1.1.4.1  1995/12/13  21:55:15  root
# 	Submit OSF/DCE 1.2.1
# 
# 	HP revision /main/HPDCE02/1  1995/05/25  15:07 UTC  mothra
# 	for non-tet tests
# 	[1995/12/13  21:53:36  root]
# 
# $EndLog$
#
#

SUBDIRS		= invalid valid

.include <${RULES_MK}>
