/*
 * @OSF_COPYRIGHT@
 * COPYRIGHT NOTICE
 * Copyright (c) 1990, 1991, 1992, 1993, 1996 Open Software Foundation, Inc.
 * ALL RIGHTS RESERVED (DCE).  See the file named COPYRIGHT.DCE in the
 * src directory for the full copyright text.
 */
/*
 * HISTORY
 * $Log: cover1.idl,v $
 * Revision 1.1.4.2  1996/03/11  02:11:18  marty
 * 	Update OSF copyright years
 * 	[1996/03/10  19:52:18  marty]
 *
 * Revision 1.1.4.1  1995/12/11  20:00:53  root
 * 	Submit OSF/DCE 1.2.1
 * 	[1995/12/11  19:29:41  root]
 * 
 * Revision 1.1.2.2  1993/01/07  19:50:22  bbelch
 * 	Embedding copyright notice
 * 	[1993/01/06  13:30:34  bbelch]
 * 
 * Revision 1.1  1992/01/19  03:31:36  devrcs
 * 	Initial revision
 * 
 * $EndLog$
 */
/*
*/
[uuid(35b10100-3c08-11c9-acd6-08002b13d56d), 
 pointer_default(ptr),
 version(0)
]
interface cover1
{
    typedef pipe char pipe_of_chars;

    void in_pipe_op([in] handle_t h, 
                  [in] pipe_of_chars in_pipe
                  );

    void out_pipe_op([in] handle_t h, 
                  [out] pipe_of_chars out_pipe
                  );

    typedef struct twochars_t {
        char upper;
        char lower;
    } twochars_t;

    typedef struct tc_link_t {
        struct tc_link_t *p_link;
        twochars_t *p_tc;
    } tc_link_t;

    void sp_pa_op([in] handle_t h, 
                 [in] tc_link_t *p_in_tc_link,
                 [out] tc_link_t **p_p_out_tc_link);

    /* Test extended to cover bug found by DTSS. AIH 1991-03-25 */
    const long DTB_ELT_COUNT = 10;
    typedef struct dtb_elt_struct {
        long a;
        long b;
    } dtb_elt_struct;

    typedef struct dtb_param_struct {
        short count;
        dtb_elt_struct elts[DTB_ELT_COUNT];
    } dtb_param_struct;

    void dtb_op ([in] handle_t h,
                 [out] dtb_param_struct *dtbp,
                 [out] error_status_t *status
                );

}
