
/*
 * @OSF_COPYRIGHT@
 * COPYRIGHT NOTICE
 * Copyright (c) 1990, 1991, 1992, 1993, 1994, 1996 Open Software Foundation, Inc.
 * ALL RIGHTS RESERVED (DCE).  See the file named COPYRIGHT.DCE for
 * the full copyright text.
 *
 */
/*
 * HISTORY
 * $Log: dtapi_1_srvr.idl,v $
 * Revision 1.1.4.2  1996/03/11  02:29:38  marty
 * 	Update OSF copyright years
 * 	[1996/03/10  19:37:22  marty]
 *
 * Revision 1.1.4.1  1995/12/11  15:18:09  root
 * 	Submit
 * 	[1995/12/11  14:33:04  root]
 * 
 * 	Submit OSF/DCE 1.2.1
 * 	[1995/12/08  23:18:17  root]
 * 
 * Revision 1.1.2.1  1994/09/28  21:47:43  melman
 * 	moved admin tests to test/functional
 * 	[1994/09/28  21:15:22  melman]
 * 
 * Revision 1.1.2.2  1994/08/10  19:22:46  annie
 * 	expand copyright with OSF copyright text
 * 	[1994/08/10  17:17:06  annie]
 * 
 * Revision 1.1.2.1  1994/07/20  19:57:45  ganni
 * 	initial version
 * 	[1994/07/20  19:37:37  ganni]
 * 
 * $EndLog$
 */

/*
** Module:      dtapi_1_srvr.idl
**
** FACILITY:    DCE Host Daemon API
**
** ABSTRACT:    This module defines the test interface
**		for dced api (server services) tests.
**
*/

/******************************************************************************/

[
    uuid(002d2117-7062-1dd2-a9bb-0000c03cd04c),
    version(1.0)
]
interface  dtapi_1_srvr
{

	const unsigned long	RESULT_1 = 4;
	error_status_t dtapi_10( 
		[in] handle_t		handle,
		[in] unsigned long 	x,
		[out] unsigned long 	*y
	);

	void stop_server( 
		[in] handle_t		handle,
		[out] error_status_t	*st
	);

}

