/*
 * @OSF_COPYRIGHT@
 * COPYRIGHT NOTICE
 * Copyright (c) 1996 Open Software Foundation, Inc.
 * ALL RIGHTS RESERVED (DCE).  See the file named COPYRIGHT.DCE for
 * the full copyright text.
 * 
 */
/*
 * HISTORY
 * $Log: rpc_ss_lm.idl,v $
 * Revision 1.1.3.2  1996/03/11  14:09:23  marty
 * 	Update OSF copyright years.
 * 	[1996/03/11  13:58:28  marty]
 *
 * Revision 1.1.3.1  1995/12/13  17:24:59  root
 * 	Submit OSF/DCE 1.2.1
 * 	[1995/12/13  17:24:02  root]
 * 
 * 	Submit OSF/DCE 1.2.1
 * 	[1995/12/13  17:23:35  root]
 * 
 * Revision 1.1.2.1  1995/11/01  14:22:25  bfc
 * 	idl cleanup
 * 	[1995/11/01  14:21:22  bfc]
 * 
 * $EndLog$
 */
/*
**++
**  Copyright (c) 1991 by
**  Digital Equipment Corporation, Maynard, Mass.
**  All Rights Reserved.  Unpublished rights reserved
**  under the copyright laws of the United States.
**
**  The software contained on this media is proprietary
**  to and embodies the confidential technology of
**  Digital Equipment Corporation.  Possession, use,
**  duplication or dissemination of the software and
**  media is authorized only pursuant to a valid written
**  license from Digital Equipment Corporation.
**
**  RESTRICTED RIGHTS LEGEND   Use, duplication, or
**  disclosure by the U.S. Government is subject to
**  restrictions as set forth in Subparagraph (c)(1)(ii)
**  of DFARS 252.227-7013, or in FAR 52.227-19, as
**  applicable.
**
**  NAME:
**
**      rpc_ss_lm.idl
**
**  FACILITY:
**
**      Log manager component of IDL Stub Runtime Support
**
**  ABSTRACT:
**
**      Provides interface for remote management of event log and
**      definitions of event log description datatypes.
**
**  MODIFICATION HISTORY:
**
**  13-Jan-92 harrow    Initial Version.
**--
*/
[uuid(E2AE5DAC-CF82-11CA-A918-08002B0ED678),
 pointer_default(ptr),
 version(0.1)]
interface rpc_ss_lm
{
    /* Filename description */
    const unsigned long rpc_ss_c_lm_string_max = 1000;

    /* Possible errors returned by event manager */
    const unsigned long rpc_ss_c_lm_error_ok = 0;
    const unsigned long rpc_ss_c_lm_error_string = 1;
    
    /* Modify log parameters */
    unsigned long rpc_ss_modify_log (
        [in] handle_t lm_handle,

        [in] boolean change_file,
                /* If true, change log file to log_file_name */

        [in,out,string] char log_file_name[rpc_ss_c_lm_string_max],
                /* If change_file then argument to change the log file name. */

        [in] boolean change_events,
                /* If true, reset logged events to event_flags */

        [in,out] unsigned long *event_flags,
                /* Optional set of flags that can be used to start/stop all */
                /* or a portion of the logging without changing the log     */
                /* file                                                     */

        [out,string] char error_message[rpc_ss_c_lm_string_max]
                /* additional error diagnostic information                 */
        );
}
