# @OSF_COPYRIGHT@
# COPYRIGHT NOTICE
# (c) Copyright International Business Machines Corp. 1994, 1996
# Copyright (c) 1990, 1991, 1992, 1993, 1994, 1996 Open Software Foundation, Inc.
# ALL RIGHTS RESERVED (DCE).  See the file named COPYRIGHT.DCE for
# the full copyright text.
# 
# HISTORY
# $Log: Makefile,v $
# Revision 1.1.6.1  1996/07/09  15:12:42  arvind
# 	Audit for 1.2.2
# 	[1996/06/21  20:30 UTC  arvind  /main/arvind_audit122/1]
#
# 	Audit for 1.2.2
# 	[1996/03/11  02:36:12  marty  1.1.4.2]
#
# Revision 1.1.4.2  1996/03/11  02:36:12  marty
# 	Update OSF copyright years
# 	[1996/03/10  20:04:21  marty]
# 
# Revision 1.1.4.1  1995/12/11  21:51:53  root
# 	Submit OSF/DCE 1.2.1
# 	[1995/12/11  20:53:53  root]
# 
# Revision 1.1.2.3  1994/06/10  20:46:19  devsrc
# 	cr10872 - fixed copyright
# 	[1994/06/10  17:17:30  devsrc]
# 
# Revision 1.1.2.2  1994/04/18  19:40:27  zeliff
# 	ot10386: minor makefile cleanup
# 	[1994/04/18  19:31:35  zeliff]
# 
# Revision 1.1.2.1  1994/04/13  21:58:34  weisz
# 	first submission
# 	[1994/04/13  19:13:26  weisz]
# 
# $EndLog$


IDIR		= /test/tet/functional/security/audit/ts/cp_filter/

ILIST		= cp_filter
IMODE		= 755

.include <${RULES_MK}>
