/*
 * @OSF_COPYRIGHT@
 * COPYRIGHT NOTICE
 * Copyright (c) 1990, 1991, 1992, 1993, 1996 Open Software Foundation, Inc.
 * ALL RIGHTS RESERVED (DCE).  See the file named COPYRIGHT.DCE in the
 * src directory for the full copyright text.
 */
/*
 * HISTORY
 * $Log: struct_ct_union.idl,v $
 * Revision 1.1.4.2  1996/03/11  02:19:14  marty
 * 	Update OSF copyright years
 * 	[1996/03/10  19:55:57  marty]
 *
 * Revision 1.1.4.1  1995/12/11  19:30:49  root
 * 	Submit OSF/DCE 1.2.1
 * 	[1995/12/11  19:16:16  root]
 * 
 * Revision 1.1.2.2  1993/01/07  23:39:35  bbelch
 * 	Embedding copyright notice
 * 	[1993/01/06  13:45:58  bbelch]
 * 
 * Revision 1.1  1992/01/19  03:30:06  devrcs
 * 	Initial revision
 * 
 * $EndLog$
 */
/*
*/
[pointer_default(ptr), uuid(5ce93300-73ee-11c9-817b-08002b0ecef1)]
interface struct_ct_union
/*
 * Test unions as arbitrary fields in a structure.
 */
{
typedef union switch(char sw)
{
case 'l':   long l;
case 's':   short s;
case 'c':   char c;
} first_union_t;

typedef union switch(short sw)
{
case 0:     char c;
case 1:     short s;
case 2:     long l;
default:    double d;
} last_union_t;

typedef union switch(long sw)
{
case 0:     ;   /* Empty arm */
case 1:     struct
            {
                long l;
                first_union_t fu;
                short s;
                last_union_t lu;
                double d;
            } struc;
} middle_union_t;

typedef struct
{
    first_union_t fu;
    char c;
    middle_union_t mu;
    double d;
    last_union_t lu;
} struct_t;

void st_dup
(
    [in] handle_t h,
    [in] struct_t *is,
    [out] struct_t *os
);
}
