/*
 * @OSF_COPYRIGHT@
 * COPYRIGHT NOTICE
 * Copyright (c) 1990, 1991, 1992, 1993, 1996 Open Software Foundation, Inc.
 * ALL RIGHTS RESERVED (DCE).  See the file named COPYRIGHT.DCE in the
 * src directory for the full copyright text.
 */
/*
 * HISTORY
 * $Log: array_v2_string.idl,v $
 * Revision 1.1.4.2  1996/03/11  02:09:02  marty
 * 	Update OSF copyright years
 * 	[1996/03/10  19:51:22  marty]
 *
 * Revision 1.1.4.1  1995/12/11  19:55:57  root
 * 	Submit OSF/DCE 1.2.1
 * 	[1995/12/11  19:28:08  root]
 * 
 * Revision 1.1.2.2  1993/01/07  19:03:49  bbelch
 * 	Embedding copyright notice
 * 	[1993/01/06  13:25:45  bbelch]
 * 
 * Revision 1.1  1992/01/19  03:30:58  devrcs
 * 	Initial revision
 * 
 * $EndLog$
 */
/*
*/
/*
 * Test arrays of strings.
 */
[
uuid(2ce0a880-f4d3-11c9-b332-08002b111685),
version(0.0)
]
interface array_v2_string
{
const long ARRAY_SIZE = 1234;
const long STRING_SIZE = 26;    /* Room for the alphabet */
typedef [string] char v1_string_t[STRING_SIZE+1];
typedef v1_string_t array_v1_string_t[ARRAY_SIZE];

long op8([in] handle_t h, [in,out] array_v1_string_t a);
}
