#
# @OSF_COPYRIGHT@
# COPYRIGHT NOTICE
# Copyright (c) 1990, 1991, 1992, 1993, 1996 Open Software Foundation, Inc.
# ALL RIGHTS RESERVED (DCE).  See the file named COPYRIGHT.DCE in the
# src directory for the full copyright text.
#
#
# HISTORY
# $Log: Makefile,v $
# Revision 1.1.8.2  1996/03/11  02:08:59  marty
# 	Update OSF copyright years
# 	[1996/03/10  19:51:21  marty]
#
# Revision 1.1.8.1  1995/12/11  19:55:54  root
# 	Submit OSF/DCE 1.2.1
# 	[1995/12/11  19:28:07  root]
# 
# Revision 1.1.6.1  1993/12/28  22:09:13  pellis
# 	Updated for ODE 2.3 make
# 	[1993/12/28  21:52:54  pellis]
# 
# Revision 1.1.4.2  1993/01/07  19:03:44  bbelch
# 	Embedding copyright notice
# 	[1993/01/06  13:25:42  bbelch]
# 
# Revision 1.1  1992/01/19  03:31:02  devrcs
# 	Initial revision
# 
# $EndLog$
#

IDLBASE = array_v2_string
OTHER_CLIENT_FILES = client_aux.o

.include "../maketest.mk"
