# @OSF_COPYRIGHT@
# COPYRIGHT NOTICE
# Copyright (c) 1990, 1991, 1992, 1993, 1994, 1996 Open Software Foundation, Inc.
# ALL RIGHTS RESERVED (DCE).  See the file named COPYRIGHT.DCE for
# the full copyright text.
# 
# HISTORY
# $Log: Makefile,v $
# Revision 1.1.4.2  1996/03/11  02:35:49  marty
# 	Update OSF copyright years
# 	[1996/03/10  20:04:11  marty]
#
# Revision 1.1.4.1  1995/12/11  21:50:46  root
# 	Submit OSF/DCE 1.2.1
# 	[1995/12/11  20:53:22  root]
# 
# Revision 1.1.2.5  1994/06/10  20:45:25  devsrc
# 	cr10872 - fixed copyright
# 	[1994/06/10  17:16:57  devsrc]
# 
# Revision 1.1.2.4  1994/04/18  19:40:23  zeliff
# 	ot10386: minor makefile cleanup
# 	[1994/04/18  19:31:29  zeliff]
# 
# Revision 1.1.2.3  1994/04/13  22:34:28  weisz
# 	tetbuild, tetclean appeared in 2 places...
# 	[1994/04/13  22:33:59  weisz]
# 
# Revision 1.1.2.2  1994/04/13  22:25:42  weisz
# 	removed tetbuild.cfg, tetclean.cfg
# 	[1994/04/13  22:25:14  weisz]
# 
# Revision 1.1.2.1  1994/04/13  21:26:40  weisz
# 	CR 10327: initial submission
# 	[1994/04/13  21:25:01  weisz]
# 
# $EndLog$


IDIR	= /test/tet/functional/security/audit/

ILIST		= tet_scen tet_code tetexec.cfg
IMODE		= 755

SUBDIRS         = ts

.include <${RULES_MK}>
