# @OSF_COPYRIGHT@
# COPYRIGHT NOTICE
# Copyright (c) 1990, 1991, 1992, 1993, 1994, 1996 Open Software Foundation, Inc.
# ALL RIGHTS RESERVED (DCE).  See the file named COPYRIGHT.DCE for
# the full copyright text.
# 
# HISTORY
# $Log: Makefile,v $
# Revision 1.1.4.2  1996/03/11  01:53:23  marty
# 	Update copyright years
# 	[1996/03/10  19:50:17  marty]
#
# Revision 1.1.4.1  1995/12/11  17:21:06  root
# 	Submit OSF/DCE 1.2.1
# 	[1995/12/11  17:03:12  root]
# 
# Revision 1.1.2.3  1994/07/06  15:12:31  marrek
# 	July 1994 code drop.
# 	[1994/07/06  12:04:16  marrek]
# 
# Revision 1.1.2.2  1994/06/10  20:25:30  devsrc
# 	cr10872 - fixed copyright
# 	[1994/06/10  17:01:17  devsrc]
# 
# Revision 1.1.2.1  1994/05/10  14:48:37  marrek
# 	Created in April 1994 submission.
# 	[1994/05/03  12:18:35  marrek]
# 
# $EndLog$
#
# $RCSfile: Makefile,v $ $Revision: 1.1.4.2 $ $Date: 1996/03/11 01:53:23 $
#

IDIR = /test/tet/functional/directory/xds/ts/xds/lib/threads_af/

DATAFILES	=		\
			BODYadd_entry32i \
			BODYbind2i \
			BODYcompare7i \
			BODYlist7i \
			BODYmod_entry14i \
			BODYmod_rdn8i \
			BODYread1i \
			BODYrem_entry8i \
			BODYsearch10i \
			BODYunbind1i \
			SHUTDOWNadd_entry32i \
			SHUTDOWNbind2i \
			SHUTDOWNcompare7i \
			SHUTDOWNlist7i \
			SHUTDOWNmod_entry14i \
			SHUTDOWNmod_rdn8i \
			SHUTDOWNread1i \
			SHUTDOWNrem_entry8i \
			SHUTDOWNsearch10i \
			SHUTDOWNunbind1i \
			STARTadd_entry32i \
			STARTbind2i \
			STARTcompare7i \
			STARTlist7i \
			STARTmod_entry14i \
			STARTmod_rdn8i \
			STARTread1i \
			STARTrem_entry8i \
			STARTsearch10i \
			STARTunbind1i \
			T10add_entry32i \
			T10bind2i \
			T10compare7i \
			T10list7i \
			T10mod_entry14i \
			T10mod_rdn8i \
			T10read1i \
			T10rem_entry8i \
			T10search10i \
			T10unbind1i

ILIST		= ${DATAFILES}

.include <${RULES_MK}>
