#
# @OSF_COPYRIGHT@
# COPYRIGHT NOTICE
# Copyright (c) 1990, 1991, 1992, 1993 Open Software Foundation, Inc.
# ALL RIGHTS RESERVED (DCE).  See the file named COPYRIGHT.DCE for
# the full copyright text.
#
# HISTORY
# $Log: Makefile,v $
# Revision 1.1.745.1  1996/10/17  18:23:29  damon
# 	Submitting on behalf of Transarc
# 	[1996/10/17  16:51:56  damon]
#
# Revision 1.1.740.1  1994/02/04  20:42:47  devsrc
# 	Merged from 1.0.3a to 1.1
# 	[1994/02/04  15:23:24  devsrc]
# 
# Revision 1.1.738.2  1994/01/20  18:43:50  annie
# 	added copyright header
# 	[1994/01/20  18:40:07  annie]
# 
# Revision 1.1.738.1  1993/12/07  17:43:03  jaffe
# 	1.0.3a update from Transarc
# 	[1993/12/03  19:06:07  jaffe]
# 
# $EndLog$
#

DATAFILES = stress1.itl stress1.config

ILIST	= ${DATAFILES}

.include <${RULES_MK}>
