# @OSF_COPYRIGHT@
# COPYRIGHT NOTICE
# Copyright (c) 1996 Open Software Foundation, Inc.
# ALL RIGHTS RESERVED (DCE).  See the file named COPYRIGHT.DCE for
# the full copyright text.
# 
# 
# HISTORY
# $Log: Makefile,v $
# Revision 1.1.2.2  1996/03/09  20:47:39  marty
# 	Add OSF copyright
# 	[1996/03/09  20:26:29  marty]
#
# Revision 1.1.2.1  1995/12/11  19:54:14  root
# 	Submit OSF/DCE 1.2.1
# 
# 	HP revision /main/HPDCE02/2  1995/05/11  12:32 UTC  root
# 	fix IDIR
# 
# 	HP revision /main/HPDCE02/1  1995/05/10  14:40 UTC  root
# 	create
# 	[1995/12/11  19:27:31  root]
# 
# $EndLog$

DATAFILES	= run_sec_cpi_test sec_cpi.sh sec_cpi0.sh sec_cpi_unit.sh

ILIST           = ${DATAFILES}
IDIR		= /test/tet/functional/security/ts/server/checkpoint/

.include <${RULES_MK}>
