/*
 * @OSF_COPYRIGHT@
 * COPYRIGHT NOTICE
 * (c) Copyright International Business Machines Corp. 1994, 1996
 * Copyright (c) 1990, 1991, 1992, 1993, 1994, 1996 Open Software Foundation, Inc.
 * ALL RIGHTS RESERVED (DCE).  See the file named COPYRIGHT.DCE for
 * the full copyright text.
 */
/*
 * HISTORY
 * $Log: aud_testec.idl,v $
 * Revision 1.1.6.1  1996/07/09  15:14:21  arvind
 * 	Audit for 1.2.2
 * 	[1996/06/21  20:30 UTC  arvind  /main/arvind_audit122/1]
 *
 * 	Audit for 1.2.2
 * 	[1996/03/11  02:36:16  marty  1.1.4.2]
 *
 * Revision 1.1.4.2  1996/03/11  02:36:16  marty
 * 	Update OSF copyright years
 * 	[1996/03/10  20:04:22  marty]
 * 
 * Revision 1.1.4.1  1995/12/11  21:52:04  root
 * 	Submit OSF/DCE 1.2.1
 * 	[1995/12/11  20:53:58  root]
 * 
 * Revision 1.1.2.2  1994/06/10  20:46:22  devsrc
 * 	cr10872 - fixed copyright
 * 	[1994/06/10  17:17:34  devsrc]
 * 
 * Revision 1.1.2.1  1994/04/20  18:09:19  weisz
 * 	initial submission
 * 	[1994/04/20  18:04:34  weisz]
 * 
 * $EndLog$
 */
[
uuid(0069182e-21e2-1d6c-8b9c-10005a4f578b),
version(1.0)
]

interface aud_testec {

    import "dce/rgynbase.idl";

    void aud_testec_case1 (
        [in] 	handle_t	h,
        [out]	error_status_t  *st
    );

}
