# @OSF_COPYRIGHT@
# COPYRIGHT NOTICE
# Copyright (c) 1996 Open Software Foundation, Inc.
# ALL RIGHTS RESERVED (DCE).  See the file named COPYRIGHT.DCE for
# the full copyright text.
# 
# 
# HISTORY
# $Log: Makefile,v $
# Revision 1.1.2.2  1996/03/11  14:10:42  marty
# 	Update OSF copyright years.
# 	[1996/03/11  13:59:16  marty]
#
# Revision 1.1.2.1  1996/02/28  07:56:23  takano
# 	First Submit
# 	[1996/02/28  07:56:02  takano]
# 
# $EndLog$

#
# Makefile
#
# Trade Secret of Hitachi, Ltd.
# Do not disclose without written concession from Hitachi, Ltd.
# Copyright 1996 Hitachi, Ltd. All Rights Reserved. Derechos Reservados.
#

SUBDIRS		= dfaagtp

.include<${RULES_MK}>

