#
# @OSF_COPYRIGHT@
# COPYRIGHT NOTICE
# Copyright (c) 1990, 1991, 1992, 1993, 1996 Open Software Foundation, Inc.
# ALL RIGHTS RESERVED (DCE).  See the file named COPYRIGHT.DCE in the
# src directory for the full copyright text.
#
#
# HISTORY
# $Log: Makefile,v $
# Revision 1.1.8.2  1996/03/11  02:15:19  marty
# 	Update OSF copyright years
# 	[1996/03/10  19:53:54  marty]
#
# Revision 1.1.8.1  1995/12/11  19:25:36  root
# 	Submit OSF/DCE 1.2.1
# 	[1995/12/11  19:13:55  root]
# 
# Revision 1.1.6.2  1994/05/24  17:57:59  tom
# 	Remove NEED_AUX_FILES since idl no longer gens them
# 	[1994/05/24  16:03:28  tom]
# 
# Revision 1.1.6.1  1993/12/28  22:10:33  pellis
# 	Updated for ODE 2.3 make
# 	[1993/12/28  21:53:59  pellis]
# 
# Revision 1.1.4.2  1993/01/07  20:00:08  bbelch
# 	Embedding copyright notice
# 	[1993/01/06  13:35:28  bbelch]
# 
# Revision 1.1  1992/01/19  03:25:07  devrcs
# 	Initial revision
# 
# $EndLog$
#

IDLBASE = nodethreads
OTHER_CLIENT_FILES = client_aux.o

.include "../maketest.mk"
