/*
 * @OSF_COPYRIGHT@
 * COPYRIGHT NOTICE
 * Copyright (c) 1990, 1991, 1992, 1993, 1996 Open Software Foundation, Inc.
 * ALL RIGHTS RESERVED (DCE).  See the file named COPYRIGHT.DCE in the
 * src directory for the full copyright text.
 */
/*
 * HISTORY
 * $Log: nodethreads.idl,v $
 * Revision 1.1.4.2  1996/03/11  02:15:22  marty
 * 	Update OSF copyright years
 * 	[1996/03/10  19:53:57  marty]
 *
 * Revision 1.1.4.1  1995/12/11  19:25:41  root
 * 	Submit OSF/DCE 1.2.1
 * 	[1995/12/11  19:13:58  root]
 * 
 * Revision 1.1.2.2  1993/01/07  20:31:29  bbelch
 * 	Embedding copyright notice
 * 	[1993/01/06  13:35:38  bbelch]
 * 
 * Revision 1.1  1992/01/19  03:25:05  devrcs
 * 	Initial revision
 * 
 * $EndLog$
 */
/*
*/
[uuid(80f6ebb8-40de-11c9-a5d9-08001e01e1e9), version(0), pointer_default(ptr)]
interface nodethreads
{
    typedef struct list_element {
        struct list_element *link;
        long value;
        long *p_value_1;
        long *p_value_2;
        long *p_value_3;
    } list_element;

    void my_oper( 
        [in] handle_t h,
        [in,out] list_element *p_list
    );

}
