# @OSF_COPYRIGHT@
# COPYRIGHT NOTICE
# Copyright (c) 1990, 1991, 1992, 1993, 1996 Open Software Foundation, Inc.
# ALL RIGHTS RESERVED (DCE).  See the file named COPYRIGHT.DCE in the
# src directory for the full copyright text.
# 
# HISTORY
# $Log: Makefile,v $
# Revision 1.1.9.3  1996/03/09  23:15:02  marty
# 	Update OSF copyright year
# 	[1996/03/09  22:32:19  marty]
#
# Revision 1.1.9.2  1995/12/08  20:54:10  root
# 	Submit OSF/DCE 1.2.1
# 	[1995/12/08  20:49:21  root]
# 
# Revision 1.1.5.1  1994/10/21  19:21:04  weir
# 	Submit sample program sources (CR 12635)
# 	[1994/10/21  19:20:32  weir]
# 
# Revision 1.1.2.1  1994/06/14  20:00:57  weir
# 	DCE 1.1 Beta check-in
# 	[1994/06/14  16:17:52  weir]
# 
# $EndLog$
# 
# 
#----------------------------------------------------------------------------------------
# [23.V.94]
# 
# ODE Makefile for src/examples
# 
# 
#----------------------------------------------------------------------------------------

ILIST	= README

IDIR	= /usr/examples/

IMODE	= 644

SUBDIRS = timop svc/timop_svc svc/hello_svc demo/context_app demo/data_test_app \
	demo/generic_app

# The following line explicitly includes the "common makefiles". For more
#  information, see Chapter 12 of the Porting Guide...

.include <${RULES_MK}>

