# @OSF_COPYRIGHT@
# COPYRIGHT NOTICE
# Copyright (c) 1990, 1991, 1992, 1993, 1994, 1996 Open Software Foundation, Inc.
# ALL RIGHTS RESERVED (DCE).  See the file named COPYRIGHT.DCE for
# the full copyright text.
# 
# 
# HISTORY
# $Log: Makefile,v $
# Revision 1.1.4.2  1996/03/11  13:21:42  marty
# 	Update OSF copyright years
# 	[1996/03/11  13:10:27  marty]
#
# Revision 1.1.4.1  1995/12/08  17:38:21  root
# 	Submit OSF/DCE 1.2.1
# 	[1995/12/08  16:21:04  root]
# 
# Revision 1.1.2.2  1994/06/10  21:08:32  devsrc
# 	cr10871 - fix copyright
# 	[1994/06/10  14:51:37  devsrc]
# 
# Revision 1.1.2.1  1994/03/23  15:37:23  keutel
# 	creation
# 	[1994/03/21  13:38:19  keutel]
# 
# $EndLog$
#
#
#
# @SNI_COPYRIGHT@
#
# $RCSfile: Makefile,v $ $Revision: 1.1.4.2 $ $Date: 1996/03/11 13:21:42 $
#

SUBDIRS		= roliby
EXPLIB_SUBDIRS	= roliby

.include <${RULES_MK}>
