/*
 * @OSF_COPYRIGHT@
 * COPYRIGHT NOTICE
 * Copyright (c) 1990, 1991, 1992, 1993, 1996 Open Software Foundation, Inc.
 * ALL RIGHTS RESERVED (DCE).  See the file named COPYRIGHT.DCE in the
 * src directory for the full copyright text.
 */
/*
 * HISTORY
 * $Log: pointarray.idl,v $
 * Revision 1.1.4.2  1996/03/11  02:17:14  marty
 * 	Update OSF copyright years
 * 	[1996/03/10  19:54:50  marty]
 *
 * Revision 1.1.4.1  1995/12/11  19:28:02  root
 * 	Submit OSF/DCE 1.2.1
 * 	[1995/12/11  19:15:01  root]
 * 
 * Revision 1.1.2.2  1993/01/07  20:42:46  bbelch
 * 	Embedding copyright notice
 * 	[1993/01/06  13:40:27  bbelch]
 * 
 * Revision 1.1  1992/01/19  03:26:40  devrcs
 * 	Initial revision
 * 
 * $EndLog$
 */
/*
*/
[
uuid (52817c7c-ffc4-11c8-8ae4-08002b104860),
pointer_default(ptr)
]
interface pointarray
{
    typedef unsigned short us33[3][3];

    void my_oper( [in] handle_t h,
                 [in,out] us33 **p_p_array);
}
