# @OSF_COPYRIGHT@
# COPYRIGHT NOTICE
# Copyright (c) 1990, 1991, 1992, 1993, 1994, 1996 Open Software Foundation, Inc.
# ALL RIGHTS RESERVED (DCE).  See the file named COPYRIGHT.DCE for
# the full copyright text.
# 
# 
# HISTORY
# $Log: Makefile,v $
# Revision 1.1.4.2  1996/03/11  02:28:48  marty
# 	Update OSF copyright years
# 	[1996/03/10  19:36:55  marty]
#
# Revision 1.1.4.1  1995/12/11  15:17:18  root
# 	Submit
# 	[1995/12/11  14:32:45  root]
# 
# 	Submit OSF/DCE 1.2.1
# 	[1995/12/08  23:17:51  root]
# 
# Revision 1.1.2.1  1994/09/28  21:47:07  melman
# 	moved admin tests to test/functional
# 	[1994/09/28  21:14:56  melman]
# 
# Revision 1.1.2.2  1994/07/08  16:57:00  rousseau
# 	More utc tests.
# 	[1994/07/08  16:56:39  rousseau]
# 
# Revision 1.1.2.1  1994/07/06  15:22:24  rousseau
# 	Initial utc tests.
# 	[1994/07/06  15:21:53  rousseau]
# 
# $EndLog$
UTC_FILES	= utc_add_N.tcl utc_add_P.tcl \
		  utc_compare_N.tcl utc_compare_P.tcl \
		  utc_convert_N.tcl utc_convert_P.tcl \
		  utc_multiply_N.tcl utc_multiply_P.tcl \
		  utc_subtract_N.tcl utc_subtract_P.tcl
IDIR		= /test/tet/functional/admin/dcecp/ts/utc/
ILIST		= ${UTC_FILES}
DATAFILES	= ${UTC_FILES}
IMODE		= 755

.include <${RULES_MK}>
