#!/bin/ksh
#
# @OSF_COPYRIGHT@
# COPYRIGHT NOTICE
# Copyright (c) 1990, 1991, 1992, 1993, 1994, 1996 Open Software Foundation, Inc.
# ALL RIGHTS RESERVED (DCE).  See the file named COPYRIGHT.DCE for
# the full copyright text.
# 
# HISTORY
# $Log: gdscp_all,v $
# Revision 1.1.4.2  1996/03/11  02:35:00  marty
# 	Update OSF copyright years
# 	[1996/03/10  19:40:20  marty]
#
# Revision 1.1.4.1  1995/12/11  15:25:40  root
# 	Submit
# 	[1995/12/11  14:36:07  root]
# 
# Revision 1.1.2.6  1994/07/15  16:58:20  keutel
# 	OT 11316: unsetting of XDS_LOG and D2_LOG removed
# 	[1994/07/15  15:29:42  keutel]
# 
# Revision 1.1.2.5  1994/07/06  15:54:03  marrek
# 	Add version string in July 1994 code drop.
# 	[1994/07/06  15:42:20  marrek]
# 
# Revision 1.1.2.4  1994/06/21  14:29:19  marrek
# 	June 1994 code submission.
# 	[1994/06/16  07:49:53  marrek]
# 
# Revision 1.1.2.3  1994/06/10  20:20:53  devsrc
# 	cr10872 - fixed copyright
# 	[1994/06/10  16:59:13  devsrc]
# 
# Revision 1.1.2.2  1994/05/18  22:09:49  zeliff
# 	missed one fix
# 	[1994/05/16  19:18:02  zeliff]
# 
# 	ot10648: fix problem with error checking
# 	[1994/05/16  19:14:53  zeliff]
# 
# Revision 1.1.2.1  1994/05/10  14:33:10  marrek
# 	Updated from old test subdir.
# 	[1994/05/10  09:35:26  marrek]
# 
# $EndLog$
#
# $RCSfile: gdscp_all,v $ $Revision: 1.1.4.2 $ $Date: 1996/03/11 02:35:00 $
#
#  (c) Copyright 1991,1992-1994 Siemens-Nixdorf Information Systems
#  Munich, Germany
#  All Rights Reserved
#
#
# gdscp
# NAME gdscp
#
# DESC
# {
# GDSCP Tests 
# Each invocable component runs the 'gdscp' executable 
# Also, the DIT must already contain at least the two following object:
#  DSA1:        /C=de/O=dbp/OU=dap11/CN=dsa/CN=dsa-m1
#  DSA2:        /C=de/O=dbp/OU=dap11/CN=dsa/CN=dsa-m2
# }
#

tet_startup="Startup"			# startup function
tet_cleanup="Cleanup"			# cleanup function

iclist="ic1"

ic1="tp1"				# functions for ic1

tp1() {
        tet_infoline "GDSCP tests"
        ksh gdscp_test.sh > /tmp/test_trace 2>&1
        check_ERROR_gdscp "/tmp/test_trace" 
}


Cleanup() {
        rm -f /tmp/test_trace
        rm -f ${TET_EXECUTE}/gdscp/*.log
        rm -f ${TET_EXECUTE}/gdscp/save*
	tet_infoline "TESTING (GDSCP) with GDSCP_TEST FINISHED"
}

Startup() {
	export_paths
	rm -f /tmp/test_trace
	tet_infoline "TESTING (GDSCP) with GDSCP_TEST STARTED"
        . ${TET_EXECUTE}/config/config_gds-admin_cache.sh
}


#source shell common functions
. ${TET_EXECUTE}/lib/shfuncs

#execute shell test case manager - must be last line
. ${TET_ROOT}/lib/xpg3sh/tcm.sh

