/*
 * @OSF_COPYRIGHT@
 * COPYRIGHT NOTICE
 * (c) Copyright International Business Machines Corp. 1994, 1996
 * Copyright (c) 1990, 1991, 1992, 1993, 1994, 1996 Open Software Foundation, Inc.
 * ALL RIGHTS RESERVED (DCE).  See the file named COPYRIGHT.DCE for
 * the full copyright text.
 */
/*
 * HISTORY
 * $Log: aud_testf.idl,v $
 * Revision 1.1.6.1  1996/07/09  15:06:15  arvind
 * 	Audit for 1.2.2
 * 	[1996/06/21  20:28 UTC  arvind  /main/arvind_audit122/1]
 *
 * 	Audit for 1.2.2
 * 	[1996/03/11  02:35:56  marty  1.1.4.2]
 *
 * Revision 1.1.4.2  1996/03/11  02:35:56  marty
 * 	Update OSF copyright years
 * 	[1996/03/10  20:04:14  marty]
 * 
 * Revision 1.1.4.1  1995/12/11  21:51:12  root
 * 	Submit OSF/DCE 1.2.1
 * 	[1995/12/11  20:53:33  root]
 * 
 * Revision 1.1.2.2  1994/06/10  20:45:29  devsrc
 * 	cr10872 - fixed copyright
 * 	[1994/06/10  17:17:03  devsrc]
 * 
 * Revision 1.1.2.1  1994/04/28  18:33:21  weisz
 * 	CR 10402: initial submission
 * 	[1994/04/28  17:50:27  weisz]
 * 
 * $EndLog$
 */
[
uuid(0069182e-21e2-1d6c-8b9c-10005a4f578b),
version(1.0)
]

interface aud_testf {

    import "dce/rgynbase.idl";

    void aud_testf_case1 (
        [in] 	handle_t	h,
        [out]	error_status_t  *st
    );

    void aud_testf_case2 (
        [in] 	handle_t	h,
        [out]	error_status_t  *st
    );

    void aud_testf_case3 (
        [in] 	handle_t	h,
        [out]	error_status_t  *st
    );

    void aud_testf_case4 (
        [in] 	handle_t	h,
        [out]	error_status_t  *st
    );

    void aud_testf_case5 (
        [in] 	handle_t	h,
        [out]	error_status_t  *st
    );

    void aud_testf_case6 (
        [in] 	handle_t	h,
        [out]	error_status_t  *st
    );

    void aud_testf_case7 (
        [in] 	handle_t	h,
        [out]	error_status_t  *st
    );

    void aud_testf_case8 (
        [in] 	handle_t	h,
        [out]	error_status_t  *st
    );

    void aud_testf_case9 (
        [in] 	handle_t	h,
        [out]	error_status_t  *st
    );

    void aud_testf_case10 (
        [in] 	handle_t	h,
        [out]	error_status_t  *st
    );

    void aud_testf_case11 (
        [in] 	handle_t	h,
        [out]	error_status_t  *st
    );
}
