/*
 * @OSF_COPYRIGHT@
 * COPYRIGHT NOTICE
 * Copyright (c) 1990, 1991, 1992, 1993, 1996 Open Software Foundation, Inc.
 * ALL RIGHTS RESERVED (DCE).  See the file named COPYRIGHT.DCE in the
 * src directory for the full copyright text.
 */
/*
 * HISTORY
 * $Log: bigtest1.idl,v $
 * Revision 1.1.4.2  1996/03/11  02:09:47  marty
 * 	Update OSF copyright years
 * 	[1996/03/10  19:51:40  marty]
 *
 * Revision 1.1.4.1  1995/12/11  19:57:30  root
 * 	Submit OSF/DCE 1.2.1
 * 	[1995/12/11  19:28:39  root]
 * 
 * Revision 1.1.2.2  1993/01/07  19:07:56  bbelch
 * 	Embedding copyright notice
 * 	[1993/01/06  13:27:44  bbelch]
 * 
 * Revision 1.1  1992/01/19  03:23:48  devrcs
 * 	Initial revision
 * 
 * $EndLog$
 */
/*
*/
[
uuid (52817c7c-ffc4-11c8-8ae4-08002b104860),
pointer_default(ptr)
]
interface bigtest1
{
    typedef struct confstruct_t {
        unsigned long s;
        [size_is(s)] long a[];
    } confstruct_t;

    typedef enum {ptr_k, count_k, sum_k} discrim_t;
    
    typedef union switch (discrim_t discrim) ub {
        case ptr_k:
            confstruct_t *ptr;
        case count_k:
            unsigned short count;
        case sum_k:
            long sum;
    } x_union_t;

    typedef struct varstruct_t {
        unsigned long f;
        unsigned long l;
        [first_is(f),last_is(l)] x_union_t x[25];
    } varstruct_t;

    void op0 ( [in]handle_t h,
               [in,out] varstruct_t *ptrtosum[5][5],
               [in,out] varstruct_t *counttoptr[5][5]
    );
}
