# @OSF_COPYRIGHT@
# COPYRIGHT NOTICE
# Copyright (c) 1990, 1991, 1992, 1993, 1994, 1996 Open Software Foundation, Inc.
# ALL RIGHTS RESERVED (DCE).  See the file named COPYRIGHT.DCE for
# the full copyright text.
# 
# HISTORY
# $Log: Makefile,v $
# Revision 1.1.4.2  1996/03/11  02:35:48  marty
# 	Update OSF copyright years
# 	[1996/03/10  19:41:03  marty]
#
# Revision 1.1.4.1  1995/12/11  15:26:43  root
# 	Submit
# 	[1995/12/11  14:36:29  root]
# 
# Revision 1.1.2.3  1994/07/06  15:11:23  marrek
# 	July 1994 code drop.
# 	[1994/07/06  12:03:23  marrek]
# 
# Revision 1.1.2.2  1994/06/10  20:22:00  devsrc
# 	cr10872 - fixed copyright
# 	[1994/06/10  16:59:41  devsrc]
# 
# Revision 1.1.2.1  1994/05/10  14:34:07  marrek
# 	Created in April 1994 submission.
# 	[1994/05/03  12:15:15  marrek]
# 
# $EndLog$
#
# $RCSfile: Makefile,v $ $Revision: 1.1.4.2 $ $Date: 1996/03/11 02:35:48 $
#

IDIR    = /test/tet/functional/directory/gds/ts/gdscp/lib/x500obj/invalid/
ILIST		= 				\
			obj_bind_i.tcl		\
			obj_compare_i.tcl	\
			obj_create_i.tcl	\
			obj_cwo_i.tcl		\
			obj_delete_i.tcl	\
			obj_general_i.tcl	\
			obj_help_i.tcl		\
			obj_list_i.tcl		\
			obj_modify_i.tcl	\
			obj_operations_i.tcl	\
			obj_search_i.tcl	\
			obj_show_i.tcl

.include <${RULES_MK}>
