/*
 * @OSF_COPYRIGHT@
 * COPYRIGHT NOTICE
 * Copyright (c) 1990, 1991, 1992, 1993, 1994, 1996 Open Software Foundation, Inc.
 * ALL RIGHTS RESERVED (DCE).  See the file named COPYRIGHT.DCE for
 * the full copyright text.
 * 
 */
/*
 * HISTORY
 * $Log: dummy_if.idl,v $
 * Revision 1.1.4.2  1996/03/11  02:06:40  marty
 * 	Update OSF copyright years
 * 	[1996/03/10  19:50:24  marty]
 *
 * Revision 1.1.4.1  1995/12/11  19:51:49  root
 * 	Submit OSF/DCE 1.2.1
 * 	[1995/12/11  19:26:33  root]
 * 
 * 	Submit OSF/DCE 1.2.1
 * 	[1995/12/11  18:17:57  root]
 * 
 * Revision 1.1.2.2  1994/06/10  20:44:23  devsrc
 * 	cr10872 - fixed copyright
 * 	[1994/06/10  17:16:13  devsrc]
 * 
 * Revision 1.1.2.1  1994/05/04  21:54:48  mori_m
 * 	CR 9701: RPC runtime I18N extension functional test drop.
 * 	[1994/05/04  21:17:18  mori_m]
 * 
 * $EndLog$
 */
[
uuid(83474732-b786-11cc-ad0f-08000925d3fe),
version(1.0)
]
interface dummy_if
{
	const unsigned short ARR = 10;
	typedef long long_array[ARR];

	void sum_arrays (
		[in] long_array a,
		[out] long_array b );
}
