/*
 * @OSF_COPYRIGHT@
 * COPYRIGHT NOTICE
 * Copyright (c) 1990, 1991, 1992, 1993, 1996 Open Software Foundation, Inc.
 * ALL RIGHTS RESERVED (DCE).  See the file named COPYRIGHT.DCE in the
 * src directory for the full copyright text.
 */
/*
 * HISTORY
 * $Log: config.h,v $
 * Revision 1.1.8.1  1996/11/13  18:03:46  arvind
 * 	CHFts20148: add MD5
 * 	[1996/10/16  23:20 UTC  sommerfeld  /main/sommerfeld_pk_kdc_3/1]
 *
 * Revision 1.1.6.2  1996/02/18  23:02:11  marty
 * 	Update OSF copyright years
 * 	[1996/02/18  22:20:37  marty]
 * 
 * Revision 1.1.6.1  1995/12/08  17:41:25  root
 * 	Submit OSF/DCE 1.2.1
 * 	[1995/12/08  16:56:54  root]
 * 
 * Revision 1.1.3.3  1992/12/29  13:58:06  zeliff
 * 	Embedding copyright notice
 * 	[1992/12/28  20:51:51  zeliff]
 * 
 * Revision 1.1.3.2  1992/09/29  21:18:51  devsrc
 * 	[OT 5373]    SNI/SVR4 merge.
 * 	[1992/09/11  21:33:04  sekhar]
 * 
 * Revision 1.1  1992/01/19  14:48:31  devrcs
 * 	Initial revision
 * 
 * $EndLog$
 */
/*
*/

/*  config.h V=2 10/23/91 //littl/prgy/krb5/include/krb5
**
** Copyright (c) Hewlett-Packard Company 1991
** Unpublished work. All Rights Reserved.
**
*/
/*
*/

/*  config.h V=MIT-beta1/1 06/06/91 //littl/prgy/krb5/include/krb5/stock
**
** Copyright (c) Hewlett-Packard Company 1991
** Unpublished work. All Rights Reserved.
**
*/
/*
 * (c) Copyright 1991, 1992 Siemens-Nixdorf Information Systems, Burlington, MA, USA
 * All Rights Reserved
 */
/* WARNING: this file is automatically generated; do not edit! */
/*
 * $Source: /u0/rcs_trees/dce/rcs/security/krb5/include/krb5/config.h,v $
 * $Author: arvind $
 * $Id: config.h,v 1.1.8.1 1996/11/13 18:03:46 arvind Exp $
 *
 * Copyright 1990,1991 by the Massachusetts Institute of Technology.
 * All Rights Reserved.
 *
 * Export of this software from the United States of America is assumed
 *   to require a specific license from the United States Government.
 *   It is the responsibility of any person or organization contemplating
 *   export to obtain such a license before exporting.
 * 
 * WITHIN THAT CONSTRAINT, permission to use, copy, modify, and
 * distribute this software and its documentation for any purpose and
 * without fee is hereby granted, provided that the above copyright
 * notice appear in all copies and that both that copyright notice and
 * this permission notice appear in supporting documentation, and that
 * the name of M.I.T. not be used in advertising or publicity pertaining
 * to distribution of the software without specific, written prior
 * permission.  M.I.T. makes no representations about the suitability of
 * this software for any purpose.  It is provided "as is" without express
 * or implied warranty.
 * 
 *
 * Configuration definition file.
 */


#ifndef KRB5_CONFIG__
#define KRB5_CONFIG__



#ifdef SNI_SVR4

#define POSIX_FILE_LOCKS
#define POSIX_TERMIOS
#define POSIX_TYPES
#define POSIX_SIGTYPE

typedef void krb5_sigtype;

#else

typedef int krb5_sigtype;

#endif /* SNI_SVR4 */

#define USE_STRING_H




#define NARROW_PROTOTYPES


#ifdef Bitsize32
#ifdef Bitsize64
 error: only one of BitsizeNN, please.
#endif
#ifdef Bitsize16
 error: only one of BitsizeNN, please.
#endif
#define BITS32
#endif

#ifdef Bitsize16
#ifdef Bitsize64
 error: only one of BitsizeNN, please.
#endif
#ifdef Bitsize32
 error: only one of BitsizeNN, please.
#endif
#define BITS16
#endif

#ifdef Bitsize64
#ifdef Bitsize32
 error: only one of BitsizeNN, please.
#endif
#ifdef Bitsize16
 error: only one of BitsizeNN, please.
#endif
#define BITS64
#endif

/* XXX these should be parameterized soon... */
#define PROVIDE_DES_CBC_CRC
#define PROVIDE_CRC32
#define PROVIDE_DES_CBC_CKSUM
#define PROVIDE_RSA_MD4
#define PROVIDE_RSA_MD5

#define DEFAULT_PWD_STRING1 "Enter password:"
#define DEFAULT_PWD_STRING2 "Re-enter password for verification:"

#define	KRB5_KDB_MAX_LIFE	(60*60*24) /* one day */
#define	KRB5_KDB_MAX_RLIFE	(60*60*24*7) /* one week */
#define	KRB5_KDB_EXPIRATION	2145830400 /* Thu Jan  1 00:00:00 2038 UTC */

#endif /* KRB5_CONFIG__ */

