/*
 * @OSF_COPYRIGHT@
 * COPYRIGHT NOTICE
 * Copyright (c) 1990, 1991, 1992, 1993, 1996 Open Software Foundation, Inc.
 * ALL RIGHTS RESERVED (DCE).  See the file named COPYRIGHT.DCE in the
 * src directory for the full copyright text.
 */
/*
 * HISTORY
 * $Log: osconf.h,v $
 * Revision 1.1.9.2  1996/02/18  23:02:54  marty
 * 	Update OSF copyright years
 * 	[1996/02/18  22:21:26  marty]
 *
 * Revision 1.1.9.1  1995/12/08  17:43:36  root
 * 	Submit OSF/DCE 1.2.1
 * 	[1995/12/08  16:57:18  root]
 * 
 * Revision 1.1.7.1  1993/10/01  17:03:48  hanfei
 * 	[OT 8012] change replay cache files from /usr/tmp to
 * 	/opt/dcelocal/var/security/rcache.
 * 	[1993/10/01  17:03:20  hanfei]
 * 
 * Revision 1.1.4.2  1992/12/29  14:01:18  zeliff
 * 	Embedding copyright notice
 * 	[1992/12/28  20:53:35  zeliff]
 * 
 * Revision 1.1.2.2  1992/06/24  22:22:33  sommerfeld
 * 	Change "kerberos" to "kerberos5" to allow parallel coexistance with krb4.
 * 	[1992/06/22  19:25:01  sommerfeld]
 * 
 * Revision 1.1  1992/01/19  14:48:52  devrcs
 * 	Initial revision
 * 
 * $EndLog$
 */
/*
*/

/*  osconf.h V=2 10/23/91 //littl/prgy/krb5/include/krb5
**
** Copyright (c) Hewlett-Packard Company 1991
** Unpublished work. All Rights Reserved.
**
*/
/* WARNING: this file is automatically generated; do not edit! */
/*
 * $Source: /u0/rcs_trees/dce/rcs/security/krb5/include/krb5/osconf.h,v $
 * $Author: marty $
 * $Id: osconf.h,v 1.1.9.2 1996/02/18 23:02:54 marty Exp $
 *
 * Copyright 1990,1991 by the Massachusetts Institute of Technology.
 * All Rights Reserved.
 *
 * Export of this software from the United States of America is assumed
 *   to require a specific license from the United States Government.
 *   It is the responsibility of any person or organization contemplating
 *   export to obtain such a license before exporting.
 * 
 * WITHIN THAT CONSTRAINT, permission to use, copy, modify, and
 * distribute this software and its documentation for any purpose and
 * without fee is hereby granted, provided that the above copyright
 * notice appear in all copies and that both that copyright notice and
 * this permission notice appear in supporting documentation, and that
 * the name of M.I.T. not be used in advertising or publicity pertaining
 * to distribution of the software without specific, written prior
 * permission.  M.I.T. makes no representations about the suitability of
 * this software for any purpose.  It is provided "as is" without express
 * or implied warranty.
 * 
 *
 * Site- and OS- dependant configuration.
 */


#ifndef KRB5_OSCONF__
#define KRB5_OSCONF__


#define	USE_SYS_TIME_H	/* Needs <sys/time.h> for time includes. */		

#define KRB5_USE_INET		/* Support IP address family */
#define	USE_DBM_LNAME		/* Use a DBM database for the aname/lname
				   conversion */

#define	DEFAULT_CONFIG_FILENAME	"/krb5/krb.conf"
#define	DEFAULT_TRANS_FILENAME	"/krb5/krb.realms"
#define	DEFAULT_LNAME_FILENAME	"/krb5/aname"
#define	DEFAULT_KEYTAB_NAME	"FILE:/krb5/v5srvtab"

#define	DEFAULT_KDC_ETYPE	ETYPE_DES_CBC_CRC
#define	DEFAULT_KDC_KEYTYPE	KEYTYPE_DES
#define KDCRCACHE		"dfl:krb5kdc_rcache"

#define KDC_PORTNAME	"kerberos5"	/* for /etc/services or equiv. */

#define MAX_DGRAM_SIZE	4096
#define MAX_SKDC_TIMEOUT 30
#define SKDC_TIMEOUT_SHIFT 2		/* left shift of timeout for backoff */
#define SKDC_TIMEOUT_1 1		/* seconds for first timeout */

#define RCTMPDIR	"/opt/dcelocal/var/security/rcache"	/* directory to store replay caches */

#endif /* KRB5_OSCONF__ */
