/*
 * @OSF_COPYRIGHT@
 * COPYRIGHT NOTICE
 * Copyright (c) 1990, 1991, 1992, 1993, 1996 Open Software Foundation, Inc.
 * ALL RIGHTS RESERVED (DCE).  See the file named COPYRIGHT.DCE in the
 * src directory for the full copyright text.
 */
/*
 * HISTORY
 * $Log: dtsstime_req.idl,v $
 * Revision 1.1.4.2  1996/03/09  23:31:52  marty
 * 	Update OSF copyright year
 * 	[1996/03/09  22:46:58  marty]
 *
 * Revision 1.1.4.1  1995/12/08  18:14:02  root
 * 	Submit OSF/DCE 1.2.1
 * 	[1995/12/08  17:26:01  root]
 * 
 * Revision 1.1.2.2  1992/12/30  20:43:03  htf
 * 	Embedding copyright notice
 * 	[1992/12/30  19:23:00  htf]
 * 
 * Revision 1.1  1992/01/19  15:34:23  devrcs
 * 	Initial revision
 * 
 * $EndLog$
 */
/*
*/
/*
 * 	Module DTSSTIME_REQ.IDL
 */
/*
 * Copyright (c) 1990 by
 * Digital Equipment Corporation, Maynard, Mass.
 *
 * This software is furnished under a license and may be used and copied
 * only  in  accordance  with  the  terms  of such  license and with the
 * inclusion of the above copyright notice.  This software or any  other
 * copies thereof may not be provided or otherwise made available to any
 * other person.  No title to and ownership of the  software  is  hereby
 * transferred.
 *
 * The information in this software  is subject to change without notice
 * and  should  not be  construed  as a commitment by Digitial Equipment
 * Corporation.
 *
 * Digital assumes no responsibility for the use or  reliablity  of its
 * software on equipment which is not supplied by Digital.

 *
 *
 */


[uuid (019ee420-682d-11c9-a607-08002b0dea7a),
    version(1)
]

interface time_service
{

 import "dce/utctypes.idl";


/*
 * CLERK_REQUEST_TIME
 *
 * This routine handles RPC time requests sent by a clerk to a DTSS 
 * server. The server returns two arguments to the clerk: its current
 * utc time and a processing delay.  Currently there is no mechanism in
 * RPC that can give an accurate measure of the time it takes the
 * server to process the request, but we keep this field here for when
 * such mechanism exists.  Communication errors are reported in 
 * comStatus.
 *
 */

void ClerkRequestTime
	(
	[in]	handle_t  	 bind_h,
	[out]	utc_t		*timeRequest,
	[out]	unsigned long 	*processingDelay,
	[out]	error_status_t	*comStatus
	);

/*
 * SERVER_REQUEST_TIME
 *
 * This routine handles RPC time requests sent by a server to another DTSS 
 * server. The server returns four arguments. The current utc time, a 
 * processing delay, the server's current epoch and its courier role.
 * Communication errors are returned in comStatus.
 *
 */

void ServerRequestTime
	(
	[in]	handle_t  	 bind_h,
	[out]	utc_t		*timeRequest,
	[out]	unsigned long 	*processingDelay,
    	[out]	long int 	*epoch,
    	[out]	long int	*courierRole,
	[out]	error_status_t	*comStatus
	);



} /* end of dtss_service_rpc interface */








