#
# @OSF_COPYRIGHT@
# COPYRIGHT NOTICE
# Copyright (c) 1996 Open Software Foundation, Inc.
# ALL RIGHTS RESERVED (DCE).  See the file named COPYRIGHT.DCE in the
# src directory for the full copyright text.
#
# HISTORY
# $Log: Makefile,v $
# Revision 1.1.2.1  1996/10/03  20:36:26  arvind
# 	OSF DCE 1.2.2 Drop 4
# 	[1996/10/03  19:44:57  arvind]
#
# 	OSF DCE 1.2.2 Drop 4
#
# Revision /main/DCE_1.2.2/1  1996/09/26  23:32 UTC  sommerfeld
# 	Add krb5 tests makefile.
# 	[1996/03/14  20:16 UTC  sommerfeld  /main/sommerfeld_CHFts17713/1]
# 
# $EndLog$

SUBDIRS=simple

.include <${RULES_MK}>
