# @OSF_COPYRIGHT@
# COPYRIGHT NOTICE
# Copyright (c) 1990, 1991, 1992, 1993, 1994, 1996 Open Software Foundation, Inc.
# ALL RIGHTS RESERVED (DCE).  See the file named COPYRIGHT.DCE for
# the full copyright text.
# 
# 
# HISTORY
# $Log: Makefile,v $
# Revision 1.1.4.2  1996/03/09  23:13:51  marty
# 	Update OSF copyright year
# 	[1996/03/09  22:31:09  marty]
#
# Revision 1.1.4.1  1995/12/08  15:58:13  root
# 	Submit OSF/DCE 1.2.1
# 	[1995/12/08  15:12:40  root]
# 
# Revision 1.1.2.3  1994/06/09  18:45:57  devsrc
# 	cr10871 - expand copyright
# 	[1994/06/09  18:18:56  devsrc]
# 
# Revision 1.1.2.2  1994/05/10  15:55:23  marrek
# 	Code submission on April 1994.
# 	[1994/05/03  14:58:23  marrek]
# 
# Revision 1.1.2.1  1994/03/23  15:17:09  keutel
# 	creation
# 	[1994/03/21  12:55:34  keutel]
# 
# $EndLog$
#
# $RCSfile: Makefile,v $ $Revision: 1.1.4.2 $ $Date: 1996/03/09 23:13:51 $
#

INCLUDES  = gdscp.h gctconv.h
EXPDIR    = /usr/include/

.include <${RULES_MK}>
