/*
 * @OSF_COPYRIGHT@
 * COPYRIGHT NOTICE
 * Copyright (c) 1990, 1991, 1992, 1993, 1996 Open Software Foundation, Inc.
 * ALL RIGHTS RESERVED (DCE).  See the file named COPYRIGHT.DCE in the
 * src directory for the full copyright text.
 */
/*
 * HISTORY
 * $Log: bug_3.idl,v $
 * Revision 1.1.4.2  1996/03/11  02:10:31  marty
 * 	Update OSF copyright years
 * 	[1996/03/10  19:52:01  marty]
 *
 * Revision 1.1.4.1  1995/12/11  19:58:59  root
 * 	Submit OSF/DCE 1.2.1
 * 	[1995/12/11  19:29:05  root]
 * 
 * Revision 1.1.2.2  1993/01/07  19:10:17  bbelch
 * 	Embedding copyright notice
 * 	[1993/01/06  13:28:54  bbelch]
 * 
 * Revision 1.1  1992/01/19  03:31:19  devrcs
 * 	Initial revision
 * 
 * $EndLog$
 */
/*
*/
[
    uuid(41058290-f8f2-11c9-aece-08001e0218e9),
    version(0.0)
]
interface bug_3
{
    const char *bug_3_name = "-bug 3 test";

    const boolean bug_3_true  = TRUE;
    const boolean bug_3_false = FALSE;

    boolean bug_3_op0(
        [in]    handle_t    h,
        [in]    boolean     b
    );

    boolean bug_3_op1(
        [in]        handle_t    h,
        [in,out]    boolean     *b
    );
}
