#!/bin/ksh
# @OSF_COPYRIGHT@
# COPYRIGHT NOTICE
# Copyright (c) 1990, 1991, 1992, 1993, 1994, 1996 Open Software Foundation, Inc.
# ALL RIGHTS RESERVED (DCE).  See the file named COPYRIGHT.DCE for
# the full copyright text.
# 
# 
# HISTORY
# $Log: dlg_kta,v $
# Revision 1.1.4.2  1996/03/11  02:47:42  marty
# 	Update OSF copyright years
# 	[1996/03/10  20:08:52  marty]
#
# Revision 1.1.4.1  1995/12/11  22:44:51  root
# 	Submit OSF/DCE 1.2.1
# 	[1995/12/11  22:21:17  root]
# 
# Revision 1.1.2.2  1994/10/06  20:38:24  agd
# 	expand copyright
# 	[1994/10/06  14:30:43  agd]
# 
# Revision 1.1.2.1  1994/08/22  17:56:31  bhaim
# 	submit dlgcfg001
# 	[1994/08/22  17:55:36  bhaim]
# 
# $EndLog$
#set -x
if [ ! -h /usr/bin/dce_login_noexec ] ; then
   ln -fs /opt/dcelocal/bin/dce_login /usr/bin/dce_login_noexec
fi
KRB5CCNAME=`dce_login_noexec cell_admin -dce-`
export KRB5CCNAME
rgy_edit <<EOF
do a
kta -p dlg_svr -pw dlg_svr
EOF

