/*
 * @OSF_COPYRIGHT@
 * COPYRIGHT NOTICE
 * Copyright (c) 1990, 1991, 1992, 1993, 1994, 1996 Open Software Foundation, Inc.
 * ALL RIGHTS RESERVED (DCE).  See the file named COPYRIGHT.DCE for
 * the full copyright text.
*/
/*
 * HISTORY
 * $Log: fmul.idl,v $
 * Revision 1.1.5.2  1996/03/11  02:44:46  marty
 * 	Update OSF copyright years
 * 	[1996/03/10  20:07:42  marty]
 *
 * Revision 1.1.5.1  1995/12/11  22:00:14  root
 * 	Submit OSF/DCE 1.2.1
 * 	[1995/12/11  20:59:23  root]
 * 
 * Revision 1.1.2.2  1994/09/01  19:37:36  rdl
 * 	Changes to fix problems with RPC where multiple servers on one machine
 * 	[1994/09/01  19:36:12  rdl]
 * 
 * Revision 1.1.2.1  1994/08/24  19:44:58  rdl
 * 	Initial submission for dfs.fmul test.
 * 	[1994/08/24  19:44:17  rdl]
 * 
 * $EndLog$
 */

/* fmul.idl */

[
    uuid(8c879efa-aace-11cd-b72c-080009320e26),
    version(1.0)
]

interface fmul
{
typedef [string] char filename_t [256];

[idempotent]

long l_lock(
	[in] handle_t h,
	[in] filename_t filename,
	[in] long start,
	[in] long size,
	[in] char chartowrite,
	[out] long *rc_return,
	[out] long *errno_return
);

long l_tlock(
	[in] handle_t h,
	[in] filename_t filename,
	[in] long start,
	[in] long size,
	[in] char chartowrite,
	[out] long *rc_return,
	[out] long *errno_return
);

long l_test(
	[in] handle_t h,
	[in] filename_t filename,
	[in] long start,
	[in] long size,
	[out] long *rc_return,
	[out] long *errno_return
);

long l_ulock(
	[in] handle_t h,
	[in] filename_t filename,
	[in] long start,
	[in] long size,
	[out] long *rc_return,
	[out] long *errno_return
);

long writeRange(
	[in] handle_t h,
	[in] filename_t filename,
	[in] long start,
	[in] long size,
	[in] char chartowrite,
	[out] long *rc_return,
	[out] long *errno_return
);
}
