/*
 * @OSF_COPYRIGHT@
 * COPYRIGHT NOTICE
 * Copyright (c) 1990, 1991, 1992, 1993, 1996 Open Software Foundation, Inc.
 * ALL RIGHTS RESERVED (DCE).  See the file named COPYRIGHT.DCE in the
 * src directory for the full copyright text.
 */
/*
 * HISTORY
 * $Log: factorial.idl,v $
 * Revision 1.1.4.2  1996/03/11  02:13:34  marty
 * 	Update OSF copyright years
 * 	[1996/03/10  19:53:09  marty]
 *
 * Revision 1.1.4.1  1995/12/11  20:05:19  root
 * 	Submit OSF/DCE 1.2.1
 * 	[1995/12/11  19:31:17  root]
 * 
 * Revision 1.1.2.2  1993/01/07  19:56:10  bbelch
 * 	Embedding copyright notice
 * 	[1993/01/06  13:33:21  bbelch]
 * 
 * Revision 1.1  1992/01/19  03:32:38  devrcs
 * 	Initial revision
 * 
 * $EndLog$
 */
/*
*/
[uuid(6027d280-8792-11c9-8314-08002b13d56d),
 version(0),
 pointer_default(ptr)]
interface factorial
{

    [idempotent] long net_factorial
    (
        [in] handle_t h,
        [in,out] long **n
    );
}
