#!/bin/ksh
# @OSF_COPYRIGHT@
# COPYRIGHT NOTICE
# Copyright (c) 1990, 1991, 1992, 1993, 1996 Open Software Foundation, Inc.
# ALL RIGHTS RESERVED (DCE).  See the file named COPYRIGHT.DCE in the
# src directory for the full copyright text.
# 
# HISTORY
# $Log: clientwait,v $
# Revision 1.1.6.2  1996/03/11  02:46:12  marty
# 	Update OSF copyright years
# 	[1996/03/10  20:08:14  marty]
#
# Revision 1.1.6.1  1995/12/11  22:43:19  root
# 	Submit OSF/DCE 1.2.1
# 
# 	HP revision /main/HPDCE02/1  1994/07/01  13:30 UTC  bissen
# 	Merge hpdce02 (DCE 1.1 beta) and HPDCE01 into HPDCE02
# 
# 	HP revision /main/HPDCE01/2  1994/03/30  16:08 UTC  truitt
# 
# 	HP revision /main/HPDCE01/truitt_junk/1  1994/03/30  15:58 UTC  truitt
# 	Update test to latest tet version
# 
# 	HP revision /main/HPDCE01/1  1994/02/01  18:04  giza
# 	merge kk & hpdce01
# 	[1995/12/11  22:20:18  root]
# 
# Revision 1.1.2.2  1993/08/24  18:47:28  giza
# 	Initial version.
# 	[1993/08/24  18:46:57  giza]
# 
# $EndLog$
#
# waitPid - dummy process used to sync client(s)/server programs

WORKDIR=/tmp/dcerpcrun

print "/bin/kill $$ >/dev/null" >$WORKDIR/clientwait.kill
chmod +x $WORKDIR/clientwait.kill

Ct()
{
  Dt=`date "+%j %H %M %S%n" | awk '
        $1 ~ /[0-9]+/ { day = $1 }
        $2 ~ /[0-9]+/ { hour = $2 }
        $3 ~ /[0-9]+/ { minute = $3 }
        $4 ~ /[0-9]+/ { second = $4 }

        END {
                hour += day * 24
                minute += hour * 60
                second += minute * 60
                printf ("%d\n", minute)
  }'`
}


integer WAITIMEOUT=10            #Maximum time to run process before exiting
integer St=0 tcount=0

Ct
St=$Dt

while (( $tcount < $WAITIMEOUT ))
do
        sleep 30
        Ct
        tcount=$Dt-$St
done
exit 0
