/*
 * @OSF_COPYRIGHT@
 * COPYRIGHT NOTICE
 * Copyright (c) 1990, 1991, 1992, 1993, 1996 Open Software Foundation, Inc.
 * ALL RIGHTS RESERVED (DCE).  See the file named COPYRIGHT.DCE in the
 * src directory for the full copyright text.
 */
/*
 * HISTORY
 * $Log: fpe.idl,v $
 * Revision 1.1.4.2  1996/03/11  02:13:50  marty
 * 	Update OSF copyright years
 * 	[1996/03/10  19:53:17  marty]
 *
 * Revision 1.1.4.1  1995/12/11  20:05:58  root
 * 	Submit OSF/DCE 1.2.1
 * 	[1995/12/11  19:31:34  root]
 * 
 * Revision 1.1.2.2  1993/01/07  19:57:12  bbelch
 * 	Embedding copyright notice
 * 	[1993/01/06  13:33:55  bbelch]
 * 
 * Revision 1.1  1992/01/19  03:24:45  devrcs
 * 	Initial revision
 * 
 * $EndLog$
 */
/*
*/
[pointer_default(ptr), uuid(a6294080-a55e-11c9-9a9f-08002b0ecef1)]
interface fpe
{
/*
 * Temp hack: return fault as status; code will ignore it.  For some reason
 * the set_fpc_csr call in the manager causes an exception that gets mapped
 * to cma_e_SIGFPE.  Should figure out why this is happening someday.
 */
error_status_t setup([in] handle_t h);

void float_overflow([in] handle_t h, [in,out] float *a, [in] float *b);
void float_underflow([in] handle_t h, [in,out] float *a, [in] float *b);
void float_divbyzero([in] handle_t h, [in,out] float *a, [in] float *b);

void double_overflow([in] handle_t h, [in,out] double *a, [in] double *b);
void double_underflow([in] handle_t h, [in,out] double *a, [in] double *b);
void double_divbyzero([in] handle_t h, [in,out] double *a, [in] double *b);
}
