#!/bin/sh

CELL_ADMIN=cell_admin
PASSWORD=-dce-

usage() {
	cat << E_O_F
usage: $0 cell_name
E_O_F
}

setup_aixdce() {
	cell_name=$1

	/etc/dce_config << E_O_F
2
1
1
y
$cell_name
kkk
$CELL_ADMIN
$PASSWORD
$PASSWORD


2

98
3
none
99
E_O_F

}

setup_hpdce() {
	cell_name=$1

	/etc/dce_config << E_O_F
1
1
1
y
$cell_name

kkk
$CELL_ADMIN
$PASSWORD
$PASSWORD


2
n
98
3
none
99
E_O_F

}

setup_hidce() {
	cell_name=$1

	/etc/dce_config << E_O_F
1
1
1
y
$cell_name
y
DES
y
kkk
$CELL_ADMIN
y
$PASSWORD
$PASSWORD



2
n
98
3
none
99
E_O_F

}

#
# main procedure
#
if [ $# -lt 1 ]; then
	usage
	exit
fi

case `uname -s` in
AIX)	setup_aixdce ${1};;
HP-UX)	setup_hpdce ${1};;
HI-UX)	setup_hidce ${1};;
*)
	echo "Sorry.  Cannot support this operating system"
	exit 1
	;;
esac

exit 0
