# @OSF_COPYRIGHT@
# COPYRIGHT NOTICE
# Copyright (c) 1990, 1991, 1992, 1993, 1994, 1996 Open Software Foundation, Inc.
# ALL RIGHTS RESERVED (DCE).  See the file named COPYRIGHT.DCE for
# the full copyright text.
# 
# 
# HISTORY
# $Log: Makefile,v $
# Revision 1.1.6.4  1996/11/13  17:55:05  arvind
# 	Merge minor change.
# 	[1996/10/29  19:13 UTC  truitt  /main/DCE_1.2.2/truitt_dcecp_pk8/1]
#
# 	Put missing script file back.
# 	[1996/09/09  21:17 UTC  arvind  /main/DCE_1.2.2/3]
#
# 	Merge changes.
# 	[1996/07/01  13:50 UTC  truitt  /main/DCE_1.2.2/truitt_dcecp_pk/1]
#
# 	Update with latest version to include utility library.
# 	[1996/05/30  21:15 UTC  mullan_s  /main/DCE_1.2.2/1]
#
# 	Merge krb5 work to DCE1.2.2 mainline
# 	[1996/05/29  20:31 UTC  mullan_s  /main/mullan_dce1.2.2_krb5_drop/1]
#
# 	Remove HPUX specific building of hostvar.dcp as it is a part
# 	of DCE 1.2.2 now.
# 	[1996/01/03  19:34 UTC  psn  /main/DCE_1.2/1]
#
# Revision 1.1.6.3  1996/10/03  17:50:12  arvind
# 	PKSS drop from DEC (DCE1.2.2)
# 	[1996/08/30  15:32 UTC  arvind  /main/DCE_1.2.2/arvind_pkss/1]
# 
# 	Merge changes.
# 	[1996/07/01  13:50 UTC  truitt  /main/DCE_1.2.2/truitt_dcecp_pk/1]
# 
# 	Update with latest version to include utility library.
# 	[1996/05/30  21:15 UTC  mullan_s  /main/DCE_1.2.2/1]
# 
# 	Merge krb5 work to DCE1.2.2 mainline
# 	[1996/05/29  20:31 UTC  mullan_s  /main/mullan_dce1.2.2_krb5_drop/1]
# 
# 	Remove HPUX specific building of hostvar.dcp as it is a part
# 	of DCE 1.2.2 now.
# 	[1996/01/03  19:34 UTC  psn  /main/DCE_1.2/1]
# 
# Revision 1.1.6.2  1996/08/09  11:51:44  arvind
# 	Merge changes.
# 	[1996/07/01  13:50 UTC  truitt  /main/DCE_1.2.2/truitt_dcecp_pk/1]
# 
# 	Update with latest version to include utility library.
# 	[1996/05/30  21:15 UTC  mullan_s  /main/DCE_1.2.2/1]
# 
# 	Merge krb5 work to DCE1.2.2 mainline
# 	[1996/05/29  20:31 UTC  mullan_s  /main/mullan_dce1.2.2_krb5_drop/1]
# 
# 	Remove HPUX specific building of hostvar.dcp as it is a part
# 	of DCE 1.2.2 now.
# 	[1996/01/03  19:34 UTC  psn  /main/DCE_1.2/1]
# 
# Revision 1.1.6.1  1996/06/04  21:42:47  arvind
# 	Merge krb5 work to DCE1.2.2 mainline
# 	[1996/05/29  20:31 UTC  mullan_s  /main/mullan_dce1.2.2_krb5_drop/1]
# 
# 	Remove HPUX specific building of hostvar.dcp as it is a part
# 	of DCE 1.2.2 now.
# 	[1996/01/03  19:34 UTC  psn  /main/DCE_1.2/1]
# 
# 	Merge changes.
# 	[1995/10/10  15:02 UTC  truitt  /main/HPDCE02/3]
# 
# 	CHFts16537: Make the 'hostvar' script HP specific.
# 	[1995/10/05  15:07 UTC  truitt  /main/HPDCE02/truitt_dcecp_chfts49/1]
# 
# 	Merge.
# 	[1995/02/02  15:43 UTC  truitt  /main/HPDCE02/2]
# 
# 	CHFts14262: Add hostvar script.
# 	[1995/02/02  15:42 UTC  truitt  /main/HPDCE02/truitt_dcecp_chfts07/1]
# 
# 	Merge addition of SCRIPTS to run unifdef on conditionalized scripts
# 	[1995/02/01  19:09 UTC  dnguyen  /main/HPDCE02/1]
# 
# 	Add SCRIPTS to run unifdef on conditionalized scripts
# 	[1995/01/31  17:19 UTC  dnguyen  /main/dnguyen_mothra/1]
# 
# Revision 1.1.4.2  1996/03/09  23:06:23  marty
# 	Update OSF copyright year
# 	[1996/03/09  22:25:16  marty]
# 
# Revision 1.1.4.1  1995/12/08  21:23:30  root
# 	Submit OSF/DCE 1.2.1
# 
# 	HP revision /main/HPDCE02/3  1995/10/10  15:02 UTC  truitt
# 	Merge changes.
# 
# 	HP revision /main/HPDCE02/truitt_dcecp_chfts49/1  1995/10/05  15:07 UTC  truitt
# 	CHFts16537: Make the 'hostvar' script HP specific.
# 
# 	HP revision /main/HPDCE02/2  1995/02/02  15:43 UTC  truitt
# 	Merge.
# 
# 	HP revision /main/HPDCE02/truitt_dcecp_chfts07/1  1995/02/02  15:42 UTC  truitt
# 	CHFts14262: Add hostvar script.
# 
# 	HP revision /main/HPDCE02/1  1995/02/01  19:09 UTC  dnguyen
# 	Merge addition of SCRIPTS to run unifdef on conditionalized scripts
# 
# 	HP revision /main/dnguyen_mothra/1  1995/01/31  17:19 UTC  dnguyen
# 	Add SCRIPTS to run unifdef on conditionalized scripts
# 	[1995/12/08  17:57:30  root]
# 
# Revision 1.1.2.13  1994/09/02  19:37:56  melman
# 	added cellalias.dcp
# 	[1994/09/02  19:37:26  melman]
# 
# Revision 1.1.2.12  1994/08/23  18:39:47  rousseau
# 	Implement help and help -verbose (CR 11559).
# 	[1994/08/23  18:39:26  rousseau]
# 
# Revision 1.1.2.11  1994/08/03  14:06:46  rousseau
# 	Add dts.dcp
# 	[1994/08/03  14:00:47  rousseau]
# 
# Revision 1.1.2.10  1994/07/28  19:31:26  kevins
# 	OT 9691 Added cell task script
# 	[1994/07/28  19:31:20  kevins]
# 
# Revision 1.1.2.9  1994/07/26  14:19:46  coren
# 	Added host.dcp task script
# 	[1994/07/22  17:52:22  coren]
# 
# Revision 1.1.2.8  1994/06/26  10:39:37  kevins
# 	OT 9691 Added user.dcp task script
# 	[1994/06/24  18:35:08  kevins]
# 
# Revision 1.1.2.7  1994/06/23  18:28:02  coren
# 	Added attrlist.dcp.
# 	[1994/06/21  20:37:01  coren]
# 
# Revision 1.1.2.6  1994/06/21  20:26:55  kevins
# 	OT 11017 Added parseargs.dcp
# 	[1994/06/21  20:26:33  kevins]
# 
# Revision 1.1.2.5  1994/06/20  21:03:13  salamone
# 	Provide auto-loading procedure support.
# 	[1994/06/20  20:37:53  salamone]
# 
# Revision 1.1.2.4  1994/06/09  16:02:31  devsrc
# 	cr10892 - fix copyright
# 	[1994/06/09  15:48:07  devsrc]
# 
# Revision 1.1.2.3  1994/04/05  20:48:30  coren
# 	Added dir_ops.dcecp for dir delete -tree.
# 	[1994/04/01  20:50:40  coren]
# 
# 	Added dir_ops.tcl.
# 	[1994/03/14  20:24:27  coren]
# 
# Revision 1.1.2.2  1994/03/08  15:49:42  melman
# 	init.dcecp and verb commands
# 	[1994/03/08  14:46:04  melman]
# 
# Revision 1.1.2.1  1994/01/05  16:30:34  kevins
# 	Modified IDIR entry for attr_eval.tcl
# 	[1994/01/05  16:22:09  kevins]
# 
# 	Added IDIR entry for attr_eval.tcl
# 	[1994/01/05  15:53:07  kevins]
# 
# $EndLog$

IDIR            = /dcecp/

TCL_CODE_BASE   = attr_eval.tcl verb-object.dcp init.dcecp \
                  dir_ops.dcecp registry.dcp parseargs.dcp attrlist.dcp \
                  user.dcp host.dcp cell.dcp bckp_sec.dcp bckp_cds.dcp \
                  dts.dcp help.dcp cellalias.dcp hostvar.dcp utility.dcp

TCL_CODE        = ${TCL_CODE_BASE}

SCRIPTS         = init.dcecp
ILIST           = ${TCL_CODE}

.include <${RULES_MK}>
