$ 
$ @OSF_COPYRIGHT@
$ COPYRIGHT NOTICE
$ Copyright (c) 1990, 1991, 1992, 1993, 1996 Open Software Foundation, Inc.
$ ALL RIGHTS RESERVED (DCE).  See the file named COPYRIGHT.DCE in the
$ src directory for the full copyright text.
$ 
$ HISTORY
$ $Log: xoserr.msg,v $
$ Revision 1.1.4.2  1996/03/11  13:25:07  marty
$ 	Update OSF copyright years
$ 	[1996/03/11  13:13:21  marty]
$
$ Revision 1.1.4.1  1995/12/08  17:51:03  root
$ 	Submit OSF/DCE 1.2.1
$ 	[1995/12/08  16:26:32  root]
$ 
$ Revision 1.1.2.1  1994/06/21  14:39:47  marrek
$ 	Created in June 94 code submission.
$ 	[1994/06/10  16:04:49  marrek]
$ 
$ $EndLog$
$ 
$ $RCSfile: xoserr.msg,v $ $Revision: 1.1.4.2 $ $Date: 1996/03/11 13:25:07 $
$ 

$set 1 preload

1 Operation cannot be performed within the administrative constraints.
2 Modification affects several DSAs and is prohibited.
3 An alias is encountered where an alias is not permitted.
4 An alias is dereferenced that names an object that does not exist.
5 An attempt is made to add an attribute or value that already exists.
6 A bad argument was supplied.
7 The OM Class of an argument is not supported for this operation.
8 An invalid context argument was supplied.
9 An invalid name argument was supplied.
10 An invalid session argument was supplied.
11 An invalid workspace argument was supplied.
12 The Directory Service is temporarily too busy to perform the operation.
13 An attempt to abandon an operation has failed.
14 Chaining is required to perform the operation, but is prohibited by the DS_CHAINING_PROHIBITED service control.
15 A communication error has occurred.
16 The attribute or attribute value does not conform to the imposed constraints.
17 An inconsistency is detected in the DIT.
18 The name passed to the add entry operation already exists.
19 The level of security attached to the requestor's credential is inconsistent.
20 An attempt was made to use an undefined matching rule for the attribute type.
21 The requestor does not have permission to perform the operation.
22 The attribute value does not conform to the attribute syntax of the attribute type.
23 The attribute value in the AVA does not conform to the attribute syntax.
24 The requester's credentials are invalid.
25 The DSA is unable to perform the request as directed.
26 The signature affixed to the request is invalid.
27 A DSA detected a loop within the directory.
28 A miscellaneous error occurred while interacting with the Directory Service.
29 The attribute type is not included in the AVA.
30 An attempt was made to start a synchronous operation with outstanding asynchronous operations.
31 The modification leaves the DIT structured incorrectly.
32 The request produced a security error for which no other information is available.
33 The specified attribute or value was not found in the directory entry.
34 The specified name does not match the name of any object in the directory.
35 The Directory Service has no knowledge of the operation that is to be abandoned.
36 Modification to an interior node of the DIT is prohibited.
37 The modification alters an object's RDN.
38 An attempt is made to use optional functionality, which is not available in this implementation.
39 The modification alters an entry's object class attribute.
40 The modification leaves a directory entry inconsistent with its object class definition.
41 The Directory cannot provide a referral or partial outcome qualifier within the required scope.
42 The Directory Service is unwilling to perform the operation because it is unsigned.
43 The operation could not be performed within the specified time limit.
44 The operation has already completed, either successfully or erroneously.
45 No more Directory Service operations can be performed.
46 No more Directory Service sessions can be started.
47 The DSA does not have the administrative authority over the particular naming context.
48 Some part of the directory is currently not available.
49 The requested critical extensions are not available.
50 The attribute type is undefined.
51 Some part of the Directory Service is not willing to perform the operation.
52 Unknown XDS Error -
53 Violating attribute -
