/*
 * @OSF_COPYRIGHT@
 * COPYRIGHT NOTICE
 * Copyright (c) 1990, 1991, 1992, 1993, 1994, 1996 Open Software Foundation, Inc.
 * ALL RIGHTS RESERVED (DCE).  See the file named COPYRIGHT.DCE for
 * the full copyright text.
 * 
 */
/*
 * HISTORY
 * $Log: sample_bind.idl,v $
 * Revision 1.1.7.3  1996/03/09  23:15:25  marty
 * 	Update OSF copyright year
 * 	[1996/03/09  22:32:40  marty]
 *
 * Revision 1.1.7.2  1995/12/08  20:54:40  root
 * 	Submit OSF/DCE 1.2.1
 * 	[1995/12/08  20:49:50  root]
 * 
 * Revision 1.1.2.2  1994/10/27  20:06:50  rrizzo
 * 	expand copyright
 * 	[1994/10/27  19:39:08  rrizzo]
 * 
 * Revision 1.1.2.1  1994/10/21  19:13:25  weir
 * 	Submit sample program sources (CR 12635)
 * 	[1994/10/21  19:12:40  weir]
 * 
 * $EndLog$
 */
/****************************************************************************/
/* [27.VI.94]                                                               */
/*                                                                          */
/* sample_bind.idl --                                                       */
/*                                                                          */
/*                                                                          */
/*                                                                          */
/*                            -77 cols-                                     */
/****************************************************************************/


[
uuid(006868ca-6064-1d49-9829-0000c0d4de56),
version(1.0)
]
interface sample_bind
{

	void rs_bind_to_object(
		[in] handle_t binding,
		[in, string] char *component,
		[out] uuid_t *object_uuid, 
		[out] uuid_t *mgr_type_uuid,
		[out] error_status_t *status
	);
}

