/*
 * @OSF_COPYRIGHT@
 * COPYRIGHT NOTICE
 * Copyright (c) 1990, 1991, 1992, 1993, 1996 Open Software Foundation, Inc.
 * ALL RIGHTS RESERVED (DCE).  See the file named COPYRIGHT.DCE in the
 * src directory for the full copyright text.
 */
/*
 * HISTORY
 * $Log: sp_union.idl,v $
 * Revision 1.1.8.2  1996/03/11  02:18:19  marty
 * 	Update OSF copyright years
 * 	[1996/03/10  19:55:27  marty]
 *
 * Revision 1.1.8.1  1995/12/11  19:29:43  root
 * 	Submit OSF/DCE 1.2.1
 * 	[1995/12/11  19:15:43  root]
 * 
 * Revision 1.1.6.2  1993/06/15  21:08:39  sommerfeld
 * 	Rename spu_t->spux_t to avoid name collision on HP-UX
 * 	[1993/06/14  21:45:01  sommerfeld]
 * 
 * Revision 1.1.2.2  1993/01/07  23:36:02  bbelch
 * 	Embedding copyright notice
 * 	[1993/01/06  13:43:18  bbelch]
 * 
 * Revision 1.1  1992/01/19  03:27:39  devrcs
 * 	Initial revision
 * 
 * $EndLog$
 */
/*
*/
[
uuid (52817c7c-ffc4-11c8-8ae4-08002b104860),
pointer_default(ptr)
]
interface sp_union
{
    typedef union spux_t switch (char c) spu_s
    {
        case 'p':
        case 'P':
            union spux_t *p_spu;
        default:
            small depth;
    } spux_t;

    void my_oper( [in] handle_t h,
             [in, out] spux_t **p_p_spu_param );
}
