/*
 * @OSF_COPYRIGHT@
 * COPYRIGHT NOTICE
 * Copyright (c) 1990, 1991, 1992, 1993, 1994 Open Software Foundation, Inc.
 * ALL RIGHTS RESERVED (DCE).  See the file named COPYRIGHT.DCE for
 * the full copyright text.
 * 
 */
/*
 * HISTORY
 * $Log: dfsdlg_int.idl,v $
 * Revision 1.1.9.1  1996/10/17  18:18:48  damon
 * 	Submitting on behalf of Transarc
 * 	[1996/10/17  16:50:15  damon]
 *
 * Revision 1.1.4.2  1994/08/10  19:23:01  annie
 * 	expand copyright with OSF copyright text
 * 	[1994/08/10  17:17:18  annie]
 * 
 * Revision 1.1.4.1  1994/07/13  22:33:02  devsrc
 * 	merged with bl-10
 * 	[1994/06/29  12:17:42  devsrc]
 * 
 * 	Delegation Functional Tests - Initial Submit
 * 	[1994/06/08  18:30:21  delgado]
 * 
 * $EndLog$
 */
[
    uuid(032cc692-6ce6-11cd-bcea-08000932821e)
]

interface dfsdlgint {
    boolean32 dfsdlgint_has_admin_access(
        [in]      handle_t    h,
        [out]     error_status_t  *st
   );

}





