#!/bin/ksh
#
# @OSF_COPYRIGHT@
# COPYRIGHT NOTICE
# (c) Copyright International Business Machines Corp. 1994, 1996
# Copyright (c) 1990, 1991, 1992, 1993, 1994, 1996 Open Software Foundation, Inc.
# ALL RIGHTS RESERVED (DCE).  See the file named COPYRIGHT.DCE for
# the full copyright text.
#
# HISTORY
#
#  02/11/94	Weisz 	Initial design.  
tet_startup="startup"
tet_cleanup="cleanup"
iclist="ic1"
ic1="api_log1"

typeset -i16 overall_status
typeset -i16 tp_status

typeset -i16 tp1_error
typeset -i16 tp2_error
typeset -i16 tp3_error 
typeset -i16 tp4_error 
typeset -i16 tp5_error 
typeset -i16 tp6_error 
typeset -i16 tp7_error 
typeset -i16 tp8_error 
typeset -i16 tp9_error 
typeset -i16 tp10_error 
typeset -i16 tp11_error 
typeset -i16 tp12_error 
typeset -i16 tp13_error 
typeset -i16 tp14_error 
typeset -i16 tp15_error 
typeset -i16 tp16_error 
typeset -i16 tp17_error 
typeset -i16 tp18_error 
typeset -i16 tp19_error 
typeset -i16 tp20_error 
typeset -i16 tp21_error 
typeset -i16 tp22_error 
typeset -i16 tp23_error 

 (( tp1_error = 16#00000001 ))
 (( tp2_error = 16#00000002 ))
 (( tp3_error = 16#00000004 ))
 (( tp4_error = 16#00000008 ))
 (( tp5_error = 16#00000010 ))
 (( tp6_error = 16#00000020 ))
 (( tp7_error = 16#00000040 ))
 (( tp8_error = 16#00000080 ))
 (( tp9_error = 16#00000100 ))
 (( tp10_error = 16#00000200 ))
 (( tp11_error = 16#00000400 ))
 (( tp12_error = 16#00000800 ))
 (( tp13_error = 16#00001000 ))
 (( tp14_error = 16#00002000 ))
 (( tp15_error = 16#00004000 ))
 (( tp16_error = 16#00008000 ))
 (( tp17_error = 16#00010000 ))
 (( tp18_error = 16#00020000 ))
 (( tp19_error = 16#00040000 ))
 (( tp20_error = 16#00080000 ))
 (( tp21_error = 16#00100000 ))
 (( tp22_error = 16#00200000 ))
 (( tp23_error = 16#00400000 ))

startup() {

	print "\nSTART DCE audit functional test: api_log; DATE: `date`"
	tet_infoline "START DCE audit functional test: ${TET_PNAME}; DATE: `date`"
        rm /tmp/aud_test_trail*
}

api_log1() {

 print "\nSTART: api_log1 started\n"
 tet_infoline "START: api_log1 started"

#set -x
 $TET_ROOT/test/functional/security/audit/ts/api_log/aud_test
 (( overall_status = $? ))

 print "Overall status: $overall_status\n"

 ((tp_status = $overall_status & $tp1_error))
 if (( $tp_status  == 0 ))
 then
   print "\nPASS: api_log01 passed"
   tet_infoline "PASS: api_log01 passed"
 else
   print "\nERROR: api_log01 failed"
   tet_infoline "ERROR: api_log01 failed"
 fi

 ((tp_status = $overall_status & $tp2_error))
 if (( $tp_status  == 0 ))
 then
   print "\nPASS: api_log02 passed"
   tet_infoline "PASS: api_log02 passed"
 else
   print "\nERROR: api_log02 failed"
   tet_infoline "ERROR: api_log02 failed"
 fi

 ((tp_status = $overall_status & $tp3_error))
 if (( $tp_status  == 0 ))
 then
   print "\nPASS: api_log03 passed"
   tet_infoline "PASS: api_log03 passed"
 else
   print "\nERROR: api_log03 failed"
   tet_infoline "ERROR: api_log03 failed"
 fi

 ((tp_status = $overall_status & $tp4_error))
 if (( $tp_status  == 0 ))
 then
   print "\nPASS: api_log04 passed"
   tet_infoline "PASS: api_log04 passed"
 else
   print "\nERROR: api_log04 failed"
   tet_infoline "ERROR: api_log04 failed"
 fi

 ((tp_status = $overall_status & $tp5_error))
 if (( $tp_status  == 0 ))
 then
   print "\nPASS: api_log05 passed"
   tet_infoline "PASS: api_log05 passed"
 else
   print "\nERROR: api_log05 failed"
   tet_infoline "ERROR: api_log05 failed"
 fi

 ((tp_status = $overall_status & $tp6_error))
 if (( $tp_status  == 0 ))
 then
   print "\nPASS: api_log06 passed"
   tet_infoline "PASS: api_log06 passed"
 else
   print "\nERROR: api_log06 failed"
   tet_infoline "ERROR: api_log06 failed"
 fi

 ((tp_status = $overall_status & $tp7_error))
 if (( $tp_status  == 0 ))
 then
   print "\nPASS: api_log07 passed"
   tet_infoline "PASS: api_log07 passed"
 else
   print "\nERROR: api_log07 failed"
   tet_infoline "ERROR: api_log07 failed"
 fi

 ((tp_status = $overall_status & $tp8_error))
 if (( $tp_status  == 0 ))
 then
   print "\nPASS: api_log08 passed"
   tet_infoline "PASS: api_log08 passed"
 else
   print "\nERROR: api_log08 failed"
   tet_infoline "ERROR: api_log08 failed"
 fi

 ((tp_status = $overall_status & $tp9_error))
 if (( $tp_status  == 0 ))
 then
   print "\nPASS: api_log09 passed"
   tet_infoline "PASS: api_log09 passed"
 else
   print "\nERROR: api_log09 failed"
   tet_infoline "ERROR: api_log09 failed"
 fi

 ((tp_status = $overall_status & $tp10_error))
 if (( $tp_status  == 0 ))
 then
   print "\nPASS: api_log10 passed"
   tet_infoline "PASS: api_log10 passed"
 else
   print "\nERROR: api_log10 failed"
   tet_infoline "ERROR: api_log10 failed"
 fi

 ((tp_status = $overall_status & $tp11_error))
 if (( $tp_status  == 0 ))
 then
   print "\nPASS: api_log11 passed"
   tet_infoline "PASS: api_log11 passed"
 else
   print "\nERROR: api_log11 failed"
   tet_infoline "ERROR: api_log11 failed"
 fi

 ((tp_status = $overall_status & $tp12_error))
 if (( $tp_status  == 0 ))
 then
   print "\nPASS: api_log12 passed"
   tet_infoline "PASS: api_log12 passed"
 else
   print "\nERROR: api_log12 failed"
   tet_infoline "ERROR: api_log12 failed"
 fi

 ((tp_status = $overall_status & $tp13_error))
 if (( $tp_status  == 0 ))
 then
   print "\nPASS: api_log13 passed"
   tet_infoline "PASS: api_log13 passed"
 else
   print "\nERROR: api_log13 failed"
   tet_infoline "ERROR: api_log13 failed"
 fi

 ((tp_status = $overall_status & $tp14_error))
 if (( $tp_status  == 0 ))
 then
   print "\nPASS: api_log14 passed"
   tet_infoline "PASS: api_log14 passed"
 else
   print "\nERROR: api_log14 failed"
   tet_infoline "ERROR: api_log14 failed"
 fi

 ((tp_status = $overall_status & $tp15_error))
 if (( $tp_status  == 0 ))
 then
   print "\nPASS: api_log15 passed"
   tet_infoline "PASS: api_log15 passed"
 else
   print "\nERROR: api_log15 failed"
   tet_infoline "ERROR: api_log15 failed"
 fi

 ((tp_status = $overall_status & $tp16_error))
 if (( $tp_status  == 0 ))
 then
   print "\nPASS: api_log16 passed"
   tet_infoline "PASS: api_log16 passed"
 else
   print "\nERROR: api_log16 failed"
   tet_infoline "ERROR: api_log16 failed"
 fi

 ((tp_status = $overall_status & $tp17_error))
 if (( $tp_status  == 0 ))
 then
   print "\nPASS: api_log17 passed"
   tet_infoline "PASS: api_log17 passed"
 else
   print "\nERROR: api_log17 failed"
   tet_infoline "ERROR: api_log17 failed"
 fi

 ((tp_status = $overall_status & $tp18_error))
 if (( $tp_status  == 0 ))
 then
   print "\nPASS: api_log18 passed"
   tet_infoline "PASS: api_log18 passed"
 else
   print "\nERROR: api_log18 failed"
   tet_infoline "ERROR: api_log18 failed"
 fi

 ((tp_status = $overall_status & $tp19_error))
 if (( $tp_status  == 0 ))
 then
   print "\nPASS: api_log19 passed"
   tet_infoline "PASS: api_log19 passed"
 else
   print "\nERROR: api_log19 failed"
   tet_infoline "ERROR: api_log19 failed"
 fi

 ((tp_status = $overall_status & $tp20_error))
 if (( $tp_status  == 0 ))
 then
   number_of_audit_trail_files=$( ls /tmp | grep -c aud_test_trail1)
   print "\nnumber_of_audit_trail_files = $number_of_audit_trail_files"
   if (( $number_of_audit_trail_files > 9 ))
   then
      print "\nPASS: api_log20 passed"
      tet_infoline "PASS: api_log20 passed"
   else
      print "\nERROR: api_log20 failed"
      tet_infoline "ERROR: api_log20 failed"
   fi
 else
   print "\nERROR: api_log20 failed"
   tet_infoline "ERROR: api_log20 failed"
 fi

 ((tp_status = $overall_status & $tp21_error))
 if (( $tp_status  == 0 ))
 then
   number_of_audit_trail_files=$( ls /tmp | grep -c aud_test_trail2)
   print "\nnumber_of_audit_trail_files = $number_of_audit_trail_files"
   if (( $number_of_audit_trail_files > 2 && $number_of_audit_trail_files < 9 ))
   then
      print "\nPASS: api_log21 passed"
      tet_infoline "PASS: api_log21 passed"
   else
      print "\nERROR: api_log21 failed"
      tet_infoline "ERROR: api_log21 failed"
   fi
 else
   print "\nERROR: api_log21 failed"
   tet_infoline "ERROR: api_log21 failed"
 fi

 ((tp_status = $overall_status & $tp22_error))
 if (( $tp_status  == 0 ))
 then
   number_of_audit_trail_files=$( ls /tmp | grep -c aud_test_trail3)
   print "\nnumber_of_audit_trail_files = $number_of_audit_trail_files"
   if (( $number_of_audit_trail_files == 2 ))
   then
      print "\nPASS: api_log22 passed"
      tet_infoline "PASS: api_log22 passed"
   else
      print "\nERROR: api_log22 failed"
      tet_infoline "ERROR: api_log22 failed"
   fi
 else
   print "\nERROR: api_log22 failed"
   tet_infoline "ERROR: api_log22 failed"
 fi

 ((tp_status = $overall_status & $tp23_error))
 if (( $tp_status  == 0 ))
 then
   print "\nPASS: api_log23 passed"
   tet_infoline "PASS: api_log23 passed"
 else
   print "\nERROR: api_log23 failed"
   tet_infoline "ERROR: api_log23 failed"
 fi

 if (( $overall_status  == 0 ))
 then
   tet_result PASS
 else
   tet_result FAIL 
 fi

}

#set +x
# cleanup of DCE audit test
cleanup() {
        rm /tmp/aud_test_trail*
	print "\nEND DCE audit functional test: api_log; DATE: `date`"
	tet_infoline "END DCE audit functional test: ${TET_PNAME}; DATE: `date`"
}

#source tcm
. $TET_ROOT/lib/ksh/tcm.ksh
