#
# @OSF_COPYRIGHT@
# COPYRIGHT NOTICE
# Copyright (c) 1990, 1991, 1992, 1993, 1996 Open Software Foundation, Inc.
# ALL RIGHTS RESERVED (DCE).  See the file named COPYRIGHT.DCE in the
# src directory for the full copyright text.
#
# HISTORY
# $Log: Makefile,v $
# Revision 1.1.2.1  1996/11/14  16:12:53  arvind
# 	OSF DCE 1.2.2 Drop 5
# 	[1996/11/14  14:28:22  arvind]
#
# Revision /main/DCE_1.2.2/1  1996/10/18  00:45 UTC  arvind
# 	Fix build error
# 	[1996/10/17  19:36 UTC  arvind  /main/arvind_capi/3]
# 
# 	Remove .include.
# 	[1996/10/17  19:22 UTC  arvind  /main/arvind_capi/2]
# 
# 	CAPI drop from DEC
# 	[1996/10/16  20:36 UTC  arvind  /main/arvind_capi/1]
# 
# $EndLog$
#
#  @DEC_COPYRIGHT@
#  Copyright (c) 1996
#  Digital Equipment Corporation, Maynard, Massachusetts, USA
#  All Rights Reserved
#  

           

# VPATH = ${MAKETOP}/test/security/api/capi/testcases
VPATH = ../../../../../security/api/capi/testcases


.include <${RULES_MK}>
