/*
 * @OSF_COPYRIGHT@
 * COPYRIGHT NOTICE
 * Copyright (c) 1990, 1991, 1992, 1993, 1996 Open Software Foundation, Inc.
 * ALL RIGHTS RESERVED (DCE).  See the file named COPYRIGHT.DCE in the
 * src directory for the full copyright text.
 */
/*
 * HISTORY
 * $Log: context2.idl,v $
 * Revision 1.1.6.2  1996/03/11  02:11:11  marty
 * 	Update OSF copyright years
 * 	[1996/03/10  19:52:15  marty]
 *
 * Revision 1.1.6.1  1995/12/11  20:00:34  root
 * 	Submit OSF/DCE 1.2.1
 * 	[1995/12/11  19:29:36  root]
 * 
 * Revision 1.1.4.1  1994/06/23  18:25:26  tom
 * 	From DEC: add opaque context handle support.
 * 	[1994/06/23  18:24:11  tom]
 * 
 * Revision 1.1.2.2  1993/01/07  19:49:47  bbelch
 * 	Embedding copyright notice
 * 	[1993/01/06  13:30:21  bbelch]
 * 
 * Revision 1.1  1992/01/19  03:24:17  devrcs
 * 	Initial revision
 * 
 * $EndLog$
 */
/*
*/
[uuid(7af34701-ffc4-11c8-8ae4-08002b104860), version(0)]
interface context2
{
    /* Rico 18-May-1994 made ch_t (struct *) to test opaque ch support */
    typedef [context_handle] struct entry_t * ch_t;
    typedef ch_t ch_t2;

    void rd_new([in] handle_t h, [out] ch_t *ch);
    unsigned long rd_inq([in] ch_t ch);
    small rd_done([in, out] ch_t *ch);
    [context_handle] void *rd_new_return([in] handle_t h);

    void rd_new_2([in] handle_t h, [out] ch_t2 *ch);
    unsigned long rd_inq_2([in] ch_t2 ch);
    small rd_done_2([in, out] ch_t2 *ch);
    [context_handle] void *rd_new_return_2([in] handle_t h);
}



