# @OSF_COPYRIGHT@
# COPYRIGHT NOTICE
# Copyright (c) 1990, 1991, 1992, 1993, 1994, 1996 Open Software Foundation, Inc.
# ALL RIGHTS RESERVED (DCE).  See the file named COPYRIGHT.DCE for
# the full copyright text.
# 
# 
# HISTORY
# $Log: Makefile,v $
# Revision 1.1.7.3  1996/03/09  23:15:04  marty
# 	Update OSF copyright year
# 	[1996/03/09  22:32:21  marty]
#
# Revision 1.1.7.2  1995/12/08  20:54:13  root
# 	Submit OSF/DCE 1.2.1
# 	[1995/12/08  20:49:23  root]
# 
# Revision 1.1.2.2  1994/10/27  20:06:16  rrizzo
# 	expand copyright
# 	[1994/10/27  19:38:39  rrizzo]
# 
# Revision 1.1.2.1  1994/10/21  19:15:00  weir
# 	Submit sample program sources (CR 12635)
# 	[1994/10/21  19:14:24  weir]
# 
# $EndLog$
# 
# 
#----------------------------------------------------------------------------------------
# [16.X.94]
# 
# ODE Makefile for src/examples/demo
# 
# 
# This Makefile allows you to type "build install_all" in this directory
#  and install only the DCE 1.1 example programs.
# 
#----------------------------------------------------------------------------------------

IDIR	= /usr/examples/demo/

IMODE	= 644

SUBDIRS = context_app data_test_app generic_app

# The following line explicitly includes the "common makefiles". For more
#  information, see Chapter 12 of the Porting Guide...

.include <${RULES_MK}>
