/* ______________________________________________________________________ */
/*
 * @OSF_COPYRIGHT@
 * Copyright (c) 1993, 1996 Open Software Foundation, Inc.
 * ALL RIGHTS RESERVED (DCE).  See the file named COPYRIGHT.DCE in the
 * src directory for the full copyright text.
 */
/*
 * HISTORY
 * $Log: dceacl.idl,v $
 * Revision 1.1.4.2  1996/03/09  23:10:44  marty
 * 	Update OSF copyright year
 * 	[1996/03/09  22:28:27  marty]
 *
 * Revision 1.1.4.1  1995/12/08  21:35:45  root
 * 	Submit OSF/DCE 1.2.1
 * 	[1995/12/08  18:07:37  root]
 * 
 * Revision 1.1.2.1  1994/01/24  22:01:47  bowe
 * 	Initial checkin
 * 	[1994/01/24  21:59:37  bowe]
 * 
 * Revision 1.1.2.1  1993/12/20  13:43:57  bowe
 * 	Initial revision.
 * 	[1993/12/16  20:41:12  bowe]
 * 
 * $EndLog$
 */
/* ______________________________________________________________________ */

[
uuid(00274c1f-ea3d-1cce-8da8-0000c09ce054),
version(1.0)
]
interface dceacl
{

import "dce/aclbase.idl";
import "dce/rdaclif.idl";


void dce_rdacl_convert(
    [in]	handle_t	h,
    [in,out]	sec_acl_t	*acl,
    [in,out]	error_status_t	*st		/* idl bug WORKAROUND */
);

}

