# 
# @OSF_COPYRIGHT@
# COPYRIGHT NOTICE
# Copyright (c) 1990, 1991, 1992, 1993, 1994, 1996 Open Software Foundation, Inc.
# ALL RIGHTS RESERVED (DCE).  See the file named COPYRIGHT.DCE for
# the full copyright text.
# 
# HISTORY
# $Log: Makefile,v $
# Revision 1.1.4.2  1996/03/11  02:34:34  marty
# 	Update OSF copyright years
# 	[1996/03/10  19:39:56  marty]
#
# Revision 1.1.4.1  1995/12/11  15:25:09  root
# 	Submit
# 	[1995/12/11  14:35:54  root]
# 
# Revision 1.1.2.1  1994/07/06  15:10:35  marrek
# 	Created in July 1994 code drop.
# 	[1994/07/06  13:02:28  marrek]
# 
# $EndLog$
#
# $RCSfile: Makefile,v $ $Revision: 1.1.4.2 $ $Date: 1996/03/11 02:34:34 $
#

IDIR    = /test/tet/functional/directory/gds/ts/gds_sec/lib/

ILIST           = sec_dap_b1.tcl \
                  sec_dap_b2.tcl \
                  sec_dap_b3.tcl \
                  sec_dap_b4.tcl \
                  sec_dsp_b1.tcl \
                  sec_dsp_b2.tcl \
                  sec_dsp_b3.tcl \
                  sec_tdt_b1.tcl \
                  sec_tdt_b2.tcl \
                  sec_tdt_b3.tcl \
                  sec_tdt_b4.tcl \
                  sec_tdt_b5.tcl

.include <${RULES_MK}>
