# @OSF_COPYRIGHT@
# COPYRIGHT NOTICE
# Copyright (c) 1990, 1991, 1992, 1993, 1994, 1996 Open Software Foundation, Inc.
# ALL RIGHTS RESERVED (DCE).  See the file named COPYRIGHT.DCE for
# the full copyright text.
# 
# HISTORY
# $Log: Makefile,v $
# Revision 1.1.4.2  1996/03/11  02:00:02  marty
# 	Update OSF copyright years
# 	[1996/03/10  19:46:45  marty]
#
# Revision 1.1.4.1  1995/12/11  18:07:03  root
# 	Submit OSF/DCE 1.2.1
# 	[1995/12/11  17:50:39  root]
# 
# Revision 1.1.2.3  1994/07/06  15:12:56  marrek
# 	July 1994 code drop.
# 	[1994/07/06  12:04:43  marrek]
# 
# Revision 1.1.2.2  1994/06/10  20:37:24  devsrc
# 	cr10872 - fixed copyright
# 	[1994/06/10  17:07:09  devsrc]
# 
# Revision 1.1.2.1  1994/05/10  15:06:25  marrek
# 	Created in April 1994 submission.
# 	[1994/05/03  12:19:17  marrek]
# 
# $EndLog$
#
# $RCSfile: Makefile,v $ $Revision: 1.1.4.2 $ $Date: 1996/03/11 02:00:02 $
#

IDIR = /test/tet/functional/directory/xds/ts/xoms/lib/valid/

DATAFILES	=				\
			Testcases		\
			extract1v		\
			extract_attr1v		\
			obj_to_str001v		\
			obj_to_str002v		\
			obj_to_str003v		\
			obj_to_str004v		\
			obj_to_str005v		\
			obj_to_str006v		\
			obj_to_str007v		\
			obj_to_str008v		\
			obj_to_str009v		\
			obj_to_str010v		\
			obj_to_str011v		\
			obj_to_str012v		\
			obj_to_str013v		\
			obj_to_str014v		\
			obj_to_str015v		\
			obj_to_str016v		\
			obj_to_str017v		\
			str_to_attr001v		\
			str_to_attr002v		\
			str_to_attr003v		\
			str_to_attr004v		\
			str_to_attr005v		\
			str_to_attr006v		\
			str_to_attr007v		\
			str_to_attr008v		\
			str_to_attr009v		\
			str_to_attr010v		\
			str_to_attr011v		\
			str_to_attr012v		\
			str_to_attr013v		\
			str_to_attr014v		\
			str_to_attr015v		\
			str_to_attr016v		\
			str_to_attr017v		\
			str_to_attr018v		\
			str_to_attr019v		\
			str_to_attr020v		\
			str_to_attr021v		\
			str_to_attr022v		\
			str_to_attr023v		\
			str_to_attr024v		\
			str_to_attr025v		\
			str_to_attr026v		\
			str_to_filter001v	\
			str_to_filter002v	\
			str_to_filter003v	\
			str_to_filter004v	\
			str_to_filter005v	\
			str_to_filter006v	\
			str_to_filter007v	\
			str_to_filter008v	\
			str_to_filter009v	\
			str_to_filter010v	\
			str_to_filter011v	\
			str_to_filter012v	\
			str_to_filter013v	\
			str_to_filter014v	\
			str_to_filter015v	\
			str_to_filter016v	\
			str_to_filter017v	\
			str_to_filter018v	\
			str_to_filter019v	\
			str_to_filter020v	\
			str_to_filter021v	\
			str_to_filter022v	\
			str_to_filter023v	\
			str_to_filter024v	\
			str_to_filter025v	\
			str_to_filter026v	\
			str_to_filter027v	\
			str_to_filter028v	\
			str_to_filter029v	\
			str_to_filter030v	\
			str_to_filter031v	\
			str_to_filter032v	\
			str_to_filter033v	\
			str_to_filter034v	\
			str_to_filter035v	\
			str_to_filter036v	\
			str_to_filter037v	\
			str_to_filter038v	\
			str_to_filter039v	\
			str_to_filter040v	\
			str_to_filter041v	\
			str_to_filter042v	\
			str_to_filter043v	\
			str_to_filter044v	\
			str_to_filter045v	\
			str_to_filter046v	\
			str_to_filter047v	\
			str_to_name001v		\
			str_to_name002v		\
			str_to_name003v		\
			str_to_name004v		\
			str_to_name005v		\
			str_to_name006v		\
			str_to_name007v		\
			str_to_name008v		\
			str_to_name009v		\
			str_to_name010v		\
			str_to_name011v		\
			str_to_name012v		\
			str_to_name013v		\
			str_to_name014v		\
			str_to_name015v		\
			str_to_name016v		\
			str_to_name017v		\
			str_to_name018v		\
			str_to_name019v		\
			str_to_name020v		\
			str_to_name021v		\
			str_to_obj001v		\
			str_to_rdn001v		\
			str_to_rdn002v		\
			str_to_rdn003v		\
			str_to_rdn004v		\
			str_to_rdn005v		\
			str_to_rdn006v

ILIST		= ${DATAFILES}

.include <${RULES_MK}>
