/*
 * @OSF_COPYRIGHT@
 * COPYRIGHT NOTICE
 * Copyright (c) 1990, 1991, 1992, 1993, 1996 Open Software Foundation, Inc.
 * ALL RIGHTS RESERVED (DCE).  See the file named COPYRIGHT.DCE in the
 * src directory for the full copyright text.
 */
/*
 * HISTORY
 * $Log: acct_type.idl,v $
 * Revision 1.1.11.2  1996/03/11  02:45:08  marty
 * 	Update OSF copyright years
 * 	[1996/03/10  20:07:51  marty]
 *
 * Revision 1.1.11.1  1995/12/11  22:00:32  root
 * 	Submit OSF/DCE 1.2.1
 * 	[1995/12/11  20:59:41  root]
 * 
 * Revision 1.1.7.2  1993/02/05  15:20:54  cjd
 * 	Embedded copyright notice
 * 	[1993/02/05  14:41:20  cjd]
 * 
 * Revision 1.1.5.2  1993/02/04  22:08:18  cjd
 * 	Embedded copyright notice
 * 
 * Revision 1.1.3.2  1992/03/18  01:18:49  rps
 * 	Fix error returns
 * 	[1992/03/18  00:11:23  rps]
 * 
 * Revision 1.1  1992/01/19  14:36:29  devrcs
 * 	Initial revision
 * 
 * $EndLog$
 */
/*
 *
 *
 *   	FILE_NAME: acct_type.idl
 *
 *   	COMPONENT_NAME: dce.systest
 *
 *   	FUNCTIONS: none
 *
 *   	ORIGINS: 2 27
 *
 *
 *   	(C) COPYRIGHT International Business Machines Corp. 1991
 *   	All Rights Reserved
 *
 *	Copyright  1987 by Apollo Computer Inc., Chelmsford, Massachusetts
 *
 *   	FOR_TEST: dcerpbnk
 *
 *   	USAGE: n/a
 *
 *   	DESCRIPTION:
 *      	This contains the structure definition of bank accounts
 *		and the definition of the circular linked list.
 *
 *   	HISTORY:
 *      	5/01/91        	Code Complete           Gerald Cantor
 *	       10/20/91		Added account locking
 *				mutex.			Gerald Cantor
 */
[pointer_default(ptr)] interface acct_type
{
	typedef struct {
		[string] char *name;
		long number;
		error_status_t ck_balance;
		error_status_t ck_trans_time;
		error_status_t sv_balance;
		error_status_t sv_trans_time;
		error_status_t cd_balance;
		error_status_t cd_trans_time;
		error_status_t ira_balance;
		error_status_t ira_trans_time;
		error_status_t create_time;
	} acct_info_t;

	typedef struct acct_t {
		acct_info_t acct_info;
		byte *acct_mutex;
		struct acct_t *next;
		struct acct_t *prev;
	} acct_t;

}
