/*
 * @OSF_COPYRIGHT@
 * COPYRIGHT NOTICE
 * Copyright (c) 1996 Open Software Foundation, Inc.
 * ALL RIGHTS RESERVED (DCE).  See the file named COPYRIGHT.DCE for
 * the full copyright text.
 */
/*
 * HISTORY
 * $Log: recov.idl,v $
 * Revision 1.1.10.2  1996/03/09  20:51:19  marty
 * 	Add OSF copyright
 * 	[1996/03/09  20:29:08  marty]
 *
 * Revision 1.1.10.1  1995/12/13  21:55:43  root
 * 	Submit OSF/DCE 1.2.1
 * 	[1995/12/13  21:45:16  root]
 * 
 * Revision 1.1.6.2  1993/07/09  12:59:48  root
 * 	Initial King Kong branch
 * 	[1993/07/09  12:59:21  root]
 * 
 * Revision 1.1.4.2  1993/03/31  12:32:31  mgm
 * 	Initial GAMERA branch
 * 
 * Revision 1.1.3.2  1992/06/11  19:56:39  mcfarland
 * 	changed files from test_latest
 * 	[1992/06/09  13:03:53  mcfarland]
 * 
 * 	Fix error returns
 * 	[1992/03/18  00:12:52  rps]
 * 
 * Revision 1.1.1.2  1992/05/28  15:14:06  root
 * 	    Loading drop Dce1_0_1b15
 * 
 * Revision 1.1  1992/01/19  14:37:35  devrcs
 * 	Initial revision
 * 
 * $EndLog$
 */
/*
 *
 *
 *   FILE_NAME: recov.idl
 *
 *   COMPONENT_NAME: dce.systest
 *
 *   FUNCTIONS: none
 *
 *   ORIGINS: 27
 *
 *
 *   (C) COPYRIGHT International Business Machines Corp. 1991
 *   All Rights Reserved
 *
 *
 *   FOR_TEST: dcerprec
 *
 *   USAGE: n/a
 *
 *   DESCRIPTION:
 *      The interface defenition language (idl) file.  Used by the NILD
 *      compiler to generate the necessary stub and header files.
 *
 *   HISTORY:
 *      11/10/90        Gerald Cantor           Initial design/code
 *      12/15/91        Gerald Cantor           Have recov_read return void
 *						rather than error_status_t.
 *						Remove idempotent call.
 *	01/03/92	Gerald Cantor		Updated prologs.
 */
[uuid(1d2a05d8-da2c-11c9-91e8-02608c2c688e), version(0), pointer_default(ref)]
interface recov 
{

error_status_t recov_read(
	[in] handle_t h,
	[in] char filename[80],
	[in] long offset,
	[out, size_is(buf_size)] char *buf,
	[in] long buf_size
	);
}
