/*
 * @OSF_COPYRIGHT@
 * COPYRIGHT NOTICE
 * Copyright (c) 1996 Open Software Foundation, Inc.
 * ALL RIGHTS RESERVED (DCE).  See the file named COPYRIGHT.DCE for
 * the full copyright text.
 */
/*
 * HISTORY
 * $Log: repas.idl,v $
 * Revision 1.1.10.2  1996/03/09  20:51:20  marty
 * 	Add OSF copyright
 * 	[1996/03/09  20:29:09  marty]
 *
 * Revision 1.1.10.1  1995/12/13  21:55:44  root
 * 	Submit OSF/DCE 1.2.1
 * 	[1995/12/13  21:45:16  root]
 * 
 * Revision 1.1.6.2  1993/07/09  13:02:48  root
 * 	Initial King Kong branch
 * 	[1993/07/09  13:02:20  root]
 * 
 * Revision 1.1.4.2  1993/03/31  12:33:17  mgm
 * 	Initial GAMERA branch
 * 
 * Revision 1.1.3.2  1992/06/11  19:56:54  mcfarland
 * 	changed files from test_latest
 * 	[1992/06/09  13:04:07  mcfarland]
 * 
 * Revision 1.1.1.2  1992/05/28  15:14:11  root
 * 	    Loading drop Dce1_0_1b15
 * 
 * Revision 1.1  1992/01/19  14:37:11  devrcs
 * 	Initial revision
 * 
 * $EndLog$
 */
/*
*/
[uuid(f9aaf300-2ba8-11c9-99f6-08002b13d56d),
 endpoint("ncadg_ip_udp:[6098]", "ncacn_ip_tcp:[6098]"),
 version(0)]
interface repas1
{

    const long MAXELEMENTS = 100;

/*  maximum size of list  */
    typedef struct trans_t
    {
        long last;
        [last_is(last)] long values[MAXELEMENTS];
    } trans_t;

    typedef struct list_t
    {
        long value;
        [ptr] struct list_t *next;
    } list_t;

    long xmitas$sum
    (
        [in] handle_t h,
        [in] trans_t list
    );

    long xmitas$sum_out
    (
        [in] handle_t h,
        [out] struct trans_t *list
    );

    long xmitas$sum_in_out
    (
        [in] handle_t h,
        [in,out] trans_t *list,
        [in] long int in_total
    );

/*
    long xmitas$sum_in_out2
    (
        [in] handle_t h,
        [in,out,ptr] trans_t *list,
        [in] long int in_total
    );
*/

}
