/*
 * @OSF_COPYRIGHT@
 * COPYRIGHT NOTICE
 * Copyright (c) 1996 Open Software Foundation, Inc.
 * ALL RIGHTS RESERVED (DCE).  See the file named COPYRIGHT.DCE for
 * the full copyright text.
 */
/*
 * HISTORY
 * $Log: sp_union.idl,v $
 * Revision 1.1.8.2  1996/03/09  20:51:40  marty
 * 	Add OSF copyright
 * 	[1996/03/09  20:29:24  marty]
 *
 * Revision 1.1.8.1  1995/12/13  21:55:59  root
 * 	Submit OSF/DCE 1.2.1
 * 	[1995/12/13  21:45:26  root]
 * 
 * Revision 1.1.6.2  1993/07/09  13:25:54  root
 * 	Initial King Kong branch
 * 	[1993/07/09  13:25:28  root]
 * 
 * Revision 1.1.4.3  1993/04/23  14:42:42  giza
 * 	dce1.0.2 merge up
 * 	[1993/04/23  13:43:48  giza]
 * 
 * Revision 1.1.4.2  1993/03/31  12:39:19  mgm
 * 	Initial GAMERA branch
 * 
 * Revision 1.1.3.2  1992/06/11  19:59:01  mcfarland
 * 	changed files from test_latest
 * 	[1992/06/09  13:05:58  mcfarland]
 * 
 * Revision 1.1.1.2  1992/05/28  15:14:54  root
 * 	    Loading drop Dce1_0_1b15
 * 
 * Revision 1.1  1992/01/19  14:37:03  devrcs
 * 	Initial revision
 * 
 * $EndLog$
 */
/*
*/
[
uuid (52817c7c-ffc4-11c8-8ae4-08002b104860),
endpoint("ncadg_ip_udp:[9009]", "ncacn_ip_tcp:[9009]"),
pointer_default(ptr)
]
interface sp_union
{
    typedef union sp_union_t switch (char c) spu_s
    {
        case 'p':
        case 'P':
            union sp_union_t *p_spu;
        default:
            small depth;
    } sp_union_t;

    void my_oper( [in] handle_t h,
             [in, out] sp_union_t **p_p_spu_param );
}
