/*
 * @OSF_COPYRIGHT@
 * COPYRIGHT NOTICE
 * Copyright (c) 1990, 1991, 1992, 1993, 1996 Open Software Foundation, Inc.
 * ALL RIGHTS RESERVED (DCE).  See the file named COPYRIGHT.DCE in the
 * src directory for the full copyright text.
 */
/*
 * HISTORY
 * $Log: trans.idl,v $
 * Revision 1.1.9.2  1996/03/11  02:47:15  marty
 * 	Update OSF copyright years
 * 	[1996/03/10  20:08:40  marty]
 *
 * Revision 1.1.9.1  1995/12/11  22:44:26  root
 * 	Submit OSF/DCE 1.2.1
 * 	[1995/12/11  22:20:59  root]
 * 
 * Revision 1.1.7.1  1994/03/11  18:52:49  pellis
 * 	Defect #10128 - Assigned tcp and udp unique endpoint values.
 * 	[1994/03/11  18:52:30  pellis]
 * 
 * Revision 1.1.3.2  1993/02/05  15:23:40  cjd
 * 	Embedded copyright notice
 * 	[1993/02/05  14:45:10  cjd]
 * 
 * Revision 1.1.1.2  1993/02/04  22:14:47  cjd
 * 	Embedded copyright notice
 * 
 * Revision 1.1  1992/01/19  14:36:02  devrcs
 * 	Initial revision
 * 
 * $EndLog$
 */
/*
 *
 *
 *   	FILE_NAME: trans.idl
 *
 *   	COMPONENT_NAME: dce.systest
 *
 *   	FUNCTIONS: none
 *
 *   	ORIGINS: 2 27
 *
 *
 *   	(C) COPYRIGHT International Business Machines Corp. 1991
 *   	All Rights Reserved
 *
 *	Copyright  1987 by Apollo Computer Inc., Chelmsford, Massachusetts
 *
 *   	FOR_TEST: dcerpbnk
 *
 *   	USAGE: n/a
 *
 *   	DESCRIPTION:
 *      	The interface defenition language (idl) file.  Used by 
 *		the NILD compiler to generate the necessary stub and 
 *		header files.
 *
 *   	HISTORY:
 *      	5/01/91        Code Complete           Gerald Cantor
 */
[uuid(88fdbace-f5a3-11c9-9999-02608c2ea88e), pointer_default(ptr),
 endpoint("ncadg_ip_udp:[6677]", "ncacn_ip_tcp:[6678]"), 
 version(0)]
interface trans
{
	import "acct_type.idl";

	error_status_t deposit(
		[in] handle_t h,
		[in] char name[30],
		[in] long amount
	);

	error_status_t withdraw(
		[in] handle_t h,
		[in] char name[30],
		[in] long amount
	);
}
