/*
 * @OSF_COPYRIGHT@
 * COPYRIGHT NOTICE
 * Copyright (c) 1996 Open Software Foundation, Inc.
 * ALL RIGHTS RESERVED (DCE).  See the file named COPYRIGHT.DCE for
 * the full copyright text.
 */
/*
 * HISTORY
 * $Log: xmitas.idl,v $
 * Revision 1.1.10.2  1996/03/09  20:51:48  marty
 * 	Add OSF copyright
 * 	[1996/03/09  20:29:30  marty]
 *
 * Revision 1.1.10.1  1995/12/13  21:56:08  root
 * 	Submit OSF/DCE 1.2.1
 * 	[1995/12/13  21:45:33  root]
 * 
 * Revision 1.1.6.2  1993/07/09  13:55:21  root
 * 	Initial King Kong branch
 * 	[1993/07/09  13:54:53  root]
 * 
 * Revision 1.1.4.2  1993/03/31  12:43:59  mgm
 * 	Initial GAMERA branch
 * 
 * Revision 1.1.3.2  1992/06/11  20:01:08  mcfarland
 * 	changed files from test_latest
 * 	[1992/06/09  13:07:54  mcfarland]
 * 
 * Revision 1.1.1.2  1992/05/28  15:15:34  root
 * 	    Loading drop Dce1_0_1b15
 * 
 * Revision 1.1  1992/01/19  14:36:47  devrcs
 * 	Initial revision
 * 
 * $EndLog$
 */
/*
*/
[uuid(f9aaf300-2ba8-11c9-99f6-08002b13d56d),
 endpoint("ncadg_ip_udp:[6312]", "ncacn_ip_tcp:[6312]"),
 pointer_default(ptr),
 version(0)]
interface xmitas
{

    const long MAXELEMENTS = 100;

/*  maximum size of list  */
    typedef struct trans_t
    {
        long last;
        [last_is(last)] long values[MAXELEMENTS];
    } trans_t;

    typedef [transmit_as(trans_t)] struct list_t
    {
        long value;
        struct list_t *next;
    } list_t;

    [idempotent] long xmitas$sum
    (
        [in] handle_t h,
        [in] struct list_t list
    );
}
