#!/bin/sh
#
# @OSF_COPYRIGHT@
# COPYRIGHT NOTICE
# Copyright (c) 1996 Open Software Foundation, Inc.
# ALL RIGHTS RESERVED (DCE).  See the file named COPYRIGHT.DCE for
# the full copyright text.
#
# HISTORY
# $Log: report_tetinfo,v $
# Revision 1.1.2.1  1996/10/16  14:09:06  arvind
# 	OSF DCE 1.2.2 Drop 4.5
# 	[1996/10/16  14:00:33  arvind]
#
# $EndLog$
#
#
# report the logged information written with tet_infoline
#
usage() {
	cat << E_O_F
usage: ${0} journal-directory [...]
E_O_F
}

#
# main procedure
#

# check argument
if [ $# -lt 1 ]; then
	usage
	exit
fi
dirs="$*"

# display the tet_infoline'd messages from journal files
for i in ${dirs}; do
	journal="${i}/journal"
	if [ ! -r ${journal} ]; then
		echo "Cannot read file: ${journal}"
		continue
	fi

	if [ $# -gt 1 ]; then
		echo "${journal}:"
	fi

	awk -F'|' '
	{
		printf("%s\n", $3)
	} ' ${journal}
done

# done successfully
exit
