/*
 * @OSF_COPYRIGHT@
 * COPYRIGHT NOTICE
 * Copyright (c) 1990, 1991, 1992, 1993, 1996 Open Software Foundation, Inc.
 * ALL RIGHTS RESERVED (DCE).  See the file named COPYRIGHT.DCE in the
 * src directory for the full copyright text.
 */
/*
 * HISTORY
 * $Log: ignore.idl,v $
 * Revision 1.1.4.2  1996/03/11  02:14:43  marty
 * 	Update OSF copyright years
 * 	[1996/03/10  19:53:38  marty]
 *
 * Revision 1.1.4.1  1995/12/11  20:08:34  root
 * 	Submit OSF/DCE 1.2.1
 * 	[1995/12/11  19:32:39  root]
 * 
 * Revision 1.1.2.2  1993/01/07  19:58:37  bbelch
 * 	Embedding copyright notice
 * 	[1993/01/06  13:34:46  bbelch]
 * 
 * Revision 1.1  1992/01/19  03:29:42  devrcs
 * 	Initial revision
 * 
 * $EndLog$
 */
/*
*/
[uuid(f9f6be80-2ba7-11c9-89fd-08002b13d56d),
 version(0),
 pointer_default(ptr),
 endpoint("ncadg_ip_udp:[6677]", "dds:[19]")]
interface ignore
{
/*
 * Version of binopwk to test [ignore] attribute.
 */
typedef struct
{
    [ignore] small * filler1;
    long a;
    [ignore] short * filler2;
    long b;
    [ignore] long * filler3;
    long c;
    [ignore] hyper * filler4;
} struct_t;

[idempotent] void binopwk_add
(
    [in] handle_t h,
    [in,out] struct_t *s
);
}
