# @OSF_COPYRIGHT@
# COPYRIGHT NOTICE
# Copyright (c) 1990, 1991, 1992, 1993, 1994, 1996 Open Software Foundation, Inc.
# ALL RIGHTS RESERVED (DCE).  See the file named COPYRIGHT.DCE for
# the full copyright text.
# 
# HISTORY
# $Log: Makefile,v $
# Revision 1.1.4.2  1996/03/11  01:38:47  marty
# 	Update copyright years
# 	[1996/03/10  19:41:42  marty]
#
# Revision 1.1.4.1  1995/12/11  16:56:23  root
# 	Submit
# 	[1995/12/11  16:40:45  root]
# 
# Revision 1.1.2.4  1994/07/11  18:22:49  keutel
# 	new subdirectory: typeless_valid
# 	[1994/07/11  18:22:32  keutel]
# 
# Revision 1.1.2.3  1994/07/06  15:12:19  marrek
# 	July 1994 code drop.
# 	[1994/07/06  12:03:57  marrek]
# 
# Revision 1.1.2.2  1994/06/10  20:24:55  devsrc
# 	cr10872 - fixed copyright
# 	[1994/06/10  17:00:57  devsrc]
# 
# Revision 1.1.2.1  1994/05/10  14:39:53  marrek
# 	Created in April 1994 submission.
# 	[1994/05/03  12:17:59  marrek]
# 
# $EndLog$
#
# $RCSfile: Makefile,v $ $Revision: 1.1.4.2 $ $Date: 1996/03/11 01:38:47 $
#

SUBDIRS		= invalid tree valid typeless_valid \
		  threads_af threads_as threads_os threads_up

.include <${RULES_MK}>
