# @OSF_COPYRIGHT@
# COPYRIGHT NOTICE
# Copyright (c) 1990, 1991, 1992, 1993, 1994, 1996 Open Software Foundation, Inc.
# ALL RIGHTS RESERVED (DCE).  See the file named COPYRIGHT.DCE for
# the full copyright text.
# 
# 
# HISTORY
# $Log: Makefile,v $
# Revision 1.1.6.3  1996/03/11  02:29:57  marty
# 	Update OSF copyright years
# 	[1996/03/10  19:37:30  marty]
#
# Revision 1.1.6.2  1995/12/11  15:20:53  root
# 	Submit
# 	[1995/12/11  14:34:04  root]
# 
# Revision 1.1.2.1  1994/10/26  21:02:55  mori_m
# 	CR 11259:  Added multi-bytes functional tests.
# 	[1994/10/26  20:52:33  mori_m]
# 
# $EndLog$

SUBDIRS		= eucjp sjis
DATA_SUBDIRS	= ${SUBDIRS}

.include <${RULES_MK}>
