#
# @OSF_COPYRIGHT@
# COPYRIGHT NOTICE
# Copyright (c) 1990, 1991, 1992, 1993, 1996 Open Software Foundation, Inc.
# ALL RIGHTS RESERVED (DCE).  See the file named COPYRIGHT.DCE in the
# src directory for the full copyright text.
#
#
# HISTORY
# $Log: Makefile,v $
# Revision 1.1.42.2  1996/03/11  02:19:26  marty
# 	Update OSF copyright years
# 	[1996/03/10  19:56:02  marty]
#
# Revision 1.1.42.1  1995/12/11  19:31:10  root
# 	Submit OSF/DCE 1.2.1
# 	[1995/12/11  19:16:25  root]
# 
# Revision 1.1.40.1  1993/12/28  22:11:24  pellis
# 	Updated for ODE 2.3 make
# 	[1993/12/28  21:54:49  pellis]
# 
# Revision 1.1.2.2  1993/08/11  16:29:03  ganni
# 	tests for new IDL functionality
# 	[1993/08/11  16:16:34  ganni]
# 
# $EndLog$
#

IDLBASE = ue1

OTHER_CLIENT_FILES = client_aux.o util1.o
OTHER_SERVER_FILES = util1.o

.include "../maketest.mk"
