# @OSF_COPYRIGHT@
# COPYRIGHT NOTICE
# Copyright (c) 1996 Open Software Foundation, Inc.
# ALL RIGHTS RESERVED (DCE).  See the file named COPYRIGHT.DCE for
# the full copyright text.
# 
# HISTORY
# $Log: Makefile,v $
# Revision 1.1.4.2  1996/03/09  20:45:59  marty
# 	Add OSF copyright
# 	[1996/03/09  20:25:18  marty]
#
# Revision 1.1.4.1  1995/12/13  21:55:14  root
# 	Submit OSF/DCE 1.2.1
# 
# 	HP revision /main/HPDCE02/1  1995/05/25  15:06 UTC  mothra
# 	for non-tet tests
# 	[1995/12/13  21:53:29  root]
# 
# $EndLog$
#
#

VPATH	= ${SOURCEBASE}/test/functional/directory/gds/ts/gdscp/lib/x500abbr/valid
IDIR    = /test/directory/gdscp/x500abbr/valid/
ILIST	= abbr_operations_v.tcl abbr_show_v.tcl

.include <${RULES_MK}>
