#
#      SCCS:  @(#)makefile	1.2 (92/09/30) 
#
#	UniSoft Ltd., London, England
#
# (C) Copyright 1992 X/Open Company Limited
#
# All rights reserved.  No part of this source code may be reproduced,
# stored in a retrieval system, or transmitted, in any form or by any
# means, electronic, mechanical, photocopying, recording or otherwise,
# except as stated in the end-user licence agreement, without the prior
# permission of the copyright owners.
#
# X/Open and the 'X' symbol are trademarks of X/Open Company Limited in
# the UK and other countries.
#
#
# ************************************************************************
#
# SCCS:   	@(#)makefile	1.2 92/09/30
# NAME:		makefile
# PRODUCT:	DTET (Distributed Test Environment Toolkit) release 1.0b
# AUTHOR:		Andrew Dingwall, UniSoft Ltd.
# DATE CREATED:	June 1992
#
# DESCRIPTION:
#	lint library makefile
#
#	this makefile depends on there being a .c.ln suffix rule in defines.mk
#	this is somewhat difficult to implement for a BSD-style lint
# 
# MODIFICATIONS:
# 
# ************************************************************************

include ../defines.mk
include ../common.mk

ALL = llib-ldapi.ln llib-ldtet.ln llib-linet.ln llib-lserv.ln

TARGETS = $(LIB)/llib-ldapi.ln

all: $(ALL)

install: $(TARGETS)

$(TARGETS): $$(@F)
	cp $(@F) $@

CLEAN clean:
	rm -f $(ALL)

CLOBBER clobber: clean
	rm -f $(TARGETS)

FORCE FRC: clobber all


# dependencies

llib-ldapi.ln: $(INC)/dapi.h

llib-ldtet.ln: $(INC)/avmsg.h $(INC)/btmsg.h $(INC)/dtetlib.h $(INC)/dtmac.h \
	$(INC)/dtmsg.h $(INC)/ftoa.h $(INC)/ldst.h $(INC)/llist.h \
	$(INC)/ltoa.h $(INC)/ptab.h $(INC)/sysent.h $(INC)/valmsg.h

llib-linet.ln: $(INC)/dtmsg.h $(INC)/inetlib_in.h $(INC)/ptab.h \
	$(INC)/tsinfo_in.h

llib-lserv.ln: $(INC)/dtmsg.h $(INC)/ptab.h $(INC)/servlib.h $(INC)/synreq.h


