/*
 * @OSF_COPYRIGHT@
 * COPYRIGHT NOTICE
 * Copyright (c) 1990, 1991, 1992, 1993, 1996 Open Software Foundation, Inc.
 * ALL RIGHTS RESERVED (DCE).  See the file named COPYRIGHT.DCE in the
 * src directory for the full copyright text.
 */
/*
 * HISTORY
 * $Log: string1.idl,v $
 * Revision 1.1.4.2  1996/03/11  02:18:39  marty
 * 	Update OSF copyright years
 * 	[1996/03/10  19:55:39  marty]
 *
 * Revision 1.1.4.1  1995/12/11  19:30:09  root
 * 	Submit OSF/DCE 1.2.1
 * 	[1995/12/11  19:15:55  root]
 * 
 * Revision 1.1.2.2  1993/01/07  23:37:57  bbelch
 * 	Embedding copyright notice
 * 	[1993/01/06  13:44:41  bbelch]
 * 
 * Revision 1.1  1992/01/19  03:28:08  devrcs
 * 	Initial revision
 * 
 * $EndLog$
 */
/*
*/
[uuid(6b908d80-838f-11c9-9053-08002b0ecef1), version(0)]
interface string1
{


    /*
    ** Operation that returns the concat of two strings 
    */
    [string] char *remote_strcat(
        [in,string] char *s1,
        [in,string] char *s2
        );
}
