# 
# @OSF_COPYRIGHT@
# COPYRIGHT NOTICE
# Copyright (c) 1990, 1991, 1992, 1993, 1994, 1996 Open Software Foundation, Inc.
# ALL RIGHTS RESERVED (DCE).  See the file named COPYRIGHT.DCE for 
# the full copyright text.
#
# 
# HISTORY
# $Log: Makefile,v $
# Revision 1.1.4.2  1996/03/11  01:34:27  marty
# 	Update copyright years
# 	[1996/03/10  19:36:36  marty]
#
# Revision 1.1.4.1  1995/12/11  15:28:25  root
# 	Submit
# 	[1995/12/11  14:37:10  root]
# 
# Revision 1.1.2.2  1994/07/06  15:12:01  marrek
# 	July 1994 code drop.
# 	[1994/07/06  12:03:37  marrek]
# 
# Revision 1.1.2.1  1994/06/21  14:32:17  marrek
# 	Created in June 94 code submission.
# 	[1994/06/10  16:07:22  marrek]
# 
# $EndLog$
#
# $RCSfile: Makefile,v $ $Revision: 1.1.4.2 $ $Date: 1996/03/11 01:34:27 $
#

SUBDIRS		= valid invalid

.include <${RULES_MK}>

