/*
 * @OSF_COPYRIGHT@
 * COPYRIGHT NOTICE
 * Copyright (c) 1990, 1991, 1992, 1993, 1996 Open Software Foundation, Inc.
 * ALL RIGHTS RESERVED (DCE).  See the file named COPYRIGHT.DCE in the
 * src directory for the full copyright text.
 */
/*
 * HISTORY
 * $Log: h_ta.idl,v $
 * Revision 1.1.4.2  1996/03/11  02:14:02  marty
 * 	Update OSF copyright years
 * 	[1996/03/10  19:53:23  marty]
 *
 * Revision 1.1.4.1  1995/12/11  20:06:33  root
 * 	Submit OSF/DCE 1.2.1
 * 	[1995/12/11  19:31:50  root]
 * 
 * Revision 1.1.2.2  1993/01/07  19:58:09  bbelch
 * 	Embedding copyright notice
 * 	[1993/01/06  13:34:29  bbelch]
 * 
 * Revision 1.1  1992/01/19  03:31:59  devrcs
 * 	Initial revision
 * 
 * $EndLog$
 */
/*
*/
/*%a%copyright(Copyright)
    72 1.1 5/8/91

    Test use of types that mix handle and transmit_as attributes.
*/

[uuid(d8715fc0-c514-11c9-af25-08001e0218e9), version(0)]
interface h_ta {

    const char *h_ta_name = "auto-handle type with transmit_as";

    const long CALLED_SIZE = 11;
    const long XMIT_T_SIZE = 12;

    const long BIND_CALLED      = 0x00000F;
    const long UNBIND_CALLED    = 0x0000F0;
    const long TO_XMIT_CALLED   = 0x000F00;
    const long FROM_XMIT_CALLED = 0x00F000;
    const long FREE_XMIT_CALLED = 0x0F0000;
    const long FREE_INST_CALLED = 0xF00000;

    const long IN_MANAGER       = 0xFFFFFF;

    typedef long xmit_t[XMIT_T_SIZE];

    typedef struct {
        long index;
        long called[CALLED_SIZE];
    } record_t;

    typedef [handle, transmit_as(xmit_t)] record_t *pres_t;

    record_t h_ta_op1(
        [in] pres_t h
    );

    record_t h_ta_op2(
        [in, out] pres_t *h
    );

    record_t h_ta_op3(
        [in]    pres_t hin,
        [out]   pres_t *hout
    );

}
