#
# @OSF_COPYRIGHT@
# COPYRIGHT NOTICE
# Copyright (c) 1990, 1991, 1992, 1993, 1996 Open Software Foundation, Inc.
# ALL RIGHTS RESERVED (DCE).  See the file named COPYRIGHT.DCE in the
# src directory for the full copyright text.
#
#
# HISTORY
# $Log: Makefile,v $
# Revision 1.1.34.2  1996/03/11  02:19:41  marty
# 	Update OSF copyright years
# 	[1996/03/10  19:56:09  marty]
#
# Revision 1.1.34.1  1995/12/11  19:31:27  root
# 	Submit OSF/DCE 1.2.1
# 	[1995/12/11  19:16:34  root]
# 
# Revision 1.1.32.1  1993/12/28  22:11:27  pellis
# 	Updated for ODE 2.3 make
# 	[1993/12/28  21:54:51  pellis]
# 
# Revision 1.1.2.2  1993/08/11  16:29:55  ganni
# 	tests for new IDL functionality
# 	[1993/08/11  16:17:13  ganni]
# 
# $EndLog$
#

IDLBASE = unique1

OTHER_CLIENT_FILES = client_aux.o

.include "../maketest.mk"
