/*
 * @OSF_COPYRIGHT@
 * COPYRIGHT NOTICE
 * Copyright (c) 1990, 1991, 1992, 1993, 1996 Open Software Foundation, Inc.
 * ALL RIGHTS RESERVED (DCE).  See the file named COPYRIGHT.DCE in the
 * src directory for the full copyright text.
 */
/*
 * HISTORY
 * $Log: unique1.idl,v $
 * Revision 1.1.4.2  1996/03/11  02:19:44  marty
 * 	Update OSF copyright years
 * 	[1996/03/10  19:56:10  marty]
 *
 * Revision 1.1.4.1  1995/12/11  19:31:32  root
 * 	Submit OSF/DCE 1.2.1
 * 	[1995/12/11  19:16:38  root]
 * 
 * Revision 1.1.2.2  1993/08/11  16:30:08  ganni
 * 	tests for new IDL functionality
 * 	[1993/08/11  16:17:24  ganni]
 * 
 * $EndLog$
 */
/*
*/
[
uuid(41a502fc-1f49-11ca-b680-08002b107359),
version(0.0)
]
interface unique1
{
    const long ARRAY_SIZE = 20;
    const long UA_SIZE = 10;

    typedef struct a_struct {
        short f1;
        long f2;
    } a_struct;

    typedef [unique] a_struct *u_a_ptr;

    void op0 (  [in] handle_t h,
                [in, out] long *f,
                [in, out] long *l,
                [in, out, first_is(*f), last_is(*l)] u_a_ptr uap[ARRAY_SIZE] );

    void op1 (  [in] handle_t h,
                [in] long s,
                [in, out] long *f,
                [in, out] long *l,
                [in, out, size_is(s), first_is(*f), last_is(*l)] u_a_ptr uap[]
             );

    typedef struct u_struct {
        u_a_ptr u1;
        u_a_ptr u2;
    } u_struct;

    void op2 (  [in] handle_t h,
                [in, out] long *f,
                [in, out] long *l,
                [in, out, first_is(*f), last_is(*l)] u_struct us[UA_SIZE] );

    void op3 (  [in] handle_t h,
                [in] long s,
                [in, out] long *f,
                [in, out] long *l,
                [in, out, size_is(s), first_is(*f), last_is(*l)] u_struct us[]
             );

    typedef [ref] u_struct *r_u_ptr;

    void op4 (  [in] handle_t h,
                [in, out] long *f,
                [in, out] long *l,
                [in, out, first_is(*f), last_is(*l)] r_u_ptr rup[ARRAY_SIZE] );

    void op5 (  [in] handle_t h,
                [in] long s,
                [in, out] long *f,
                [in, out] long *l,
                [in, out, size_is(s), first_is(*f), last_is(*l)] r_u_ptr rup[]
             );

}
