# @OSF_COPYRIGHT@
# COPYRIGHT NOTICE
# Copyright (c) 1990, 1991, 1992, 1993, 1994, 1996 Open Software Foundation, Inc.
# ALL RIGHTS RESERVED (DCE).  See the file named COPYRIGHT.DCE for
# the full copyright text.
# 
# HISTORY
# $Log: Makefile,v $
# Revision 1.1.4.2  1996/03/11  02:33:43  marty
# 	Update OSF copyright years
# 	[1996/03/10  19:39:15  marty]
#
# Revision 1.1.4.1  1995/12/11  15:23:37  root
# 	Submit
# 	[1995/12/11  14:35:20  root]
# 
# Revision 1.1.2.4  1994/07/06  15:09:57  marrek
# 	July 1994 code drop.
# 	[1994/07/06  12:03:03  marrek]
# 
# Revision 1.1.2.3  1994/06/21  14:29:11  marrek
# 	June 1994 code submission.
# 	[1994/06/16  07:49:34  marrek]
# 
# Revision 1.1.2.2  1994/06/10  20:20:31  devsrc
# 	cr10872 - fixed copyright
# 	[1994/06/10  16:58:54  devsrc]
# 
# Revision 1.1.2.1  1994/05/10  14:32:11  marrek
# 	Created in April 1994 submission.
# 	[1994/05/03  12:13:39  marrek]
# 
# $EndLog$
#
# $RCSfile: Makefile,v $ $Revision: 1.1.4.2 $ $Date: 1996/03/11 02:33:43 $
#

SUBDIRS         = admin config gdscp lib gdssetup gds_sec

.include <${RULES_MK}>

