# @OSF_COPYRIGHT@
# COPYRIGHT NOTICE
# Copyright (c) 1990, 1991, 1992, 1993, 1994 Open Software Foundation, Inc.
# ALL RIGHTS RESERVED (DCE).  See the file named COPYRIGHT.DCE for
# the full copyright text.
# 
# HISTORY
# $Log: Makefile,v $
# Revision 1.1.24.1  1996/10/02  17:15:29  damon
# 	Newest DFS from Transarc
# 	[1996/10/01  18:06:53  damon]
#
# Revision 1.1.18.2  1994/06/09  13:55:59  annie
# 	fixed copyright in src/file
# 	[1994/06/08  21:30:32  annie]
# 
# Revision 1.1.18.1  1994/02/04  20:09:53  devsrc
# 	Merged from 1.0.3a to 1.1
# 	[1994/02/04  15:08:26  devsrc]
# 
# Revision 1.1.16.1  1993/12/07  17:15:47  jaffe
# 	New File from Transarc 1.0.3a
# 	[1993/12/02  20:19:17  jaffe]
# 
# $EndLog$

INCFLAGS		+= -I../anode/${TARGET_OS}
