#!/bin/awk
# @OSF_COPYRIGHT@
# COPYRIGHT NOTICE
# Copyright (c) 1996 Open Software Foundation, Inc.
# ALL RIGHTS RESERVED (DCE).  See the file named COPYRIGHT.DCE for
# the full copyright text.
# 
# 
# HISTORY
# $Log: filter,v $
# Revision 1.1.2.1  1996/09/09  16:30:12  bfc
# 	finish TETizing and cleanup
# 	[1996/09/09  16:19:57  bfc]
#
# $EndLog$

BEGIN { 
	FS = "|"
	passed = 0
	failed = 0
	missing = 0
	tc_start = 0
}
{
  if ($1 ~ /400/) {
    if (tc_start) {
      ++missing
    }
    else {
      tc_start = 1
    }
  }
  else if ($1 ~ /220/) {
    print $0
    if ($3 ~ /PASS/) {
	++passed
    }
    else {
	++failed
    }
    tc_start = 0
  }
}
END {
  printf "Passed: %d\n",passed
  printf "Failed: %d\n",failed
  printf "Missing results: %d\n",missing
}
