# @OSF_COPYRIGHT@
# COPYRIGHT NOTICE
# Copyright (c) 1990, 1991, 1992, 1993, 1994, 1996 Open Software Foundation, Inc.
# ALL RIGHTS RESERVED (DCE).  See the file named COPYRIGHT.DCE for
# the full copyright text.
# 
# 
# HISTORY
# $Log: Makefile,v $
# Revision 1.1.4.2  1996/03/11  02:05:45  marty
# 	Update OSF copyright years
# 	[1996/03/10  19:49:56  marty]
#
# Revision 1.1.4.1  1995/12/11  19:47:42  root
# 	Submit OSF/DCE 1.2.1
# 	[1995/12/11  19:25:07  root]
# 
# 	Submit OSF/DCE 1.2.1
# 	[1995/12/11  18:16:21  root]
# 
# Revision 1.1.2.2  1994/06/10  20:42:29  devsrc
# 	cr10872 - fixed copyright
# 	[1994/06/10  17:14:52  devsrc]
# 
# Revision 1.1.2.1  1994/05/04  21:53:03  mori_m
# 	CR 9701:  RPC runtime I18N extension functional test drop.
# 	[1994/05/04  21:08:09  mori_m]
# 
# $EndLog$

SUBDIRS = runtime

DATA_SUBDIRS = runtime

.include <${RULES_MK}>
