/*
 * @OSF_COPYRIGHT@
 * COPYRIGHT NOTICE
 * Copyright (c) 1996 Open Software Foundation, Inc.
 * ALL RIGHTS RESERVED (DCE).  See the file named COPYRIGHT.DCE for
 * the full copyright text.
 * 
 */
/*
 * HISTORY
 * $Log: static.idl,v $
 * Revision 1.1.2.2  1996/03/09  20:50:10  marty
 * 	Add OSF copyright
 * 	[1996/03/09  20:28:20  marty]
 *
 * Revision 1.1.2.1  1995/12/11  19:36:06  root
 * 	Submit OSF/DCE 1.2.1
 * 	[1995/12/11  19:18:56  root]
 * 
 * $EndLog$
 */
[
    uuid(1906d1b4-e46a-11cd-af6a-08002b3d8412)
] interface Static
{
    static short foo(void);
    short fee(void);
    short fii(void);
}
