/*
 * @OSF_COPYRIGHT@
 * COPYRIGHT NOTICE
 * Copyright (c) 1990, 1991, 1992, 1993, 1996 Open Software Foundation, Inc.
 * ALL RIGHTS RESERVED (DCE).  See the file named COPYRIGHT.DCE in the
 * src directory for the full copyright text.
 */
/*
 * HISTORY
 * $Log: string0.idl,v $
 * Revision 1.1.4.2  1996/03/11  02:18:31  marty
 * 	Update OSF copyright years
 * 	[1996/03/10  19:55:34  marty]
 *
 * Revision 1.1.4.1  1995/12/11  19:29:59  root
 * 	Submit OSF/DCE 1.2.1
 * 	[1995/12/11  19:15:51  root]
 * 
 * Revision 1.1.2.2  1993/01/07  23:37:13  bbelch
 * 	Embedding copyright notice
 * 	[1993/01/06  13:44:10  bbelch]
 * 
 * Revision 1.1  1992/01/19  03:27:55  devrcs
 * 	Initial revision
 * 
 * $EndLog$
 */
/*
*/
[uuid(1c324c00-822d-11c9-aff2-08002b0a98a3), version(0)]
interface string0
{
    const long A = 10000;
    const long B = 100;
    const long C = 100;

    typedef [v1_array] char v1_array_t[A];

    small op1([in] handle_t h, [in, v1_string] v1_array_t s, [in] long checksum);
    void op2([in] handle_t h, [in, out, v1_string, v1_array] char s[A]);
    small op3([in] handle_t h, [in, v1_string, v1_array] char s[B][C], [in] long checksum);
}
