#!/bin/ksh
#
# @OSF_COPYRIGHT@
# COPYRIGHT NOTICE
# Copyright (c) 1990, 1991, 1992, 1993, 1994, 1996 Open Software Foundation, Inc.
# ALL RIGHTS RESERVED (DCE).  See the file named COPYRIGHT.DCE for
# the full copyright text.
# 
# HISTORY
# $Log: xds_st,v $
# Revision 1.1.4.2  1996/03/11  02:07:02  marty
# 	Update copyright years
# 	[1996/03/10  19:57:23  marty]
#
# Revision 1.1.4.1  1995/12/11  17:31:37  root
# 	Submit OSF/DCE 1.2.1
# 	[1995/12/11  17:09:06  root]
# 
# Revision 1.1.2.9  1994/08/17  11:51:47  marrek
# 	Use uname -n .
# 	[1994/08/17  07:37:24  marrek]
# 
# Revision 1.1.2.8  1994/08/01  12:27:27  marrek
# 	Fixes for OT 10742, 11357, 11432.
# 	[1994/08/01  12:26:21  marrek]
# 
# Revision 1.1.2.7  1994/07/15  16:58:25  keutel
# 	OT 11316: unsetting of XDS_LOG and D2_LOG removed
# 	[1994/07/15  15:29:54  keutel]
# 
# Revision 1.1.2.6  1994/07/06  15:54:31  marrek
# 	Add version string in July 1994 code drop.
# 	[1994/07/06  15:43:18  marrek]
# 
# Revision 1.1.2.5  1994/06/21  14:29:44  marrek
# 	June 1994 code submission.
# 	[1994/06/16  07:51:01  marrek]
# 
# Revision 1.1.2.4  1994/06/10  20:25:59  devsrc
# 	cr10872 - fixed copyright
# 	[1994/06/10  17:01:24  devsrc]
# 
# Revision 1.1.2.3  1994/05/23  17:42:29  zeliff
# 	ot10705: fix tet lock problem
# 	[1994/05/23  15:52:38  zeliff]
# 
# Revision 1.1.2.2  1994/05/18  22:10:35  zeliff
# 	ot10695: fix testcases mismatch
# 	[1994/05/18  21:54:11  zeliff]
# 
# 	ot10647: added prefixs for script invocations
# 	[1994/05/15  21:03:16  zeliff]
# 
# Revision 1.1.2.1  1994/05/10  14:56:22  marrek
# 	Add shell interpreter in first line.
# 	[1994/05/09  09:13:39  marrek]
# 
# 	Created in April 1994 submission.
# 	[1994/05/03  12:18:51  marrek]
# 
# $EndLog$
#
# $RCSfile: xds_st,v $ $Revision: 1.1.4.2 $ $Date: 1996/03/11 02:07:02 $
#
#  (c) Copyright 1991,1992-1994 Siemens-Nixdorf Information Systems
#  Munich, Germany
#  All Rights Reserved
#
# xds_st
# NAME xds_st
#
# DESC
# {
# GDS XDS Tests (single threaded mode)
# Each invocable component runs the 'xt_test -i' executable using as standard
# input the batch file specified in each strategy statement.
# Also, the DIT must already contain at least the two following object:
#  DSA1:        /C=de/O=dbp/OU=dap11/CN=dsa/CN=dsa-m1
#  DSA2:        /C=de/O=dbp/OU=dap11/CN=dsa/CN=dsa-m2
# }
#

TP_PATH="lib/"
_HOST_NAME=`uname -n`

tet_startup="Startup"			# startup function
tet_cleanup="Cleanup"			# cleanup function

iclist="ic1 ic2 ic3 ic4 ic5 ic6 ic7 ic8"

ic1="tp1"				# functions for ic1
ic2="tp2"				# functions for ic2
ic3="tp1"				# functions for ic3
ic4="tp3"				# functions for ic4
ic5="tp1"				# functions for ic5
ic6="tp4"				# functions for ic6
ic7="tp1"
ic8="tp5"

tp1() {
	tet_infoline "XDS - cleantree"
	$API_SCRIPTS/cleantree "${TP_PATH}"
}

tp2() {
	tet_infoline "XDS - basic Testcases"
	$API_SCRIPTS/TEST "${TP_PATH}"basic > /tmp/test_trace 2>&1
	check_ERROR_xds "${TP_PATH}basic.$_HOST_NAME.result" 0 1
}

tp3() {
        tet_infoline "XDS - valid Testcases"
        $API_SCRIPTS/TEST "${TP_PATH}"valid > /tmp/test_trace 2>&1
        check_ERROR_xds "${TP_PATH}valid.$_HOST_NAME.result" 0 1
}

tp4() {
        tet_infoline "XDS - invalid Testcases"
        $API_SCRIPTS/TEST "${TP_PATH}"invalid > /tmp/test_trace 2>&1
        check_ERROR_xds "${TP_PATH}invalid.$_HOST_NAME.result" 0 1
}

tp5() {
        tet_infoline "XDS - stress Testcases"
        $API_SCRIPTS/TEST "${TP_PATH}"stress > /tmp/test_trace 2>&1
        check_ERROR_xds "${TP_PATH}stress.$_HOST_NAME.result" 0 1
}

Cleanup() {
        rm -f /tmp/test_trace
        if [[ -z "$KEEP_API_LOGS" ]]
        then
	   find ${TET_EXECUTE}/xds/lib/valid -name *.log -exec rm -f {} \;
	   find ${TET_EXECUTE}/xds/lib/invalid -name *.log -exec rm -f {} \;
	   find ${TET_EXECUTE}/xds/lib/stress -name *.log -exec rm -f {} \;
	   find ${TET_EXECUTE}/xds/lib/basic -name *.log -exec rm -f {} \;
        fi
        rm -f ${TET_EXECUTE}/xds/save*
	tet_infoline "TESTING with XT_TEST FINISHED"
}

Startup() {
	export_paths
        rm -f ${TET_EXECUTE}/tet.log
	tet_infoline "TESTING with XT_TEST STARTED"
        . ${TET_EXECUTE}/config/two_dsas.sh
}

#source shell common functions
. ${TET_EXECUTE}/lib/shfuncs

#execute shell test case manager - must be last line
. ${TET_ROOT}/lib/xpg3sh/tcm.sh

