# @OSF_COPYRIGHT@
# COPYRIGHT NOTICE
# Copyright (c) 1990, 1991, 1992, 1993, 1994, 1996 Open Software Foundation, Inc.
# ALL RIGHTS RESERVED (DCE).  See the file named COPYRIGHT.DCE for
# the full copyright text.
# 
# 
# HISTORY
# $Log: Makefile,v $
# Revision 1.1.4.2  1996/03/11  02:08:05  marty
# 	Update OSF copyright years
# 	[1996/03/10  19:51:01  marty]
#
# Revision 1.1.4.1  1995/12/11  19:54:26  root
# 	Submit OSF/DCE 1.2.1
# 	[1995/12/11  19:27:36  root]
# 
# Revision 1.1.2.2  1994/06/10  20:44:44  devsrc
# 	cr10872 - fixed copyright
# 	[1994/06/10  17:16:24  devsrc]
# 
# Revision 1.1.2.1  1994/03/10  22:40:55  bhaim
# 	Common TET functions
# 	[1994/03/10  22:40:01  bhaim]
# 
# $EndLog$

INCLUDES        = tst_comm_api.h

EXPDIR  = /usr/include/dce/

.include <${RULES_MK}>

