# @OSF_COPYRIGHT@
# COPYRIGHT NOTICE
# Copyright (c) 1990, 1991, 1992, 1993, 1994, 1996 Open Software Foundation, Inc.
# ALL RIGHTS RESERVED (DCE).  See the file named COPYRIGHT.DCE for
# the full copyright text.
# 
# HISTORY
# $Log: Makefile,v $
# Revision 1.1.8.2  1996/03/11  02:39:46  marty
# 	Update OSF copyright years
# 	[1996/03/10  20:05:56  marty]
#
# Revision 1.1.8.1  1995/12/11  21:56:52  root
# 	Submit OSF/DCE 1.2.1
# 
# 	HP revision /main/HPDCE02/1  1994/06/29  18:26 UTC  bissen
# 	Merge hpdce02 (DCE 1.1 beta) and HPDCE01 into HPDCE02
# 
# 	HP revision /main/HPDCE01/1  1994/02/02  14:03  bissen
# 	merge kk and hpdce01
# 	[1995/12/11  20:56:43  root]
# 
# Revision 1.1.4.2  1993/08/30  18:18:00  giza
# 	fixed IDIRs for TET
# 	[1993/08/27  21:19:04  giza]
# 
# Revision 1.1.1.6  1993/05/04  22:20:14  mgm
# 	    Loading drop DCE1_0_2FNL
# 
# Revision 1.1.4.1  1993/09/15  13:15:24  cmckeen
# 	Added cdsserv.cfg to OTHERS line.  Added IDIR line
# 	[1993/09/15  13:15:10  cmckeen]
# 
# Revision 1.1.2.2  1993/03/31  19:57:06  eperkins
# 	Initial version
# 	[1993/03/31  19:56:43  eperkins]
# 
# $EndLog$

OTHERS = cdsserv.ksh cdsserv.cfg

#
# List of installables  
#
cdsserv.ksh_IDIR = /tet/cds/ts/cds.server.4/
cdsserv.cfg_IDIR = /tet/cds/ts/cds.server.4/

ILIST = ${OTHERS}

.include <${RULES_MK}>

