#!/bin/csh -f
#
# @OSF_COPYRIGHT@
# COPYRIGHT NOTICE
# Copyright (c) 1990, 1991, 1992, 1993 Open Software Foundation, Inc.
# ALL RIGHTS RESERVED (DCE).  See the file named COPYRIGHT.DCE in the
# src directory for the full copyright text.
#
# HISTORY
# $Log: test1,v $
# Revision 1.1.10.1  1996/10/17  18:35:46  damon
# 	Submitting on behalf of Transarc
# 	[1996/10/17  16:57:43  damon]
#
# Revision 1.1.5.2  1993/01/11  18:37:14  htf
# 	Embedded copyright notice
# 	[1993/01/11  17:21:47  htf]
# 
# Revision 1.1.2.2  1992/05/21  12:52:23  jaffe
# 	Transarc delta: fred-merge-tests 1.1
# 	  Selected comments:
# 	    Created this delta to merge Phil Hirsch's final DFS test code changes with
# 	    the test code that the OSF had.  Hopefully, this means we and the OSF
# 	    should be looking at the same test code.
# 	    Changes to facilitate merge of local DFS test code with the OSF's.
# 
# 	$TALog: test1,v $
# 	Revision 4.6  1994/11/08  16:23:41  cfe
# 	[merge of changes from 4.3 to 4.5 into 4.4]
# 
# 	[*** log entries omitted ***]
# 
# Revision 4.4  1994/08/24  20:27:19  andi
# 	Fix typos.
# 
# 	Fix typos.
# 	[from r4.3 by delta andi-db5908-fix-scout-tests, r1.1]
# 
# Revision 4.3  1993/01/14  17:41:42  jaffe
# 	revdrop of latest OSF copyright changes to these files
# 	[from r4.2 by delta osf-revdrop-01-12-92, r1.1]
# 
# 	[1992/05/20  21:10:03  jaffe]
# 
# $EndLog$
#

###############################################################################
#    Copyright (C) 1991, 1992 Transarc Corporation - All rights reserved      #
###############################################################################

# This test is applicable to DFS.
# The script tests the scout commands that don't actually run the scout
# monitor.

###############################################################################

# Usage:                test1

# Typically run via:    test1 >& test1.out

###############################################################################

# Test environment:
# This test requires DFS server $SERVER_1 to be up and running.

# Privilege required:
# Nothing special.

# Highest error number is: 12.

###############################################################################

setenv d `pwd`
setenv hn `hostname`
setenv p `basename $0`
setenv p1 $p":"
setenv rc 0
setenv ty scout

if ($?AUTH_ARG == 0) setenv AUTH_ARG ""
if ($?CELL_NAME == 0) setenv CELL_NAME `sed -n '/cellname/s/cellname[         ]*\/\.\.\.\///p' /opt/dcelocal/dce_cf.db`}
if ($?CELL_ARG == 0) setenv CELL_ARG ""
if ($?SERVER_1 == 0) setenv SERVER_1 $hn
if ($?VERB_ARG == 0) setenv VERB_ARG ""

if ($?sbin_dir == 0) setenv sbin_dir /opt/dceshared/bin
if ($?dns_cell_name == 0) setenv dns_cell_name /.../$CELL_NAME
if ($?dns_server_prefix == 0) setenv dns_server_prefix /.:/hosts

setenv PATH ":"$sbin_dir":"$PATH

setenv sav_arg "-server $dns_server_prefix/$SERVER_1 $AUTH_ARG $VERB_ARG"

###############################################################################

echo ""
echo "RUNNING scout COMMANDS on SERVER $SERVER_1 in CELL $CELL_NAME."
echo "========================================================================"
date
echo ""

if ($?CELL_NAME == 0) then
   echo "Can't find cellname in /opt/dcelocal/dce_cf.db - aborting."
   exit 2
   endif

###############################################################################

echo ""; echo scout
scout
if ($status == 0) then
  echo "- worked ($p1 E12)"	
  setenv rc `expr $rc + 1`
endif

echo ""; echo scout initcmd -help
scout initcmd -help
if ($status != 0) then
  echo "- failed ($p1 E1)"	
  setenv rc `expr $rc + 1`
endif

echo ""; echo scout help
scout help
if ($status != 0) then
  echo "- failed ($p1 E2)"	
  setenv rc `expr $rc + 1`
endif

echo ""; echo scout -help
scout -help
if ($status != 0) then
  echo "- failed ($p1 E11)"	
  setenv rc `expr $rc + 1`
endif

echo ""; echo scout initcmd -server $SERVER_1 -help
scout initcmd -server $SERVER_1 -help
if ($status != 0) then
  echo "- failed ($p1 E3)"
  setenv rc `expr $rc + 1`
endif

###############################################################################

echo ""; echo scout apropos foo
scout apropos foo
if ($status != 0) then
  echo "- failed ($p1 E4)"	
  setenv rc `expr $rc + 1`
endif

echo ""; echo scout apropos help
scout apropos help
if ($status != 0) then
  echo "- failed ($p1 E5)"	
  setenv rc `expr $rc + 1`
endif

echo ""; echo scout apropos apropos
scout apropos apropos
if ($status != 0) then
  echo "- failed ($p1 E6)"	
  setenv rc `expr $rc + 1`
endif

###############################################################################

echo ""; echo scout not_a_real_server
scout not_a_real_server
if ( $status == 0) then
  echo "- worked (EXX)"
  setenv rc `expr $rc + 1`
endif

echo ""; echo scout initcmd -server $SERVER_1 -freq -100 
scout initcmd -server $SERVER_1 -freq -100 
if ( $status == 0) then
  echo "- worked ($p1 E7)"
  setenv rc `expr $rc + 1`
endif

echo ""; echo scout initcmd -server $SERVER_1 -attention fetch -100 
scout initcmd -server $SERVER_1 -attention fetch -100 
if ( $status == 0) then
  echo "- worked ($p1 E8)"
  setenv rc `expr $rc + 1`
endif

echo ""; echo scout initcmd -server $SERVER_1 -attention disk 1000%
scout initcmd -server $SERVER_1 -attention disk 1000%
if ( $status == 0) then
  echo "- worked ($p1 E9)"
  setenv rc `expr $rc + 1`
endif

echo ""; echo scout initcmd -server $SERVER_1 -attention fetch 1000000000000 
scout initcmd -server $SERVER_1 -attention fetch 1000000000000 
if ( $status == 0) then
  echo "- worked ($p1 E10)"
  setenv rc `expr $rc + 1`
endif

###############################################################################

sync; sync; sleep 2

echo ""; echo "Done at `date`."; echo ""
if ( $rc == 0) then
   echo "$ty/$p PASSED"
   else
   echo "$ty/$p FAILED ($rc errors)"
   endif

exit $rc

###############################################################################
