/*
 * @OSF_COPYRIGHT@
 * COPYRIGHT NOTICE
 * Copyright (c) 1990, 1991, 1992, 1993, 1994, 1996 Open Software Foundation, Inc.
 * ALL RIGHTS RESERVED (DCE).  See the file named COPYRIGHT.DCE for
 * the full copyright text.
 * 
 */
/*
 * HISTORY
 * $Log: dcdrel003.idl,v $
 * Revision 1.1.4.2  1996/03/11  02:38:36  marty
 * 	Update OSF copyright years
 * 	[1996/03/10  20:05:26  marty]
 *
 * Revision 1.1.4.1  1995/12/11  21:55:48  root
 * 	Submit OSF/DCE 1.2.1
 * 	[1995/12/11  20:55:44  root]
 * 
 * Revision 1.1.2.2  1994/08/10  19:23:23  annie
 * 	expand copyright with OSF copyright text
 * 	[1994/08/10  17:17:40  annie]
 * 
 * Revision 1.1.2.1  1994/06/27  17:12:34  baum
 * 	Changed names from 03 -> 003
 * 	[1994/06/27  17:09:35  baum]
 * 
 * $EndLog$
 */


[
    uuid(008bebed-c7c1-1ddc-9cb3-0000c0ba4944),
    version(1.0)
]
interface dcdrel003
{
	/*
	 * Instruct the server quits as exit(quit_code)
	 */
	[idempotent]
	void server_stop(
		[in]	handle_t	h,
		[in]	unsigned32	quit_code,
		[out]	error_status_t	*st
	);
}
