/*
 * @OSF_COPYRIGHT@
 * COPYRIGHT NOTICE
 * Copyright (c) 1990, 1991, 1992, 1993, 1996 Open Software Foundation, Inc.
 * ALL RIGHTS RESERVED (DCE).  See the file named COPYRIGHT.DCE in the
 * src directory for the full copyright text.
 */
/*
 * HISTORY
 * $Log: threads.idl,v $
 * Revision 1.1.4.2  1996/03/11  02:19:20  marty
 * 	Update OSF copyright years
 * 	[1996/03/10  19:55:59  marty]
 *
 * Revision 1.1.4.1  1995/12/11  19:31:03  root
 * 	Submit OSF/DCE 1.2.1
 * 	[1995/12/11  19:16:21  root]
 * 
 * Revision 1.1.2.2  1993/01/07  23:40:05  bbelch
 * 	Embedding copyright notice
 * 	[1993/01/06  13:46:17  bbelch]
 * 
 * Revision 1.1  1992/01/19  03:28:45  devrcs
 * 	Initial revision
 * 
 * $EndLog$
 */
/*
*/
[version(0), pointer_default(ptr), uuid(4f94ff80-7a11-11c9-968f-08002b0ecef1)]
interface threads
{
/*
 * Test of CMA threads and RPC context handles.
 */
typedef [context_handle] void * ch_t;

void th_init([in] handle_t h);      /* Client-server initialization */
long th_cleanup([in] handle_t h);   /* Client-server cleanup */

void open_counter               /* "Open" counter cell on server */
(
    [in] handle_t h,            /* Binding handle */
    [in] long tid,              /* Thread ID */
    [out] ch_t * th_ctx         /* Thread context handle on counter data */
);

void incr_counter               /* Increment the counter */
(
    [in] ch_t th_ctx            /* Counter context handle */
);

long close_counter              /* "Close" the counter */
(
    [in,out] ch_t * th_ctx      /* Counter context handle */
);
}
