/*
 * @OSF_COPYRIGHT@
 * COPYRIGHT NOTICE
 * Copyright (c) 1990, 1991, 1992, 1993, 1994 Open Software Foundation, Inc.
 * ALL RIGHTS RESERVED (DCE).  See the file named COPYRIGHT.DCE for
 * the full copyright text.
 */
/*
 * HISTORY
 * $Log: ubikvote_proc.idl,v $
 * Revision 1.1.10.1  1996/10/02  17:56:19  damon
 * 	Newest DFS from Transarc
 * 	[1996/10/01  18:42:59  damon]
 *
 * $EndLog$
 */
/*
 * Copyright (C) 1991, 1996 Transarc Corporation
 * All rights reserved.
 */

/* $Header: /u0/rcs_trees/dce/rcs/file/ncsubik/ubikvote_proc.idl,v 1.1.10.1 1996/10/02 17:56:19 damon Exp $ */
[
uuid(4d37f2dd-ed43-0003-02c0-37cf1e000000),
version(4.0)
/* provider version 2 */
]

interface UBIKVOTE
{

import "dcedfs/ubik_data.idl";

/* Vote package interface calls */
/*
 * provider_version(1)
 */
error_status_t UBIKVOTE_Beacon (
	[in] handle_t h,
	[in] signed32 state,
	[in] signed32 voteStart, 
	[in] net_version *Version, 
	[in] net_tid *tid,
	[out] signed32 *voteTime
);

/*
 * provider_version(1)
 */
error_status_t UBIKVOTE_Debug (
	[in] handle_t h,
	[out] ubik_debug *db
);

/*
 * provider_version(1)
 */
error_status_t UBIKVOTE_SDebug (
	[in] handle_t h,
	[in] signed32 which, 
	[out] ubik_sdebug *db
);

/*
 * provider_version(1)
 */
error_status_t UBIKVOTE_GetServerInterfaces (
	[in] handle_t h,
	[out] dfs_interfaceList *serverInterfacesP
);

/*
 * provider_version(1)
 */
error_status_t UBIKVOTE_GetSyncSite (
	[in] handle_t h,
	[out] signed32 *site
);

/*
 * provider_version(2)
 */
error_status_t UBIKVOTE_DebugV2 (
	[in] handle_t h,
	[out] ubik_debug *db,
	[out] ubik_debug_v2 *db_v2
);

/*
 * provider_version(2)
 */
error_status_t UBIKVOTE_SDebugV2 (
	[in] handle_t h,
	[in] signed32 which, 
	[out] ubik_sdebug *db,
	[out] ubik_sdebug_v2 *db_v2
);

/*
 * provider_version(2)
 */
error_status_t UBIKVOTE_GetSyncSiteIdentity (
	[in] handle_t h,
	[out] uuid_t *syncRealm,
	[out] uuid_t *syncPrinc
);

}
