/*
 * @OSF_COPYRIGHT@
 * COPYRIGHT NOTICE
 * Copyright (c) 1990, 1991, 1992, 1993, 1994 Open Software Foundation, Inc.
 * ALL RIGHTS RESERVED (DCE).  See the file named COPYRIGHT.DCE for
 * the full copyright text.
 */
/*
 * HISTORY
 * $Log: ubikdisk_proc.idl,v $
 * Revision 1.1.10.1  1996/10/02  17:56:14  damon
 * 	Newest DFS from Transarc
 * 	[1996/10/01  18:42:57  damon]
 *
 * $EndLog$
 */
/*
 * Copyright (C) 1991, 1996 Transarc Corporation
 * All rights reserved.
 */

/* $Header: /u0/rcs_trees/dce/rcs/file/ncsubik/ubikdisk_proc.idl,v 1.1.10.1 1996/10/02 17:56:14 damon Exp $ */
[
uuid(4d37f2dd-ed43-0002-02c0-37cf1e000000),
version(4.0)
/*provider_version(2)*/
]

interface UBIKDISK
{

import "dcedfs/ubik_data.idl";

/* Disk package interface calls */
/*
 * provider_version(1)
 */
error_status_t UBIKDISK_Begin (
	[in] handle_t	h,
	[in] net_tid	*tid
);

/*
 * provider_version(1)
 */
error_status_t UBIKDISK_Commit (
	[in] handle_t	h,
	[in] net_tid *tid
);

/*
 * provider_version(1)
 */
error_status_t UBIKDISK_Lock (
	[in] handle_t h,
	[in] net_tid *tid,
	[in] signed32 file, 
	[in] signed32 position, 
	[in] signed32 length, 
	[in] signed32 type
);

/*
 * provider_version(1)
 */
error_status_t UBIKDISK_Write (
	[in] handle_t h,
	[in] net_tid *tid, 
	[in] signed32 file, 
	[in] signed32 position,
	[in] signed32 length,
	[in] bulkdata *data
);

/*
 * provider_version(1)
 */
error_status_t UBIKDISK_GetVersion (
	[in] handle_t	h,
	[out] net_version *Version
);

/*
 * provider_version(1)
 */
error_status_t UBIKDISK_GetFile (
	[in] handle_t h,
	[in] signed32 file,
	[out] pipe_t *data,
	[out] net_version *Version
);

/*
 * provider_version(1)
 */
error_status_t UBIKDISK_SendFile (
	[in] handle_t h,
	[in] signed32 file,
	[in] signed32 length,
	[in] net_version *Version,
	[in] pipe_t *data
);
		
/*
 * provider_version(1)
 */
error_status_t UBIKDISK_Abort (
	[in] handle_t h,
	[in] net_tid *tid
);

/*
 * provider_version(1)
 */
error_status_t UBIKDISK_ReleaseLocks (
	[in] handle_t h,
	[in] net_tid *tid
);

/*
 * provider_version(1)
 */
error_status_t UBIKDISK_Truncate (
	[in] handle_t h,
	[in] net_tid *tid, 
	[in] signed32 file,
	[in] signed32 length
);

/*
 * provider_version(1)
 */
error_status_t UBIKDISK_Probe (
	[in] handle_t h
);

/*
 * provider_version(1)
 */
error_status_t UBIKDISK_GetServerInterfaces (
	[in] handle_t h,
	[in, out] dfs_interfaceList *serverInterfacesP
);

/*
 * provider_version(2)
 */
error_status_t UBIKDISK_BulkUpdate (
	[in] handle_t h,
	[in] net_tid *tid, 
	[in] unsigned32 cnt,
	[in,size_is(cnt)] ubik_bulk_update bulk[]
);

}
