/*
 * @OSF_COPYRIGHT@
 * COPYRIGHT NOTICE
 * Copyright (c) 1990, 1991, 1992, 1993, 1996 Open Software Foundation, Inc.
 * ALL RIGHTS RESERVED (DCE).  See the file named COPYRIGHT.DCE in the
 * src directory for the full copyright text.
 */
/*
 * @HP_DCE_VERSION@
 * @(#)Module: utctypes.idl $Revision: 1.1.4.2 $ $Date: 1996/03/09 23:31:14 $
 */
/*
 * HISTORY
 * $Log: utctypes.idl,v $
 * Revision 1.1.4.2  1996/03/09  23:31:14  marty
 * 	Update OSF copyright year
 * 	[1996/03/09  22:46:26  marty]
 *
 * 	DCE1_0_3b03 Merge
 * 	[1993/09/23  17:34:12  pare]
 *
 * Revision 1.1.4.1  1995/12/08  18:08:43  root
 * 	Submit OSF/DCE 1.2.1
 * 
 * 	HP revision /main/HPDCE02/1  1994/06/29  20:42 UTC  pare
 * 	Merge hpdce02 (DCE 1.1 beta) and HPDCE01 into HPDCE02
 * 	[1995/12/08  17:24:10  root]
 * 
 * 	Added HP version control string.
 * 	[1993/06/17  13:37:16  truitt]
 * 
 * 	Embedding copyright notice
 * 	[1992/12/30  19:08:56  htf]
 * 
 * Revision 1.1.6.3  1993/09/15  17:46:59  root
 * 	    Loading drop DCE1_0_3b03
 * 	Revision 1.1.5.2  1993/07/08  19:45:55  root
 * 	Initial King Kong branch
 * 	[1993/07/08  19:45:28  root]
 * 
 * Revision 1.1.1.10  1993/05/04  22:38:20  mgm
 * 	    Loading drop DCE1_0_2FNL
 * 
 * Revision 1.1  1992/01/19  15:32:06  devrcs
 * 	Initial revision
 * 
 * $EndLog$
 */
/*
*/
/*
 * 	Module utctypes.idl
 */

/*
 * Copyright (c) 1991 by
 * Digital Equipment Corporation, Maynard, Mass.
 *
 * This software is furnished under a license and may be used and copied
 * only  in  accordance  with  the  terms  of such  license and with the
 * inclusion of the above copyright notice.  This software or any  other
 * copies thereof may not be provided or otherwise made available to any
 * other person.  No title to and ownership of the  software  is  hereby
 * transferred.
 *
 * The information in this software  is subject to change without notice
 * and  should  not be  construed  as a commitment by Digitial Equipment
 * Corporation.
 *
 * Digital assumes no responsibility for the use or  reliablity  of its
 * software on equipment which is not supplied by Digital.
 *
 *
 */

interface utctypes
{
  import "dce/nbase.idl";

/*
 * UTC opaque structure.
 * This structure is used to represent Absolute Times
 * and Relative times.
 */
typedef struct utc
{
	byte char_array[16];
} utc_t;

} /* end of interface utctypes */
