#
# @OSF_COPYRIGHT@
#
#
# HISTORY
# $Log: Makefile,v $
# Revision 1.1.5.1  1996/10/17  18:16:16  damon
# 	Submitting on behalf of Transarc
# 	[1996/10/17  16:49:08  damon]
#
# $EndLog$
#

DATA_FILES = text_version.itl sequential_add.itl text_locks.itl text_add.itl finddump.itl lookup.itl concurrent_add.itl restore_header.itl dumpdb.itl

ILIST	= ${DATA_FILES}

.include <${RULES_MK}>
