/*
 * @OSF_COPYRIGHT@
 * COPYRIGHT NOTICE
 * Copyright (c) 1996 Open Software Foundation, Inc.
 * ALL RIGHTS RESERVED (DCE).  See the file named COPYRIGHT.DCE for
 * the full copyright text.
 * 
 */
/*
 * HISTORY
 * $Log: text.idl,v $
 * Revision 1.1.2.2  1996/03/09  20:49:27  marty
 * 	Add OSF copyright
 * 	[1996/03/09  20:27:50  marty]
 *
 * Revision 1.1.2.1  1995/12/11  19:35:06  root
 * 	Submit OSF/DCE 1.2.1
 * 	[1995/12/11  19:18:28  root]
 * 
 * $EndLog$
 */
[uuid(4f425b01-ff20-11ce-9174-08002be415b2)]

interface Text
{

#ifdef _WIN32

cpp_quote("#undef _WINDOWS_")
cpp_quote("#include <myafx.h>")     	  // This is a modified version of afx.h, the system version has ~CString in it which 
					  // causes the compiler on Alpha NT to accvio'd.  The compiler folks say they are going
					  // to fix that in next release.  Work around for now is to comment out ~CString.
cpp_quote("#undef EXC_HANDLING")
cpp_quote("#undef CMA_CONFIG")
cpp_quote("#include <windows.h>")
cpp_quote("#include <myexc_handling.h>")  // This is a modified version of exc_handling.h from pthread.
					  // Pthread needs to add 3 #ifndef in it (check first 3 lines of myexc_handling.h).
#endif
	/*
	** Define a type for my network representation of a C++ String object.
	** Application uses String type but RPC runtime transmits a net_string.
	*/
	typedef [string, unique] char *net_string;

	/*
	** object creator takes a String object as an argument
	*/
	Text *newText(
		[in] net_string s
	);

	/*
	** return a String object representing the server's text
	*/
	net_string getText();

	/*
	** return a String object representing the upper case of the text
	*/
	net_string upper();

	/*
	** return a String object representing the lower case of the text
	*/
	net_string lower();

	/*
	** concatenate a String argument onto the existing text
	*/
	void concat(
		[in] net_string s
	);
}
