#
# @OSF_COPYRIGHT@
# COPYRIGHT NOTICE
# Copyright (c) 1990, 1991, 1992, 1993, 1996 Open Software Foundation, Inc.
# ALL RIGHTS RESERVED (DCE).  See the file named COPYRIGHT.DCE in the
# src directory for the full copyright text.
#
#
# HISTORY
# $Log: Makefile,v $
# Revision 1.1.8.2  1996/03/11  02:16:23  marty
# 	Update OSF copyright years
# 	[1996/03/10  19:54:23  marty]
#
# Revision 1.1.8.1  1995/12/11  19:26:56  root
# 	Submit OSF/DCE 1.2.1
# 	[1995/12/11  19:14:32  root]
# 
# Revision 1.1.6.2  1994/05/24  17:58:03  tom
# 	Remove NEED_AUX_FILES since idl no longer gens them
# 	[1994/05/24  16:03:33  tom]
# 
# Revision 1.1.6.1  1993/12/28  22:10:46  pellis
# 	Updated for ODE 2.3 make
# 	[1993/12/28  21:54:12  pellis]
# 
# Revision 1.1.4.3  1993/01/13  21:49:42  bbelch
# 	Embedding copyright notice
# 	[1993/01/06  13:38:20  bbelch]
# 
# Revision 1.1  1992/01/19  03:32:56  devrcs
# 	Initial revision
# 
# $EndLog$
#

IDLBASE = pipe_of_array
OTHER_CLIENT_FILES = client_aux.o

.include "../maketest.mk"
