/*
 * @OSF_COPYRIGHT@
 * COPYRIGHT NOTICE
 * Copyright (c) 1990, 1991, 1992, 1993, 1996 Open Software Foundation, Inc.
 * ALL RIGHTS RESERVED (DCE).  See the file named COPYRIGHT.DCE in the
 * src directory for the full copyright text.
 */
/*
 * HISTORY
 * $Log: pipe_of_array.idl,v $
 * Revision 1.1.4.2  1996/03/11  02:16:27  marty
 * 	Update OSF copyright years
 * 	[1996/03/10  19:54:26  marty]
 *
 * Revision 1.1.4.1  1995/12/11  19:27:02  root
 * 	Submit OSF/DCE 1.2.1
 * 	[1995/12/11  19:14:37  root]
 * 
 * Revision 1.1.2.2  1993/01/07  20:38:51  bbelch
 * 	Embedding copyright notice
 * 	[1993/01/06  13:38:34  bbelch]
 * 
 * Revision 1.1  1992/01/19  03:32:54  devrcs
 * 	Initial revision
 * 
 * $EndLog$
 */
/*
*/
[uuid(a1b93ac0-d586-11c9-92c3-08001e01e1e9), version(0)]
interface pipe_of_array
{
    const long ARRAYSIZE = 20;

    typedef long array_t[ARRAYSIZE];

    typedef pipe array_t pipe_t;

    void op0(
        [in] handle_t h,
        [in] pipe_t *in_pipe,
        [out] long *p_manager_checksum, 
        [out] pipe_t *out_pipe
    );

    const long ILASIZE = 4;
    const long OOLASIZE = 5;

    typedef long ool_a_t[OOLASIZE];

    typedef ool_a_t il_a_t[ILASIZE];

    typedef pipe il_a_t pipe2_t;

    void op1(
        [in] handle_t h,
        [in] pipe2_t *in_pipe,
        [out] long *p_manager_checksum, 
        [out] pipe2_t *out_pipe
    );
}
