# @OSF_COPYRIGHT@
# COPYRIGHT NOTICE
# Copyright (c) 1996 Open Software Foundation, Inc.
# ALL RIGHTS RESERVED (DCE).  See the file named COPYRIGHT.DCE for
# the full copyright text.
# 
# HISTORY
# $Log: Makefile,v $
# Revision 1.1.4.2  1996/03/09  20:46:02  marty
# 	Add OSF copyright
# 	[1996/03/09  20:25:21  marty]
#
# Revision 1.1.4.1  1995/12/13  21:55:18  root
# 	Submit OSF/DCE 1.2.1
# 
# 	HP revision /main/HPDCE02/1  1995/05/25  15:07 UTC  mothra
# 	for non-tet tests
# 	[1995/12/13  21:53:51  root]
# 
# $EndLog$
#
#

VPATH	= ${SOURCEBASE}/test/functional/directory/gds/ts/gdscp/lib/x500obj/valid
IDIR    = /test/directory/gdscp/x500obj/valid/
ILIST	= 	obj_bind_v.tcl		\
		obj_compare_v.tcl	\
		obj_create_v.tcl	\
		obj_cwo_v.tcl		\
		obj_delete_v.tcl	\
		obj_general_v.tcl	\
		obj_list_v.tcl		\
		obj_modify_v.tcl	\
		obj_operations_v.tcl	\
		obj_search_v.tcl	\
		obj_show_v.tcl

.include <${RULES_MK}>
