#! /afs/tr/proj/tools/bin/perl 

#
# @OSF_COPYRIGHT@
#
# Copyright (C) 1992 Transarc Corporation - All rights reserved
# 

#
# HISTORY
# $Log: acldriver,v $
# Revision 1.1.2.2  1993/01/28  19:46:35  shl
# 	Transarc delta: rajesh-ot6318-acl-recovery-test 1.7
# 	  Selected comments:
# 	    Test recovery for correct restoration of acls.
# 	    Checkpoint since need to temporarily move to something else.
# 	    Another checkpoint since I am upgrading to dfs-102-2.2.
# 	    See above.
# 	    Needed to import another delta.
# 	    Sleep between calls to checkaggr.
# 	    Since the acl tests should not be run as root, but checkaggr needs
# 	    to be run as root, modifications were needed. The main program acldriver
# 	    is to be invoked as root, with the name of the local/DCE user to run the
# 	    ACL tests as specified via an environment variable. The user's DCE passwd
# 	    is specified likewise. The remaining programs are invoked as necessary.
# 	    Add support for options via env. variables.
# 	    Add support for checking aggregate after freezing it at random points.
# 	    Add support for checking aggregate after each async layer I/O always and only
# 	    on error.
# 	    Make sure the directory to store bad aggregates exists. The directory
# 	    actually used is a subdir (named using the current date) of the one specified.
# 	    Do not issue kill -9 to the process executing checkaggr but instead send
# 	    it SIGUSR1. The checkaggr process on receiving the SIGUSR1 signal sets itself
# 	    up for termination after current check aggregate cycle is over.
# 	    Specify a log dir to the checkaggr tool.
# 	    Add support for running multiple copies of ACL tests on different
# 	    filesets in the same aggregate simultaneously.
# 	    See above.
# 	    Debug support code added in previous revision of this delta.
# 	    Miscellaneous changes to increase robustness and quality.
# 	    Remove typo in setting environment variable NUMSETS.
# 	    Use a different seed in each run for the random number generator, that
# 	    generates number I/Os between freezes.
# 	[1993/01/27  23:09:23  shl]
#
# $EndLog$
#

#
# acldriver - driver to test recovery of acls.
#

$AGGRBASE = "epi";

$NUMSETS_ACLTEST = $ENV{'NUMSETS'} || 1;
$DRIVERDIR = $ENV{'DRIVERDIR'} || $ENV{'PWD'};
$ACLTESTDIR= $ENV{'ACLTESTDIR'} || $ENV{'PWD'};

$SRCAGGR = $ENV{'SRCDEV'} || "${AGGRBASE}a";
$COPYAGGR = $ENV{'SCRATCHDEV1'} || "${AGGRBASE}b";
$BACKUPAGGR = $ENV{'SCRATCHDEV2'} || "${AGGRBASE}c";
$ACLTESTER = $ENV{'TESTER'} || `whoami`;
$ACLTESTER_DCEPASSWD = $ENV{'TESTER_DCEPASSWD'} || $ACLTESTER;
$REPEATCOUNT = $ENV{'NUMTIMES'} || -1 ;

($ENV{'SINGLESTEP'}) ? 	($SINGLESTEP=1) : ();
($ENV{'SINGLESTEP_ONERROR'}) ? ($SINGLESTEP_ONERROR=1) : () ;

if ( $ENV{'DEBUG'} eq "1" ) {
	$debug=1;
}

$ACLTEST = "$ACLTESTDIR/driver.sh";

$ACLTESTDRIVER = "$DRIVERDIR/runacltest";
$CHECKAGGRTOOL="$DRIVERDIR/checkaggr";
$BADAGGRDIR = $ENV{'BADAGGRDIR'} || "/tmp/acl_badaggr";

$minIOCount=1;
($SINGLESTEP ) ? ($maxIOCount = 1) : ($maxIOCount = 50);

if ( ! -d $BADAGGRDIR ) { 
        mkdir($BADAGGRDIR,0755) ||
	die("unable to create bad aggregate directory $BADAGGRDIR",
		 __FILE__, __LINE__, $!	);
}

$date=sprintf("%s",join('-',(localtime())[5,4,3]));
$BADAGGRDIR = "$BADAGGRDIR/$date";
if ( ! -d $BADAGGRDIR ) { 
        mkdir($BADAGGRDIR,0755) ||
	die("unable to create bad aggregate directory $BADAGGRDIR",
		 __FILE__, __LINE__, $!	);
}

$ENV{'NUMSETS'} = $NUMSETS_ACLTEST;
$ENV{'DRIVERDIR'} = $DRIVERDIR;
$ENV{'ACLTESTDIR'} = $ACLTESTDIR;
$ENV{'SRCDEV'} = $SRCAGGR;
$ENV{'SCRATCHDEV1'} = $COPYAGGR;
$ENV{'SCRATCHDEV2'} = $BACKUPAGGR;
$ENV{'ACLTESTDRIVER'} = $ACLTESTDRIVER;
$ENV{'ACLTEST'} = $ACLTEST;
$ENV{'TESTER'} = $ACLTESTER;
$ENV{'TESTER_DCEPASSWD'} = $ACLTESTER_DCEPASSWD;
$ENV{'NUMTIMES'} = $REPEATCOUNT;

print "*** $0: ENV is \n";
system("env"); 

print "*** $0: Forking child 1 \n" if $debug;
$id1=fork();
if ( !$id1 ) {
#	# child
	&runacltest();
	exit;
} else {
	#parent
	print "*** $0: Forking child 2 \n" if $debug;
	$id2=fork();
	if ( !$id2 ) {
		# Give time for acl tests to start.
		sleep(60);
		print "@@@ $0: checkaggr about to start \n";	
		&checkaggr();
		print "@@@ $0: checkaggr returned \n";
		exit;
	} else {
	    print "*** $0: Checkaggr pid is $id2 \n" if $debug;
		print "*** $0: Waiting for $id1 \n" if $debug;
		$wait=waitpid($id1,0);
	    print "*** $0: $id1 completed \n" if $debug;
#		sleep(20);
	    print "*** $0: Sending SIGUSR1 to $id2 \n" if $debug;
		kill('SIGUSR1',$id2);
		sleep(20);
		waitpid($id2,0);
	}
}

sub loop {
	for($i=0;$i < 2;$i++) {
	 	print "%%% $0: i is $i \n";
		sleep(120);
	}
}

sub checkaggr {
	local($IOCount);

	sub settermination {
       local($sig)=@_;
       print "@@@ $0: Caught SIG$sig. Will terminate after current cycle is over.\n";
       #
       # If checkaggr is waiting for aggregate to freeze after n i/o's
       # it will wait forever, as the test causing i/o's has finished.
       # Hence freeze aggregate now, so that checkaggr can continue
       #
	   print "@@@ $0: freeze aggregate $SRCAGGR \n";
	   system("perl $CHECKAGGRTOOL -srcAggr $SRCAGGR -freezeOnly");
       $terminate = 1;
    }

    $terminate = 0;
    $SIG{'USR1'} = 'settermination';

	if ( $ENV{'DEBUG'} eq "1" ) {
		$debug=1;
	}
	sleep(60);
	print "@@@ $0: starting checkaggr" ;
	srand(time());
	for( $i = 1; $terminate != 1 ; $i++ ) {
		print  "@@@ $0: checkaggr iteration $i \n"; # if $debug;
		$IOCount = int( rand( $maxIOCount - $minIOCount + 1 ) ) + $minIOCount;
	    print "@@@ $0: execute $CHECKAGGRTOOL -srcAggr $SRCAGGR -backupAggr $BACKUPAGGR -copyAggr $COPYAGGR -noSalvage -badAggrDir $BADAGGRDIR -badAggrNamePrefix acltest  -log $BADAGGRDIR/checkaggr.log.$$-$i -numIOBeforeFreeze $IOCount -leaveFrozen\n";

		$code=system("perl $CHECKAGGRTOOL -srcAggr $SRCAGGR -backupAggr $BACKUPAGGR -copyAggr $COPYAGGR -noSalvage -badAggrDir $BADAGGRDIR -badAggrNamePrefix acltest.$$-$i -log $BADAGGRDIR/checkaggr.log.$$-$i -numIOBeforeFreeze $IOCount -leaveFrozen");
		if ( $code != 0 ) {
			if ( $SINGLESTEP_ONERROR ) {
 				print "@@@ $0: $CHECKAGGRTOOL iteration $i returned error ... \n";
				print "switching to single step mode \n";
				$maxIOCount = 1;
			}		
		}
	}
	print "@@@ $0: Unfreeze aggregate $SRCAGGR \n";
	system("perl $CHECKAGGRTOOL -srcAggr $SRCAGGR -unfreezeOnly");
    print "@@@ $0: terminating after checking aggregate $i times \n";
}

sub runacltest  {
	print "%%% $0: runacltest starting \n" if $debug;
	system("su $ACLTESTER -f -c $ACLTESTDRIVER");
}


__END__

# Emacs Variable settings.
# Local Variables:
# tab-width:4
# End:
