#!/bin/csh

#
# @OSF_COPYRIGHT@
#

#
# HISTORY
# $Log: setuppctstest,v $
# Revision 1.1.2.2  1993/01/28  21:36:13  shl
# 	Transarc delta: rajesh-ot6686-pcts-recovery-test-driver 1.1
# 	  Selected comments:
# 	    Code and debug scripts to drive PCTS tests and checkaggr tool.
# 	    The C shell scripts that defines the most common environment variables
# 	    needed by the pctsdriver.
# 	[1993/01/27  23:23:29  shl]
#
# $EndLog$
#

setenv PCTSTESTDIR /pcts
setenv NUMTIMES 1
setenv NUMSETS 2
setenv PCTSLOGDIR /afs/tr/usr/rajesh/epi/test/recovery/pcts/log/pctslog
setenv DRIVERDIR /afs/transarc.com/project/fs/sb/rajesh/dce/src/test/file/recovery
setenv SRCDEV /dev/epi1
setenv SCRATCHDEV1 /dev/epi-pcts1
setenv SCRATCHDEV2 /dev/epi-pcts2
setenv PTESTER rajesh
setenv BADAGGRDIR /afs/tr/usr/rajesh/epi/test/recovery/pcts/log/driverlog
