# @OSF_COPYRIGHT@
# COPYRIGHT NOTICE
# Copyright (c) 1990, 1991, 1992, 1993, 1994, 1996 Open Software Foundation, Inc.
# ALL RIGHTS RESERVED (DCE).  See the file named COPYRIGHT.DCE for
# the full copyright text.
# 
# 
# HISTORY
# $Log: Makefile,v $
# Revision 1.1.4.2  1996/03/11  01:43:03  marty
# 	Update OSF copyright years
# 	[1996/03/10  19:14:14  marty]
#
# Revision 1.1.4.1  1995/12/08  22:06:26  root
# 	Submit OSF/DCE 1.2.1
# 	[1995/12/08  21:42:26  root]
# 
# Revision 1.1.2.2  1994/06/17  18:45:24  devsrc
# 	cr10872 - fix copyright
# 	[1994/06/17  18:34:27  devsrc]
# 
# Revision 1.1.2.1  1994/05/19  14:50:27  baum
# 	Initial checkin
# 	[1994/05/19  14:50:03  baum]
# 
# $EndLog$

TET_FILES	= tet_scen tet_code tetexec.cfg
IDIR		= /test/tet/functional/dce/utils/acldb/
ILIST		= ${TET_FILES}
DATAFILES	= ${TET_FILES}
IMODE 		= 755

SUBDIRS		= ts
DATA_SUBDIRS	= ${SUBDIRS}

.include <${RULES_MK}>
