/*
 * @OSF_COPYRIGHT@
 * COPYRIGHT NOTICE
 * Copyright (c) 1990, 1991, 1992, 1993, 1996 Open Software Foundation, Inc.
 * ALL RIGHTS RESERVED (DCE).  See the file named COPYRIGHT.DCE in the
 * src directory for the full copyright text.
 */
/*
 * HISTORY
 * $Log: pipetest2.idl,v $
 * Revision 1.1.4.2  1996/03/11  02:16:51  marty
 * 	Update OSF copyright years
 * 	[1996/03/10  19:54:42  marty]
 *
 * Revision 1.1.4.1  1995/12/11  19:27:37  root
 * 	Submit OSF/DCE 1.2.1
 * 	[1995/12/11  19:14:50  root]
 * 
 * Revision 1.1.2.3  1993/01/13  21:50:01  bbelch
 * 	Embedding copyright notice
 * 	[1993/01/06  13:39:38  bbelch]
 * 
 * Revision 1.1  1992/01/19  03:26:31  devrcs
 * 	Initial revision
 * 
 * $EndLog$
 */
/*
*/
[uuid(492790a6-4000-0000-0d00-00feda000000), version(0),
 endpoint("ncadg_ip_udp:[35002]", "ncadg_dds:[773]")]
interface pipetest2
{
    typedef [handle] long my_handle;

    typedef pipe float pipe_of_float;

    typedef struct pt2_struct {
        long    pt2_long;
        double  pt2_double;
    } pt2_struct;

    typedef pipe pt2_struct pipe_of_struct;

    void my_oper2(
                  [out] pipe_of_float *op_float,
                  [in,out] pipe_of_struct *iop_struct,
                  [in] pipe_of_float *ip_float,
                  [out] boolean *correct_to_server
                 );
}
