# @OSF_COPYRIGHT@
# COPYRIGHT NOTICE
# Copyright (c) 1990, 1991, 1992, 1993, 1994, 1996 Open Software Foundation, Inc.
# ALL RIGHTS RESERVED (DCE).  See the file named COPYRIGHT.DCE for
# the full copyright text.
# 
# 
# HISTORY
# $Log: Makefile,v $
# Revision 1.1.4.2  1996/03/11  02:36:31  marty
# 	Update OSF copyright years
# 	[1996/03/10  20:04:29  marty]
#
# Revision 1.1.4.1  1995/12/11  21:52:41  root
# 	Submit OSF/DCE 1.2.1
# 	[1995/12/11  20:54:15  root]
# 
# Revision 1.1.2.3  1994/09/08  20:28:32  dassarma
# 	Adding data files for I18N systest
# 	[1994/09/08  20:26:27  dassarma]
# 
# Revision 1.1.2.2  1994/06/17  18:45:55  devsrc
# 	cr10872 - fix copyright
# 	[1994/06/17  18:35:47  devsrc]
# 
# Revision 1.1.2.1  1994/05/23  21:54:33  dassarma
# 	Initial version.
# 	[1994/05/23  21:54:14  dassarma]
# 
# $EndLog$
#==================================================


TET_FILES       = test_common.tcl test_setup.tcl
DATAFILES	= french.short danish.short german.short spanish.short
IDIR            = /test/tet/system/I18N/lib/
ILIST           = ${TET_FILES} ${DATAFILES}
IMODE           = 755

.include <${RULES_MK}>

