#
# @OSF_COPYRIGHT@
# COPYRIGHT NOTICE
# Copyright (c) 1990, 1991, 1992, 1993, 1996 Open Software Foundation, Inc.
# ALL RIGHTS RESERVED (DCE).  See the file named COPYRIGHT.DCE in the
# src directory for the full copyright text.
#
#
# HISTORY
# $Log: Makefile,v $
# Revision 1.1.8.2  1996/03/11  02:20:42  marty
# 	Update OSF copyright years
# 	[1996/03/10  19:56:40  marty]
#
# Revision 1.1.8.1  1995/12/11  19:36:32  root
# 	Submit OSF/DCE 1.2.1
# 	[1995/12/11  19:19:14  root]
# 
# Revision 1.1.6.1  1993/11/02  22:02:02  tom
# 	Install new README file.
# 	[1993/11/02  22:00:12  tom]
# 
# Revision 1.1.4.2  1993/01/11  21:15:25  bbelch
# 	Embedding copyright notice
# 	[1993/01/06  14:55:57  bbelch]
# 
# Revision 1.1  1992/01/19  03:41:10  devrcs
# 	Initial revision
# 
# $EndLog$
#
#
#

EXPINC_SUBDIRS = control
DATA_SUBDIRS = control
SUBDIRS = testsh control moretests 

DATAFILES	= README
IMODE		= 644
ILIST		= ${DATAFILES}

.include <${RULES_MK}>
