/*
 * @OSF_COPYRIGHT@
 * COPYRIGHT NOTICE
 * Copyright (c) 1990, 1991, 1992, 1993, 1994, 1996 Open Software Foundation, Inc.
 * ALL RIGHTS RESERVED (DCE).  See the file named COPYRIGHT.DCE for
 * the full copyright text.
 * 
 */
/*
 * HISTORY
 * $Log: tserver.idl,v $
 * Revision 1.1.4.2  1996/03/11  02:28:46  marty
 * 	Update OSF copyright years
 * 	[1996/03/10  19:36:53  marty]
 *
 * Revision 1.1.4.1  1995/12/11  15:17:15  root
 * 	Submit
 * 	[1995/12/11  14:32:44  root]
 * 
 * 	Submit OSF/DCE 1.2.1
 * 	[1995/12/08  23:17:50  root]
 * 
 * Revision 1.1.2.1  1994/09/28  21:47:04  melman
 * 	moved admin tests to test/functional
 * 	[1994/09/28  21:14:55  melman]
 * 
 * Revision 1.1.2.2  1994/06/17  18:44:36  devsrc
 * 	cr10872 - fix copyright
 * 	[1994/06/17  18:31:42  devsrc]
 * 
 * Revision 1.1.2.1  1994/06/10  21:39:24  pwang
 * 	Initial implementation
 * 	[1994/06/10  21:36:17  pwang]
 * 
 * $EndLog$
 */

[
    uuid(008bebed-c7c1-1ddc-9cb3-0000c0ba4944),
    version(1.0)
]
interface tserver 
{
	/*
	 * Instruct the server quits as exit(quit_code)
	 */
	[idempotent]
	void server_stop(
		[in]	handle_t	h,
		[in]	unsigned32	quit_code,
		[out]	error_status_t	*st
	);
}
