/*
 * @OSF_COPYRIGHT@
 * COPYRIGHT NOTICE
 * Copyright (c) 1990, 1991, 1992, 1993, 1994, 1996 Open Software Foundation, Inc.
 * ALL RIGHTS RESERVED (DCE).  See the file named COPYRIGHT.DCE for
 * the full copyright text.
 */
/*
 * HISTORY
 * $Log: dce_cf_const.idl,v $
 * Revision 1.1.19.2  1996/03/09  23:11:07  marty
 * 	Update OSF copyright year
 * 	[1996/03/09  22:28:35  marty]
 *
 * Revision 1.1.19.1  1995/12/08  21:36:52  root
 * 	Submit OSF/DCE 1.2.1
 * 	[1995/12/08  18:08:41  root]
 * 
 * Revision 1.1.17.2  1994/06/09  16:05:43  devsrc
 * 	cr10892 - fix copyright
 * 	[1994/06/09  15:50:20  devsrc]
 * 
 * Revision 1.1.17.1  1993/12/29  19:22:30  rsalz
 * 	Move dce_cf_XXX from config to dce/utils/dcecf (OT CR 9663).
 * 	Rewrite to fix various bugs (OT CR 9665).
 * 	[1993/12/29  16:18:20  rsalz]
 * 
 * $EndLog$
 */

/*
** Copyright (c) Hewlett-Packard Company 1991
** Unpublished work. All Rights Reserved.
** 
** DCE Architectural Constants
*/
interface dce_cf_const
{
    const char PATH_COMPONENT_SEPARATOR = '/';
    
    const char *    CELL_DIR_ROOT       = "/.:/";
    const signed32  CELL_DIR_ROOT_LEN   = 4;
    
    const char *    GLOBAL_DIR_ROOT     = "/.../";
    const signed32  GLOBAL_DIR_ROOT_LEN = 5;
    
    const char *   CELL_PROFILE_NAME    = "cell-profile";
    const signed32 CELL_PROFILE_LEN     = 12;
    const signed32 CELL_NAME_LEN	= 1024;
    
}

